/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -fno-strict-aliasing -pthread -I/home/icarogdo/.nimble/pkgs2/bearssl-0.2.10-e53ab85b8c4c1ce3aa1f4eb251c0ab29e08d4972/bearssl/abi -I/home/icarogdo/.nimble/pkgs2/bearssl-0.2.10-e53ab85b8c4c1ce3aa1f4eb251c0ab29e08d4972/bearssl/abi/../csources/src/ -I/home/icarogdo/.nimble/pkgs2/bearssl-0.2.10-e53ab85b8c4c1ce3aa1f4eb251c0ab29e08d4972/bearssl/abi/../csources/inc/ -I/home/icarogdo/.nimble/pkgs2/bearssl-0.2.10-e53ab85b8c4c1ce3aa1f4eb251c0ab29e08d4972/bearssl/abi/../csources/tools/ -DBR_USE_UNIX_TIME=1 -DBR_USE_URANDOM=1 -DBR_LE_UNALIGNED=1 -DBR_64=1  -DBR_amd64=1 -DBR_INT128=1 -Wno-incompatible-pointer-types -I/usr/include/webkitgtk-4.1 -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/cloudproviders -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/glycin-2 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/atk-1.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/fribidi -I/usr/include/pixman-1 -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gio-unix-2.0 -I/usr/include/libsoup-3.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-6 -pthread -O3 -fno-ident -fno-math-errno   -I/usr/lib/nim/lib -I/home/icarogdo/dev/macroobras-jazzy/app/macroobras/src -o /home/icarogdo/dev/macroobras-jazzy/app/macroobras/.nimcache-release/@njazzy-0.4.5-4fdda426bdb506437985763b18fb2c79ca01e6e0@sjazzy@sutils@smultipart.nim.c.o /home/icarogdo/dev/macroobras-jazzy/app/macroobras/.nimcache-release/@njazzy-0.4.5-4fdda426bdb506437985763b18fb2c79ca01e6e0@sjazzy@sutils@smultipart.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tyObject_Table__1rGa4Qc8s9bajqNj6vNuVcw tyObject_Table__1rGa4Qc8s9bajqNj6vNuVcw;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tySequence__XUcmaxm9b9attK75fbPuUHtw tySequence__XUcmaxm9b9attK75fbPuUHtw;
typedef struct tySequence__XUcmaxm9b9attK75fbPuUHtw_Content tySequence__XUcmaxm9b9attK75fbPuUHtw_Content;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content;
typedef struct tyObject_HSlice__hCONkfGh5Y79cjKbAHxROMQ tyObject_HSlice__hCONkfGh5Y79cjKbAHxROMQ;
typedef struct tyObject_HSlice__OAVEPXFBgbTm1jVNAuKEpw tyObject_HSlice__OAVEPXFBgbTm1jVNAuKEpw;
typedef struct tyObject_UploadedFile__Ttgk4NpE79ahXZ9aF4eH5jFg tyObject_UploadedFile__Ttgk4NpE79ahXZ9aF4eH5jFg;
typedef struct tyTuple__VkaA9bzBYmNkyt5Z9b9b9a2K6A tyTuple__VkaA9bzBYmNkyt5Z9b9b9a2K6A;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tySequence__XUcmaxm9b9attK75fbPuUHtw {
  NI len; tySequence__XUcmaxm9b9attK75fbPuUHtw_Content* p;
};
struct tyObject_Table__1rGa4Qc8s9bajqNj6vNuVcw {
	tySequence__XUcmaxm9b9attK75fbPuUHtw data;
	NI counter;
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  NI len; tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content* p;
};
struct tyObject_HSlice__hCONkfGh5Y79cjKbAHxROMQ {
	NI a;
	NI b;
};
typedef NU8 tySet_tyChar__nmiMWKVIe46vacnhAFrQvw[32];
struct tyObject_HSlice__OAVEPXFBgbTm1jVNAuKEpw {
	NI a;
	NI b;
};
struct tyObject_UploadedFile__Ttgk4NpE79ahXZ9aF4eH5jFg {
	NimStringV2 filename;
	NimStringV2 contentType;
	NimStringV2 content;
};
struct tyTuple__VkaA9bzBYmNkyt5Z9b9b9a2K6A {
	NI Field0;
	NimStringV2 Field1;
	tyObject_UploadedFile__Ttgk4NpE79ahXZ9aF4eH5jFg Field2;
};
struct tySequence__XUcmaxm9b9attK75fbPuUHtw_Content { NI cap; tyTuple__VkaA9bzBYmNkyt5Z9b9b9a2K6A data[SEQ_DECL_SIZE]; };
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE]; };
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(tyObject_Table__1rGa4Qc8s9bajqNj6vNuVcw, initTable__pkgZjazzyZutilsZmultipart_u22)(NI initialSize_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, contains__pureZstrutils_u1900)(NimStringV2 s_p0, NimStringV2 sub_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u5657)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ dest_p0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(NI, nsuFindStr)(NimStringV2 s_p0, NimStringV2 sub_p1, NI start_p2, NI last_p3);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(NimStringV2, X5BX5D___pureZstrutils_u1319)(NimStringV2 s_p0, tyObject_HSlice__hCONkfGh5Y79cjKbAHxROMQ x_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(NimStringV2, mnewString)(NI len_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimPrepareStrMutationImpl__system_u2511)(NimStringV2* s_p0);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4511)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(tyObject_HSlice__hCONkfGh5Y79cjKbAHxROMQ, dotdot___stdZenumutils_u105)(NI a_p0, NI b_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space_p0);
N_LIB_PRIVATE N_NIMCALL(tySequence__sM4lkSb7zS6F7OVMvW9cffQ, nsuSplitString)(NimStringV2 s_p0, NimStringV2 sep_p1, NI maxsplit_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuStrip)(NimStringV2 s_p0, NIM_BOOL leading_p1, NIM_BOOL trailing_p2, tySet_tyChar__nmiMWKVIe46vacnhAFrQvw chars_p3);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1);
static N_INLINE(NIM_BOOL, equalMem__system_u1763)(void* a_p0, void* b_p1, NI size_p2);
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2);
static N_INLINE(NimStringV2, X5BX5D___pureZstrutils_u1291)(NimStringV2 s_p0, tyObject_HSlice__OAVEPXFBgbTm1jVNAuKEpw x_p1);
static N_INLINE(tyObject_HSlice__OAVEPXFBgbTm1jVNAuKEpw, dotdot___stdZstrbasics_u48)(NI a_p0, NI b_p1);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nsuEndsWith)(NimStringV2 s_p0, NimStringV2 suffix_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___system_u2769)(NimStringV2* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___system_u2778)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, eqdestroy___system_u281)(NimStringV2 x_p0);
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq___pkgZjazzyZutilsZmultipart_u290)(tyObject_Table__1rGa4Qc8s9bajqNj6vNuVcw* t_p0, NimStringV2 key_p1, tyObject_UploadedFile__Ttgk4NpE79ahXZ9aF4eH5jFg* val_p2);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u95)(NimStringV2 msg_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static const struct {
  NI cap; NIM_CHAR data[9+1];
} TM__hO9bfka8UKA7JUzPEOgt2LQ_2 = { 9 | NIM_STRLIT_FLAG, "boundary=" };
static const NimStringV2 TM__hO9bfka8UKA7JUzPEOgt2LQ_3 = {9, (NimStrPayload*)&TM__hO9bfka8UKA7JUzPEOgt2LQ_2};
static const NimStringV2 TM__hO9bfka8UKA7JUzPEOgt2LQ_4 = {9, (NimStrPayload*)&TM__hO9bfka8UKA7JUzPEOgt2LQ_2};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__hO9bfka8UKA7JUzPEOgt2LQ_5 = { 2 | NIM_STRLIT_FLAG, "--" };
static const NimStringV2 TM__hO9bfka8UKA7JUzPEOgt2LQ_6 = {2, (NimStrPayload*)&TM__hO9bfka8UKA7JUzPEOgt2LQ_5};
static NIM_CONST tySet_tyChar__nmiMWKVIe46vacnhAFrQvw TM__hO9bfka8UKA7JUzPEOgt2LQ_13 = {
0x00, 0x3e, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
static const NimStringV2 TM__hO9bfka8UKA7JUzPEOgt2LQ_14 = {2, (NimStrPayload*)&TM__hO9bfka8UKA7JUzPEOgt2LQ_5};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__hO9bfka8UKA7JUzPEOgt2LQ_15 = { 4 | NIM_STRLIT_FLAG, "\015\012\015\012" };
static const NimStringV2 TM__hO9bfka8UKA7JUzPEOgt2LQ_16 = {4, (NimStrPayload*)&TM__hO9bfka8UKA7JUzPEOgt2LQ_15};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__hO9bfka8UKA7JUzPEOgt2LQ_23 = { 2 | NIM_STRLIT_FLAG, "\015\012" };
static const NimStringV2 TM__hO9bfka8UKA7JUzPEOgt2LQ_24 = {2, (NimStrPayload*)&TM__hO9bfka8UKA7JUzPEOgt2LQ_23};
static const struct {
  NI cap; NIM_CHAR data[10+1];
} TM__hO9bfka8UKA7JUzPEOgt2LQ_25 = { 10 | NIM_STRLIT_FLAG, "filename=\"" };
static const NimStringV2 TM__hO9bfka8UKA7JUzPEOgt2LQ_26 = {10, (NimStrPayload*)&TM__hO9bfka8UKA7JUzPEOgt2LQ_25};
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__hO9bfka8UKA7JUzPEOgt2LQ_27 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__hO9bfka8UKA7JUzPEOgt2LQ_28 = {0, (NimStrPayload*)&TM__hO9bfka8UKA7JUzPEOgt2LQ_27};
static const NimStringV2 TM__hO9bfka8UKA7JUzPEOgt2LQ_29 = {0, (NimStrPayload*)&TM__hO9bfka8UKA7JUzPEOgt2LQ_27};
static const struct {
  NI cap; NIM_CHAR data[24+1];
} TM__hO9bfka8UKA7JUzPEOgt2LQ_30 = { 24 | NIM_STRLIT_FLAG, "application/octet-stream" };
static const NimStringV2 TM__hO9bfka8UKA7JUzPEOgt2LQ_31 = {24, (NimStrPayload*)&TM__hO9bfka8UKA7JUzPEOgt2LQ_30};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__hO9bfka8UKA7JUzPEOgt2LQ_32 = { 6 | NIM_STRLIT_FLAG, "name=\"" };
static const NimStringV2 TM__hO9bfka8UKA7JUzPEOgt2LQ_33 = {6, (NimStrPayload*)&TM__hO9bfka8UKA7JUzPEOgt2LQ_32};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__hO9bfka8UKA7JUzPEOgt2LQ_35 = { 1 | NIM_STRLIT_FLAG, "\"" };
static const NimStringV2 TM__hO9bfka8UKA7JUzPEOgt2LQ_36 = {1, (NimStrPayload*)&TM__hO9bfka8UKA7JUzPEOgt2LQ_35};
static const NimStringV2 TM__hO9bfka8UKA7JUzPEOgt2LQ_38 = {10, (NimStrPayload*)&TM__hO9bfka8UKA7JUzPEOgt2LQ_25};
static const NimStringV2 TM__hO9bfka8UKA7JUzPEOgt2LQ_40 = {1, (NimStrPayload*)&TM__hO9bfka8UKA7JUzPEOgt2LQ_35};
static const struct {
  NI cap; NIM_CHAR data[14+1];
} TM__hO9bfka8UKA7JUzPEOgt2LQ_42 = { 14 | NIM_STRLIT_FLAG, "Content-Type: " };
static const NimStringV2 TM__hO9bfka8UKA7JUzPEOgt2LQ_43 = {14, (NimStrPayload*)&TM__hO9bfka8UKA7JUzPEOgt2LQ_42};
static const struct {
  NI cap; NIM_CHAR data[90+1];
} TM__hO9bfka8UKA7JUzPEOgt2LQ_44 = { 90 | NIM_STRLIT_FLAG, "iterators.nim(254, 11) `len(a) == L` the length of the seq changed while iterating over it" };
static const NimStringV2 TM__hO9bfka8UKA7JUzPEOgt2LQ_45 = {90, (NimStrPayload*)&TM__hO9bfka8UKA7JUzPEOgt2LQ_44};
extern NIM_THREADVAR TFrame* framePtr__system_u2809;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4293;
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	nimSetMem__system_u2188(p_p0, ((int)0), size_p1);
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
	{
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		copyMem__system_u1755(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		(*dest_p0).len += src_p1.len;
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
}
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = !(((*s_p0).p == ((NimStrPayload*) NIM_NIL)));
		if (!(T3_)) goto LA4_;
		T3_ = ((NI)((*(*s_p0).p).cap & ((NI)IL64(4611686018427387904))) == ((NI)IL64(4611686018427387904)));
LA4_: ;
		if (!T3_) goto LA5_;
		nimPrepareStrMutationImpl__system_u2511(s_p0);
	}
LA5_: ;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2809 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2809).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2809;
	framePtr__system_u2809 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4511();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2809 = (*framePtr__system_u2809).prev;
}
static N_INLINE(NimStringV2, X5BX5D___pureZstrutils_u1319)(NimStringV2 s_p0, tyObject_HSlice__hCONkfGh5Y79cjKbAHxROMQ x_p1) {
	NimStringV2 result;
	NI a_1;
	NI L_1;
	NI TM__hO9bfka8UKA7JUzPEOgt2LQ_7;
	NI TM__hO9bfka8UKA7JUzPEOgt2LQ_8;
	NI TM__hO9bfka8UKA7JUzPEOgt2LQ_9;
	nimfr_("[]", "indices.nim");
{	result.len = 0; result.p = NIM_NIL;
	nimlf_(83, "indices.nim");	a_1 = x_p1.a;
	nimln_(84);	nimln_(59);	if (nimSubInt(s_p0.len, x_p1.b, &TM__hO9bfka8UKA7JUzPEOgt2LQ_7)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimSubInt((NI)(TM__hO9bfka8UKA7JUzPEOgt2LQ_7), a_1, &TM__hO9bfka8UKA7JUzPEOgt2LQ_8)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimAddInt((NI)(TM__hO9bfka8UKA7JUzPEOgt2LQ_8), ((NI)1), &TM__hO9bfka8UKA7JUzPEOgt2LQ_9)) { raiseOverflow(); goto BeforeRet_;
	};
	L_1 = (NI)(TM__hO9bfka8UKA7JUzPEOgt2LQ_9);
	nimln_(85);	if ((L_1) < ((NI)0) || (L_1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(L_1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	result = mnewString((L_1));
	{
		NI i_1;
		NI i_2;
		i_1 = (NI)0;
		nimlf_(128, "iterators_1.nim");		i_2 = ((NI)0);
		{
			nimln_(129);			while (1) {
				NI TM__hO9bfka8UKA7JUzPEOgt2LQ_10;
				NI TM__hO9bfka8UKA7JUzPEOgt2LQ_11;
				if (!(i_2 < L_1)) goto LA3;
				nimlf_(86, "indices.nim");				i_1 = i_2;
				if (i_1 < 0 || i_1 >= result.len){ raiseIndexError2(i_1,result.len-1); goto BeforeRet_;
				}
				nimPrepareStrMutationV2((&result));
				if (nimAddInt(i_1, a_1, &TM__hO9bfka8UKA7JUzPEOgt2LQ_10)) { raiseOverflow(); goto BeforeRet_;
				};
				if ((NI)(TM__hO9bfka8UKA7JUzPEOgt2LQ_10) < 0 || (NI)(TM__hO9bfka8UKA7JUzPEOgt2LQ_10) >= s_p0.len){ raiseIndexError2((NI)(TM__hO9bfka8UKA7JUzPEOgt2LQ_10),s_p0.len-1); goto BeforeRet_;
				}
				result.p->data[i_1] = s_p0.p->data[(NI)(TM__hO9bfka8UKA7JUzPEOgt2LQ_10)];
				nimlf_(131, "iterators_1.nim");				if (nimAddInt(i_2, ((NI)1), &TM__hO9bfka8UKA7JUzPEOgt2LQ_11)) { raiseOverflow(); goto BeforeRet_;
				};
				i_2 = (NI)(TM__hO9bfka8UKA7JUzPEOgt2LQ_11);
			} LA3: ;
		}
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(tyObject_HSlice__hCONkfGh5Y79cjKbAHxROMQ, dotdot___stdZenumutils_u105)(NI a_p0, NI b_p1) {
	tyObject_HSlice__hCONkfGh5Y79cjKbAHxROMQ result;
	nimfr_("..", "system.nim");
	nimlf_(436, "system.nim");	result.a = a_p0;
	result.b = b_p1;
	popFrame();
	return result;
}
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2) {
	int result;
	result = memcmp(a_p0, b_p1, ((size_t) (size_p2)));
	return result;
}
static N_INLINE(NIM_BOOL, equalMem__system_u1763)(void* a_p0, void* b_p1, NI size_p2) {
	NIM_BOOL result;
	int T1_;
	T1_ = (int)0;
	T1_ = nimCmpMem(a_p0, b_p1, size_p2);
	result = (T1_ == ((NI32)0));
	return result;
}
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1) {
	NIM_BOOL result;
	NI alen_1;
	NI blen_1;
	nimfr_("eqStrings", "strmantle.nim");
{	nimlf_(33, "strmantle.nim");	result = NIM_FALSE;
	nimln_(34);	alen_1 = a_p0.len;
	nimln_(35);	blen_1 = b_p1.len;
	nimln_(36);	{
		if (!(alen_1 == blen_1)) goto LA3_;
		nimln_(37);		{
			if (!(alen_1 == ((NI)0))) goto LA7_;
			nimln_(32);			nimln_(37);			result = NIM_TRUE;
			goto BeforeRet_;
		}
LA7_: ;
		nimln_(38);		nimln_(32);		nimln_(38);		result = equalMem__system_u1763(((void*) ((&a_p0.p->data[((NI)0)]))), ((void*) ((&b_p1.p->data[((NI)0)]))), (alen_1));
		goto BeforeRet_;
	}
LA3_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NimStringV2, X5BX5D___pureZstrutils_u1291)(NimStringV2 s_p0, tyObject_HSlice__OAVEPXFBgbTm1jVNAuKEpw x_p1) {
	NimStringV2 result;
	NI a_1;
	NI L_1;
	NI TM__hO9bfka8UKA7JUzPEOgt2LQ_17;
	NI TM__hO9bfka8UKA7JUzPEOgt2LQ_18;
	nimfr_("[]", "indices.nim");
{	result.len = 0; result.p = NIM_NIL;
	nimlf_(83, "indices.nim");	a_1 = x_p1.a;
	nimln_(84);	if (nimSubInt(x_p1.b, a_1, &TM__hO9bfka8UKA7JUzPEOgt2LQ_17)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimAddInt((NI)(TM__hO9bfka8UKA7JUzPEOgt2LQ_17), ((NI)1), &TM__hO9bfka8UKA7JUzPEOgt2LQ_18)) { raiseOverflow(); goto BeforeRet_;
	};
	L_1 = (NI)(TM__hO9bfka8UKA7JUzPEOgt2LQ_18);
	nimln_(85);	if ((L_1) < ((NI)0) || (L_1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(L_1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	result = mnewString((L_1));
	{
		NI i_1;
		NI i_2;
		i_1 = (NI)0;
		nimlf_(128, "iterators_1.nim");		i_2 = ((NI)0);
		{
			nimln_(129);			while (1) {
				NI TM__hO9bfka8UKA7JUzPEOgt2LQ_19;
				NI TM__hO9bfka8UKA7JUzPEOgt2LQ_20;
				if (!(i_2 < L_1)) goto LA3;
				nimlf_(86, "indices.nim");				i_1 = i_2;
				if (i_1 < 0 || i_1 >= result.len){ raiseIndexError2(i_1,result.len-1); goto BeforeRet_;
				}
				nimPrepareStrMutationV2((&result));
				if (nimAddInt(i_1, a_1, &TM__hO9bfka8UKA7JUzPEOgt2LQ_19)) { raiseOverflow(); goto BeforeRet_;
				};
				if ((NI)(TM__hO9bfka8UKA7JUzPEOgt2LQ_19) < 0 || (NI)(TM__hO9bfka8UKA7JUzPEOgt2LQ_19) >= s_p0.len){ raiseIndexError2((NI)(TM__hO9bfka8UKA7JUzPEOgt2LQ_19),s_p0.len-1); goto BeforeRet_;
				}
				result.p->data[i_1] = s_p0.p->data[(NI)(TM__hO9bfka8UKA7JUzPEOgt2LQ_19)];
				nimlf_(131, "iterators_1.nim");				if (nimAddInt(i_2, ((NI)1), &TM__hO9bfka8UKA7JUzPEOgt2LQ_20)) { raiseOverflow(); goto BeforeRet_;
				};
				i_2 = (NI)(TM__hO9bfka8UKA7JUzPEOgt2LQ_20);
			} LA3: ;
		}
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(tyObject_HSlice__OAVEPXFBgbTm1jVNAuKEpw, dotdot___stdZstrbasics_u48)(NI a_p0, NI b_p1) {
	tyObject_HSlice__OAVEPXFBgbTm1jVNAuKEpw result;
	nimfr_("..", "system.nim");
	nimlf_(436, "system.nim");	result.a = a_p0;
	result.b = b_p1;
	popFrame();
	return result;
}
static N_INLINE(void, eqdestroy___system_u281)(NimStringV2 x_p0) {
	nimfr_("=destroy", "system.nim");
	popFrame();
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4293);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_Table__1rGa4Qc8s9bajqNj6vNuVcw, parseMultipart__pkgZjazzyZutilsZmultipart_u4)(NimStringV2 body_p0, NimStringV2 contentType_p1) {
	tyObject_Table__1rGa4Qc8s9bajqNj6vNuVcw result;
	NimStringV2 boundaryPrefix_1;
	NimStringV2 boundary_1;
	NimStringV2 colontmpD_;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ parts_1;
	NI boundaryIndex_1;
	NimStringV2 T11_;
	NI TM__hO9bfka8UKA7JUzPEOgt2LQ_12;
	tyObject_HSlice__hCONkfGh5Y79cjKbAHxROMQ T12_;
NIM_BOOL* nimErr_;
	nimfr_("parseMultipart", "multipart.nim");
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_Table__1rGa4Qc8s9bajqNj6vNuVcw));
	boundaryPrefix_1.len = 0; boundaryPrefix_1.p = NIM_NIL;
	boundary_1.len = 0; boundary_1.p = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	parts_1.len = 0; parts_1.p = NIM_NIL;
	nimlf_(6, "multipart.nim");	result = initTable__pkgZjazzyZutilsZmultipart_u22(((NI)32));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(10);	{
		NIM_BOOL T4_;
		T4_ = (NIM_BOOL)0;
		T4_ = contains__pureZstrutils_u1900(contentType_p1, TM__hO9bfka8UKA7JUzPEOgt2LQ_3);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		if (!!(T4_)) goto LA5_;
		nimln_(11);		nimlf_(2219, "system.nim");		eqdestroy___system_u5657(parts_1);
		nimln_(394);		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
		if (boundary_1.p && !(boundary_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(boundary_1.p);
}
		goto BeforeRet_;
	}
LA5_: ;
	nimlf_(13, "multipart.nim");	boundaryPrefix_1 = TM__hO9bfka8UKA7JUzPEOgt2LQ_4;
	nimln_(14);	boundaryIndex_1 = nsuFindStr(contentType_p1, boundaryPrefix_1, ((NI)0), ((NI)-1));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(15);	{
		if (!(boundaryIndex_1 == ((NI)-1))) goto LA9_;
		nimlf_(2219, "system.nim");		eqdestroy___system_u5657(parts_1);
		nimln_(394);		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
		if (boundary_1.p && !(boundary_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(boundary_1.p);
}
		goto BeforeRet_;
	}
LA9_: ;
	nimlf_(17, "multipart.nim");	T11_.len = 0; T11_.p = NIM_NIL;
	if (nimAddInt(boundaryIndex_1, boundaryPrefix_1.len, &TM__hO9bfka8UKA7JUzPEOgt2LQ_12)) { raiseOverflow(); goto LA1_;
	};
	T12_ = dotdot___stdZenumutils_u105((NI)(TM__hO9bfka8UKA7JUzPEOgt2LQ_12), ((NI)1));
	colontmpD_ = X5BX5D___pureZstrutils_u1319(contentType_p1, T12_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T11_ = rawNewString(colontmpD_.len + 2);
appendString((&T11_), TM__hO9bfka8UKA7JUzPEOgt2LQ_6);
appendString((&T11_), colontmpD_);
	boundary_1 = T11_;
	nimln_(19);	{
		if (!(body_p0.len == ((NI)0))) goto LA15_;
		nimlf_(2219, "system.nim");		eqdestroy___system_u5657(parts_1);
		nimln_(394);		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
		if (boundary_1.p && !(boundary_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(boundary_1.p);
}
		goto BeforeRet_;
	}
LA15_: ;
	nimlf_(24, "multipart.nim");	parts_1 = nsuSplitString(body_p0, boundary_1, ((NI)-1));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		NimStringV2* part_1;
		NI i_1;
		NI L_1;
		NI T18_;
		part_1 = (NimStringV2*)0;
		nimlf_(249, "iterators.nim");		i_1 = ((NI)0);
		nimln_(250);		T18_ = parts_1.len;
		L_1 = T18_;
		{
			nimln_(251);			while (1) {
				if (!(i_1 < L_1)) goto LA20;
				nimlf_(26, "multipart.nim");				if (i_1 < 0 || i_1 >= parts_1.len){ raiseIndexError2(i_1,parts_1.len-1); goto LA1_;
				}
				part_1 = (&parts_1.p->data[i_1]);
				{
					NimStringV2 colontmpD__2;
					NimStringV2 colontmpD__3;
					NimStringV2 headersRaw_1;
					NimStringV2 colontmpD__4;
					NimStringV2 content_1;
					NimStringV2 cleanContent_1;
					NI headerEndFn_1;
					NI TM__hO9bfka8UKA7JUzPEOgt2LQ_21;
					tyObject_HSlice__OAVEPXFBgbTm1jVNAuKEpw T33_;
					NI TM__hO9bfka8UKA7JUzPEOgt2LQ_22;
					tyObject_HSlice__hCONkfGh5Y79cjKbAHxROMQ T34_;
					NimStringV2 T35_;
					colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
					colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
					headersRaw_1.len = 0; headersRaw_1.p = NIM_NIL;
					colontmpD__4.len = 0; colontmpD__4.p = NIM_NIL;
					content_1.len = 0; content_1.p = NIM_NIL;
					cleanContent_1.len = 0; cleanContent_1.p = NIM_NIL;
					nimln_(27);					{
						NIM_BOOL T25_;
						T25_ = (NIM_BOOL)0;
						colontmpD__2 = nsuStrip((*part_1), NIM_TRUE, NIM_TRUE, TM__hO9bfka8UKA7JUzPEOgt2LQ_13);
						if (NIM_UNLIKELY(*nimErr_)) goto LA22_;
						T25_ = eqStrings(colontmpD__2, TM__hO9bfka8UKA7JUzPEOgt2LQ_14);
						if (T25_) goto LA26_;
						colontmpD__3 = nsuStrip((*part_1), NIM_TRUE, NIM_TRUE, TM__hO9bfka8UKA7JUzPEOgt2LQ_13);
						if (NIM_UNLIKELY(*nimErr_)) goto LA22_;
						T25_ = (colontmpD__3.len == 0);
LA26_: ;
						if (!T25_) goto LA27_;
						nimlf_(394, "system.nim");						if (cleanContent_1.p && !(cleanContent_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(cleanContent_1.p);
}
						if (content_1.p && !(content_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(content_1.p);
}
						if (colontmpD__4.p && !(colontmpD__4.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__4.p);
}
						if (headersRaw_1.p && !(headersRaw_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(headersRaw_1.p);
}
						if (colontmpD__3.p && !(colontmpD__3.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__3.p);
}
						if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
						nimlf_(27, "multipart.nim");						goto LA21;
					}
LA27_: ;
					nimln_(31);					headerEndFn_1 = nsuFindStr((*part_1), TM__hO9bfka8UKA7JUzPEOgt2LQ_16, ((NI)0), ((NI)-1));
					if (NIM_UNLIKELY(*nimErr_)) goto LA22_;
					nimln_(32);					{
						if (!(headerEndFn_1 == ((NI)-1))) goto LA31_;
						nimlf_(394, "system.nim");						if (cleanContent_1.p && !(cleanContent_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(cleanContent_1.p);
}
						if (content_1.p && !(content_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(content_1.p);
}
						if (colontmpD__4.p && !(colontmpD__4.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__4.p);
}
						if (headersRaw_1.p && !(headersRaw_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(headersRaw_1.p);
}
						if (colontmpD__3.p && !(colontmpD__3.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__3.p);
}
						if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
						nimlf_(32, "multipart.nim");						goto LA21;
					}
LA31_: ;
					nimln_(34);					nimlf_(53, "indices.nim");					if (nimSubInt(headerEndFn_1, ((NI)1), &TM__hO9bfka8UKA7JUzPEOgt2LQ_21)) { raiseOverflow(); goto LA22_;
					};
					nimlf_(34, "multipart.nim");					T33_ = dotdot___stdZstrbasics_u48(((NI)0), (NI)(TM__hO9bfka8UKA7JUzPEOgt2LQ_21));
					colontmpD__4 = X5BX5D___pureZstrutils_u1291((*part_1), T33_);
					if (NIM_UNLIKELY(*nimErr_)) goto LA22_;
					headersRaw_1 = nsuStrip(colontmpD__4, NIM_TRUE, NIM_TRUE, TM__hO9bfka8UKA7JUzPEOgt2LQ_13);
					if (NIM_UNLIKELY(*nimErr_)) goto LA22_;
					nimln_(35);					if (nimAddInt(headerEndFn_1, ((NI)4), &TM__hO9bfka8UKA7JUzPEOgt2LQ_22)) { raiseOverflow(); goto LA22_;
					};
					T34_ = dotdot___stdZenumutils_u105((NI)(TM__hO9bfka8UKA7JUzPEOgt2LQ_22), ((NI)1));
					content_1 = X5BX5D___pureZstrutils_u1319((*part_1), T34_);
					if (NIM_UNLIKELY(*nimErr_)) goto LA22_;
					T35_.len = 0; T35_.p = NIM_NIL;
					nimln_(38);					{
						NIM_BOOL T38_;
						tyObject_HSlice__hCONkfGh5Y79cjKbAHxROMQ T41_;
						T38_ = (NIM_BOOL)0;
						T38_ = nsuEndsWith(content_1, TM__hO9bfka8UKA7JUzPEOgt2LQ_24);
						if (NIM_UNLIKELY(*nimErr_)) goto LA22_;
						if (!T38_) goto LA39_;
						T41_ = dotdot___stdZenumutils_u105(((NI)0), ((NI)3));
						cleanContent_1 = X5BX5D___pureZstrutils_u1319(content_1, T41_);
						if (NIM_UNLIKELY(*nimErr_)) goto LA22_;
					}
					goto LA36_;
LA39_: ;
					{
						nimln_(39);						cleanContent_1 = content_1;
						nimlf_(1715, "system.nim");						eqwasMoved___system_u2769((&content_1));
					}
LA36_: ;
					nimlf_(43, "multipart.nim");					{
						NIM_BOOL T45_;
						NimStringV2 filename_1;
						NimStringV2 fieldname_1;
						NimStringV2 partContentType_1;
						NimStringV2 nameMarker_1;
						NimStringV2 fnMarker_1;
						NI nameStart_1;
						NI fnStart_1;
						T45_ = (NIM_BOOL)0;
						T45_ = contains__pureZstrutils_u1900(headersRaw_1, TM__hO9bfka8UKA7JUzPEOgt2LQ_26);
						if (NIM_UNLIKELY(*nimErr_)) goto LA22_;
						if (!T45_) goto LA46_;
						filename_1.len = 0; filename_1.p = NIM_NIL;
						fieldname_1.len = 0; fieldname_1.p = NIM_NIL;
						partContentType_1.len = 0; partContentType_1.p = NIM_NIL;
						nameMarker_1.len = 0; nameMarker_1.p = NIM_NIL;
						fnMarker_1.len = 0; fnMarker_1.p = NIM_NIL;
						nimln_(44);						filename_1 = TM__hO9bfka8UKA7JUzPEOgt2LQ_28;
						nimln_(45);						fieldname_1 = TM__hO9bfka8UKA7JUzPEOgt2LQ_29;
						nimln_(46);						partContentType_1 = TM__hO9bfka8UKA7JUzPEOgt2LQ_31;
						nimln_(49);						nameMarker_1 = TM__hO9bfka8UKA7JUzPEOgt2LQ_33;
						nimln_(50);						nameStart_1 = nsuFindStr(headersRaw_1, nameMarker_1, ((NI)0), ((NI)-1));
						if (NIM_UNLIKELY(*nimErr_)) goto LA22_;
						nimln_(51);						{
							NimStringV2 rest_1;
							NI TM__hO9bfka8UKA7JUzPEOgt2LQ_34;
							tyObject_HSlice__hCONkfGh5Y79cjKbAHxROMQ T52_;
							NI nameEnd_1;
							if (!!((nameStart_1 == ((NI)-1)))) goto LA50_;
							rest_1.len = 0; rest_1.p = NIM_NIL;
							nimln_(52);							if (nimAddInt(nameStart_1, nameMarker_1.len, &TM__hO9bfka8UKA7JUzPEOgt2LQ_34)) { raiseOverflow(); goto LA22_;
							};
							T52_ = dotdot___stdZenumutils_u105((NI)(TM__hO9bfka8UKA7JUzPEOgt2LQ_34), ((NI)1));
							rest_1 = X5BX5D___pureZstrutils_u1319(headersRaw_1, T52_);
							if (NIM_UNLIKELY(*nimErr_)) goto LA22_;
							nimln_(53);							nameEnd_1 = nsuFindStr(rest_1, TM__hO9bfka8UKA7JUzPEOgt2LQ_36, ((NI)0), ((NI)-1));
							if (NIM_UNLIKELY(*nimErr_)) goto LA22_;
							nimln_(54);							{
								NI TM__hO9bfka8UKA7JUzPEOgt2LQ_37;
								tyObject_HSlice__OAVEPXFBgbTm1jVNAuKEpw T57_;
								NimStringV2 T58_;
								if (!!((nameEnd_1 == ((NI)-1)))) goto LA55_;
								nimlf_(1715, "system.nim");								nimlf_(55, "multipart.nim");								nimlf_(53, "indices.nim");								if (nimSubInt(nameEnd_1, ((NI)1), &TM__hO9bfka8UKA7JUzPEOgt2LQ_37)) { raiseOverflow(); goto LA22_;
								};
								nimlf_(55, "multipart.nim");								T57_ = dotdot___stdZstrbasics_u48(((NI)0), (NI)(TM__hO9bfka8UKA7JUzPEOgt2LQ_37));
								T58_.len = 0; T58_.p = NIM_NIL;
								T58_ = X5BX5D___pureZstrutils_u1291(rest_1, T57_);
								if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T58_); goto LA22_;}
								nimlf_(1715, "system.nim");								eqsink___system_u2778((&fieldname_1), T58_);
							}
LA55_: ;
							nimln_(394);							if (rest_1.p && !(rest_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(rest_1.p);
}
						}
LA50_: ;
						nimlf_(58, "multipart.nim");						fnMarker_1 = TM__hO9bfka8UKA7JUzPEOgt2LQ_38;
						nimln_(59);						fnStart_1 = nsuFindStr(headersRaw_1, fnMarker_1, ((NI)0), ((NI)-1));
						if (NIM_UNLIKELY(*nimErr_)) goto LA22_;
						nimln_(60);						{
							NimStringV2 rest_2;
							NI TM__hO9bfka8UKA7JUzPEOgt2LQ_39;
							tyObject_HSlice__hCONkfGh5Y79cjKbAHxROMQ T63_;
							NI fnEnd_1;
							if (!!((fnStart_1 == ((NI)-1)))) goto LA61_;
							rest_2.len = 0; rest_2.p = NIM_NIL;
							nimln_(61);							if (nimAddInt(fnStart_1, fnMarker_1.len, &TM__hO9bfka8UKA7JUzPEOgt2LQ_39)) { raiseOverflow(); goto LA22_;
							};
							T63_ = dotdot___stdZenumutils_u105((NI)(TM__hO9bfka8UKA7JUzPEOgt2LQ_39), ((NI)1));
							rest_2 = X5BX5D___pureZstrutils_u1319(headersRaw_1, T63_);
							if (NIM_UNLIKELY(*nimErr_)) goto LA22_;
							nimln_(62);							fnEnd_1 = nsuFindStr(rest_2, TM__hO9bfka8UKA7JUzPEOgt2LQ_40, ((NI)0), ((NI)-1));
							if (NIM_UNLIKELY(*nimErr_)) goto LA22_;
							nimln_(63);							{
								NI TM__hO9bfka8UKA7JUzPEOgt2LQ_41;
								tyObject_HSlice__OAVEPXFBgbTm1jVNAuKEpw T68_;
								NimStringV2 T69_;
								if (!!((fnEnd_1 == ((NI)-1)))) goto LA66_;
								nimlf_(1715, "system.nim");								nimlf_(64, "multipart.nim");								nimlf_(53, "indices.nim");								if (nimSubInt(fnEnd_1, ((NI)1), &TM__hO9bfka8UKA7JUzPEOgt2LQ_41)) { raiseOverflow(); goto LA22_;
								};
								nimlf_(64, "multipart.nim");								T68_ = dotdot___stdZstrbasics_u48(((NI)0), (NI)(TM__hO9bfka8UKA7JUzPEOgt2LQ_41));
								T69_.len = 0; T69_.p = NIM_NIL;
								T69_ = X5BX5D___pureZstrutils_u1291(rest_2, T68_);
								if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T69_); goto LA22_;}
								nimlf_(1715, "system.nim");								eqsink___system_u2778((&filename_1), T69_);
							}
LA66_: ;
							nimln_(394);							if (rest_2.p && !(rest_2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(rest_2.p);
}
						}
LA61_: ;
						nimlf_(67, "multipart.nim");						{
							NIM_BOOL T72_;
							T72_ = (NIM_BOOL)0;
							T72_ = contains__pureZstrutils_u1900(headersRaw_1, TM__hO9bfka8UKA7JUzPEOgt2LQ_43);
							if (NIM_UNLIKELY(*nimErr_)) goto LA22_;
							if (!T72_) goto LA73_;
						}
LA73_: ;
						nimln_(71);						{
							NIM_BOOL T77_;
							tyObject_UploadedFile__Ttgk4NpE79ahXZ9aF4eH5jFg T81_;
							NimStringV2 blitTmp_1;
							NimStringV2 blitTmp_2;
							NimStringV2 blitTmp_3;
							T77_ = (NIM_BOOL)0;
							T77_ = (((NI)0) < fieldname_1.len);
							if (!(T77_)) goto LA78_;
							T77_ = (((NI)0) < filename_1.len);
LA78_: ;
							if (!T77_) goto LA79_;
							nimln_(72);							nimln_(73);							blitTmp_1 = filename_1;
							nimlf_(1715, "system.nim");							eqwasMoved___system_u2769((&filename_1));
							T81_.filename = blitTmp_1;
							nimlf_(74, "multipart.nim");							blitTmp_2 = partContentType_1;
							nimlf_(1715, "system.nim");							eqwasMoved___system_u2769((&partContentType_1));
							T81_.contentType = blitTmp_2;
							nimlf_(75, "multipart.nim");							blitTmp_3 = cleanContent_1;
							nimlf_(1715, "system.nim");							eqwasMoved___system_u2769((&cleanContent_1));
							T81_.content = blitTmp_3;
							nimlf_(72, "multipart.nim");							X5BX5Deq___pkgZjazzyZutilsZmultipart_u290((&result), fieldname_1, (&T81_));
							if (NIM_UNLIKELY(*nimErr_)) goto LA22_;
						}
LA79_: ;
						nimlf_(394, "system.nim");						if (fnMarker_1.p && !(fnMarker_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(fnMarker_1.p);
}
						if (nameMarker_1.p && !(nameMarker_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(nameMarker_1.p);
}
						if (partContentType_1.p && !(partContentType_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(partContentType_1.p);
}
						if (fieldname_1.p && !(fieldname_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(fieldname_1.p);
}
						if (filename_1.p && !(filename_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(filename_1.p);
}
					}
LA46_: ;
					{
						LA22_:;
					}
					{
						if (cleanContent_1.p && !(cleanContent_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(cleanContent_1.p);
}
						if (content_1.p && !(content_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(content_1.p);
}
						if (colontmpD__4.p && !(colontmpD__4.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__4.p);
}
						if (headersRaw_1.p && !(headersRaw_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(headersRaw_1.p);
}
						if (colontmpD__3.p && !(colontmpD__3.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__3.p);
}
						if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
					}
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
				} LA21: ;
				nimlf_(13, "iterators.nim");				i_1 += ((NI)1);
				nimlf_(254, "iterators.nim");				{
					NI T86_;
					T86_ = parts_1.len;
					if (!!((T86_ == L_1))) goto LA87_;
					failedAssertImpl__stdZassertions_u95(TM__hO9bfka8UKA7JUzPEOgt2LQ_45);
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
				}
LA87_: ;
			} LA20: ;
		}
	}
	{
		LA1_:;
	}
	{
		nimlf_(2219, "system.nim");		eqdestroy___system_u5657(parts_1);
		nimln_(394);		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
		if (boundary_1.p && !(boundary_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(boundary_1.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
