/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -fno-strict-aliasing -pthread -I/home/icarogdo/.nimble/pkgs2/bearssl-0.2.10-e53ab85b8c4c1ce3aa1f4eb251c0ab29e08d4972/bearssl/abi -I/home/icarogdo/.nimble/pkgs2/bearssl-0.2.10-e53ab85b8c4c1ce3aa1f4eb251c0ab29e08d4972/bearssl/abi/../csources/src/ -I/home/icarogdo/.nimble/pkgs2/bearssl-0.2.10-e53ab85b8c4c1ce3aa1f4eb251c0ab29e08d4972/bearssl/abi/../csources/inc/ -I/home/icarogdo/.nimble/pkgs2/bearssl-0.2.10-e53ab85b8c4c1ce3aa1f4eb251c0ab29e08d4972/bearssl/abi/../csources/tools/ -DBR_USE_UNIX_TIME=1 -DBR_USE_URANDOM=1 -DBR_LE_UNALIGNED=1 -DBR_64=1  -DBR_amd64=1 -DBR_INT128=1 -Wno-incompatible-pointer-types -I/usr/include/webkitgtk-4.1 -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/cloudproviders -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/glycin-2 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/atk-1.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/fribidi -I/usr/include/pixman-1 -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gio-unix-2.0 -I/usr/include/libsoup-3.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-6 -pthread -O3 -fno-ident -fno-math-errno   -I/usr/lib/nim/lib -I/home/icarogdo/dev/macroobras-jazzy/app/macroobras/src -o /home/icarogdo/dev/macroobras-jazzy/app/macroobras/.nimcache-release/@njazzy-0.4.5-4fdda426bdb506437985763b18fb2c79ca01e6e0@sjazzy@sauth@ssecurity.nim.c.o /home/icarogdo/dev/macroobras-jazzy/app/macroobras/.nimcache-release/@njazzy-0.4.5-4fdda426bdb506437985763b18fb2c79ca01e6e0@sjazzy@sauth@ssecurity.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4511)(void);
static N_INLINE(void, popFrame)(void);
extern NIM_THREADVAR TFrame* framePtr__system_u2809;
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2809 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2809).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2809;
	framePtr__system_u2809 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4511();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2809 = (*framePtr__system_u2809).prev;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, constantTimeCompare__pkgZjazzyZauthZsecurity_u7)(NimStringV2 a_p0, NimStringV2 b_p1) {
	NIM_BOOL result;
	NU8 diff_1;
	nimfr_("constantTimeCompare", "security.nim");
{	nimlf_(8, "security.nim");	{
		if (!!((a_p0.len == b_p1.len))) goto LA3_;
		nimln_(9);		nimln_(7);		nimln_(9);		result = NIM_FALSE;
		goto BeforeRet_;
	}
LA3_: ;
	nimln_(10);	diff_1 = ((NU8)0);
	{
		NI i_1;
		NI colontmp_;
		NI i_2;
		i_1 = (NI)0;
		colontmp_ = (NI)0;
		nimlf_(126, "iterators_1.nim");		nimlf_(11, "security.nim");		colontmp_ = a_p0.len;
		nimlf_(128, "iterators_1.nim");		i_2 = ((NI)0);
		{
			nimln_(129);			while (1) {
				NI TM__ECdU3AYr0Nap69bT8fqOpKg_2;
				if (!(i_2 < colontmp_)) goto LA7;
				nimlf_(11, "security.nim");				i_1 = i_2;
				nimln_(12);				if (i_1 < 0 || i_1 >= a_p0.len){ raiseIndexError2(i_1,a_p0.len-1); goto BeforeRet_;
				}
				if (i_1 < 0 || i_1 >= b_p1.len){ raiseIndexError2(i_1,b_p1.len-1); goto BeforeRet_;
				}
				diff_1 = (NU8)(diff_1 | (NU8)(((NU8) (((NU8)(a_p0.p->data[i_1])))) ^ ((NU8) (((NU8)(b_p1.p->data[i_1]))))));
				nimlf_(131, "iterators_1.nim");				if (nimAddInt(i_2, ((NI)1), &TM__ECdU3AYr0Nap69bT8fqOpKg_2)) { raiseOverflow(); goto BeforeRet_;
				};
				i_2 = (NI)(TM__ECdU3AYr0Nap69bT8fqOpKg_2);
			} LA7: ;
		}
	}
	nimlf_(13, "security.nim");	nimln_(7);	nimln_(13);	result = (diff_1 == ((NU8)0));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
