/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -fno-strict-aliasing -pthread -I/home/icarogdo/.nimble/pkgs2/bearssl-0.2.10-e53ab85b8c4c1ce3aa1f4eb251c0ab29e08d4972/bearssl/abi -I/home/icarogdo/.nimble/pkgs2/bearssl-0.2.10-e53ab85b8c4c1ce3aa1f4eb251c0ab29e08d4972/bearssl/abi/../csources/src/ -I/home/icarogdo/.nimble/pkgs2/bearssl-0.2.10-e53ab85b8c4c1ce3aa1f4eb251c0ab29e08d4972/bearssl/abi/../csources/inc/ -I/home/icarogdo/.nimble/pkgs2/bearssl-0.2.10-e53ab85b8c4c1ce3aa1f4eb251c0ab29e08d4972/bearssl/abi/../csources/tools/ -DBR_USE_UNIX_TIME=1 -DBR_USE_URANDOM=1 -DBR_LE_UNALIGNED=1 -DBR_64=1  -DBR_amd64=1 -DBR_INT128=1 -Wno-incompatible-pointer-types -I/usr/include/webkitgtk-4.1 -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/cloudproviders -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/glycin-2 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/atk-1.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/fribidi -I/usr/include/pixman-1 -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gio-unix-2.0 -I/usr/include/libsoup-3.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-6 -pthread -O3 -fno-ident -fno-math-errno   -I/usr/lib/nim/lib -I/home/icarogdo/dev/macroobras-jazzy/app/macroobras/src -o /home/icarogdo/dev/macroobras-jazzy/app/macroobras/.nimcache-release/@njazzy-0.4.5-4fdda426bdb506437985763b18fb2c79ca01e6e0@sjazzy@score@sconfig.nim.c.o /home/icarogdo/dev/macroobras-jazzy/app/macroobras/.nimcache-release/@njazzy-0.4.5-4fdda426bdb506437985763b18fb2c79ca01e6e0@sjazzy@score@sconfig.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tyObject_Table__4GRLZ9aW6ODpuhpKCQowSeg tyObject_Table__4GRLZ9aW6ODpuhpKCQowSeg;
typedef struct tySequence__SFipDZIkFtPcrLs0AGBBjQ tySequence__SFipDZIkFtPcrLs0AGBBjQ;
typedef struct tySequence__SFipDZIkFtPcrLs0AGBBjQ_Content tySequence__SFipDZIkFtPcrLs0AGBBjQ_Content;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content;
typedef struct tyTuple__8ZxhPt1NwfElsJs8zUSV9bg tyTuple__8ZxhPt1NwfElsJs8zUSV9bg;
struct tySequence__SFipDZIkFtPcrLs0AGBBjQ {
  NI len; tySequence__SFipDZIkFtPcrLs0AGBBjQ_Content* p;
};
struct tyObject_Table__4GRLZ9aW6ODpuhpKCQowSeg {
	tySequence__SFipDZIkFtPcrLs0AGBBjQ data;
	NI counter;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef NU8 tyEnum_FileMode__BzUbNzIgtuxKp78IxN69cmQ;
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  NI len; tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content* p;
};
typedef NU8 tySet_tyChar__nmiMWKVIe46vacnhAFrQvw[32];
typedef NimStringV2 tyArray__YgExxhfgKcesA5EOUj1MOA[1];
struct tyTuple__8ZxhPt1NwfElsJs8zUSV9bg {
	NI Field0;
	NimStringV2 Field1;
	NimStringV2 Field2;
};
struct tySequence__SFipDZIkFtPcrLs0AGBBjQ_Content { NI cap; tyTuple__8ZxhPt1NwfElsJs8zUSV9bg data[SEQ_DECL_SIZE]; };
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(tyObject_Table__4GRLZ9aW6ODpuhpKCQowSeg, initTable__pkgZjazzyZcoreZconfig_u28)(NI initialSize_p0);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZjazzyZcoreZconfig_u167)(tyObject_Table__4GRLZ9aW6ODpuhpKCQowSeg* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, loadEnv__pkgZjazzyZcoreZconfig_u226)(NimStringV2 filename_p0, NIM_BOOL silent_p1);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nosfileExists)(NimStringV2 filename_p0);
N_LIB_PRIVATE N_NIMCALL(FILE*, open__stdZsyncio_u487)(NimStringV2 filename_p0, tyEnum_FileMode__BzUbNzIgtuxKp78IxN69cmQ mode_p1, NI bufSize_p2);
N_NIMCALL(NimStringV2, rawNewString)(NI cap_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, readLine__stdZsyncio_u289)(FILE* f_p0, NimStringV2* line_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuStrip)(NimStringV2 s_p0, NIM_BOOL leading_p1, NIM_BOOL trailing_p2, tySet_tyChar__nmiMWKVIe46vacnhAFrQvw chars_p3);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nsuStartsWith)(NimStringV2 s_p0, NimStringV2 prefix_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u5657)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ dest_p0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(tySequence__sM4lkSb7zS6F7OVMvW9cffQ, nsuSplitChar)(NimStringV2 s_p0, NIM_CHAR sep_p1, NI maxsplit_p2);
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq___pkgZjazzyZcoreZconfig_u271)(tyObject_Table__4GRLZ9aW6ODpuhpKCQowSeg* t_p0, NimStringV2 key_p1, NimStringV2 val_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
static N_INLINE(void, eqdestroy___system_u281)(NimStringV2 x_p0);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4511)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, close__stdZsyncio_u268)(FILE* f_p0);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, echoBinSafe)(NimStringV2* args_p0, NI args_p0Len_0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasKey__pkgZjazzyZcoreZconfig_u1500)(tyObject_Table__4GRLZ9aW6ODpuhpKCQowSeg t_p0, NimStringV2 key_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u2772)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2*, X5BX5D___pkgZjazzyZcoreZconfig_u1562)(tyObject_Table__4GRLZ9aW6ODpuhpKCQowSeg* t_p0, NimStringV2 key_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, getEnv__stdZenvvars_u15)(NimStringV2 key_p0, NimStringV2 default_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, getAppEnv__pkgZjazzyZcoreZconfig_u1632)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuToLowerAsciiStr)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, getConfig__pkgZjazzyZcoreZconfig_u1460)(NimStringV2 key_p0, NimStringV2 default_p1);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1);
static N_INLINE(NIM_BOOL, equalMem__system_u1763)(void* a_p0, void* b_p1, NI size_p2);
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pkgZjazzyZcoreZconfig_u170)(tyObject_Table__4GRLZ9aW6ODpuhpKCQowSeg* dest_p0, tyObject_Table__4GRLZ9aW6ODpuhpKCQowSeg src_p1);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
static NIM_CONST tySet_tyChar__nmiMWKVIe46vacnhAFrQvw TM__EXonQ9aP7vCD9cYhGU8VTIug_2 = {
0x00, 0x3e, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__EXonQ9aP7vCD9cYhGU8VTIug_3 = { 1 | NIM_STRLIT_FLAG, "#" };
static const NimStringV2 TM__EXonQ9aP7vCD9cYhGU8VTIug_4 = {1, (NimStrPayload*)&TM__EXonQ9aP7vCD9cYhGU8VTIug_3};
static const struct {
  NI cap; NIM_CHAR data[17+1];
} TM__EXonQ9aP7vCD9cYhGU8VTIug_5 = { 17 | NIM_STRLIT_FLAG, "\342\232\240\357\270\217  Warning: " };
static const NimStringV2 TM__EXonQ9aP7vCD9cYhGU8VTIug_6 = {17, (NimStrPayload*)&TM__EXonQ9aP7vCD9cYhGU8VTIug_5};
static const struct {
  NI cap; NIM_CHAR data[11+1];
} TM__EXonQ9aP7vCD9cYhGU8VTIug_7 = { 11 | NIM_STRLIT_FLAG, " not found." };
static const NimStringV2 TM__EXonQ9aP7vCD9cYhGU8VTIug_8 = {11, (NimStrPayload*)&TM__EXonQ9aP7vCD9cYhGU8VTIug_7};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__EXonQ9aP7vCD9cYhGU8VTIug_9 = { 4 | NIM_STRLIT_FLAG, ".env" };
static const NimStringV2 TM__EXonQ9aP7vCD9cYhGU8VTIug_10 = {4, (NimStrPayload*)&TM__EXonQ9aP7vCD9cYhGU8VTIug_9};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__EXonQ9aP7vCD9cYhGU8VTIug_11 = { 7 | NIM_STRLIT_FLAG, "APP_ENV" };
static const NimStringV2 TM__EXonQ9aP7vCD9cYhGU8VTIug_12 = {7, (NimStrPayload*)&TM__EXonQ9aP7vCD9cYhGU8VTIug_11};
static const struct {
  NI cap; NIM_CHAR data[11+1];
} TM__EXonQ9aP7vCD9cYhGU8VTIug_13 = { 11 | NIM_STRLIT_FLAG, "development" };
static const NimStringV2 TM__EXonQ9aP7vCD9cYhGU8VTIug_14 = {11, (NimStrPayload*)&TM__EXonQ9aP7vCD9cYhGU8VTIug_13};
static const struct {
  NI cap; NIM_CHAR data[10+1];
} TM__EXonQ9aP7vCD9cYhGU8VTIug_15 = { 10 | NIM_STRLIT_FLAG, "production" };
static const NimStringV2 TM__EXonQ9aP7vCD9cYhGU8VTIug_16 = {10, (NimStrPayload*)&TM__EXonQ9aP7vCD9cYhGU8VTIug_15};
static const NimStringV2 TM__EXonQ9aP7vCD9cYhGU8VTIug_17 = {11, (NimStrPayload*)&TM__EXonQ9aP7vCD9cYhGU8VTIug_13};
N_LIB_PRIVATE tyObject_Table__4GRLZ9aW6ODpuhpKCQowSeg configs__pkgZjazzyZcoreZconfig_u225;
extern NIM_THREADVAR TFrame* framePtr__system_u2809;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4293;
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	nimSetMem__system_u2188(p_p0, ((int)0), size_p1);
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2809 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2809).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2809;
	framePtr__system_u2809 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4511();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2809 = (*framePtr__system_u2809).prev;
}
static N_INLINE(void, eqdestroy___system_u281)(NimStringV2 x_p0) {
	nimfr_("=destroy", "system.nim");
	popFrame();
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
	{
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		copyMem__system_u1755(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		(*dest_p0).len += src_p1.len;
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4293);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, loadEnv__pkgZjazzyZcoreZconfig_u226)(NimStringV2 filename_p0, NIM_BOOL silent_p1) {
NIM_BOOL oldNimErrFin7_;
NIM_BOOL* nimErr_;
	nimfr_("loadEnv", "config.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(6, "config.nim");	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nosfileExists(filename_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!T3_) goto LA4_;
		{
			NimStringV2 line_1;
			FILE* f_1;
			NimStringV2 res_1;
			line_1.len = 0; line_1.p = NIM_NIL;
			nimlf_(944, "syncio.nim");			f_1 = open__stdZsyncio_u487(filename_p0, ((tyEnum_FileMode__BzUbNzIgtuxKp78IxN69cmQ)0), ((NI)8000));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			res_1.len = 0; res_1.p = NIM_NIL;
			nimln_(946);			res_1 = rawNewString(((NI)80));
			{
				nimln_(947);				while (1) {
					NIM_BOOL T11_;
					T11_ = (NIM_BOOL)0;
					T11_ = readLine__stdZsyncio_u289(f_1, (&res_1));
					if (NIM_UNLIKELY(*nimErr_)) goto LA8_;
					if (!T11_) goto LA10;
					nimlf_(7, "config.nim");					line_1 = res_1;
					{
						NimStringV2 trimmed_1;
						tySequence__sM4lkSb7zS6F7OVMvW9cffQ parts_1;
						trimmed_1.len = 0; trimmed_1.p = NIM_NIL;
						parts_1.len = 0; parts_1.p = NIM_NIL;
						nimln_(8);						trimmed_1 = nsuStrip(line_1, NIM_TRUE, NIM_TRUE, TM__EXonQ9aP7vCD9cYhGU8VTIug_2);
						if (NIM_UNLIKELY(*nimErr_)) goto LA13_;
						nimln_(9);						{
							NIM_BOOL T16_;
							T16_ = (NIM_BOOL)0;
							T16_ = (trimmed_1.len == ((NI)0));
							if (T16_) goto LA17_;
							T16_ = nsuStartsWith(trimmed_1, TM__EXonQ9aP7vCD9cYhGU8VTIug_4);
							if (NIM_UNLIKELY(*nimErr_)) goto LA13_;
LA17_: ;
							if (!T16_) goto LA18_;
							nimlf_(2219, "system.nim");							eqdestroy___system_u5657(parts_1);
							nimln_(394);							if (trimmed_1.p && !(trimmed_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(trimmed_1.p);
}
							nimlf_(10, "config.nim");							goto LA12;
						}
LA18_: ;
						nimln_(11);						parts_1 = nsuSplitChar(trimmed_1, 61, ((NI)1));
						if (NIM_UNLIKELY(*nimErr_)) goto LA13_;
						nimln_(12);						{
							NI T22_;
							NimStringV2 colontmpD_;
							NimStringV2 T25_;
							T22_ = parts_1.len;
							if (!(T22_ == ((NI)2))) goto LA23_;
							colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
							nimln_(13);							if (((NI)0) < 0 || ((NI)0) >= parts_1.len){ raiseIndexError2(((NI)0),parts_1.len-1); goto LA13_;
							}
							colontmpD_ = nsuStrip(parts_1.p->data[((NI)0)], NIM_TRUE, NIM_TRUE, TM__EXonQ9aP7vCD9cYhGU8VTIug_2);
							if (NIM_UNLIKELY(*nimErr_)) goto LA13_;
							if (((NI)1) < 0 || ((NI)1) >= parts_1.len){ raiseIndexError2(((NI)1),parts_1.len-1); goto LA13_;
							}
							T25_.len = 0; T25_.p = NIM_NIL;
							T25_ = nsuStrip(parts_1.p->data[((NI)1)], NIM_TRUE, NIM_TRUE, TM__EXonQ9aP7vCD9cYhGU8VTIug_2);
							if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T25_); goto LA13_;}
							X5BX5Deq___pkgZjazzyZcoreZconfig_u271((&configs__pkgZjazzyZcoreZconfig_u225), colontmpD_, T25_);
							if (NIM_UNLIKELY(*nimErr_)) goto LA13_;
							nimlf_(394, "system.nim");							if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
						}
LA23_: ;
						{
							LA13_:;
						}
						{
							nimln_(2219);							eqdestroy___system_u5657(parts_1);
							nimln_(394);							if (trimmed_1.p && !(trimmed_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(trimmed_1.p);
}
						}
						if (NIM_UNLIKELY(*nimErr_)) goto LA8_;
					} LA12: ;
				} LA10: ;
			}
			{
				LA8_:;
			}
			{
				if (res_1.p && !(res_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(res_1.p);
}
			}
			if (NIM_UNLIKELY(*nimErr_)) goto LA7_;
			{
				LA7_:;
			}
			{
				oldNimErrFin7_ = *nimErr_; *nimErr_ = NIM_FALSE;
				nimlf_(949, "syncio.nim");				close__stdZsyncio_u268(f_1);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				*nimErr_ = oldNimErrFin7_;
			}
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
	}
	goto LA1_;
LA4_: ;
	{
		nimlf_(15, "config.nim");		{
			NimStringV2 colontmpD__2;
			tyArray__YgExxhfgKcesA5EOUj1MOA T38_;
			NimStringV2 T39_;
			if (!!(silent_p1)) goto LA35_;
			colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
			nimln_(16);			T39_.len = 0; T39_.p = NIM_NIL;
			T39_ = rawNewString(filename_p0.len + 28);
appendString((&T39_), TM__EXonQ9aP7vCD9cYhGU8VTIug_6);
appendString((&T39_), filename_p0);
appendString((&T39_), TM__EXonQ9aP7vCD9cYhGU8VTIug_8);
			colontmpD__2 = T39_;
			T38_[0] = colontmpD__2;
			echoBinSafe(T38_, 1);
			{
				LA37_:;
			}
			{
				nimlf_(394, "system.nim");				if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
			}
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA35_: ;
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, getConfig__pkgZjazzyZcoreZconfig_u1460)(NimStringV2 key_p0, NimStringV2 default_p1) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("getConfig", "config.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimlf_(20, "config.nim");	{
		NIM_BOOL T3_;
		NimStringV2* T6_;
		T3_ = (NIM_BOOL)0;
		T3_ = hasKey__pkgZjazzyZcoreZconfig_u1500(configs__pkgZjazzyZcoreZconfig_u225, key_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!T3_) goto LA4_;
		nimln_(21);		nimlf_(1715, "system.nim");		nimlf_(21, "config.nim");		T6_ = (NimStringV2*)0;
		T6_ = X5BX5D___pkgZjazzyZcoreZconfig_u1562((&configs__pkgZjazzyZcoreZconfig_u225), key_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimlf_(1715, "system.nim");		eqcopy___system_u2772((&result), (*T6_));
		goto BeforeRet_;
	}
LA4_: ;
	nimlf_(22, "config.nim");	nimln_(18);	nimln_(22);	result = getEnv__stdZenvvars_u15(key_p0, default_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, getAppEnv__pkgZjazzyZcoreZconfig_u1632)(void) {
	NimStringV2 result;
	NimStringV2 colontmpD_;
NIM_BOOL* nimErr_;
	nimfr_("getAppEnv", "config.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	nimln_(32);	colontmpD_ = getConfig__pkgZjazzyZcoreZconfig_u1460(TM__EXonQ9aP7vCD9cYhGU8VTIug_12, TM__EXonQ9aP7vCD9cYhGU8VTIug_14);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	result = nsuToLowerAsciiStr(colontmpD_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		LA1_:;
	}
	{
		nimlf_(394, "system.nim");		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2) {
	int result;
	result = memcmp(a_p0, b_p1, ((size_t) (size_p2)));
	return result;
}
static N_INLINE(NIM_BOOL, equalMem__system_u1763)(void* a_p0, void* b_p1, NI size_p2) {
	NIM_BOOL result;
	int T1_;
	T1_ = (int)0;
	T1_ = nimCmpMem(a_p0, b_p1, size_p2);
	result = (T1_ == ((NI32)0));
	return result;
}
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1) {
	NIM_BOOL result;
	NI alen_1;
	NI blen_1;
	nimfr_("eqStrings", "strmantle.nim");
{	nimlf_(33, "strmantle.nim");	result = NIM_FALSE;
	nimln_(34);	alen_1 = a_p0.len;
	nimln_(35);	blen_1 = b_p1.len;
	nimln_(36);	{
		if (!(alen_1 == blen_1)) goto LA3_;
		nimln_(37);		{
			if (!(alen_1 == ((NI)0))) goto LA7_;
			nimln_(32);			nimln_(37);			result = NIM_TRUE;
			goto BeforeRet_;
		}
LA7_: ;
		nimln_(38);		nimln_(32);		nimln_(38);		result = equalMem__system_u1763(((void*) ((&a_p0.p->data[((NI)0)]))), ((void*) ((&b_p1.p->data[((NI)0)]))), (alen_1));
		goto BeforeRet_;
	}
LA3_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isProduction__pkgZjazzyZcoreZconfig_u1636)(void) {
	NIM_BOOL result;
	NimStringV2 colontmpD_;
NIM_BOOL* nimErr_;
	nimfr_("isProduction", "config.nim");
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	nimlf_(40, "config.nim");	colontmpD_ = getAppEnv__pkgZjazzyZcoreZconfig_u1632();
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	result = eqStrings(colontmpD_, TM__EXonQ9aP7vCD9cYhGU8VTIug_16);
	{
		LA1_:;
	}
	{
		nimlf_(394, "system.nim");		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isDevelopment__pkgZjazzyZcoreZconfig_u1634)(void) {
	NIM_BOOL result;
	NimStringV2 colontmpD_;
NIM_BOOL* nimErr_;
	nimfr_("isDevelopment", "config.nim");
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	nimlf_(36, "config.nim");	colontmpD_ = getAppEnv__pkgZjazzyZcoreZconfig_u1632();
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	result = eqStrings(colontmpD_, TM__EXonQ9aP7vCD9cYhGU8VTIug_17);
	{
		LA1_:;
	}
	{
		nimlf_(394, "system.nim");		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_Table__4GRLZ9aW6ODpuhpKCQowSeg, getAllConfigs__pkgZjazzyZcoreZconfig_u1628)(void) {
	tyObject_Table__4GRLZ9aW6ODpuhpKCQowSeg result;
	nimfr_("getAllConfigs", "config.nim");
{	nimZeroMem((void*)(&result), sizeof(tyObject_Table__4GRLZ9aW6ODpuhpKCQowSeg));
	nimlf_(26, "config.nim");	nimlf_(281, "tables.nim");	eqcopy___pkgZjazzyZcoreZconfig_u170((&result), configs__pkgZjazzyZcoreZconfig_u225);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, atnjazzyminus0dot4dot5minus4fdda426bdb506437985763b18fb2c79ca01e6e0atsjazzyatscoreatsconfigdotnim_Init000)(void) {
{
	tyObject_Table__4GRLZ9aW6ODpuhpKCQowSeg T1_;
NIM_BOOL* nimErr_;
	nimfr_("config", "config.nim");
nimErr_ = nimErrorFlag();
	nimlf_(3, "config.nim");	nimZeroMem((void*)(&T1_), sizeof(tyObject_Table__4GRLZ9aW6ODpuhpKCQowSeg));
	T1_ = initTable__pkgZjazzyZcoreZconfig_u28(((NI)32));
	if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___pkgZjazzyZcoreZconfig_u167(&T1_); goto BeforeRet_;}
	configs__pkgZjazzyZcoreZconfig_u225 = T1_;
	nimln_(43);	loadEnv__pkgZjazzyZcoreZconfig_u226(TM__EXonQ9aP7vCD9cYhGU8VTIug_10, NIM_TRUE);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	BeforeRet_: ;
	nimTestErrorFlag();
	popFrame();
}
}

