/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -fno-strict-aliasing -pthread -I/home/icarogdo/.nimble/pkgs2/bearssl-0.2.10-e53ab85b8c4c1ce3aa1f4eb251c0ab29e08d4972/bearssl/abi -I/home/icarogdo/.nimble/pkgs2/bearssl-0.2.10-e53ab85b8c4c1ce3aa1f4eb251c0ab29e08d4972/bearssl/abi/../csources/src/ -I/home/icarogdo/.nimble/pkgs2/bearssl-0.2.10-e53ab85b8c4c1ce3aa1f4eb251c0ab29e08d4972/bearssl/abi/../csources/inc/ -I/home/icarogdo/.nimble/pkgs2/bearssl-0.2.10-e53ab85b8c4c1ce3aa1f4eb251c0ab29e08d4972/bearssl/abi/../csources/tools/ -DBR_USE_UNIX_TIME=1 -DBR_USE_URANDOM=1 -DBR_LE_UNALIGNED=1 -DBR_64=1  -DBR_amd64=1 -DBR_INT128=1 -Wno-incompatible-pointer-types -I/usr/include/webkitgtk-4.1 -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/cloudproviders -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/glycin-2 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/atk-1.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/fribidi -I/usr/include/pixman-1 -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gio-unix-2.0 -I/usr/include/libsoup-3.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-6 -pthread -O3 -fno-ident -fno-math-errno   -I/usr/lib/nim/lib -I/home/icarogdo/dev/macroobras-jazzy/app/macroobras/src -o /home/icarogdo/dev/macroobras-jazzy/app/macroobras/.nimcache-release/@nwebby-0.2.1-1d9978ac16fdb56fad2ee9eaa0fcbb7860229d39@swebby@shttpheaders.nim.c.o /home/icarogdo/dev/macroobras-jazzy/app/macroobras/.nimcache-release/@nwebby-0.2.1-1d9978ac16fdb56fad2ee9eaa0fcbb7860229d39@swebby@shttpheaders.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tySequence__4eQHGndY6XBYpFOH09apV8Q tySequence__4eQHGndY6XBYpFOH09apV8Q;
typedef struct tySequence__4eQHGndY6XBYpFOH09apV8Q_Content tySequence__4eQHGndY6XBYpFOH09apV8Q_Content;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyTuple__UV3llMMYFckfui8YMBuUZA tyTuple__UV3llMMYFckfui8YMBuUZA;
struct tySequence__4eQHGndY6XBYpFOH09apV8Q {
  NI len; tySequence__4eQHGndY6XBYpFOH09apV8Q_Content* p;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tyTuple__UV3llMMYFckfui8YMBuUZA {
	NimStringV2 Field0;
	NimStringV2 Field1;
};
struct tySequence__4eQHGndY6XBYpFOH09apV8Q_Content { NI cap; tyTuple__UV3llMMYFckfui8YMBuUZA data[SEQ_DECL_SIZE]; };
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4511)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(tySequence__4eQHGndY6XBYpFOH09apV8Q*, toBase__pkgZwebbyZhttpheaders_u4)(tySequence__4eQHGndY6XBYpFOH09apV8Q* headers_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u2772)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NIMCALL(NI, nsuCmpIgnoreCase)(NimStringV2 a_p0, NimStringV2 b_p1);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u95)(NimStringV2 msg_p0);
N_LIB_PRIVATE N_NIMCALL(void, add__pkgZmummyZcommon_u157)(tySequence__4eQHGndY6XBYpFOH09apV8Q* x_p0, tyTuple__UV3llMMYFckfui8YMBuUZA* y_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, eqdup___system_u2775)(NimStringV2 src_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(tySequence__4eQHGndY6XBYpFOH09apV8Q*, toBase__pkgZwebbyZhttpheaders_u39)(tySequence__4eQHGndY6XBYpFOH09apV8Q* params_p0);
N_LIB_PRIVATE N_NIMCALL(tySequence__4eQHGndY6XBYpFOH09apV8Q, eqdup___stdZenvvars_u89)(tySequence__4eQHGndY6XBYpFOH09apV8Q src_p0);
static const struct {
  NI cap; NIM_CHAR data[90+1];
} TM__sIuaO7I9bEdU9c2qj3mZCcQg_2 = { 90 | NIM_STRLIT_FLAG, "iterators.nim(187, 11) `len(a) == L` the length of the seq changed while iterating over it" };
static const NimStringV2 TM__sIuaO7I9bEdU9c2qj3mZCcQg_3 = {90, (NimStrPayload*)&TM__sIuaO7I9bEdU9c2qj3mZCcQg_2};
static const struct {
  NI cap; NIM_CHAR data[90+1];
} TM__sIuaO7I9bEdU9c2qj3mZCcQg_4 = { 90 | NIM_STRLIT_FLAG, "iterators.nim(254, 11) `len(a) == L` the length of the seq changed while iterating over it" };
static const NimStringV2 TM__sIuaO7I9bEdU9c2qj3mZCcQg_5 = {90, (NimStrPayload*)&TM__sIuaO7I9bEdU9c2qj3mZCcQg_4};
static const NimStringV2 TM__sIuaO7I9bEdU9c2qj3mZCcQg_6 = {90, (NimStrPayload*)&TM__sIuaO7I9bEdU9c2qj3mZCcQg_4};
extern NIM_THREADVAR TFrame* framePtr__system_u2809;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4293;
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2809 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2809).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2809;
	framePtr__system_u2809 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4511();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2809 = (*framePtr__system_u2809).prev;
}
N_LIB_PRIVATE N_NIMCALL(tySequence__4eQHGndY6XBYpFOH09apV8Q*, toBase__pkgZwebbyZhttpheaders_u4)(tySequence__4eQHGndY6XBYpFOH09apV8Q* headers_p0) {
	tySequence__4eQHGndY6XBYpFOH09apV8Q* result;
	nimfr_("toBase", "httpheaders.nim");
	nimlf_(6, "httpheaders.nim");	result = (&(*headers_p0));
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4293);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq___pkgZwebbyZhttpheaders_u72)(tySequence__4eQHGndY6XBYpFOH09apV8Q* headers_p0, NimStringV2 key_p1, NimStringV2 value_p2) {
	NimStringV2 colontmpD_;
	NimStringV2 colontmpD__2;
	tySequence__4eQHGndY6XBYpFOH09apV8Q* T19_;
	tyTuple__UV3llMMYFckfui8YMBuUZA T20_;
NIM_BOOL* nimErr_;
	nimfr_("[]=", "httpheaders.nim");
{nimErr_ = nimErrorFlag();
	{
		NimStringV2 k_1;
		NimStringV2 v_1;
		NI i_1;
		tySequence__4eQHGndY6XBYpFOH09apV8Q* colontmp_;
		NI i_2;
		NI L_1;
		NI T3_;
		k_1.len = 0; k_1.p = NIM_NIL;
		v_1.len = 0; v_1.p = NIM_NIL;
		i_1 = (NI)0;
		colontmp_ = (tySequence__4eQHGndY6XBYpFOH09apV8Q*)0;
		nimlf_(180, "iterators.nim");		nimlf_(34, "httpheaders.nim");		colontmp_ = toBase__pkgZwebbyZhttpheaders_u4(headers_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto LA2_;
		nimlf_(182, "iterators.nim");		i_2 = ((NI)0);
		nimln_(183);		T3_ = (*colontmp_).len;
		L_1 = T3_;
		{
			nimln_(184);			while (1) {
				if (!(i_2 < L_1)) goto LA5;
				nimlf_(34, "httpheaders.nim");				i_1 = i_2;
				nimlf_(1715, "system.nim");				if (i_2 < 0 || i_2 >= (*colontmp_).len){ raiseIndexError2(i_2,(*colontmp_).len-1); goto LA2_;
				}
				eqcopy___system_u2772((&k_1), (*colontmp_).p->data[i_2].Field0);
				if (i_2 < 0 || i_2 >= (*colontmp_).len){ raiseIndexError2(i_2,(*colontmp_).len-1); goto LA2_;
				}
				eqcopy___system_u2772((&v_1), (*colontmp_).p->data[i_2].Field1);
				nimlf_(35, "httpheaders.nim");				{
					NI T8_;
					tySequence__4eQHGndY6XBYpFOH09apV8Q* T11_;
					T8_ = (NI)0;
					T8_ = nsuCmpIgnoreCase(k_1, key_p1);
					if (NIM_UNLIKELY(*nimErr_)) goto LA2_;
					if (!(T8_ == ((NI)0))) goto LA9_;
					nimlf_(1715, "system.nim");					nimlf_(36, "httpheaders.nim");					T11_ = (tySequence__4eQHGndY6XBYpFOH09apV8Q*)0;
					T11_ = toBase__pkgZwebbyZhttpheaders_u4(headers_p0);
					if (NIM_UNLIKELY(*nimErr_)) goto LA2_;
					if (i_1 < 0 || i_1 >= (*T11_).len){ raiseIndexError2(i_1,(*T11_).len-1); goto LA2_;
					}
					nimlf_(1715, "system.nim");					eqcopy___system_u2772((&(*T11_).p->data[i_1].Field1), value_p2);
					nimlf_(37, "httpheaders.nim");					nimlf_(394, "system.nim");					if (v_1.p && !(v_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(v_1.p);
}
					if (k_1.p && !(k_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(k_1.p);
}
					goto BeforeRet_;
				}
LA9_: ;
				nimlf_(13, "iterators.nim");				i_2 += ((NI)1);
				nimlf_(187, "iterators.nim");				{
					NI T14_;
					T14_ = (*colontmp_).len;
					if (!!((T14_ == L_1))) goto LA15_;
					failedAssertImpl__stdZassertions_u95(TM__sIuaO7I9bEdU9c2qj3mZCcQg_3);
					if (NIM_UNLIKELY(*nimErr_)) goto LA2_;
				}
LA15_: ;
			} LA5: ;
		}
		{
			LA2_:;
		}
		{
			nimlf_(394, "system.nim");			if (v_1.p && !(v_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(v_1.p);
}
			if (k_1.p && !(k_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(k_1.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	nimlf_(38, "httpheaders.nim");	T19_ = (tySequence__4eQHGndY6XBYpFOH09apV8Q*)0;
	T19_ = toBase__pkgZwebbyZhttpheaders_u4(headers_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimlf_(1715, "system.nim");	colontmpD_ = eqdup___system_u2775(key_p1);
	T20_.Field0 = colontmpD_;
	nimlf_(38, "httpheaders.nim");	nimlf_(1715, "system.nim");	colontmpD__2 = eqdup___system_u2775(value_p2);
	T20_.Field1 = colontmpD__2;
	nimlf_(38, "httpheaders.nim");	add__pkgZmummyZcommon_u157((&(*T19_)), (&T20_));
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(tySequence__4eQHGndY6XBYpFOH09apV8Q*, toBase__pkgZwebbyZhttpheaders_u39)(tySequence__4eQHGndY6XBYpFOH09apV8Q* params_p0) {
	tySequence__4eQHGndY6XBYpFOH09apV8Q* result;
	nimfr_("toBase", "httpheaders.nim");
	nimln_(10);	result = params_p0;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, contains__pkgZwebbyZhttpheaders_u54)(tySequence__4eQHGndY6XBYpFOH09apV8Q headers_p0, NimStringV2 key_p1) {
	NIM_BOOL result;
NIM_BOOL* nimErr_;
	nimfr_("contains", "httpheaders.nim");
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	{
		tySequence__4eQHGndY6XBYpFOH09apV8Q colontmp_;
		NimStringV2* k_1;
		NimStringV2* v_1;
		tySequence__4eQHGndY6XBYpFOH09apV8Q* T2_;
		NI i_1;
		NI L_1;
		NI T3_;
		colontmp_.len = 0; colontmp_.p = NIM_NIL;
		k_1 = (NimStringV2*)0;
		v_1 = (NimStringV2*)0;
		nimlf_(247, "iterators.nim");		nimlf_(20, "httpheaders.nim");		T2_ = (tySequence__4eQHGndY6XBYpFOH09apV8Q*)0;
		T2_ = toBase__pkgZwebbyZhttpheaders_u39((&headers_p0));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		colontmp_ = (*T2_);
		nimlf_(249, "iterators.nim");		i_1 = ((NI)0);
		nimln_(250);		T3_ = colontmp_.len;
		L_1 = T3_;
		{
			nimln_(251);			while (1) {
				if (!(i_1 < L_1)) goto LA5;
				nimlf_(20, "httpheaders.nim");				if (i_1 < 0 || i_1 >= colontmp_.len){ raiseIndexError2(i_1,colontmp_.len-1); goto BeforeRet_;
				}
				k_1 = (&colontmp_.p->data[i_1].Field0);
				if (i_1 < 0 || i_1 >= colontmp_.len){ raiseIndexError2(i_1,colontmp_.len-1); goto BeforeRet_;
				}
				v_1 = (&colontmp_.p->data[i_1].Field1);
				nimln_(21);				{
					NI T8_;
					T8_ = (NI)0;
					T8_ = nsuCmpIgnoreCase((*k_1), key_p1);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					if (!(T8_ == ((NI)0))) goto LA9_;
					nimln_(22);					nimln_(18);					nimln_(22);					result = NIM_TRUE;
					goto BeforeRet_;
				}
LA9_: ;
				nimlf_(13, "iterators.nim");				i_1 += ((NI)1);
				nimlf_(254, "iterators.nim");				{
					NI T13_;
					T13_ = colontmp_.len;
					if (!!((T13_ == L_1))) goto LA14_;
					failedAssertImpl__stdZassertions_u95(TM__sIuaO7I9bEdU9c2qj3mZCcQg_5);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
LA14_: ;
			} LA5: ;
		}
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tySequence__4eQHGndY6XBYpFOH09apV8Q, emptyHttpHeaders__pkgZwebbyZhttpheaders_u129)(void) {
	tySequence__4eQHGndY6XBYpFOH09apV8Q result;
	nimfr_("emptyHttpHeaders", "httpheaders.nim");
	result.len = 0; result.p = NIM_NIL;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, X5BX5D___pkgZwebbyZhttpheaders_u63)(tySequence__4eQHGndY6XBYpFOH09apV8Q headers_p0, NimStringV2 key_p1) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("[]", "httpheaders.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	{
		tySequence__4eQHGndY6XBYpFOH09apV8Q colontmp_;
		NimStringV2* k_1;
		NimStringV2* v_1;
		tySequence__4eQHGndY6XBYpFOH09apV8Q* T2_;
		NI i_1;
		NI L_1;
		NI T3_;
		colontmp_.len = 0; colontmp_.p = NIM_NIL;
		k_1 = (NimStringV2*)0;
		v_1 = (NimStringV2*)0;
		nimlf_(247, "iterators.nim");		nimlf_(26, "httpheaders.nim");		T2_ = (tySequence__4eQHGndY6XBYpFOH09apV8Q*)0;
		T2_ = toBase__pkgZwebbyZhttpheaders_u39((&headers_p0));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		colontmp_ = (*T2_);
		nimlf_(249, "iterators.nim");		i_1 = ((NI)0);
		nimln_(250);		T3_ = colontmp_.len;
		L_1 = T3_;
		{
			nimln_(251);			while (1) {
				if (!(i_1 < L_1)) goto LA5;
				nimlf_(26, "httpheaders.nim");				if (i_1 < 0 || i_1 >= colontmp_.len){ raiseIndexError2(i_1,colontmp_.len-1); goto BeforeRet_;
				}
				k_1 = (&colontmp_.p->data[i_1].Field0);
				if (i_1 < 0 || i_1 >= colontmp_.len){ raiseIndexError2(i_1,colontmp_.len-1); goto BeforeRet_;
				}
				v_1 = (&colontmp_.p->data[i_1].Field1);
				nimln_(27);				{
					NI T8_;
					T8_ = (NI)0;
					T8_ = nsuCmpIgnoreCase((*k_1), key_p1);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					if (!(T8_ == ((NI)0))) goto LA9_;
					nimln_(28);					nimlf_(1715, "system.nim");					eqcopy___system_u2772((&result), (*v_1));
					goto BeforeRet_;
				}
LA9_: ;
				nimlf_(13, "iterators.nim");				i_1 += ((NI)1);
				nimlf_(254, "iterators.nim");				{
					NI T13_;
					T13_ = colontmp_.len;
					if (!!((T13_ == L_1))) goto LA14_;
					failedAssertImpl__stdZassertions_u95(TM__sIuaO7I9bEdU9c2qj3mZCcQg_6);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
LA14_: ;
			} LA5: ;
		}
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tySequence__4eQHGndY6XBYpFOH09apV8Q, toWebby__pkgZwebbyZhttpheaders_u51)(tySequence__4eQHGndY6XBYpFOH09apV8Q headers_p0) {
	tySequence__4eQHGndY6XBYpFOH09apV8Q result;
	tySequence__4eQHGndY6XBYpFOH09apV8Q colontmpD_;
	nimfr_("toWebby", "httpheaders.nim");
	nimlf_(16, "httpheaders.nim");	nimlf_(220, "envvars.nim");	colontmpD_ = eqdup___stdZenvvars_u89(headers_p0);
	result = colontmpD_;
	popFrame();
	return result;
}
