/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -fno-strict-aliasing -pthread -I/home/icarogdo/.nimble/pkgs2/bearssl-0.2.10-e53ab85b8c4c1ce3aa1f4eb251c0ab29e08d4972/bearssl/abi -I/home/icarogdo/.nimble/pkgs2/bearssl-0.2.10-e53ab85b8c4c1ce3aa1f4eb251c0ab29e08d4972/bearssl/abi/../csources/src/ -I/home/icarogdo/.nimble/pkgs2/bearssl-0.2.10-e53ab85b8c4c1ce3aa1f4eb251c0ab29e08d4972/bearssl/abi/../csources/inc/ -I/home/icarogdo/.nimble/pkgs2/bearssl-0.2.10-e53ab85b8c4c1ce3aa1f4eb251c0ab29e08d4972/bearssl/abi/../csources/tools/ -DBR_USE_UNIX_TIME=1 -DBR_USE_URANDOM=1 -DBR_LE_UNALIGNED=1 -DBR_64=1  -DBR_amd64=1 -DBR_INT128=1 -Wno-incompatible-pointer-types -I/usr/include/webkitgtk-4.1 -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/cloudproviders -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/glycin-2 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/atk-1.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/fribidi -I/usr/include/pixman-1 -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gio-unix-2.0 -I/usr/include/libsoup-3.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-6 -pthread -O3 -fno-ident -fno-math-errno   -I/usr/lib/nim/lib -I/home/icarogdo/dev/macroobras-jazzy/app/macroobras/src -o /home/icarogdo/dev/macroobras-jazzy/app/macroobras/.nimcache-release/@nzippy-0.10.19-706d8c10778f32d28b060dbcc84143ca4bfb9bcd@szippy@sbitstreams.nim.c.o /home/icarogdo/dev/macroobras-jazzy/app/macroobras/.nimcache-release/@nzippy-0.10.19-706d8c10778f32d28b060dbcc84143ca4bfb9bcd@szippy@sbitstreams.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tyObject_BitStreamWriter__PafQK71hWM9bwwFa4GLPYfA tyObject_BitStreamWriter__PafQK71hWM9bwwFa4GLPYfA;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_ZippyError__gk5B8fBakq6y8uV4xKFV1Q tyObject_ZippyError__gk5B8fBakq6y8uV4xKFV1Q;
typedef struct tyObject_CatchableError__9ab9cPq83jNmwEkPYefdrBpg tyObject_CatchableError__9ab9cPq83jNmwEkPYefdrBpg;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tySequence__lQ1UsDGK2GVVm9bDjc3VrPQ tySequence__lQ1UsDGK2GVVm9bDjc3VrPQ;
typedef struct tySequence__lQ1UsDGK2GVVm9bDjc3VrPQ_Content tySequence__lQ1UsDGK2GVVm9bDjc3VrPQ_Content;
typedef struct tyObject_StackTraceEntry__Ys9cmA3ckZAVfrZgZt9axXEw tyObject_StackTraceEntry__Ys9cmA3ckZAVfrZgZt9axXEw;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tyObject_BitStreamWriter__PafQK71hWM9bwwFa4GLPYfA {
	NI pos;
	NI bitPos;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tySequence__lQ1UsDGK2GVVm9bDjc3VrPQ {
  NI len; tySequence__lQ1UsDGK2GVVm9bDjc3VrPQ_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__lQ1UsDGK2GVVm9bDjc3VrPQ trace;
	Exception* up;
};
struct tyObject_CatchableError__9ab9cPq83jNmwEkPYefdrBpg {
	Exception Sup;
};
struct tyObject_ZippyError__gk5B8fBakq6y8uV4xKFV1Q {
	tyObject_CatchableError__9ab9cPq83jNmwEkPYefdrBpg Sup;
};
struct tyObject_StackTraceEntry__Ys9cmA3ckZAVfrZgZt9axXEw {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__lQ1UsDGK2GVVm9bDjc3VrPQ_Content { NI cap; tyObject_StackTraceEntry__Ys9cmA3ckZAVfrZgZt9axXEw data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(void, setLengthStrV2)(NimStringV2* s_p0, NI newLen_p1);
static N_INLINE(void, write64__pkgZzippyZinternal_u509)(NU8* dst_p0, NI op_p1, NU64 v_p2);
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4511)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NU32, read32__pkgZzippyZinternal_u501)(NU8* src_p0, NI ip_p1);
static N_INLINE(void, incPos__pkgZzippyZbitstreams_u57)(tyObject_BitStreamWriter__PafQK71hWM9bwwFa4GLPYfA* b_p0, NI bits_p1);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e_p0, NCSTRING ename_p1, NCSTRING procname_p2, NCSTRING filename_p3, NI line_p4);
extern TNimTypeV2 NTIv2__gk5B8fBakq6y8uV4xKFV1Q_;
static const struct {
  NI cap; NIM_CHAR data[26+1];
} TM__7rCnxYg56U0HCf5pOiFXFw_2 = { 26 | NIM_STRLIT_FLAG, "Must be at a byte boundary" };
static const NimStringV2 TM__7rCnxYg56U0HCf5pOiFXFw_3 = {26, (NimStrPayload*)&TM__7rCnxYg56U0HCf5pOiFXFw_2};
extern NIM_THREADVAR TFrame* framePtr__system_u2809;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4293;
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2809 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2809).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2809;
	framePtr__system_u2809 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4511();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2809 = (*framePtr__system_u2809).prev;
}
static N_INLINE(void, write64__pkgZzippyZinternal_u509)(NU8* dst_p0, NI op_p1, NU64 v_p2) {
	nimfr_("write64", "internal.nim");
	nimlf_(213, "internal.nim");	copyMem__system_u1755(((void*) ((&dst_p0[op_p1]))), ((void*) ((&v_p2))), ((NI)8));
	popFrame();
}
static N_INLINE(NU32, read32__pkgZzippyZinternal_u501)(NU8* src_p0, NI ip_p1) {
	NU32 result;
	nimfr_("read32", "internal.nim");
	result = (NU32)0;
	nimln_(207);	copyMem__system_u1755(((void*) ((&result))), ((void*) ((&src_p0[ip_p1]))), ((NI)4));
	popFrame();
	return result;
}
static N_INLINE(void, incPos__pkgZzippyZbitstreams_u57)(tyObject_BitStreamWriter__PafQK71hWM9bwwFa4GLPYfA* b_p0, NI bits_p1) {
	nimfr_("incPos", "bitstreams.nim");
	nimlf_(83, "bitstreams.nim");	(*b_p0).pos += (NI)((NI64)((NI)(bits_p1 + (*b_p0).bitPos)) >> (NU64)(((NI)3) & (64 - 1)));
	nimln_(84);	(*b_p0).bitPos = (NI)((NI)(bits_p1 + (*b_p0).bitPos) & ((NI)7));
	popFrame();
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4293);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, addBits__pkgZzippyZbitstreams_u68)(tyObject_BitStreamWriter__PafQK71hWM9bwwFa4GLPYfA* b_p0, NimStringV2* dst_p1, NU32 value_p2, NI bitLen_p3) {
	NU8* dst_2;
	NU64 value_2;
	NU32 T5_;
NIM_BOOL* nimErr_;
	nimfr_("addBits", "bitstreams.nim");
{nimErr_ = nimErrorFlag();
	nimln_(94);	{
		if (!((*dst_p1).len < (NI)((*b_p0).pos + ((NI)8)))) goto LA3_;
		nimln_(96);		setLengthStrV2((&(*dst_p1)), ((((NI)((*dst_p1).len * ((NI)2)) >= (NI)((*b_p0).pos + ((NI)8))) ? (NI)((*dst_p1).len * ((NI)2)) : (NI)((*b_p0).pos + ((NI)8)))));
	}
LA3_: ;
	nimln_(99);	dst_2 = ((NU8*) ((&(*dst_p1).p->data[((NI)0)])));
	nimln_(100);	value_2 = (NU64)(((NU64) (value_p2)) & (NU64)((NU64)((NU64)((NU64)(1ULL) << (NU64)(bitLen_p3 & (64 - 1)))) - (NU64)(1ULL)));
	nimln_(101);	T5_ = (NU32)0;
	T5_ = read32__pkgZzippyZinternal_u501(dst_2, (*b_p0).pos);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	write64__pkgZzippyZinternal_u509(dst_2, (*b_p0).pos, (NU64)(((NU64) (T5_)) | (NU64)((NU64)(value_2) << (NU64)((*b_p0).bitPos & (64 - 1)))));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(102);	incPos__pkgZzippyZbitstreams_u57(b_p0, bitLen_p3);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, skipRemainingBitsInCurrentByte__pkgZzippyZbitstreams_u93)(tyObject_BitStreamWriter__PafQK71hWM9bwwFa4GLPYfA* b_p0) {
NIM_BOOL* nimErr_;
	nimfr_("skipRemainingBitsInCurrentByte", "bitstreams.nim");
{nimErr_ = nimErrorFlag();
	nimln_(120);	{
		if (!(((NI)0) < (*b_p0).bitPos)) goto LA3_;
		nimln_(121);		incPos__pkgZzippyZbitstreams_u57(b_p0, (NI)(((NI)8) - (*b_p0).bitPos));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA3_: ;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, addBytes__pkgZzippyZbitstreams_u86)(tyObject_BitStreamWriter__PafQK71hWM9bwwFa4GLPYfA* b_p0, NimStringV2* dst_p1, NU8* src_p2, NI srcPos_p3, NI len_p4) {
NIM_BOOL* nimErr_;
	nimfr_("addBytes", "bitstreams.nim");
{nimErr_ = nimErrorFlag();
	nimln_(110);	{
		tyObject_ZippyError__gk5B8fBakq6y8uV4xKFV1Q* T5_;
		if (!!(((*b_p0).bitPos == ((NI)0)))) goto LA3_;
		T5_ = NIM_NIL;
		T5_ = (tyObject_ZippyError__gk5B8fBakq6y8uV4xKFV1Q*) nimNewObj(sizeof(tyObject_ZippyError__gk5B8fBakq6y8uV4xKFV1Q), NIM_ALIGNOF(tyObject_ZippyError__gk5B8fBakq6y8uV4xKFV1Q));
		(*T5_).Sup.Sup.Sup.m_type = (&NTIv2__gk5B8fBakq6y8uV4xKFV1Q_);
		(*T5_).Sup.Sup.name = "ZippyError";
		(*T5_).Sup.Sup.message = TM__7rCnxYg56U0HCf5pOiFXFw_3;
		(*T5_).Sup.Sup.parent = ((Exception*) NIM_NIL);
		nimln_(111);		raiseExceptionEx((Exception*)T5_, "ZippyError", "addBytes", "bitstreams.nim", 111);
goto BeforeRet_;
	}
LA3_: ;
	nimln_(113);	{
		if (!((*dst_p1).len < (NI)((*b_p0).pos + len_p4))) goto LA8_;
		nimln_(114);		setLengthStrV2((&(*dst_p1)), ((NI)((*b_p0).pos + len_p4)));
	}
LA8_: ;
	nimln_(116);	copyMem__system_u1755(((void*) ((&(*dst_p1).p->data[(*b_p0).pos]))), ((void*) ((&src_p2[srcPos_p3]))), (len_p4));
	nimln_(117);	incPos__pkgZzippyZbitstreams_u57(b_p0, (NI)(len_p4 * ((NI)8)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
