/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -fno-strict-aliasing -pthread -I/home/icarogdo/.nimble/pkgs2/bearssl-0.2.10-e53ab85b8c4c1ce3aa1f4eb251c0ab29e08d4972/bearssl/abi -I/home/icarogdo/.nimble/pkgs2/bearssl-0.2.10-e53ab85b8c4c1ce3aa1f4eb251c0ab29e08d4972/bearssl/abi/../csources/src/ -I/home/icarogdo/.nimble/pkgs2/bearssl-0.2.10-e53ab85b8c4c1ce3aa1f4eb251c0ab29e08d4972/bearssl/abi/../csources/inc/ -I/home/icarogdo/.nimble/pkgs2/bearssl-0.2.10-e53ab85b8c4c1ce3aa1f4eb251c0ab29e08d4972/bearssl/abi/../csources/tools/ -DBR_USE_UNIX_TIME=1 -DBR_USE_URANDOM=1 -DBR_LE_UNALIGNED=1 -DBR_64=1  -DBR_amd64=1 -DBR_INT128=1 -Wno-incompatible-pointer-types -I/usr/include/webkitgtk-4.1 -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/cloudproviders -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/glycin-2 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/atk-1.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/fribidi -I/usr/include/pixman-1 -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gio-unix-2.0 -I/usr/include/libsoup-3.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-6 -pthread -O3 -fno-ident -fno-math-errno   -I/usr/lib/nim/lib -I/home/icarogdo/dev/macroobras-jazzy/app/macroobras/src -o /home/icarogdo/dev/macroobras-jazzy/app/macroobras/.nimcache-release/@pbrowsers.nim.c.o /home/icarogdo/dev/macroobras-jazzy/app/macroobras/.nimcache-release/@pbrowsers.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <sys/types.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_ProcessObj__nw29c9aD4A3ZqRJTR8I8fkqQ tyObject_ProcessObj__nw29c9aD4A3ZqRJTR8I8fkqQ;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tyObject_StreamObj__r1XfanY7DoimMbYEDg3nww tyObject_StreamObj__r1XfanY7DoimMbYEDg3nww;
typedef struct tyObject_StringTableObj__9bdWUs0ugwF1J9bvgBDSWyoQ tyObject_StringTableObj__9bdWUs0ugwF1J9bvgBDSWyoQ;
typedef struct Exception Exception;
typedef struct tySequence__lQ1UsDGK2GVVm9bDjc3VrPQ tySequence__lQ1UsDGK2GVVm9bDjc3VrPQ;
typedef struct tySequence__lQ1UsDGK2GVVm9bDjc3VrPQ_Content tySequence__lQ1UsDGK2GVVm9bDjc3VrPQ_Content;
typedef struct tyObject_StackTraceEntry__Ys9cmA3ckZAVfrZgZt9axXEw tyObject_StackTraceEntry__Ys9cmA3ckZAVfrZgZt9axXEw;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
typedef NU8 tySet_tyEnum_ProcessOption__MtcGChoVVfy7qzPVtMz9aDg;
struct tyObject_ProcessObj__nw29c9aD4A3ZqRJTR8I8fkqQ {
	RootObj Sup;
	int inHandle;
	int outHandle;
	int errHandle;
	pid_t id;
	tyObject_StreamObj__r1XfanY7DoimMbYEDg3nww* inStream;
	tyObject_StreamObj__r1XfanY7DoimMbYEDg3nww* outStream;
	tyObject_StreamObj__r1XfanY7DoimMbYEDg3nww* errStream;
	int exitStatus;
	NIM_BOOL exitFlag;
	tySet_tyEnum_ProcessOption__MtcGChoVVfy7qzPVtMz9aDg options;
};
typedef NimStringV2 tyArray__YgExxhfgKcesA5EOUj1MOA[1];
struct tySequence__lQ1UsDGK2GVVm9bDjc3VrPQ {
  NI len; tySequence__lQ1UsDGK2GVVm9bDjc3VrPQ_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__lQ1UsDGK2GVVm9bDjc3VrPQ trace;
	Exception* up;
};
struct tyObject_StackTraceEntry__Ys9cmA3ckZAVfrZgZt9axXEw {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__lQ1UsDGK2GVVm9bDjc3VrPQ_Content { NI cap; tyObject_StackTraceEntry__Ys9cmA3ckZAVfrZgZt9axXEw data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u95)(NimStringV2 msg_p0);
N_LIB_PRIVATE N_NIMCALL(void, openDefaultBrowserRaw__pureZbrowsers_u9)(NimStringV2 url_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nospquoteShell)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NIMCALL(NI, nosexecShellCmd)(NimStringV2 command_p0);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space_p0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, getEnv__stdZenvvars_u15)(NimStringV2 key_p0, NimStringV2 default_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___system_u2778)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, substr__system_u9181)(NimStringV2 s_p0, NI first_p1, NI last_p2);
N_LIB_PRIVATE N_NIMCALL(tyObject_ProcessObj__nw29c9aD4A3ZqRJTR8I8fkqQ*, nospstartProcess)(NimStringV2 command_p0, NimStringV2 workingDir_p1, NimStringV2* args_p2, NI args_p2Len_0, tyObject_StringTableObj__9bdWUs0ugwF1J9bvgBDSWyoQ* env_p3, tySet_tyEnum_ProcessOption__MtcGChoVVfy7qzPVtMz9aDg options_p4);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZosproc_u228)(tyObject_ProcessObj__nw29c9aD4A3ZqRJTR8I8fkqQ* dest_p0);
static N_INLINE(NIM_BOOL, isObjDisplayCheck)(TNimTypeV2* source_p0, NI16 targetDepth_p1, NU32 token_p2);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4511)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(Exception*, nimBorrowCurrentException)(void);
static N_INLINE(void, popCurrentException)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u3737)(Exception** dest_p0, Exception* src_p1, NIM_BOOL cyclic_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static const struct {
  NI cap; NIM_CHAR data[62+1];
} TM__CZNeKGdQ8AWxD1HSDIq5DQ_2 = { 62 | NIM_STRLIT_FLAG, "browsers.nim(77, 3) `url.len > 0` URL must not be empty string" };
static const NimStringV2 TM__CZNeKGdQ8AWxD1HSDIq5DQ_3 = {62, (NimStrPayload*)&TM__CZNeKGdQ8AWxD1HSDIq5DQ_2};
static const struct {
  NI cap; NIM_CHAR data[9+1];
} TM__CZNeKGdQ8AWxD1HSDIq5DQ_4 = { 9 | NIM_STRLIT_FLAG, "xdg-open " };
static const NimStringV2 TM__CZNeKGdQ8AWxD1HSDIq5DQ_5 = {9, (NimStrPayload*)&TM__CZNeKGdQ8AWxD1HSDIq5DQ_4};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__CZNeKGdQ8AWxD1HSDIq5DQ_6 = { 7 | NIM_STRLIT_FLAG, "BROWSER" };
static const NimStringV2 TM__CZNeKGdQ8AWxD1HSDIq5DQ_7 = {7, (NimStrPayload*)&TM__CZNeKGdQ8AWxD1HSDIq5DQ_6};
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__CZNeKGdQ8AWxD1HSDIq5DQ_8 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__CZNeKGdQ8AWxD1HSDIq5DQ_9 = {0, (NimStrPayload*)&TM__CZNeKGdQ8AWxD1HSDIq5DQ_8};
static const NimStringV2 TM__CZNeKGdQ8AWxD1HSDIq5DQ_12 = {0, (NimStrPayload*)&TM__CZNeKGdQ8AWxD1HSDIq5DQ_8};
extern NIM_THREADVAR TFrame* framePtr__system_u2809;
extern NIM_THREADVAR Exception* currException__system_u3704;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4293;
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
	{
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		copyMem__system_u1755(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		(*dest_p0).len += src_p1.len;
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2809 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2809).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2809;
	framePtr__system_u2809 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4511();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2809 = (*framePtr__system_u2809).prev;
}
static N_INLINE(NIM_BOOL, isObjDisplayCheck)(TNimTypeV2* source_p0, NI16 targetDepth_p1, NU32 token_p2) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	nimfr_("isObjDisplayCheck", "arc.nim");
	nimlf_(288, "arc.nim");	T1_ = (NIM_BOOL)0;
	T1_ = (targetDepth_p1 <= (*source_p0).depth);
	if (!(T1_)) goto LA2_;
	T1_ = ((*source_p0).display[targetDepth_p1] == token_p2);
LA2_: ;
	result = T1_;
	popFrame();
	return result;
}
static N_INLINE(Exception*, nimBorrowCurrentException)(void) {
	Exception* result;
	nimfr_("nimBorrowCurrentException", "system.nim");
	nimlf_(2371, "system.nim");	result = currException__system_u3704;
	popFrame();
	return result;
}
static N_INLINE(void, popCurrentException)(void) {
	eqcopy___system_u3737(&currException__system_u3704, (*currException__system_u3704).up, NIM_FALSE);
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4293);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, openDefaultBrowserRaw__pureZbrowsers_u9)(NimStringV2 url_p0) {
	NimStringV2 u_1;
	NimStringV2 colontmpD_;
NIM_BOOL* nimErr_;
	nimfr_("openDefaultBrowserRaw", "browsers.nim");
{nimErr_ = nimErrorFlag();
	u_1.len = 0; u_1.p = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	nimlf_(53, "browsers.nim");	u_1 = nospquoteShell(url_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(54);	{
		NimStringV2 T4_;
		NI T5_;
		T4_.len = 0; T4_.p = NIM_NIL;
		T4_ = rawNewString(u_1.len + 9);
appendString((&T4_), TM__CZNeKGdQ8AWxD1HSDIq5DQ_5);
appendString((&T4_), u_1);
		colontmpD_ = T4_;
		T5_ = (NI)0;
		T5_ = nosexecShellCmd(colontmpD_);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		if (!(T5_ == ((NI)0))) goto LA6_;
		nimlf_(394, "system.nim");		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
		if (u_1.p && !(u_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(u_1.p);
}
		goto BeforeRet_;
	}
LA6_: ;
	{
		NimStringV2 b_1;
		NimStringV2 colontmp_;
		NI lastX60gensym34__1;
		NI splitsX60gensym34__1;
		b_1.len = 0; b_1.p = NIM_NIL;
		colontmp_.len = 0; colontmp_.p = NIM_NIL;
		nimlf_(422, "strutils.nim");		nimlf_(55, "browsers.nim");		colontmp_ = getEnv__stdZenvvars_u15(TM__CZNeKGdQ8AWxD1HSDIq5DQ_7, TM__CZNeKGdQ8AWxD1HSDIq5DQ_9);
		if (NIM_UNLIKELY(*nimErr_)) goto LA9_;
		nimlf_(390, "strutils.nim");		lastX60gensym34__1 = ((NI)0);
		nimln_(391);		splitsX60gensym34__1 = ((NI)-1);
		{
			nimln_(450);			while (1) {
				NI firstX60gensym34__1;
				NI TM__CZNeKGdQ8AWxD1HSDIq5DQ_11;
				NimStringV2 T20_;
				tyObject_ProcessObj__nw29c9aD4A3ZqRJTR8I8fkqQ* colontmpD__2;
				tyArray__YgExxhfgKcesA5EOUj1MOA T23_;
				tyObject_ProcessObj__nw29c9aD4A3ZqRJTR8I8fkqQ* T24_;
				NI TM__CZNeKGdQ8AWxD1HSDIq5DQ_13;
				NI TM__CZNeKGdQ8AWxD1HSDIq5DQ_14;
				nimln_(393);				if (!(lastX60gensym34__1 <= colontmp_.len)) goto LA11;
				nimln_(394);				firstX60gensym34__1 = lastX60gensym34__1;
				{
					nimln_(395);					while (1) {
						NIM_BOOL T14_;
						NI TM__CZNeKGdQ8AWxD1HSDIq5DQ_10;
						T14_ = (NIM_BOOL)0;
						T14_ = (lastX60gensym34__1 < colontmp_.len);
						if (!(T14_)) goto LA15_;
						if (lastX60gensym34__1 < 0 || lastX60gensym34__1 >= colontmp_.len){ raiseIndexError2(lastX60gensym34__1,colontmp_.len-1); goto LA9_;
						}
						T14_ = !(((NU8)(colontmp_.p->data[lastX60gensym34__1]) == (NU8)(58)));
LA15_: ;
						if (!T14_) goto LA13;
						nimln_(396);						if (nimAddInt(lastX60gensym34__1, ((NI)1), &TM__CZNeKGdQ8AWxD1HSDIq5DQ_10)) { raiseOverflow(); goto LA9_;
						};
						lastX60gensym34__1 = (NI)(TM__CZNeKGdQ8AWxD1HSDIq5DQ_10);
					} LA13: ;
				}
				nimln_(397);				{
					if (!(splitsX60gensym34__1 == ((NI)0))) goto LA18_;
					lastX60gensym34__1 = colontmp_.len;
				}
LA18_: ;
				nimlf_(1715, "system.nim");				nimlf_(55, "browsers.nim");				nimlf_(398, "strutils.nim");				if (nimSubInt(lastX60gensym34__1, ((NI)1), &TM__CZNeKGdQ8AWxD1HSDIq5DQ_11)) { raiseOverflow(); goto LA9_;
				};
				nimlf_(55, "browsers.nim");				T20_.len = 0; T20_.p = NIM_NIL;
				T20_ = substr__system_u9181(colontmp_, firstX60gensym34__1, (NI)(TM__CZNeKGdQ8AWxD1HSDIq5DQ_11));
				nimlf_(1715, "system.nim");				eqsink___system_u2778((&b_1), T20_);
				colontmpD__2 = NIM_NIL;
				nimlf_(58, "browsers.nim");				T23_[0] = url_p0;
				T24_ = NIM_NIL;
				T24_ = nospstartProcess(b_1, TM__CZNeKGdQ8AWxD1HSDIq5DQ_12, T23_, 1, ((tyObject_StringTableObj__9bdWUs0ugwF1J9bvgBDSWyoQ*) NIM_NIL), 2);
				if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___pureZosproc_u228(T24_); goto LA22_;}
				colontmpD__2 = T24_;
				(void)(colontmpD__2);
				nimln_(59);				nimlf_(934, "system.nim");				eqdestroy___pureZosproc_u228(colontmpD__2);
				nimln_(394);				if (colontmp_.p && !(colontmp_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmp_.p);
}
				if (b_1.p && !(b_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(b_1.p);
}
				if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
				if (u_1.p && !(u_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(u_1.p);
}
				goto BeforeRet_;
				{
					LA22_:;
				}
				{
					nimln_(934);					eqdestroy___pureZosproc_u228(colontmpD__2);
				}
				if (NIM_UNLIKELY(*nimErr_)) goto LA21_;
				if (NIM_UNLIKELY(*nimErr_)) {
					LA21_:;
					if (isObjDisplayCheck(nimBorrowCurrentException()->Sup.m_type, 3, 1879086592)) {
						*nimErr_ = NIM_FALSE;
						popCurrentException();
						LA28_:;
					}
				}
				if (NIM_UNLIKELY(*nimErr_)) goto LA9_;
				nimlf_(399, "strutils.nim");				{
					if (!(splitsX60gensym34__1 == ((NI)0))) goto LA32_;
					goto LA10;
				}
LA32_: ;
				nimln_(400);				if (nimSubInt(splitsX60gensym34__1, ((NI)1), &TM__CZNeKGdQ8AWxD1HSDIq5DQ_13)) { raiseOverflow(); goto LA9_;
				};
				splitsX60gensym34__1 = (NI)(TM__CZNeKGdQ8AWxD1HSDIq5DQ_13);
				nimln_(401);				if (nimAddInt(lastX60gensym34__1, ((NI)1), &TM__CZNeKGdQ8AWxD1HSDIq5DQ_14)) { raiseOverflow(); goto LA9_;
				};
				lastX60gensym34__1 = (NI)(TM__CZNeKGdQ8AWxD1HSDIq5DQ_14);
			} LA11: ;
		} LA10: ;
		{
			LA9_:;
		}
		{
			nimlf_(394, "system.nim");			if (colontmp_.p && !(colontmp_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmp_.p);
}
			if (b_1.p && !(b_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(b_1.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
	{
		LA1_:;
	}
	{
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
		if (u_1.p && !(u_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(u_1.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, openDefaultBrowser__pureZbrowsers_u13)(NimStringV2 url_p0) {
NIM_BOOL* nimErr_;
	nimfr_("openDefaultBrowser", "browsers.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(77, "browsers.nim");	{
		if (!!((((NI)0) < url_p0.len))) goto LA3_;
		failedAssertImpl__stdZassertions_u95(TM__CZNeKGdQ8AWxD1HSDIq5DQ_3);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA3_: ;
	nimlf_(78, "browsers.nim");	openDefaultBrowserRaw__pureZbrowsers_u9(url_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
