/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -fno-strict-aliasing -pthread -I/home/icarogdo/.nimble/pkgs2/bearssl-0.2.10-e53ab85b8c4c1ce3aa1f4eb251c0ab29e08d4972/bearssl/abi -I/home/icarogdo/.nimble/pkgs2/bearssl-0.2.10-e53ab85b8c4c1ce3aa1f4eb251c0ab29e08d4972/bearssl/abi/../csources/src/ -I/home/icarogdo/.nimble/pkgs2/bearssl-0.2.10-e53ab85b8c4c1ce3aa1f4eb251c0ab29e08d4972/bearssl/abi/../csources/inc/ -I/home/icarogdo/.nimble/pkgs2/bearssl-0.2.10-e53ab85b8c4c1ce3aa1f4eb251c0ab29e08d4972/bearssl/abi/../csources/tools/ -DBR_USE_UNIX_TIME=1 -DBR_USE_URANDOM=1 -DBR_LE_UNALIGNED=1 -DBR_64=1  -DBR_amd64=1 -DBR_INT128=1 -Wno-incompatible-pointer-types -I/usr/include/webkitgtk-4.1 -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/cloudproviders -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/glycin-2 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/atk-1.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/fribidi -I/usr/include/pixman-1 -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gio-unix-2.0 -I/usr/include/libsoup-3.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-6 -pthread -O3 -fno-ident -fno-math-errno   -I/usr/lib/nim/lib -I/home/icarogdo/dev/macroobras-jazzy/app/macroobras/src -o /home/icarogdo/dev/macroobras-jazzy/app/macroobras/.nimcache-release/@pdynlib.nim.c.o /home/icarogdo/dev/macroobras-jazzy/app/macroobras/.nimcache-release/@pdynlib.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <dlfcn.h>
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content;
typedef struct tyObject_LibraryError__ub36VjuPCI6UByw9cFuscow tyObject_LibraryError__ub36VjuPCI6UByw9cFuscow;
typedef struct tyObject_OSError__vXAAlvrJPOVadDkbOWUyiA tyObject_OSError__vXAAlvrJPOVadDkbOWUyiA;
typedef struct tyObject_CatchableError__9ab9cPq83jNmwEkPYefdrBpg tyObject_CatchableError__9ab9cPq83jNmwEkPYefdrBpg;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tySequence__lQ1UsDGK2GVVm9bDjc3VrPQ tySequence__lQ1UsDGK2GVVm9bDjc3VrPQ;
typedef struct tySequence__lQ1UsDGK2GVVm9bDjc3VrPQ_Content tySequence__lQ1UsDGK2GVVm9bDjc3VrPQ_Content;
typedef struct tyObject_StackTraceEntry__Ys9cmA3ckZAVfrZgZt9axXEw tyObject_StackTraceEntry__Ys9cmA3ckZAVfrZgZt9axXEw;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  NI len; tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content* p;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tySequence__lQ1UsDGK2GVVm9bDjc3VrPQ {
  NI len; tySequence__lQ1UsDGK2GVVm9bDjc3VrPQ_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__lQ1UsDGK2GVVm9bDjc3VrPQ trace;
	Exception* up;
};
struct tyObject_CatchableError__9ab9cPq83jNmwEkPYefdrBpg {
	Exception Sup;
};
struct tyObject_OSError__vXAAlvrJPOVadDkbOWUyiA {
	tyObject_CatchableError__9ab9cPq83jNmwEkPYefdrBpg Sup;
	NI32 errorCode;
};
struct tyObject_LibraryError__ub36VjuPCI6UByw9cFuscow {
	tyObject_OSError__vXAAlvrJPOVadDkbOWUyiA Sup;
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE]; };
struct tyObject_StackTraceEntry__Ys9cmA3ckZAVfrZgZt9axXEw {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__lQ1UsDGK2GVVm9bDjc3VrPQ_Content { NI cap; tyObject_StackTraceEntry__Ys9cmA3ckZAVfrZgZt9axXEw data[SEQ_DECL_SIZE]; };
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4511)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(tySequence__sM4lkSb7zS6F7OVMvW9cffQ, newSeq__stdZsyncio_u573)(NI len_p0);
N_LIB_PRIVATE N_NIMCALL(void, libCandidates__pureZdynlib_u81)(NimStringV2 s_p0, tySequence__sM4lkSb7zS6F7OVMvW9cffQ* dest_p1);
N_LIB_PRIVATE N_NIMCALL(NI, nsuFindChar)(NimStringV2 s_p0, NIM_CHAR sub_p1, NI start_p2, NI last_p3);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, substr__system_u9181)(NimStringV2 s_p0, NI first_p1, NI last_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, substr__system_u9194)(NimStringV2 s_p0, NI first_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___system_u2778)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space_p0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, add__stdZenumutils_u70)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ* x_p0, NimStringV2 y_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, eqdup___system_u2775)(NimStringV2 src_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void*, loadLib__pureZdynlib_u3)(NimStringV2 path_p0, NIM_BOOL globalSymbols_p1);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u95)(NimStringV2 msg_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u5657)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ dest_p0);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, cstrToNimstr)(NCSTRING str_p0);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e_p0, NCSTRING ename_p1, NCSTRING procname_p2, NCSTRING filename_p3, NI line_p4);
static const struct {
  NI cap; NIM_CHAR data[90+1];
} TM__Vbi6rBBOqdMySprhH3iUcg_11 = { 90 | NIM_STRLIT_FLAG, "iterators.nim(254, 11) `len(a) == L` the length of the seq changed while iterating over it" };
static const NimStringV2 TM__Vbi6rBBOqdMySprhH3iUcg_12 = {90, (NimStrPayload*)&TM__Vbi6rBBOqdMySprhH3iUcg_11};
extern TNimTypeV2 NTIv2__ub36VjuPCI6UByw9cFuscow_;
static const struct {
  NI cap; NIM_CHAR data[23+1];
} TM__Vbi6rBBOqdMySprhH3iUcg_13 = { 23 | NIM_STRLIT_FLAG, "could not find symbol: " };
static const NimStringV2 TM__Vbi6rBBOqdMySprhH3iUcg_14 = {23, (NimStrPayload*)&TM__Vbi6rBBOqdMySprhH3iUcg_13};
extern NIM_THREADVAR TFrame* framePtr__system_u2809;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4293;
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2809 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2809).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2809;
	framePtr__system_u2809 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4511();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2809 = (*framePtr__system_u2809).prev;
}
N_LIB_PRIVATE N_NIMCALL(void*, symAddr__pureZdynlib_u74)(void* lib_p0, NCSTRING name_p1) {
	void* result;
	nimfr_("symAddr", "dynlib.nim");
	result = dlsym(lib_p0, name_p1);
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void*, loadLib__pureZdynlib_u6)(void) {
	void* result;
	nimfr_("loadLib", "dynlib.nim");
	result = dlopen(((NCSTRING) NIM_NIL), ((int)2));
	popFrame();
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
	{
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		copyMem__system_u1755(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		(*dest_p0).len += src_p1.len;
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4293);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, libCandidates__pureZdynlib_u81)(NimStringV2 s_p0, tySequence__sM4lkSb7zS6F7OVMvW9cffQ* dest_p1) {
	NI le_1;
	NI ri_1;
	NI TM__Vbi6rBBOqdMySprhH3iUcg_2;
NIM_BOOL* nimErr_;
	nimfr_("libCandidates", "dynlib.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(78, "dynlib.nim");	le_1 = nsuFindChar(s_p0, 40, ((NI)0), ((NI)-1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(79);	if (nimAddInt(le_1, ((NI)1), &TM__Vbi6rBBOqdMySprhH3iUcg_2)) { raiseOverflow(); goto BeforeRet_;
	};
	if (((NI)(TM__Vbi6rBBOqdMySprhH3iUcg_2)) < ((NI)0) || ((NI)(TM__Vbi6rBBOqdMySprhH3iUcg_2)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__Vbi6rBBOqdMySprhH3iUcg_2), ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	ri_1 = nsuFindChar(s_p0, 41, ((NI)(TM__Vbi6rBBOqdMySprhH3iUcg_2)), ((NI)-1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(80);	{
		NIM_BOOL T3_;
		NimStringV2 prefix_1;
		NimStringV2 suffix_1;
		NI TM__Vbi6rBBOqdMySprhH3iUcg_3;
		NI TM__Vbi6rBBOqdMySprhH3iUcg_4;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= le_1);
		if (!(T3_)) goto LA4_;
		T3_ = (le_1 < ri_1);
LA4_: ;
		if (!T3_) goto LA5_;
		prefix_1.len = 0; prefix_1.p = NIM_NIL;
		suffix_1.len = 0; suffix_1.p = NIM_NIL;
		nimln_(81);		if (nimSubInt(le_1, ((NI)1), &TM__Vbi6rBBOqdMySprhH3iUcg_3)) { raiseOverflow(); goto LA7_;
		};
		prefix_1 = substr__system_u9181(s_p0, ((NI)0), (NI)(TM__Vbi6rBBOqdMySprhH3iUcg_3));
		nimln_(82);		if (nimAddInt(ri_1, ((NI)1), &TM__Vbi6rBBOqdMySprhH3iUcg_4)) { raiseOverflow(); goto LA7_;
		};
		suffix_1 = substr__system_u9194(s_p0, (NI)(TM__Vbi6rBBOqdMySprhH3iUcg_4));
		{
			NimStringV2 middle_1;
			NimStringV2 colontmp_;
			NI TM__Vbi6rBBOqdMySprhH3iUcg_5;
			NI TM__Vbi6rBBOqdMySprhH3iUcg_6;
			NI lastX60gensym34__1;
			NI splitsX60gensym34__1;
			middle_1.len = 0; middle_1.p = NIM_NIL;
			colontmp_.len = 0; colontmp_.p = NIM_NIL;
			nimlf_(422, "strutils.nim");			nimlf_(83, "dynlib.nim");			if (nimAddInt(le_1, ((NI)1), &TM__Vbi6rBBOqdMySprhH3iUcg_5)) { raiseOverflow(); goto LA9_;
			};
			if (nimSubInt(ri_1, ((NI)1), &TM__Vbi6rBBOqdMySprhH3iUcg_6)) { raiseOverflow(); goto LA9_;
			};
			colontmp_ = substr__system_u9181(s_p0, (NI)(TM__Vbi6rBBOqdMySprhH3iUcg_5), (NI)(TM__Vbi6rBBOqdMySprhH3iUcg_6));
			nimlf_(390, "strutils.nim");			lastX60gensym34__1 = ((NI)0);
			nimln_(391);			splitsX60gensym34__1 = ((NI)-1);
			{
				nimln_(450);				while (1) {
					NimStringV2 colontmpD_;
					NI firstX60gensym34__1;
					NI TM__Vbi6rBBOqdMySprhH3iUcg_8;
					NimStringV2 T21_;
					NimStringV2 T22_;
					NI TM__Vbi6rBBOqdMySprhH3iUcg_9;
					NI TM__Vbi6rBBOqdMySprhH3iUcg_10;
					nimln_(393);					if (!(lastX60gensym34__1 <= colontmp_.len)) goto LA11;
					colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
					nimln_(394);					firstX60gensym34__1 = lastX60gensym34__1;
					{
						nimln_(395);						while (1) {
							NIM_BOOL T15_;
							NI TM__Vbi6rBBOqdMySprhH3iUcg_7;
							T15_ = (NIM_BOOL)0;
							T15_ = (lastX60gensym34__1 < colontmp_.len);
							if (!(T15_)) goto LA16_;
							if (lastX60gensym34__1 < 0 || lastX60gensym34__1 >= colontmp_.len){ raiseIndexError2(lastX60gensym34__1,colontmp_.len-1); goto LA12_;
							}
							T15_ = !(((NU8)(colontmp_.p->data[lastX60gensym34__1]) == (NU8)(124)));
LA16_: ;
							if (!T15_) goto LA14;
							nimln_(396);							if (nimAddInt(lastX60gensym34__1, ((NI)1), &TM__Vbi6rBBOqdMySprhH3iUcg_7)) { raiseOverflow(); goto LA12_;
							};
							lastX60gensym34__1 = (NI)(TM__Vbi6rBBOqdMySprhH3iUcg_7);
						} LA14: ;
					}
					nimln_(397);					{
						if (!(splitsX60gensym34__1 == ((NI)0))) goto LA19_;
						lastX60gensym34__1 = colontmp_.len;
					}
LA19_: ;
					nimlf_(1715, "system.nim");					nimlf_(83, "dynlib.nim");					nimlf_(398, "strutils.nim");					if (nimSubInt(lastX60gensym34__1, ((NI)1), &TM__Vbi6rBBOqdMySprhH3iUcg_8)) { raiseOverflow(); goto LA12_;
					};
					nimlf_(83, "dynlib.nim");					T21_.len = 0; T21_.p = NIM_NIL;
					T21_ = substr__system_u9181(colontmp_, firstX60gensym34__1, (NI)(TM__Vbi6rBBOqdMySprhH3iUcg_8));
					nimlf_(1715, "system.nim");					eqsink___system_u2778((&middle_1), T21_);
					nimlf_(84, "dynlib.nim");					T22_.len = 0; T22_.p = NIM_NIL;
					T22_ = rawNewString(prefix_1.len + middle_1.len + suffix_1.len + 0);
appendString((&T22_), prefix_1);
appendString((&T22_), middle_1);
appendString((&T22_), suffix_1);
					colontmpD_ = T22_;
					libCandidates__pureZdynlib_u81(colontmpD_, dest_p1);
					if (NIM_UNLIKELY(*nimErr_)) goto LA12_;
					nimlf_(399, "strutils.nim");					{
						if (!(splitsX60gensym34__1 == ((NI)0))) goto LA25_;
						nimlf_(394, "system.nim");						if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
						nimlf_(399, "strutils.nim");						goto LA10;
					}
LA25_: ;
					nimln_(400);					if (nimSubInt(splitsX60gensym34__1, ((NI)1), &TM__Vbi6rBBOqdMySprhH3iUcg_9)) { raiseOverflow(); goto LA12_;
					};
					splitsX60gensym34__1 = (NI)(TM__Vbi6rBBOqdMySprhH3iUcg_9);
					nimln_(401);					if (nimAddInt(lastX60gensym34__1, ((NI)1), &TM__Vbi6rBBOqdMySprhH3iUcg_10)) { raiseOverflow(); goto LA12_;
					};
					lastX60gensym34__1 = (NI)(TM__Vbi6rBBOqdMySprhH3iUcg_10);
					{
						LA12_:;
					}
					{
						nimlf_(394, "system.nim");						if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
					}
					if (NIM_UNLIKELY(*nimErr_)) goto LA9_;
				} LA11: ;
			} LA10: ;
			{
				LA9_:;
			}
			{
				if (colontmp_.p && !(colontmp_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmp_.p);
}
				if (middle_1.p && !(middle_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(middle_1.p);
}
			}
			if (NIM_UNLIKELY(*nimErr_)) goto LA7_;
		}
		{
			LA7_:;
		}
		{
			if (suffix_1.p && !(suffix_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(suffix_1.p);
}
			if (prefix_1.p && !(prefix_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(prefix_1.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA1_;
LA5_: ;
	{
		NimStringV2 colontmpD__2;
		nimlf_(86, "dynlib.nim");		nimlf_(1715, "system.nim");		colontmpD__2 = eqdup___system_u2775(s_p0);
		nimlf_(86, "dynlib.nim");		add__stdZenumutils_u70((&(*dest_p1)), colontmpD__2);
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0) {
	NCSTRING result;
	{
		if (!(s_p0.len == ((NI)0))) goto LA3_;
		result = "";
	}
	goto LA1_;
LA3_: ;
	{
		result = ((NCSTRING) ((*s_p0.p).data));
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void*, loadLib__pureZdynlib_u3)(NimStringV2 path_p0, NIM_BOOL globalSymbols_p1) {
	void* result;
	NI32 colontmpD_;
	int colontmpD__2;
	NI32 flags_1;
	nimfr_("loadLib", "dynlib.nim");
	colontmpD_ = (NI32)0;
	colontmpD__2 = (int)0;
	nimln_(112);	nimln_(113);	{
		if (!globalSymbols_p1) goto LA3_;
		colontmpD_ = ((NI32)258);
		flags_1 = colontmpD_;
	}
	goto LA1_;
LA3_: ;
	{
		nimln_(114);		colontmpD__2 = ((int)2);
		flags_1 = colontmpD__2;
	}
LA1_: ;
	nimln_(111);	nimln_(116);	result = dlopen(nimToCStringConv(path_p0), flags_1);
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void*, loadLibPattern__pureZdynlib_u93)(NimStringV2 pattern_p0, NIM_BOOL globalSymbols_p1) {
	void* result;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ candidates_1;
NIM_BOOL* nimErr_;
	nimfr_("loadLibPattern", "dynlib.nim");
{nimErr_ = nimErrorFlag();
	result = (void*)0;
	candidates_1.len = 0; candidates_1.p = NIM_NIL;
	nimln_(93);	result = 0;
	nimln_(94);	candidates_1 = newSeq__stdZsyncio_u573(((NI)0));
	nimln_(95);	libCandidates__pureZdynlib_u81(pattern_p0, (&candidates_1));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		NimStringV2* c_1;
		NI i_1;
		NI L_1;
		NI T3_;
		c_1 = (NimStringV2*)0;
		nimlf_(249, "iterators.nim");		i_1 = ((NI)0);
		nimln_(250);		T3_ = candidates_1.len;
		L_1 = T3_;
		{
			nimln_(251);			while (1) {
				if (!(i_1 < L_1)) goto LA5;
				nimlf_(96, "dynlib.nim");				if (i_1 < 0 || i_1 >= candidates_1.len){ raiseIndexError2(i_1,candidates_1.len-1); goto LA1_;
				}
				c_1 = (&candidates_1.p->data[i_1]);
				nimln_(97);				result = loadLib__pureZdynlib_u3((*c_1), globalSymbols_p1);
				if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
				nimln_(98);				{
					if (!!((result == 0))) goto LA8_;
					goto LA2;
				}
LA8_: ;
				nimlf_(13, "iterators.nim");				i_1 += ((NI)1);
				nimlf_(254, "iterators.nim");				{
					NI T12_;
					T12_ = candidates_1.len;
					if (!!((T12_ == L_1))) goto LA13_;
					failedAssertImpl__stdZassertions_u95(TM__Vbi6rBBOqdMySprhH3iUcg_12);
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
				}
LA13_: ;
			} LA5: ;
		}
	} LA2: ;
	{
		LA1_:;
	}
	{
		nimlf_(2219, "system.nim");		eqdestroy___system_u5657(candidates_1);
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NOINLINE(void, raiseInvalidLibrary__pureZdynlib_u9)(NCSTRING name_p0) {
	NimStringV2 colontmpD_;
	tyObject_LibraryError__ub36VjuPCI6UByw9cFuscow* T2_;
	NimStringV2 T3_;
NIM_BOOL* nimErr_;
	nimfr_("raiseInvalidLibrary", "dynlib.nim");
{nimErr_ = nimErrorFlag();
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	T2_ = NIM_NIL;
	T2_ = (tyObject_LibraryError__ub36VjuPCI6UByw9cFuscow*) nimNewObj(sizeof(tyObject_LibraryError__ub36VjuPCI6UByw9cFuscow), NIM_ALIGNOF(tyObject_LibraryError__ub36VjuPCI6UByw9cFuscow));
	(*T2_).Sup.Sup.Sup.Sup.m_type = (&NTIv2__ub36VjuPCI6UByw9cFuscow_);
	(*T2_).Sup.Sup.Sup.name = "LibraryError";
	nimlf_(64, "dynlib.nim");	T3_.len = 0; T3_.p = NIM_NIL;
	colontmpD_ = cstrToNimstr(name_p0);
	T3_ = rawNewString(colontmpD_.len + 23);
appendString((&T3_), TM__Vbi6rBBOqdMySprhH3iUcg_14);
appendString((&T3_), colontmpD_);
	(*T2_).Sup.Sup.Sup.message = T3_;
	(*T2_).Sup.Sup.Sup.parent = ((Exception*) NIM_NIL);
	raiseExceptionEx((Exception*)T2_, "LibraryError", "raiseInvalidLibrary", "dynlib.nim", 64);
goto LA1_;
	{
		LA1_:;
	}
	{
		nimlf_(394, "system.nim");		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
