/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -fno-strict-aliasing -pthread -I/home/icarogdo/.nimble/pkgs2/bearssl-0.2.10-e53ab85b8c4c1ce3aa1f4eb251c0ab29e08d4972/bearssl/abi -I/home/icarogdo/.nimble/pkgs2/bearssl-0.2.10-e53ab85b8c4c1ce3aa1f4eb251c0ab29e08d4972/bearssl/abi/../csources/src/ -I/home/icarogdo/.nimble/pkgs2/bearssl-0.2.10-e53ab85b8c4c1ce3aa1f4eb251c0ab29e08d4972/bearssl/abi/../csources/inc/ -I/home/icarogdo/.nimble/pkgs2/bearssl-0.2.10-e53ab85b8c4c1ce3aa1f4eb251c0ab29e08d4972/bearssl/abi/../csources/tools/ -DBR_USE_UNIX_TIME=1 -DBR_USE_URANDOM=1 -DBR_LE_UNALIGNED=1 -DBR_64=1  -DBR_amd64=1 -DBR_INT128=1 -Wno-incompatible-pointer-types -I/usr/include/webkitgtk-4.1 -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/cloudproviders -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/glycin-2 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/atk-1.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/fribidi -I/usr/include/pixman-1 -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gio-unix-2.0 -I/usr/include/libsoup-3.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-6 -pthread   -I/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib -I/home/icarogdo/dev/macroobras-jazzy/app/macroobras/src -o /home/icarogdo/dev/macroobras-jazzy/app/macroobras/.nimcache/@njazzy-0.4.5-4fdda426bdb506437985763b18fb2c79ca01e6e0@sjazzy@shttp@stypes.nim.c.o /home/icarogdo/dev/macroobras-jazzy/app/macroobras/.nimcache/@njazzy-0.4.5-4fdda426bdb506437985763b18fb2c79ca01e6e0@sjazzy@shttp@stypes.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <sys/types.h>
                          #include <pthread.h>
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tyObject_FuturecolonObjectType___7M77QG5xE71ZeiEPHTHzlw tyObject_FuturecolonObjectType___7M77QG5xE71ZeiEPHTHzlw;
typedef struct tyObject_ContextcolonObjectType___vPbCnNPUUpPcpphVHtPCbQ tyObject_ContextcolonObjectType___vPbCnNPUUpPcpphVHtPCbQ;
typedef struct tyObject_RefHeader__sqhyc4FSbGmPtkvXRNl9acg tyObject_RefHeader__sqhyc4FSbGmPtkvXRNl9acg;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tyObject_JazzyRequestcolonObjectType___X9c9aFPye9b9bO49bVRTsaWgwmg tyObject_JazzyRequestcolonObjectType___X9c9aFPye9b9bO49bVRTsaWgwmg;
typedef struct tySequence__XUcmaxm9b9attK75fbPuUHtw tySequence__XUcmaxm9b9attK75fbPuUHtw;
typedef struct tySequence__XUcmaxm9b9attK75fbPuUHtw_Content tySequence__XUcmaxm9b9attK75fbPuUHtw_Content;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_HttpHeaderscolonObjectType___q5RmldX8ngqdFdLFcD77Rw tyObject_HttpHeaderscolonObjectType___q5RmldX8ngqdFdLFcD77Rw;
typedef struct tyObject_Table__NZJ29bKsNkpKOymJNw10EvA tyObject_Table__NZJ29bKsNkpKOymJNw10EvA;
typedef struct tySequence__SFipDZIkFtPcrLs0AGBBjQ tySequence__SFipDZIkFtPcrLs0AGBBjQ;
typedef struct tySequence__SFipDZIkFtPcrLs0AGBBjQ_Content tySequence__SFipDZIkFtPcrLs0AGBBjQ_Content;
typedef struct tyObject_Table__31xuHZc9bAmTbF7XdBW9czqQ tyObject_Table__31xuHZc9bAmTbF7XdBW9czqQ;
typedef struct tyObject_Table__vMsav2LrmlVebnca684Wgg tyObject_Table__vMsav2LrmlVebnca684Wgg;
typedef struct tyObject_UploadedFile__Ttgk4NpE79ahXZ9aF4eH5jFg tyObject_UploadedFile__Ttgk4NpE79ahXZ9aF4eH5jFg;
typedef struct tyObject_JazzyResponsecolonObjectType___On29aIA9b0GJZYdz6Rbi0LBQ tyObject_JazzyResponsecolonObjectType___On29aIA9b0GJZYdz6Rbi0LBQ;
typedef struct tyObject_AuthManagercolonObjectType___gOLtYOmALWyhwhMKlAPryg tyObject_AuthManagercolonObjectType___gOLtYOmALWyhwhMKlAPryg;
typedef struct tyObject_JazzyCachecolonObjectType___fpLUIztpyx9cPt53jUHAYOw tyObject_JazzyCachecolonObjectType___fpLUIztpyx9cPt53jUHAYOw;
typedef struct tyObject_JazzyWebSocketcolonObjectType___r9aTBofI9a9brF5cZ9bq3nHg6w tyObject_JazzyWebSocketcolonObjectType___r9aTBofI9a9brF5cZ9bq3nHg6w;
typedef struct tyObject_WsMessage__M1WcqFI9cNutj0pLceTrRSg tyObject_WsMessage__M1WcqFI9cNutj0pLceTrRSg;
typedef struct tyObject_Table__1AlPqRYs6ur3IqFjyvJsHA tyObject_Table__1AlPqRYs6ur3IqFjyvJsHA;
typedef struct tySequence__EFF6kNqkhC9ap9bGaKijS9bfg tySequence__EFF6kNqkhC9ap9bGaKijS9bfg;
typedef struct tySequence__EFF6kNqkhC9ap9bGaKijS9bfg_Content tySequence__EFF6kNqkhC9ap9bGaKijS9bfg_Content;
typedef struct tyObject_Option__lQKWyGNFr2caVNdYC8WM8Q tyObject_Option__lQKWyGNFr2caVNdYC8WM8Q;
typedef struct tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog;
typedef struct tyObject_OrderedTable__alibvEreYoDQX0zEzfTleQ tyObject_OrderedTable__alibvEreYoDQX0zEzfTleQ;
typedef struct tySequence__xUV33m0d5HZLvMGUKDBm7Q tySequence__xUV33m0d5HZLvMGUKDBm7Q;
typedef struct tySequence__xUV33m0d5HZLvMGUKDBm7Q_Content tySequence__xUV33m0d5HZLvMGUKDBm7Q_Content;
typedef struct tySequence__YWxjq9aB9anxKHaOq65jIGKw tySequence__YWxjq9aB9anxKHaOq65jIGKw;
typedef struct tySequence__YWxjq9aB9anxKHaOq65jIGKw_Content tySequence__YWxjq9aB9anxKHaOq65jIGKw_Content;
typedef struct tyObject_GcEnv__85WwC9a1qDcL9aPJ9b1qr0g2Q tyObject_GcEnv__85WwC9a1qDcL9aPJ9b1qr0g2Q;
typedef struct tyObject_CellSeq__tmpRNCI2baMQRvZpqUI72g tyObject_CellSeq__tmpRNCI2baMQRvZpqUI72g;
typedef struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q tyTuple__N4J9cV4JZGem3ljqqj5rT0Q;
typedef struct tyObject_CellSeq__bUU9cGCnoYZUQbR5GgWvc0g tyObject_CellSeq__bUU9cGCnoYZUQbR5GgWvc0g;
typedef struct tyTuple__WEETd9ajw9a010wvV0CoGNuw tyTuple__WEETd9ajw9a010wvV0CoGNuw;
typedef struct tyObject_Middleware__gcFIH9b5wYIk9clYE57STTKw tyObject_Middleware__gcFIH9b5wYIk9clYE57STTKw;
typedef struct tyObject_ValidationErrorcolonObjectType___aGMqOUhehgbfAM0VRas3zg tyObject_ValidationErrorcolonObjectType___aGMqOUhehgbfAM0VRas3zg;
typedef struct tyTuple__VkaA9bzBYmNkyt5Z9b9b9a2K6A tyTuple__VkaA9bzBYmNkyt5Z9b9b9a2K6A;
typedef struct tyTuple__8ZxhPt1NwfElsJs8zUSV9bg tyTuple__8ZxhPt1NwfElsJs8zUSV9bg;
typedef struct tyTuple__P7zXJIzFLHQMHTlTJ8rSRg tyTuple__P7zXJIzFLHQMHTlTJ8rSRg;
typedef struct tyObject_CacheItem__5TBSJD5vIvN0N78v9cjaBnQ tyObject_CacheItem__5TBSJD5vIvN0N78v9cjaBnQ;
typedef struct tyTuple__s8qsQCcBOMNS7M9aFeWibtQ tyTuple__s8qsQCcBOMNS7M9aFeWibtQ;
typedef struct {
N_NIMCALL_PTR(tyObject_FuturecolonObjectType___7M77QG5xE71ZeiEPHTHzlw*, ClP_0) (tyObject_ContextcolonObjectType___vPbCnNPUUpPcpphVHtPCbQ* ctx_p0, void* ClE_0);
void* ClE_0;
} tyProc__9bEKzqwPW59c2SORTEBVDeiQ;
struct tyObject_RefHeader__sqhyc4FSbGmPtkvXRNl9acg {
	NI rc;
	NI rootIdx;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct tySequence__XUcmaxm9b9attK75fbPuUHtw {
  NI len; tySequence__XUcmaxm9b9attK75fbPuUHtw_Content* p;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef NU8 tyEnum_HttpMethod__8E0cnqA4t7LOGc109a8NMBg;
struct tySequence__SFipDZIkFtPcrLs0AGBBjQ {
  NI len; tySequence__SFipDZIkFtPcrLs0AGBBjQ_Content* p;
};
struct tyObject_Table__NZJ29bKsNkpKOymJNw10EvA {
	tySequence__SFipDZIkFtPcrLs0AGBBjQ data;
	NI counter;
};
struct tyObject_Table__31xuHZc9bAmTbF7XdBW9czqQ {
	tySequence__XUcmaxm9b9attK75fbPuUHtw data;
	NI counter;
};
struct tyObject_JazzyRequestcolonObjectType___X9c9aFPye9b9bO49bVRTsaWgwmg {
	NimStringV2 body;
	tyObject_HttpHeaderscolonObjectType___q5RmldX8ngqdFdLFcD77Rw* headers;
	tyEnum_HttpMethod__8E0cnqA4t7LOGc109a8NMBg httpMethod;
	NimStringV2 url;
	NimStringV2 path;
	NimStringV2 ip;
	tyObject_Table__NZJ29bKsNkpKOymJNw10EvA queryParams;
	tyObject_Table__NZJ29bKsNkpKOymJNw10EvA params;
	tyObject_Table__31xuHZc9bAmTbF7XdBW9czqQ files;
};
struct tyObject_HttpHeaderscolonObjectType___q5RmldX8ngqdFdLFcD77Rw {
	tyObject_Table__vMsav2LrmlVebnca684Wgg* table;
	NIM_BOOL isTitleCase;
};
struct tyObject_UploadedFile__Ttgk4NpE79ahXZ9aF4eH5jFg {
	NimStringV2 filename;
	NimStringV2 contentType;
	NimStringV2 content;
};
typedef NU8 tyEnum_WsEvent__DktjOI8Hy8XBBijjN6nC4w;
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (tyObject_JazzyWebSocketcolonObjectType___r9aTBofI9a9brF5cZ9bq3nHg6w* ws_p0, tyEnum_WsEvent__DktjOI8Hy8XBBijjN6nC4w event_p1, tyObject_WsMessage__M1WcqFI9cNutj0pLceTrRSg msg_p2, void* ClE_0);
void* ClE_0;
} tyProc__VnepQSEZ75oWG7v3imFgXg;
struct tyObject_ContextcolonObjectType___vPbCnNPUUpPcpphVHtPCbQ {
	tyObject_JazzyRequestcolonObjectType___X9c9aFPye9b9bO49bVRTsaWgwmg* request;
	tyObject_JazzyResponsecolonObjectType___On29aIA9b0GJZYdz6Rbi0LBQ* response;
	tyObject_AuthManagercolonObjectType___gOLtYOmALWyhwhMKlAPryg* auth;
	tyObject_JazzyCachecolonObjectType___fpLUIztpyx9cPt53jUHAYOw* cache;
	NimStringV2 requestId;
	tyProc__VnepQSEZ75oWG7v3imFgXg wsHandler;
};
struct tySequence__EFF6kNqkhC9ap9bGaKijS9bfg {
  NI len; tySequence__EFF6kNqkhC9ap9bGaKijS9bfg_Content* p;
};
struct tyObject_Table__1AlPqRYs6ur3IqFjyvJsHA {
	tySequence__EFF6kNqkhC9ap9bGaKijS9bfg data;
	NI counter;
};
typedef long tyArray__7QgzEjDMuQ7wLEmz8Xm47g[5];
struct tyObject_JazzyCachecolonObjectType___fpLUIztpyx9cPt53jUHAYOw {
	tyObject_Table__1AlPqRYs6ur3IqFjyvJsHA data;
	pthread_mutex_t lock;
};
struct tyObject_Option__lQKWyGNFr2caVNdYC8WM8Q {
	tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog* val;
};
typedef struct {
N_NIMCALL_PTR(NimStringV2, ClP_0) (tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog* user_p0, NIM_BOOL remember_p1, void* ClE_0);
void* ClE_0;
} tyProc__EmB4JCTeANRl1MLjDP613g;
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (void* ClE_0);
void* ClE_0;
} tyProc__HzVCwACFYM9cx9aV62PdjtuA;
struct tyObject_AuthManagercolonObjectType___gOLtYOmALWyhwhMKlAPryg {
	tyObject_Option__lQKWyGNFr2caVNdYC8WM8Q user;
	NIM_BOOL isLoggedIn;
	NimStringV2 token;
	tyProc__EmB4JCTeANRl1MLjDP613g loginProc;
	tyProc__HzVCwACFYM9cx9aV62PdjtuA logoutProc;
};
typedef NU8 tyEnum_JsonNodeKind__AgEdEY3Szs9c2LYpGqyQ2lA;
struct tySequence__xUV33m0d5HZLvMGUKDBm7Q {
  NI len; tySequence__xUV33m0d5HZLvMGUKDBm7Q_Content* p;
};
struct tyObject_OrderedTable__alibvEreYoDQX0zEzfTleQ {
	tySequence__xUV33m0d5HZLvMGUKDBm7Q data;
	NI counter;
	NI first;
	NI last;
};
struct tySequence__YWxjq9aB9anxKHaOq65jIGKw {
  NI len; tySequence__YWxjq9aB9anxKHaOq65jIGKw_Content* p;
};
struct tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog {
	NIM_BOOL isUnquoted;
	tyEnum_JsonNodeKind__AgEdEY3Szs9c2LYpGqyQ2lA kind;
union{
	struct {
	NimStringV2 str;
} _kind_1;
	struct {
	NI64 num;
} _kind_2;
	struct {
	NF fnum;
} _kind_3;
	struct {
	NIM_BOOL bval;
} _kind_4;
	struct {
	tyObject_OrderedTable__alibvEreYoDQX0zEzfTleQ fields;
} _kind_6;
	struct {
	tySequence__YWxjq9aB9anxKHaOq65jIGKw elems;
} _kind_7;
};
};
struct tyObject_CellSeq__tmpRNCI2baMQRvZpqUI72g {
	NI len;
	NI cap;
	tyTuple__N4J9cV4JZGem3ljqqj5rT0Q* d;
};
struct tyObject_CellSeq__bUU9cGCnoYZUQbR5GgWvc0g {
	NI len;
	NI cap;
	tyTuple__WEETd9ajw9a010wvV0CoGNuw* d;
};
struct tyObject_GcEnv__85WwC9a1qDcL9aPJ9b1qr0g2Q {
	tyObject_CellSeq__tmpRNCI2baMQRvZpqUI72g traceStack;
	tyObject_CellSeq__bUU9cGCnoYZUQbR5GgWvc0g toFree;
	NI freed;
	NI touched;
	NI edges;
	NI rcSum;
	NIM_BOOL keepThreshold;
};
struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q {
	void** Field0;
	TNimTypeV2* Field1;
};
struct tyObject_JazzyResponsecolonObjectType___On29aIA9b0GJZYdz6Rbi0LBQ {
	NI code;
	NimStringV2 body;
	tyObject_HttpHeaderscolonObjectType___q5RmldX8ngqdFdLFcD77Rw* headers;
};
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (NimStringV2 data_p0, void* ClE_0);
void* ClE_0;
} tyProc__k2HFjxisIgDALbEUFojxaQ;
struct tyObject_JazzyWebSocketcolonObjectType___r9aTBofI9a9brF5cZ9bq3nHg6w {
	tyProc__k2HFjxisIgDALbEUFojxaQ sendProc;
	tyProc__HzVCwACFYM9cx9aV62PdjtuA closeProc;
};
typedef NU8 tyEnum_WsMessageKind__IxouhxZN1mw6s9bzhjwCj5g;
struct tyObject_WsMessage__M1WcqFI9cNutj0pLceTrRSg {
	tyEnum_WsMessageKind__IxouhxZN1mw6s9bzhjwCj5g kind;
	NimStringV2 data;
};
typedef struct {
N_NIMCALL_PTR(tyObject_FuturecolonObjectType___7M77QG5xE71ZeiEPHTHzlw*, ClP_0) (tyObject_ContextcolonObjectType___vPbCnNPUUpPcpphVHtPCbQ* ctx_p0, tyProc__9bEKzqwPW59c2SORTEBVDeiQ next_p1, void* ClE_0);
void* ClE_0;
} tyProc__j89aRUQC3b7SLMc1D5kYuoA;
struct tyObject_Middleware__gcFIH9b5wYIk9clYE57STTKw {
	NimStringV2 name;
	tyProc__j89aRUQC3b7SLMc1D5kYuoA handler;
};
struct tyTuple__VkaA9bzBYmNkyt5Z9b9b9a2K6A {
	NI Field0;
	NimStringV2 Field1;
	tyObject_UploadedFile__Ttgk4NpE79ahXZ9aF4eH5jFg Field2;
};
struct tySequence__XUcmaxm9b9attK75fbPuUHtw_Content { NI cap; tyTuple__VkaA9bzBYmNkyt5Z9b9b9a2K6A data[SEQ_DECL_SIZE]; };
struct tyTuple__8ZxhPt1NwfElsJs8zUSV9bg {
	NI Field0;
	NimStringV2 Field1;
	NimStringV2 Field2;
};
struct tySequence__SFipDZIkFtPcrLs0AGBBjQ_Content { NI cap; tyTuple__8ZxhPt1NwfElsJs8zUSV9bg data[SEQ_DECL_SIZE]; };
struct tyObject_CacheItem__5TBSJD5vIvN0N78v9cjaBnQ {
	NimStringV2 value;
	NF expiresAt;
};
struct tyTuple__P7zXJIzFLHQMHTlTJ8rSRg {
	NI Field0;
	NimStringV2 Field1;
	tyObject_CacheItem__5TBSJD5vIvN0N78v9cjaBnQ Field2;
};
struct tySequence__EFF6kNqkhC9ap9bGaKijS9bfg_Content { NI cap; tyTuple__P7zXJIzFLHQMHTlTJ8rSRg data[SEQ_DECL_SIZE]; };
struct tyTuple__s8qsQCcBOMNS7M9aFeWibtQ {
	NI Field0;
	NI Field1;
	NimStringV2 Field2;
	tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog* Field3;
};
struct tySequence__xUV33m0d5HZLvMGUKDBm7Q_Content { NI cap; tyTuple__s8qsQCcBOMNS7M9aFeWibtQ data[SEQ_DECL_SIZE]; };
struct tySequence__YWxjq9aB9anxKHaOq65jIGKw_Content { NI cap; tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog* data[SEQ_DECL_SIZE]; };
static N_INLINE(void, nimIncRefCyclic)(void* p_p0, NIM_BOOL cyclic_p1);
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4511)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NI, pluspercent___system_u793)(NI x_p0, NI y_p1);
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0);
N_LIB_PRIVATE N_NOINLINE(void, rememberCycle__system_u3573)(NIM_BOOL isDestroyAction_p0, tyObject_RefHeader__sqhyc4FSbGmPtkvXRNl9acg* s_p1, TNimTypeV2* desc_p2);
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p_p0);
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZjazzyZhttpZcontext_u424)(tyObject_JazzyRequestcolonObjectType___X9c9aFPye9b9bO49bVRTsaWgwmg* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZjazzyZhttpZcontext_u453)(tySequence__XUcmaxm9b9attK75fbPuUHtw dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZjazzyZcoreZconfig_u185)(tySequence__SFipDZIkFtPcrLs0AGBBjQ dest_p0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZhttpcore_u414)(tyObject_HttpHeaderscolonObjectType___q5RmldX8ngqdFdLFcD77Rw* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimRawDispose)(void* p_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__pkgZjazzyZhttpZtypes_u190)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZjazzyZhttpZcontext_u406)(tyObject_ContextcolonObjectType___vPbCnNPUUpPcpphVHtPCbQ* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZjazzyZcoreZcache_u235)(tyObject_JazzyCachecolonObjectType___fpLUIztpyx9cPt53jUHAYOw* dest_p0);
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicStatic)(void* p_p0, TNimTypeV2* desc_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__pkgZjazzyZhttpZtypes_u192)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZjazzyZhttpZcontext_u265)(tyObject_AuthManagercolonObjectType___gOLtYOmALWyhwhMKlAPryg* dest_p0);
static N_INLINE(NIM_BOOL, nimDecRefIsLastDyn)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, unregisterCycle__system_u3203)(tyObject_RefHeader__sqhyc4FSbGmPtkvXRNl9acg* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZjson_u67)(tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog* dest_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___pkgZjazzyZhttpZcontext_u277)(tyObject_AuthManagercolonObjectType___gOLtYOmALWyhwhMKlAPryg* dest_p0, void* env_p1);
static N_INLINE(void, nimTraceRefDyn)(void* q_p0, void* env_p1);
static N_INLINE(void, add__system_u3094)(tyObject_CellSeq__tmpRNCI2baMQRvZpqUI72g* s_p0, void** c_p1, TNimTypeV2* t_p2);
N_LIB_PRIVATE N_NIMCALL(void, resize__system_u3102)(tyObject_CellSeq__tmpRNCI2baMQRvZpqUI72g* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZjazzyZhttpZtypes_u125)(tyObject_JazzyResponsecolonObjectType___On29aIA9b0GJZYdz6Rbi0LBQ* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___pkgZjazzyZhttpZcontext_u418)(tyObject_ContextcolonObjectType___vPbCnNPUUpPcpphVHtPCbQ* dest_p0, void* env_p1);
static N_INLINE(void, nimTraceRef)(void* q_p0, TNimTypeV2* desc_p1, void* env_p2);
static N_INLINE(void, nimIncRef)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZjazzyZhttpZtypes_u153)(tyObject_JazzyResponsecolonObjectType___On29aIA9b0GJZYdz6Rbi0LBQ* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___pureZhttpcore_u449)(tyObject_HttpHeaderscolonObjectType___q5RmldX8ngqdFdLFcD77Rw** dest_p0, tyObject_HttpHeaderscolonObjectType___q5RmldX8ngqdFdLFcD77Rw* src_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_HttpHeaderscolonObjectType___q5RmldX8ngqdFdLFcD77Rw*, newHttpHeaders__pureZhttpcore_u114)(NIM_BOOL titleCase_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZhttpcore_u440)(tyObject_HttpHeaderscolonObjectType___q5RmldX8ngqdFdLFcD77Rw* dest_p0);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__pkgZjazzyZhttpZtypes_u194)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZjazzyZdriversZmummy95driver_u1081)(tyObject_JazzyWebSocketcolonObjectType___r9aTBofI9a9brF5cZ9bq3nHg6w* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___pkgZjazzyZdriversZmummy95driver_u1093)(tyObject_JazzyWebSocketcolonObjectType___r9aTBofI9a9brF5cZ9bq3nHg6w* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u2772)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, eqdup___system_u2775)(NimStringV2 src_p0);
N_LIB_PRIVATE TNimTypeV2 NTIv2__vPbCnNPUUpPcpphVHtPCbQ_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__gOLtYOmALWyhwhMKlAPryg_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__r9aTBofI9a9brF5cZ9bq3nHg6w_;
extern NIM_THREADVAR TFrame* framePtr__system_u2809;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4293;
static NIM_CONST NU32 TM__BpkMBdgkor6QAb0krRcyiQ_2[1] = {3807207424};
N_LIB_PRIVATE TNimTypeV2 NTIv2__gOLtYOmALWyhwhMKlAPryg_ = {.destructor = (void*)rttiDestroy__pkgZjazzyZhttpZtypes_u192, .size = sizeof(tyObject_AuthManagercolonObjectType___gOLtYOmALWyhwhMKlAPryg), .align = (NI16) NIM_ALIGNOF(tyObject_AuthManagercolonObjectType___gOLtYOmALWyhwhMKlAPryg), .depth = 0, .display = TM__BpkMBdgkor6QAb0krRcyiQ_2, .traceImpl = (void*)eqtrace___pkgZjazzyZhttpZcontext_u277, .flags = 0};
static NIM_CONST NU32 TM__BpkMBdgkor6QAb0krRcyiQ_3[1] = {4139949056};
N_LIB_PRIVATE TNimTypeV2 NTIv2__vPbCnNPUUpPcpphVHtPCbQ_ = {.destructor = (void*)rttiDestroy__pkgZjazzyZhttpZtypes_u190, .size = sizeof(tyObject_ContextcolonObjectType___vPbCnNPUUpPcpphVHtPCbQ), .align = (NI16) NIM_ALIGNOF(tyObject_ContextcolonObjectType___vPbCnNPUUpPcpphVHtPCbQ), .depth = 0, .display = TM__BpkMBdgkor6QAb0krRcyiQ_3, .traceImpl = (void*)eqtrace___pkgZjazzyZhttpZcontext_u418, .flags = 0};
static NIM_CONST NU32 TM__BpkMBdgkor6QAb0krRcyiQ_4[1] = {3569459456};
N_LIB_PRIVATE TNimTypeV2 NTIv2__r9aTBofI9a9brF5cZ9bq3nHg6w_ = {.destructor = (void*)rttiDestroy__pkgZjazzyZhttpZtypes_u194, .size = sizeof(tyObject_JazzyWebSocketcolonObjectType___r9aTBofI9a9brF5cZ9bq3nHg6w), .align = (NI16) NIM_ALIGNOF(tyObject_JazzyWebSocketcolonObjectType___r9aTBofI9a9brF5cZ9bq3nHg6w), .depth = 0, .display = TM__BpkMBdgkor6QAb0krRcyiQ_4, .traceImpl = (void*)eqtrace___pkgZjazzyZdriversZmummy95driver_u1093, .flags = 0};
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2809 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2809).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2809;
	framePtr__system_u2809 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4511();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2809 = (*framePtr__system_u2809).prev;
}
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1) {
	NI result;
	nimfr_("-%", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/arithmetics.nim");
	nimlf_(377, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/arithmetics.nim");	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) - (NU64)(((NU) (y_p1))))));
	popFrame();
	return result;
}
static N_INLINE(NI, pluspercent___system_u793)(NI x_p0, NI y_p1) {
	NI result;
	nimfr_("+%", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/arithmetics.nim");
	nimln_(366);	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) + (NU64)(((NU) (y_p1))))));
	popFrame();
	return result;
}
static N_INLINE(void, nimIncRefCyclic)(void* p_p0, NIM_BOOL cyclic_p1) {
	tyObject_RefHeader__sqhyc4FSbGmPtkvXRNl9acg* h_1;
	NI T1_;
	nimfr_("nimIncRefCyclic", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/orc.nim");
	nimlf_(47, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/orc.nim");	nimlf_(60, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/arc.nim");	T1_ = (NI)0;
	T1_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)16));
	h_1 = ((tyObject_RefHeader__sqhyc4FSbGmPtkvXRNl9acg*) (T1_));
	nimlf_(48, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/orc.nim");	(*h_1).rc = pluspercent___system_u793((*h_1).rc, ((NI)16));
	popFrame();
}
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0) {
	NIM_BOOL result;
	nimfr_("nimDecRefIsLastCyclicDyn", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/orc.nim");
	nimln_(518);	result = NIM_FALSE;
	nimln_(519);	{
		tyObject_RefHeader__sqhyc4FSbGmPtkvXRNl9acg* cell_1;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		nimln_(520);		nimlf_(60, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/arc.nim");		T5_ = (NI)0;
		T5_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)16));
		cell_1 = ((tyObject_RefHeader__sqhyc4FSbGmPtkvXRNl9acg*) (T5_));
		nimlf_(521, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/orc.nim");		{
			if (!((NI)((*cell_1).rc & ((NI)-16)) == ((NI)0))) goto LA8_;
			nimln_(522);			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			nimln_(525);			(*cell_1).rc = minuspercent___system_u813((*cell_1).rc, ((NI)16));
		}
LA6_: ;
		nimln_(527);		rememberCycle__system_u3573(result, cell_1, (*((TNimTypeV2**) (p_p0))));
	}
LA3_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pkgZjazzyZcoreZserver_u140)(tyProc__9bEKzqwPW59c2SORTEBVDeiQ* dest_p0, tyProc__9bEKzqwPW59c2SORTEBVDeiQ src_p1, NIM_BOOL cyclic_p2) {
	void* colontmp_;
	colontmp_ = (*dest_p0).ClE_0;
	{
		if (!src_p1.ClE_0) goto LA3_;
		nimIncRefCyclic(src_p1.ClE_0, cyclic_p2);
	}
LA3_: ;
	(*dest_p0).ClE_0 = src_p1.ClE_0;
	(*dest_p0).ClP_0 = src_p1.ClP_0;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = nimDecRefIsLastCyclicDyn(colontmp_);
		if (!T7_) goto LA8_;
		nimDestroyAndDispose(colontmp_);
	}
LA8_: ;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p_p0) {
	NIM_BOOL result;
	nimfr_("nimDecRefIsLast", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/arc.nim");
	nimlf_(239, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/arc.nim");	result = NIM_FALSE;
	nimln_(240);	{
		tyObject_RefHeader__sqhyc4FSbGmPtkvXRNl9acg* cell_1;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		nimln_(241);		nimln_(60);		T5_ = (NI)0;
		T5_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)16));
		cell_1 = ((tyObject_RefHeader__sqhyc4FSbGmPtkvXRNl9acg*) (T5_));
		nimln_(255);		{
			if (!((NI)((NI64)((*cell_1).rc) >> (NU64)(((NI)4) & (64 - 1))) == ((NI)0))) goto LA8_;
			nimln_(256);			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			nimln_(86);			(*cell_1).rc = minuspercent___system_u813((*cell_1).rc, ((NI)16));
		}
LA6_: ;
	}
LA3_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZjazzyZhttpZcontext_u424)(tyObject_JazzyRequestcolonObjectType___X9c9aFPye9b9bO49bVRTsaWgwmg* dest_p0) {
	eqdestroy___pkgZjazzyZhttpZcontext_u453((*dest_p0).files.data);
	eqdestroy___pkgZjazzyZcoreZconfig_u185((*dest_p0).params.data);
	eqdestroy___pkgZjazzyZcoreZconfig_u185((*dest_p0).queryParams.data);
	if ((*dest_p0).ip.p && !((*dest_p0).ip.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).ip.p);
}
	if ((*dest_p0).path.p && !((*dest_p0).path.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).path.p);
}
	if ((*dest_p0).url.p && !((*dest_p0).url.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).url.p);
}
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast((*dest_p0).headers);
		if (!T3_) goto LA4_;
		eqdestroy___pureZhttpcore_u414((&(*(*dest_p0).headers)));
		nimRawDispose((*dest_p0).headers, ((NI)8));
	}
LA4_: ;
	if ((*dest_p0).body.p && !((*dest_p0).body.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).body.p);
}
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZjazzyZhttpZcontext_u710)(tyObject_JazzyRequestcolonObjectType___X9c9aFPye9b9bO49bVRTsaWgwmg* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast(dest_p0);
		if (!T3_) goto LA4_;
		eqdestroy___pkgZjazzyZhttpZcontext_u424((&(*dest_p0)));
		nimRawDispose(dest_p0, ((NI)8));
	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___pkgZjazzyZhttpZcontext_u707)(tyObject_JazzyRequestcolonObjectType___X9c9aFPye9b9bO49bVRTsaWgwmg** dest_p0) {
	(*dest_p0) = 0;
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___pkgZjazzyZhttpZcontext_u1617)(tyObject_UploadedFile__Ttgk4NpE79ahXZ9aF4eH5jFg* dest_p0, tyObject_UploadedFile__Ttgk4NpE79ahXZ9aF4eH5jFg* src_p1) {
	if ((*dest_p0).filename.p != (*src_p1).filename.p) {	if ((*dest_p0).filename.p && !((*dest_p0).filename.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).filename.p);
}
	}
(*dest_p0).filename.len = (*src_p1).filename.len; (*dest_p0).filename.p = (*src_p1).filename.p;
	if ((*dest_p0).contentType.p != (*src_p1).contentType.p) {	if ((*dest_p0).contentType.p && !((*dest_p0).contentType.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).contentType.p);
}
	}
(*dest_p0).contentType.len = (*src_p1).contentType.len; (*dest_p0).contentType.p = (*src_p1).contentType.p;
	if ((*dest_p0).content.p != (*src_p1).content.p) {	if ((*dest_p0).content.p && !((*dest_p0).content.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).content.p);
}
	}
(*dest_p0).content.len = (*src_p1).content.len; (*dest_p0).content.p = (*src_p1).content.p;
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___pkgZjazzyZhttpZcontext_u1605)(tyObject_UploadedFile__Ttgk4NpE79ahXZ9aF4eH5jFg* dest_p0) {
	(*dest_p0).filename.len = 0; (*dest_p0).filename.p = NIM_NIL;
	(*dest_p0).contentType.len = 0; (*dest_p0).contentType.p = NIM_NIL;
	(*dest_p0).content.len = 0; (*dest_p0).content.p = NIM_NIL;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicStatic)(void* p_p0, TNimTypeV2* desc_p1) {
	NIM_BOOL result;
	nimfr_("nimDecRefIsLastCyclicStatic", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/orc.nim");
	nimlf_(544, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/orc.nim");	result = NIM_FALSE;
	nimln_(545);	{
		tyObject_RefHeader__sqhyc4FSbGmPtkvXRNl9acg* cell_1;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		nimln_(546);		nimlf_(60, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/arc.nim");		T5_ = (NI)0;
		T5_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)16));
		cell_1 = ((tyObject_RefHeader__sqhyc4FSbGmPtkvXRNl9acg*) (T5_));
		nimlf_(547, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/orc.nim");		{
			if (!((NI)((*cell_1).rc & ((NI)-16)) == ((NI)0))) goto LA8_;
			nimln_(548);			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			nimln_(551);			(*cell_1).rc = minuspercent___system_u813((*cell_1).rc, ((NI)16));
		}
LA6_: ;
		nimln_(553);		rememberCycle__system_u3573(result, cell_1, desc_p1);
	}
LA3_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLastDyn)(void* p_p0) {
	NIM_BOOL result;
	nimfr_("nimDecRefIsLastDyn", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/orc.nim");
	nimln_(530);	result = NIM_FALSE;
	nimln_(531);	{
		tyObject_RefHeader__sqhyc4FSbGmPtkvXRNl9acg* cell_1;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		nimln_(532);		nimlf_(60, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/arc.nim");		T5_ = (NI)0;
		T5_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)16));
		cell_1 = ((tyObject_RefHeader__sqhyc4FSbGmPtkvXRNl9acg*) (T5_));
		nimlf_(533, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/orc.nim");		{
			if (!((NI)((*cell_1).rc & ((NI)-16)) == ((NI)0))) goto LA8_;
			nimln_(534);			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			nimln_(537);			(*cell_1).rc = minuspercent___system_u813((*cell_1).rc, ((NI)16));
		}
LA6_: ;
		nimln_(539);		{
			if (!result) goto LA13_;
			nimln_(540);			{
				if (!(((NI)0) < (*cell_1).rootIdx)) goto LA17_;
				nimln_(541);				unregisterCycle__system_u3203(cell_1);
			}
LA17_: ;
		}
LA13_: ;
	}
LA3_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZjazzyZhttpZcontext_u265)(tyObject_AuthManagercolonObjectType___gOLtYOmALWyhwhMKlAPryg* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).logoutProc.ClE_0);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).logoutProc.ClE_0);
	}
LA4_: ;
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).loginProc.ClE_0);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).loginProc.ClE_0);
	}
LA9_: ;
	if ((*dest_p0).token.p && !((*dest_p0).token.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).token.p);
}
	{
		NIM_BOOL T13_;
		T13_ = (NIM_BOOL)0;
		T13_ = nimDecRefIsLastDyn((*dest_p0).user.val);
		if (!T13_) goto LA14_;
		eqdestroy___pureZjson_u67((&(*(*dest_p0).user.val)));
		nimRawDispose((*dest_p0).user.val, ((NI)8));
	}
LA14_: ;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4293);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__pkgZjazzyZhttpZtypes_u192)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___pkgZjazzyZhttpZcontext_u265(((tyObject_AuthManagercolonObjectType___gOLtYOmALWyhwhMKlAPryg*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(void, add__system_u3094)(tyObject_CellSeq__tmpRNCI2baMQRvZpqUI72g* s_p0, void** c_p1, TNimTypeV2* t_p2) {
	void** colontmp_;
	TNimTypeV2* colontmp__2;
	nimfr_("add", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/cellseqs_v2.nim");
	nimlf_(28, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/cellseqs_v2.nim");	{
		if (!((*s_p0).cap <= (*s_p0).len)) goto LA3_;
		nimln_(29);		resize__system_u3102(s_p0);
	}
LA3_: ;
	nimln_(30);	colontmp_ = c_p1;
	colontmp__2 = t_p2;
	(*s_p0).d[(*s_p0).len].Field0 = colontmp_;
	(*s_p0).d[(*s_p0).len].Field1 = colontmp__2;
	nimln_(31);	(*s_p0).len = pluspercent___system_u793((*s_p0).len, ((NI)1));
	popFrame();
}
static N_INLINE(void, nimTraceRefDyn)(void* q_p0, void* env_p1) {
	void** p_1;
	nimfr_("nimTraceRefDyn", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/orc.nim");
	nimlf_(138, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/orc.nim");	p_1 = ((void**) (q_p0));
	nimln_(139);	{
		tyObject_GcEnv__85WwC9a1qDcL9aPJ9b1qr0g2Q* j_1;
		if (!!(((*p_1) == NIM_NIL))) goto LA3_;
		nimln_(140);		j_1 = ((tyObject_GcEnv__85WwC9a1qDcL9aPJ9b1qr0g2Q*) (env_p1));
		nimln_(141);		add__system_u3094((&(*j_1).traceStack), p_1, (*((TNimTypeV2**) ((*p_1)))));
	}
LA3_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___pkgZjazzyZhttpZcontext_u277)(tyObject_AuthManagercolonObjectType___gOLtYOmALWyhwhMKlAPryg* dest_p0, void* env_p1) {
	nimTraceRefDyn((&(*dest_p0).loginProc.ClE_0), env_p1);
	nimTraceRefDyn((&(*dest_p0).logoutProc.ClE_0), env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZjazzyZhttpZtypes_u125)(tyObject_JazzyResponsecolonObjectType___On29aIA9b0GJZYdz6Rbi0LBQ* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast((*dest_p0).headers);
		if (!T3_) goto LA4_;
		eqdestroy___pureZhttpcore_u414((&(*(*dest_p0).headers)));
		nimRawDispose((*dest_p0).headers, ((NI)8));
	}
LA4_: ;
	if ((*dest_p0).body.p && !((*dest_p0).body.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).body.p);
}
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZjazzyZhttpZcontext_u406)(tyObject_ContextcolonObjectType___vPbCnNPUUpPcpphVHtPCbQ* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).wsHandler.ClE_0);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).wsHandler.ClE_0);
	}
LA4_: ;
	if ((*dest_p0).requestId.p && !((*dest_p0).requestId.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).requestId.p);
}
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLast((*dest_p0).cache);
		if (!T8_) goto LA9_;
		eqdestroy___pkgZjazzyZcoreZcache_u235((&(*(*dest_p0).cache)));
		nimRawDispose((*dest_p0).cache, ((NI)NIM_ALIGNOF(tyObject_JazzyCachecolonObjectType___fpLUIztpyx9cPt53jUHAYOw)));
	}
LA9_: ;
	{
		NIM_BOOL T13_;
		T13_ = (NIM_BOOL)0;
		T13_ = nimDecRefIsLastCyclicStatic((*dest_p0).auth, ((TNimTypeV2*) ((&NTIv2__gOLtYOmALWyhwhMKlAPryg_))));
		if (!T13_) goto LA14_;
		eqdestroy___pkgZjazzyZhttpZcontext_u265((&(*(*dest_p0).auth)));
		nimRawDispose((*dest_p0).auth, ((NI)8));
	}
LA14_: ;
	{
		NIM_BOOL T18_;
		T18_ = (NIM_BOOL)0;
		T18_ = nimDecRefIsLast((*dest_p0).response);
		if (!T18_) goto LA19_;
		eqdestroy___pkgZjazzyZhttpZtypes_u125((&(*(*dest_p0).response)));
		nimRawDispose((*dest_p0).response, ((NI)8));
	}
LA19_: ;
	{
		NIM_BOOL T23_;
		T23_ = (NIM_BOOL)0;
		T23_ = nimDecRefIsLast((*dest_p0).request);
		if (!T23_) goto LA24_;
		eqdestroy___pkgZjazzyZhttpZcontext_u424((&(*(*dest_p0).request)));
		nimRawDispose((*dest_p0).request, ((NI)8));
	}
LA24_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__pkgZjazzyZhttpZtypes_u190)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___pkgZjazzyZhttpZcontext_u406(((tyObject_ContextcolonObjectType___vPbCnNPUUpPcpphVHtPCbQ*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(void, nimTraceRef)(void* q_p0, TNimTypeV2* desc_p1, void* env_p2) {
	void** p_1;
	nimfr_("nimTraceRef", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/orc.nim");
	nimln_(129);	p_1 = ((void**) (q_p0));
	nimln_(130);	{
		tyObject_GcEnv__85WwC9a1qDcL9aPJ9b1qr0g2Q* j_1;
		if (!!(((*p_1) == NIM_NIL))) goto LA3_;
		nimln_(134);		j_1 = ((tyObject_GcEnv__85WwC9a1qDcL9aPJ9b1qr0g2Q*) (env_p2));
		nimln_(135);		add__system_u3094((&(*j_1).traceStack), p_1, desc_p1);
	}
LA3_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___pkgZjazzyZhttpZcontext_u418)(tyObject_ContextcolonObjectType___vPbCnNPUUpPcpphVHtPCbQ* dest_p0, void* env_p1) {
	nimTraceRef(&(*dest_p0).auth, ((TNimTypeV2*) ((&NTIv2__gOLtYOmALWyhwhMKlAPryg_))), env_p1);
	nimTraceRefDyn((&(*dest_p0).wsHandler.ClE_0), env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZjazzyZhttpZcontext_u673)(tyObject_ContextcolonObjectType___vPbCnNPUUpPcpphVHtPCbQ* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicStatic(dest_p0, ((TNimTypeV2*) ((&NTIv2__vPbCnNPUUpPcpphVHtPCbQ_))));
		if (!T3_) goto LA4_;
		eqdestroy___pkgZjazzyZhttpZcontext_u406((&(*dest_p0)));
		nimRawDispose(dest_p0, ((NI)8));
	}
LA4_: ;
}
static N_INLINE(void, nimIncRef)(void* p_p0) {
	NI T1_;
	NI T2_;
	nimfr_("nimIncRef", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/arc.nim");
	nimlf_(88, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/arc.nim");	nimln_(60);	T1_ = (NI)0;
	T1_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)16));
	nimln_(88);	nimln_(60);	T2_ = (NI)0;
	T2_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)16));
	nimln_(88);	(*((tyObject_RefHeader__sqhyc4FSbGmPtkvXRNl9acg*) (T1_))).rc = pluspercent___system_u793((*((tyObject_RefHeader__sqhyc4FSbGmPtkvXRNl9acg*) (T2_))).rc, ((NI)16));
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pkgZjazzyZhttpZcontext_u713)(tyObject_JazzyRequestcolonObjectType___X9c9aFPye9b9bO49bVRTsaWgwmg** dest_p0, tyObject_JazzyRequestcolonObjectType___X9c9aFPye9b9bO49bVRTsaWgwmg* src_p1) {
	{
		if (!src_p1) goto LA3_;
		nimIncRef(src_p1);
	}
LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = nimDecRefIsLast((*dest_p0));
		if (!T7_) goto LA8_;
		eqdestroy___pkgZjazzyZhttpZcontext_u424((&(*(*dest_p0))));
		nimRawDispose((*dest_p0), ((NI)8));
	}
LA8_: ;
	(*dest_p0) = src_p1;
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___pkgZjazzyZhttpZtypes_u162)(tyObject_JazzyResponsecolonObjectType___On29aIA9b0GJZYdz6Rbi0LBQ** dest_p0, tyObject_JazzyResponsecolonObjectType___On29aIA9b0GJZYdz6Rbi0LBQ* src_p1) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast((*dest_p0));
		if (!T3_) goto LA4_;
		eqdestroy___pkgZjazzyZhttpZtypes_u125((&(*(*dest_p0))));
		nimRawDispose((*dest_p0), ((NI)8));
	}
LA4_: ;
	(*dest_p0) = src_p1;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZjazzyZhttpZtypes_u153)(tyObject_JazzyResponsecolonObjectType___On29aIA9b0GJZYdz6Rbi0LBQ* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast(dest_p0);
		if (!T3_) goto LA4_;
		eqdestroy___pkgZjazzyZhttpZtypes_u125((&(*dest_p0)));
		nimRawDispose(dest_p0, ((NI)8));
	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_JazzyResponsecolonObjectType___On29aIA9b0GJZYdz6Rbi0LBQ*, newJazzyResponse__pkgZjazzyZhttpZtypes_u117)(void) {
	tyObject_JazzyResponsecolonObjectType___On29aIA9b0GJZYdz6Rbi0LBQ* result;
	tyObject_HttpHeaderscolonObjectType___q5RmldX8ngqdFdLFcD77Rw* T1_;
NIM_BOOL* nimErr_;
	nimfr_("newJazzyResponse", "/home/icarogdo/.nimble/pkgs2/jazzy-0.4.5-4fdda426bdb506437985763b18fb2c79ca01e6e0/jazzy/http/types.nim");
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	nimlf_(69, "/home/icarogdo/.nimble/pkgs2/jazzy-0.4.5-4fdda426bdb506437985763b18fb2c79ca01e6e0/jazzy/http/types.nim");	eqdestroy___pkgZjazzyZhttpZtypes_u153(result);
	result = (tyObject_JazzyResponsecolonObjectType___On29aIA9b0GJZYdz6Rbi0LBQ*) nimNewObj(sizeof(tyObject_JazzyResponsecolonObjectType___On29aIA9b0GJZYdz6Rbi0LBQ), NIM_ALIGNOF(tyObject_JazzyResponsecolonObjectType___On29aIA9b0GJZYdz6Rbi0LBQ));
	nimln_(70);	(*result).code = ((NI)200);
	nimlf_(136, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/pure/httpcore.nim");	nimlf_(71, "/home/icarogdo/.nimble/pkgs2/jazzy-0.4.5-4fdda426bdb506437985763b18fb2c79ca01e6e0/jazzy/http/types.nim");	T1_ = NIM_NIL;
	T1_ = newHttpHeaders__pureZhttpcore_u114(NIM_FALSE);
	if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___pureZhttpcore_u440(T1_); goto BeforeRet_;}
	nimlf_(136, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/pure/httpcore.nim");	eqsink___pureZhttpcore_u449(&(*result).headers, T1_);
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___pkgZjazzyZhttpZcontext_u256)(tyObject_AuthManagercolonObjectType___gOLtYOmALWyhwhMKlAPryg** dest_p0, tyObject_AuthManagercolonObjectType___gOLtYOmALWyhwhMKlAPryg* src_p1) {
	tyObject_AuthManagercolonObjectType___gOLtYOmALWyhwhMKlAPryg* colontmp_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	colontmp_ = (*dest_p0);
	(*dest_p0) = src_p1;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicStatic(colontmp_, ((TNimTypeV2*) ((&NTIv2__gOLtYOmALWyhwhMKlAPryg_))));
		if (!T3_) goto LA4_;
		eqdestroy___pkgZjazzyZhttpZcontext_u265((&(*colontmp_)));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimRawDispose(colontmp_, ((NI)8));
	}
LA4_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZjazzyZhttpZcontext_u245)(tyObject_AuthManagercolonObjectType___gOLtYOmALWyhwhMKlAPryg* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicStatic(dest_p0, ((TNimTypeV2*) ((&NTIv2__gOLtYOmALWyhwhMKlAPryg_))));
		if (!T3_) goto LA4_;
		eqdestroy___pkgZjazzyZhttpZcontext_u265((&(*dest_p0)));
		nimRawDispose(dest_p0, ((NI)8));
	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___pkgZjazzyZhttpZcontext_u242)(tyObject_AuthManagercolonObjectType___gOLtYOmALWyhwhMKlAPryg** dest_p0) {
	(*dest_p0) = 0;
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pkgZjazzyZhttpZcontext_u676)(tyObject_ContextcolonObjectType___vPbCnNPUUpPcpphVHtPCbQ** dest_p0, tyObject_ContextcolonObjectType___vPbCnNPUUpPcpphVHtPCbQ* src_p1, NIM_BOOL cyclic_p2) {
	tyObject_ContextcolonObjectType___vPbCnNPUUpPcpphVHtPCbQ* colontmp_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	colontmp_ = (*dest_p0);
	{
		if (!src_p1) goto LA3_;
		nimIncRefCyclic(src_p1, cyclic_p2);
	}
LA3_: ;
	(*dest_p0) = src_p1;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = nimDecRefIsLastCyclicStatic(colontmp_, ((TNimTypeV2*) ((&NTIv2__vPbCnNPUUpPcpphVHtPCbQ_))));
		if (!T7_) goto LA8_;
		eqdestroy___pkgZjazzyZhttpZcontext_u406((&(*colontmp_)));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimRawDispose(colontmp_, ((NI)8));
	}
LA8_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___pkgZjazzyZhttpZcontext_u746)(tyProc__EmB4JCTeANRl1MLjDP613g* dest_p0, tyProc__EmB4JCTeANRl1MLjDP613g src_p1) {
	void* colontmp_;
	colontmp_ = (*dest_p0).ClE_0;
	(*dest_p0).ClE_0 = src_p1.ClE_0;
	(*dest_p0).ClP_0 = src_p1.ClP_0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn(colontmp_);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose(colontmp_);
	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___pkgZjazzyZhttpZrouter_u4033)(tyProc__VnepQSEZ75oWG7v3imFgXg* dest_p0, tyProc__VnepQSEZ75oWG7v3imFgXg src_p1) {
	void* colontmp_;
	colontmp_ = (*dest_p0).ClE_0;
	(*dest_p0).ClE_0 = src_p1.ClE_0;
	(*dest_p0).ClP_0 = src_p1.ClP_0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn(colontmp_);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose(colontmp_);
	}
LA4_: ;
}
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	nimSetMem__system_u2188(p_p0, ((int)0), size_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___pkgZjazzyZhttpZrouter_u4019)(tyProc__VnepQSEZ75oWG7v3imFgXg* dest_p0) {
	nimZeroMem((void*)(&(*dest_p0)), sizeof(tyProc__VnepQSEZ75oWG7v3imFgXg));
}
N_LIB_PRIVATE N_NIMCALL(void, eqdup___pkgZjazzyZhttpZrouter_u4029)(tyProc__VnepQSEZ75oWG7v3imFgXg src_p0, NIM_BOOL cyclic_p1, tyProc__VnepQSEZ75oWG7v3imFgXg* Result) {
	void* colontmp_;
	nimZeroMem((void*)Result, sizeof(tyProc__VnepQSEZ75oWG7v3imFgXg));
	colontmp_ = (*Result).ClE_0;
	(*Result).ClE_0 = src_p0.ClE_0;
	(*Result).ClP_0 = src_p0.ClP_0;
	{
		if (!src_p0.ClE_0) goto LA3_;
		nimIncRefCyclic(src_p0.ClE_0, cyclic_p1);
	}
LA3_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pkgZjazzyZhttpZrouter_u4025)(tyProc__VnepQSEZ75oWG7v3imFgXg* dest_p0, tyProc__VnepQSEZ75oWG7v3imFgXg src_p1, NIM_BOOL cyclic_p2) {
	void* colontmp_;
	colontmp_ = (*dest_p0).ClE_0;
	{
		if (!src_p1.ClE_0) goto LA3_;
		nimIncRefCyclic(src_p1.ClE_0, cyclic_p2);
	}
LA3_: ;
	(*dest_p0).ClE_0 = src_p1.ClE_0;
	(*dest_p0).ClP_0 = src_p1.ClP_0;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = nimDecRefIsLastCyclicDyn(colontmp_);
		if (!T7_) goto LA8_;
		nimDestroyAndDispose(colontmp_);
	}
LA8_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZjazzyZhttpZrouter_u4022)(tyProc__VnepQSEZ75oWG7v3imFgXg* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).ClE_0);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).ClE_0);
	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZjazzyZdriversZmummy95driver_u1081)(tyObject_JazzyWebSocketcolonObjectType___r9aTBofI9a9brF5cZ9bq3nHg6w* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).closeProc.ClE_0);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).closeProc.ClE_0);
	}
LA4_: ;
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).sendProc.ClE_0);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).sendProc.ClE_0);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__pkgZjazzyZhttpZtypes_u194)(void* dest_p0) {
	eqdestroy___pkgZjazzyZdriversZmummy95driver_u1081(((tyObject_JazzyWebSocketcolonObjectType___r9aTBofI9a9brF5cZ9bq3nHg6w*) (dest_p0)));
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___pkgZjazzyZdriversZmummy95driver_u1093)(tyObject_JazzyWebSocketcolonObjectType___r9aTBofI9a9brF5cZ9bq3nHg6w* dest_p0, void* env_p1) {
	nimTraceRefDyn((&(*dest_p0).sendProc.ClE_0), env_p1);
	nimTraceRefDyn((&(*dest_p0).closeProc.ClE_0), env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZjazzyZdriversZmummy95driver_u1061)(tyObject_JazzyWebSocketcolonObjectType___r9aTBofI9a9brF5cZ9bq3nHg6w* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicStatic(dest_p0, ((TNimTypeV2*) ((&NTIv2__r9aTBofI9a9brF5cZ9bq3nHg6w_))));
		if (!T3_) goto LA4_;
		eqdestroy___pkgZjazzyZdriversZmummy95driver_u1081((&(*dest_p0)));
		nimRawDispose(dest_p0, ((NI)8));
	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___pkgZjazzyZdriversZmummy95driver_u1058)(tyObject_JazzyWebSocketcolonObjectType___r9aTBofI9a9brF5cZ9bq3nHg6w** dest_p0) {
	(*dest_p0) = 0;
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___pkgZjazzyZdriversZmummy95driver_u1215)(tyProc__k2HFjxisIgDALbEUFojxaQ* dest_p0, tyProc__k2HFjxisIgDALbEUFojxaQ src_p1) {
	void* colontmp_;
	colontmp_ = (*dest_p0).ClE_0;
	(*dest_p0).ClE_0 = src_p1.ClE_0;
	(*dest_p0).ClP_0 = src_p1.ClP_0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn(colontmp_);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose(colontmp_);
	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZjazzyZdriversZmummy95driver_u1183)(tyObject_WsMessage__M1WcqFI9cNutj0pLceTrRSg* dest_p0) {
	if ((*dest_p0).data.p && !((*dest_p0).data.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).data.p);
}
}
N_LIB_PRIVATE N_NIMCALL(void, eqdup___pkgZjazzyZhttpZstatic95files_u875)(tyProc__j89aRUQC3b7SLMc1D5kYuoA src_p0, NIM_BOOL cyclic_p1, tyProc__j89aRUQC3b7SLMc1D5kYuoA* Result) {
	void* colontmp_;
	nimZeroMem((void*)Result, sizeof(tyProc__j89aRUQC3b7SLMc1D5kYuoA));
	colontmp_ = (*Result).ClE_0;
	(*Result).ClE_0 = src_p0.ClE_0;
	(*Result).ClP_0 = src_p0.ClP_0;
	{
		if (!src_p0.ClE_0) goto LA3_;
		nimIncRefCyclic(src_p0.ClE_0, cyclic_p1);
	}
LA3_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pkgZjazzyZhttpZstatic95files_u903)(tyObject_Middleware__gcFIH9b5wYIk9clYE57STTKw* dest_p0, tyObject_Middleware__gcFIH9b5wYIk9clYE57STTKw* src_p1) {
	void* colontmp_;
	eqcopy___system_u2772((&(*dest_p0).name), (*src_p1).name);
	colontmp_ = (*dest_p0).handler.ClE_0;
	{
		if (!(*src_p1).handler.ClE_0) goto LA3_;
		nimIncRefCyclic((*src_p1).handler.ClE_0, NIM_TRUE);
	}
LA3_: ;
	(*dest_p0).handler.ClE_0 = (*src_p1).handler.ClE_0;
	(*dest_p0).handler.ClP_0 = (*src_p1).handler.ClP_0;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = nimDecRefIsLastCyclicDyn(colontmp_);
		if (!T7_) goto LA8_;
		nimDestroyAndDispose(colontmp_);
	}
LA8_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___pkgZjazzyZcoreZserver_u148)(tyProc__9bEKzqwPW59c2SORTEBVDeiQ* dest_p0, tyProc__9bEKzqwPW59c2SORTEBVDeiQ src_p1) {
	void* colontmp_;
	colontmp_ = (*dest_p0).ClE_0;
	(*dest_p0).ClE_0 = src_p1.ClE_0;
	(*dest_p0).ClP_0 = src_p1.ClP_0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn(colontmp_);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose(colontmp_);
	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZjazzyZhttpZstatic95files_u900)(tyObject_Middleware__gcFIH9b5wYIk9clYE57STTKw* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).handler.ClE_0);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).handler.ClE_0);
	}
LA4_: ;
	if ((*dest_p0).name.p && !((*dest_p0).name.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).name.p);
}
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZjazzyZcoreZserver_u137)(tyProc__9bEKzqwPW59c2SORTEBVDeiQ* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).ClE_0);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).ClE_0);
	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdup___pkgZjazzyZhttpZstatic95files_u906)(tyObject_Middleware__gcFIH9b5wYIk9clYE57STTKw* src_p0, tyObject_Middleware__gcFIH9b5wYIk9clYE57STTKw* Result) {
	void* colontmp_;
	nimZeroMem((void*)Result, sizeof(tyObject_Middleware__gcFIH9b5wYIk9clYE57STTKw));
	(*Result).name = eqdup___system_u2775((*src_p0).name);
	colontmp_ = (*Result).handler.ClE_0;
	(*Result).handler.ClE_0 = (*src_p0).handler.ClE_0;
	(*Result).handler.ClP_0 = (*src_p0).handler.ClP_0;
	{
		if (!(*src_p0).handler.ClE_0) goto LA3_;
		nimIncRefCyclic((*src_p0).handler.ClE_0, NIM_TRUE);
	}
LA3_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___pkgZjazzyZhttpZstatic95files_u865)(tyProc__j89aRUQC3b7SLMc1D5kYuoA* dest_p0) {
	nimZeroMem((void*)(&(*dest_p0)), sizeof(tyProc__j89aRUQC3b7SLMc1D5kYuoA));
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZjazzyZhttpZstatic95files_u868)(tyProc__j89aRUQC3b7SLMc1D5kYuoA* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).ClE_0);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).ClE_0);
	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_JazzyWebSocketcolonObjectType___r9aTBofI9a9brF5cZ9bq3nHg6w*, eqdup___pkgZjazzyZdriversZmummy95driver_u1068)(tyObject_JazzyWebSocketcolonObjectType___r9aTBofI9a9brF5cZ9bq3nHg6w* src_p0, NIM_BOOL cyclic_p1) {
	tyObject_JazzyWebSocketcolonObjectType___r9aTBofI9a9brF5cZ9bq3nHg6w* result;
	tyObject_JazzyWebSocketcolonObjectType___r9aTBofI9a9brF5cZ9bq3nHg6w* colontmp_;
	result = NIM_NIL;
	colontmp_ = result;
	result = src_p0;
	{
		if (!src_p0) goto LA3_;
		nimIncRefCyclic(src_p0, cyclic_p1);
	}
LA3_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___pkgZjazzyZdriversZmummy95driver_u1072)(tyObject_JazzyWebSocketcolonObjectType___r9aTBofI9a9brF5cZ9bq3nHg6w** dest_p0, tyObject_JazzyWebSocketcolonObjectType___r9aTBofI9a9brF5cZ9bq3nHg6w* src_p1) {
	tyObject_JazzyWebSocketcolonObjectType___r9aTBofI9a9brF5cZ9bq3nHg6w* colontmp_;
	colontmp_ = (*dest_p0);
	(*dest_p0) = src_p1;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicStatic(colontmp_, ((TNimTypeV2*) ((&NTIv2__r9aTBofI9a9brF5cZ9bq3nHg6w_))));
		if (!T3_) goto LA4_;
		eqdestroy___pkgZjazzyZdriversZmummy95driver_u1081((&(*colontmp_)));
		nimRawDispose(colontmp_, ((NI)8));
	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZjazzyZhttpZvalidation_u422)(tyObject_ValidationErrorcolonObjectType___aGMqOUhehgbfAM0VRas3zg* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn(dest_p0);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose(dest_p0);
	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___pkgZjazzyZcoreZserver_u134)(tyProc__9bEKzqwPW59c2SORTEBVDeiQ* dest_p0) {
	nimZeroMem((void*)(&(*dest_p0)), sizeof(tyProc__9bEKzqwPW59c2SORTEBVDeiQ));
}
