/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -fno-strict-aliasing -pthread -I/home/icarogdo/.nimble/pkgs2/bearssl-0.2.10-e53ab85b8c4c1ce3aa1f4eb251c0ab29e08d4972/bearssl/abi -I/home/icarogdo/.nimble/pkgs2/bearssl-0.2.10-e53ab85b8c4c1ce3aa1f4eb251c0ab29e08d4972/bearssl/abi/../csources/src/ -I/home/icarogdo/.nimble/pkgs2/bearssl-0.2.10-e53ab85b8c4c1ce3aa1f4eb251c0ab29e08d4972/bearssl/abi/../csources/inc/ -I/home/icarogdo/.nimble/pkgs2/bearssl-0.2.10-e53ab85b8c4c1ce3aa1f4eb251c0ab29e08d4972/bearssl/abi/../csources/tools/ -DBR_USE_UNIX_TIME=1 -DBR_USE_URANDOM=1 -DBR_LE_UNALIGNED=1 -DBR_64=1  -DBR_amd64=1 -DBR_INT128=1 -Wno-incompatible-pointer-types -I/usr/include/webkitgtk-4.1 -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/cloudproviders -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/glycin-2 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/atk-1.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/fribidi -I/usr/include/pixman-1 -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gio-unix-2.0 -I/usr/include/libsoup-3.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-6 -pthread   -I/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib -I/home/icarogdo/dev/macroobras-jazzy/app/macroobras/src -o /home/icarogdo/dev/macroobras-jazzy/app/macroobras/.nimcache/@njazzy-0.4.5-4fdda426bdb506437985763b18fb2c79ca01e6e0@sjazzy@score@sserver.nim.c.o /home/icarogdo/dev/macroobras-jazzy/app/macroobras/.nimcache/@njazzy-0.4.5-4fdda426bdb506437985763b18fb2c79ca01e6e0@sjazzy@score@sserver.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tyObject_FuturecolonObjectType___7M77QG5xE71ZeiEPHTHzlw tyObject_FuturecolonObjectType___7M77QG5xE71ZeiEPHTHzlw;
typedef struct tyObject_ServerDrivercolonObjectType___1B9aC8SAqlBwmqHUT5tnGMg tyObject_ServerDrivercolonObjectType___1B9aC8SAqlBwmqHUT5tnGMg;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_ContextcolonObjectType___vPbCnNPUUpPcpphVHtPCbQ tyObject_ContextcolonObjectType___vPbCnNPUUpPcpphVHtPCbQ;
typedef struct tyObject_Env_asyncmacrodotnim_serveX20X28AsyncX29___Zlu8vHPJZ6LjmjoyKQN9bGQ tyObject_Env_asyncmacrodotnim_serveX20X28AsyncX29___Zlu8vHPJZ6LjmjoyKQN9bGQ;
typedef struct tyObject_FutureBasecolonObjectType___JUz0HBo9c4EYTeM7Tvc9bBRg tyObject_FutureBasecolonObjectType___JUz0HBo9c4EYTeM7Tvc9bBRg;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tyObject_CallbackList__it5iv1uemYEbBPfXoNnzZg tyObject_CallbackList__it5iv1uemYEbBPfXoNnzZg;
typedef struct Exception Exception;
typedef struct tySequence__UIJx6FJrflnhA9a3u1VF1vA tySequence__UIJx6FJrflnhA9a3u1VF1vA;
typedef struct tySequence__UIJx6FJrflnhA9a3u1VF1vA_Content tySequence__UIJx6FJrflnhA9a3u1VF1vA_Content;
typedef struct tyObject_Env_asyncmacrodotnim_serveNimAsyncContinue___ElhNFGpLGpiqK1CYfRGoZg tyObject_Env_asyncmacrodotnim_serveNimAsyncContinue___ElhNFGpLGpiqK1CYfRGoZg;
typedef struct tyObject_RefHeader__sqhyc4FSbGmPtkvXRNl9acg tyObject_RefHeader__sqhyc4FSbGmPtkvXRNl9acg;
typedef struct tyObject_GcEnv__85WwC9a1qDcL9aPJ9b1qr0g2Q tyObject_GcEnv__85WwC9a1qDcL9aPJ9b1qr0g2Q;
typedef struct tyObject_CellSeq__tmpRNCI2baMQRvZpqUI72g tyObject_CellSeq__tmpRNCI2baMQRvZpqUI72g;
typedef struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q tyTuple__N4J9cV4JZGem3ljqqj5rT0Q;
typedef struct tyObject_CellSeq__bUU9cGCnoYZUQbR5GgWvc0g tyObject_CellSeq__bUU9cGCnoYZUQbR5GgWvc0g;
typedef struct tyTuple__WEETd9ajw9a010wvV0CoGNuw tyTuple__WEETd9ajw9a010wvV0CoGNuw;
typedef struct tyObject_AssertionDefect__fAtMgIeNQyfDKIqRjGsXPw tyObject_AssertionDefect__fAtMgIeNQyfDKIqRjGsXPw;
typedef struct tyObject_Defect__9cay1P9cMS9bqQj8GzEyUp67g tyObject_Defect__9cay1P9cMS9bqQj8GzEyUp67g;
typedef struct tyObject_StackTraceEntry__UznwMnjUHK6AxZHnP9bMXEA tyObject_StackTraceEntry__UznwMnjUHK6AxZHnP9bMXEA;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef struct {
N_NIMCALL_PTR(tyObject_FuturecolonObjectType___7M77QG5xE71ZeiEPHTHzlw*, ClP_0) (tyObject_ContextcolonObjectType___vPbCnNPUUpPcpphVHtPCbQ* ctx_p0, void* ClE_0);
void* ClE_0;
} tyProc__9bEKzqwPW59c2SORTEBVDeiQ;
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (void* ClE_0);
void* ClE_0;
} tyProc__HzVCwACFYM9cx9aV62PdjtuA;
struct tyObject_CallbackList__it5iv1uemYEbBPfXoNnzZg {
	tyProc__HzVCwACFYM9cx9aV62PdjtuA function;
	tyObject_CallbackList__it5iv1uemYEbBPfXoNnzZg* next;
};
struct tySequence__UIJx6FJrflnhA9a3u1VF1vA {
  NI len; tySequence__UIJx6FJrflnhA9a3u1VF1vA_Content* p;
};
struct tyObject_FutureBasecolonObjectType___JUz0HBo9c4EYTeM7Tvc9bBRg {
	RootObj Sup;
	tyObject_CallbackList__it5iv1uemYEbBPfXoNnzZg callbacks;
	NIM_BOOL finished;
	Exception* error;
	NimStringV2 errorStackTrace;
	tySequence__UIJx6FJrflnhA9a3u1VF1vA stackTrace;
	NI id;
	NimStringV2 fromProc;
};
struct tyObject_FuturecolonObjectType___7M77QG5xE71ZeiEPHTHzlw {
	tyObject_FutureBasecolonObjectType___JUz0HBo9c4EYTeM7Tvc9bBRg Sup;
};
typedef struct {
N_NIMCALL_PTR(tyObject_FutureBasecolonObjectType___JUz0HBo9c4EYTeM7Tvc9bBRg*, ClP_0) (tyObject_FuturecolonObjectType___7M77QG5xE71ZeiEPHTHzlw* f_p0, void* ClE_0);
void* ClE_0;
} tyProc__9aRgHm8v4viL9ca0DLqdkxfw;
struct tyObject_Env_asyncmacrodotnim_serveNimAsyncContinue___ElhNFGpLGpiqK1CYfRGoZg {
	RootObj Sup;
	tyObject_FuturecolonObjectType___7M77QG5xE71ZeiEPHTHzlw* futX60gensym40_;
	tyProc__9aRgHm8v4viL9ca0DLqdkxfw itX60gensym41_;
};
struct tyObject_RefHeader__sqhyc4FSbGmPtkvXRNl9acg {
	NI rc;
	NI rootIdx;
};
struct tyObject_CellSeq__tmpRNCI2baMQRvZpqUI72g {
	NI len;
	NI cap;
	tyTuple__N4J9cV4JZGem3ljqqj5rT0Q* d;
};
struct tyObject_CellSeq__bUU9cGCnoYZUQbR5GgWvc0g {
	NI len;
	NI cap;
	tyTuple__WEETd9ajw9a010wvV0CoGNuw* d;
};
struct tyObject_GcEnv__85WwC9a1qDcL9aPJ9b1qr0g2Q {
	tyObject_CellSeq__tmpRNCI2baMQRvZpqUI72g traceStack;
	tyObject_CellSeq__bUU9cGCnoYZUQbR5GgWvc0g toFree;
	NI freed;
	NI touched;
	NI edges;
	NI rcSum;
	NIM_BOOL keepThreshold;
};
struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q {
	void** Field0;
	TNimTypeV2* Field1;
};
typedef N_CLOSURE_PTR(tyObject_FutureBasecolonObjectType___JUz0HBo9c4EYTeM7Tvc9bBRg*, TM__VOvae9c8Y2K9aBawx5M9cHhAQ_5) (tyObject_FuturecolonObjectType___7M77QG5xE71ZeiEPHTHzlw* f_p0);
typedef N_CLOSURE_PTR(tyObject_FutureBasecolonObjectType___JUz0HBo9c4EYTeM7Tvc9bBRg*, TM__VOvae9c8Y2K9aBawx5M9cHhAQ_6) (tyObject_FuturecolonObjectType___7M77QG5xE71ZeiEPHTHzlw* f_p0);
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__UIJx6FJrflnhA9a3u1VF1vA trace;
	Exception* up;
};
struct tyObject_Defect__9cay1P9cMS9bqQj8GzEyUp67g {
	Exception Sup;
};
struct tyObject_AssertionDefect__fAtMgIeNQyfDKIqRjGsXPw {
	tyObject_Defect__9cay1P9cMS9bqQj8GzEyUp67g Sup;
};
struct tyObject_Env_asyncmacrodotnim_serveX20X28AsyncX29___Zlu8vHPJZ6LjmjoyKQN9bGQ {
	RootObj Sup;
	NI colonstate_;
};
struct tyObject_StackTraceEntry__UznwMnjUHK6AxZHnP9bMXEA {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__UIJx6FJrflnhA9a3u1VF1vA_Content { NI cap; tyObject_StackTraceEntry__UznwMnjUHK6AxZHnP9bMXEA data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType___7M77QG5xE71ZeiEPHTHzlw*, serve__pkgZjazzyZcoreZserver_u19)(tyObject_ServerDrivercolonObjectType___1B9aC8SAqlBwmqHUT5tnGMg* driver_p0, NI port_p1, NimStringV2 address_p2, tyProc__9bEKzqwPW59c2SORTEBVDeiQ handler_p3);
N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType___7M77QG5xE71ZeiEPHTHzlw*, newFuture__pureZasyncdispatch_u5453)(NimStringV2 fromProc_p0);
N_LIB_PRIVATE N_NIMCALL(void, serveNimAsyncContinue__pkgZjazzyZcoreZserver_u13)(tyObject_FuturecolonObjectType___7M77QG5xE71ZeiEPHTHzlw* futX60gensym4__p0, tyProc__9aRgHm8v4viL9ca0DLqdkxfw itX60gensym4__p1);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__pkgZjazzyZcoreZserver_u320)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZjazzyZcoreZserver_u182)(tyObject_Env_asyncmacrodotnim_serveNimAsyncContinue___ElhNFGpLGpiqK1CYfRGoZg* dest_p0);
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0);
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4511)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NOINLINE(void, rememberCycle__system_u3573)(NIM_BOOL isDestroyAction_p0, tyObject_RefHeader__sqhyc4FSbGmPtkvXRNl9acg* s_p1, TNimTypeV2* desc_p2);
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___pkgZjazzyZcoreZserver_u194)(tyObject_Env_asyncmacrodotnim_serveNimAsyncContinue___ElhNFGpLGpiqK1CYfRGoZg* dest_p0, void* env_p1);
static N_INLINE(void, nimTraceRefDyn)(void* q_p0, void* env_p1);
static N_INLINE(void, add__system_u3094)(tyObject_CellSeq__tmpRNCI2baMQRvZpqUI72g* s_p0, void** c_p1, TNimTypeV2* t_p2);
N_LIB_PRIVATE N_NIMCALL(void, resize__system_u3102)(tyObject_CellSeq__tmpRNCI2baMQRvZpqUI72g* s_p0);
static N_INLINE(NI, pluspercent___system_u793)(NI x_p0, NI y_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pureZasyncfutures_u550)(tyObject_FuturecolonObjectType___7M77QG5xE71ZeiEPHTHzlw** dest_p0, tyObject_FuturecolonObjectType___7M77QG5xE71ZeiEPHTHzlw* src_p1, NIM_BOOL cyclic_p2);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pkgZjazzyZcoreZserver_u55)(tyProc__9aRgHm8v4viL9ca0DLqdkxfw* dest_p0, tyProc__9aRgHm8v4viL9ca0DLqdkxfw src_p1, NIM_BOOL cyclic_p2);
static N_INLINE(NIM_BOOL, finished__pkgZjazzyZcoreZserver_u45)(tyProc__9aRgHm8v4viL9ca0DLqdkxfw x_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, finished__pureZasyncdispatch_u8644)(tyObject_FutureBasecolonObjectType___JUz0HBo9c4EYTeM7Tvc9bBRg* future_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___pureZasyncfutures_u534)(tyObject_FutureBasecolonObjectType___JUz0HBo9c4EYTeM7Tvc9bBRg** dest_p0, tyObject_FutureBasecolonObjectType___JUz0HBo9c4EYTeM7Tvc9bBRg* src_p1);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, finished__pkgZjazzyZcoreZserver_u95)(tyObject_FuturecolonObjectType___7M77QG5xE71ZeiEPHTHzlw* future_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuFormatSingleElem)(NimStringV2 formatstr_p0, NimStringV2 a_p1);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e_p0, NCSTRING ename_p1, NCSTRING procname_p2, NCSTRING filename_p3, NI line_p4);
N_LIB_PRIVATE N_NIMCALL(void, addCallback__pureZasyncfutures_u677)(tyObject_FutureBasecolonObjectType___JUz0HBo9c4EYTeM7Tvc9bBRg* future_p0, tyProc__HzVCwACFYM9cx9aV62PdjtuA cb_p1);
N_LIB_PRIVATE N_CLOSURE(void, colonanonymous___pkgZjazzyZcoreZserver_u106)(void* ClE_0);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZasyncfutures_u523)(tyObject_FutureBasecolonObjectType___JUz0HBo9c4EYTeM7Tvc9bBRg* dest_p0);
static N_INLINE(NIM_BOOL, isObjDisplayCheck)(TNimTypeV2* source_p0, NI16 targetDepth_p1, NU32 token_p2);
static N_INLINE(Exception*, nimBorrowCurrentException)(void);
N_LIB_PRIVATE N_NIMCALL(void, reraiseException)(void);
N_LIB_PRIVATE N_NIMCALL(void, fail__pureZasyncdispatch_u5492)(tyObject_FuturecolonObjectType___7M77QG5xE71ZeiEPHTHzlw* future_p0, Exception* error_p1);
static N_INLINE(Exception*, getCurrentException)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u3737)(Exception** dest_p0, Exception* src_p1, NIM_BOOL cyclic_p2);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u3734)(Exception* dest_p0);
static N_INLINE(void, popCurrentException)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZjazzyZcoreZserver_u222)(tyObject_Env_asyncmacrodotnim_serveNimAsyncContinue___ElhNFGpLGpiqK1CYfRGoZg* dest_p0);
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicStatic)(void* p_p0, TNimTypeV2* desc_p1);
N_LIB_PRIVATE N_NIMCALL(void, nimRawDispose)(void* p_p0, NI alignment_p1);
N_LIB_PRIVATE N_CLOSURE(tyObject_FutureBasecolonObjectType___JUz0HBo9c4EYTeM7Tvc9bBRg*, serveX20X28AsyncX29___pkgZjazzyZcoreZserver_u7)(tyObject_FuturecolonObjectType___7M77QG5xE71ZeiEPHTHzlw* retFutParamSym_p0, void* ClE_0);
N_LIB_PRIVATE N_NIMCALL(void, quit__system_u8532)(NimStringV2 errormsg_p0, NI errorcode_p1);
N_LIB_PRIVATE N_NIMCALL(void, complete__pureZasyncfutures_u247)(tyObject_FuturecolonObjectType___7M77QG5xE71ZeiEPHTHzlw* future_p0, tyObject_FuturecolonObjectType___7M77QG5xE71ZeiEPHTHzlw* val_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZasyncfutures_u547)(tyObject_FuturecolonObjectType___7M77QG5xE71ZeiEPHTHzlw* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___pureZasyncfutures_u544)(tyObject_FuturecolonObjectType___7M77QG5xE71ZeiEPHTHzlw** dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZjazzyZcoreZserver_u285)(tyObject_Env_asyncmacrodotnim_serveX20X28AsyncX29___Zlu8vHPJZ6LjmjoyKQN9bGQ* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZjazzyZcoreZserver_u260)(tyObject_Env_asyncmacrodotnim_serveX20X28AsyncX29___Zlu8vHPJZ6LjmjoyKQN9bGQ* dest_p0);
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__VOvae9c8Y2K9aBawx5M9cHhAQ_2 = { 5 | NIM_STRLIT_FLAG, "serve" };
static const NimStringV2 TM__VOvae9c8Y2K9aBawx5M9cHhAQ_3 = {5, (NimStrPayload*)&TM__VOvae9c8Y2K9aBawx5M9cHhAQ_2};
N_LIB_PRIVATE TNimTypeV2 NTIv2__ElhNFGpLGpiqK1CYfRGoZg_;
static const struct {
  NI cap; NIM_CHAR data[69+1];
} TM__VOvae9c8Y2K9aBawx5M9cHhAQ_7 = { 69 | NIM_STRLIT_FLAG, "Async procedure ($1) yielded `nil`, are you await\'ing a `nil` Future\?" };
static const NimStringV2 TM__VOvae9c8Y2K9aBawx5M9cHhAQ_8 = {69, (NimStrPayload*)&TM__VOvae9c8Y2K9aBawx5M9cHhAQ_7};
extern TNimTypeV2 NTIv2__fAtMgIeNQyfDKIqRjGsXPw_;
static const NimStringV2 TM__VOvae9c8Y2K9aBawx5M9cHhAQ_9 = {5, (NimStrPayload*)&TM__VOvae9c8Y2K9aBawx5M9cHhAQ_2};
N_LIB_PRIVATE TNimTypeV2 NTIv2__Zlu8vHPJZ6LjmjoyKQN9bGQ_;
static const struct {
  NI cap; NIM_CHAR data[43+1];
} TM__VOvae9c8Y2K9aBawx5M9cHhAQ_11 = { 43 | NIM_STRLIT_FLAG, "Base ServerDriver.serve must be overridden!" };
static const NimStringV2 TM__VOvae9c8Y2K9aBawx5M9cHhAQ_12 = {43, (NimStrPayload*)&TM__VOvae9c8Y2K9aBawx5M9cHhAQ_11};
extern NIM_THREADVAR TFrame* framePtr__system_u2809;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4293;
static NIM_CONST NU32 TM__VOvae9c8Y2K9aBawx5M9cHhAQ_4[2] = {3701606400, 1481446400};
N_LIB_PRIVATE TNimTypeV2 NTIv2__ElhNFGpLGpiqK1CYfRGoZg_ = {.destructor = (void*)rttiDestroy__pkgZjazzyZcoreZserver_u320, .size = sizeof(tyObject_Env_asyncmacrodotnim_serveNimAsyncContinue___ElhNFGpLGpiqK1CYfRGoZg), .align = (NI16) NIM_ALIGNOF(tyObject_Env_asyncmacrodotnim_serveNimAsyncContinue___ElhNFGpLGpiqK1CYfRGoZg), .depth = 1, .display = TM__VOvae9c8Y2K9aBawx5M9cHhAQ_4, .traceImpl = (void*)eqtrace___pkgZjazzyZcoreZserver_u194, .flags = 0};
extern NIM_THREADVAR Exception* currException__system_u3704;
static NIM_CONST NU32 TM__VOvae9c8Y2K9aBawx5M9cHhAQ_10[2] = {3701606400, 1539095552};
N_LIB_PRIVATE TNimTypeV2 NTIv2__Zlu8vHPJZ6LjmjoyKQN9bGQ_ = {.destructor = (void*)NIM_NIL, .size = sizeof(tyObject_Env_asyncmacrodotnim_serveX20X28AsyncX29___Zlu8vHPJZ6LjmjoyKQN9bGQ), .align = (NI16) NIM_ALIGNOF(tyObject_Env_asyncmacrodotnim_serveX20X28AsyncX29___Zlu8vHPJZ6LjmjoyKQN9bGQ), .depth = 1, .display = TM__VOvae9c8Y2K9aBawx5M9cHhAQ_10, .traceImpl = (void*)NIM_NIL, .flags = 0};
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2809 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2809).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2809;
	framePtr__system_u2809 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4511();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2809 = (*framePtr__system_u2809).prev;
}
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1) {
	NI result;
	nimfr_("-%", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/arithmetics.nim");
	nimlf_(377, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/arithmetics.nim");	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) - (NU64)(((NU) (y_p1))))));
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0) {
	NIM_BOOL result;
	nimfr_("nimDecRefIsLastCyclicDyn", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/orc.nim");
	nimlf_(518, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/orc.nim");	result = NIM_FALSE;
	nimln_(519);	{
		tyObject_RefHeader__sqhyc4FSbGmPtkvXRNl9acg* cell_1;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		nimln_(520);		nimlf_(60, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/arc.nim");		T5_ = (NI)0;
		T5_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)16));
		cell_1 = ((tyObject_RefHeader__sqhyc4FSbGmPtkvXRNl9acg*) (T5_));
		nimlf_(521, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/orc.nim");		{
			if (!((NI)((*cell_1).rc & ((NI)-16)) == ((NI)0))) goto LA8_;
			nimln_(522);			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			nimln_(525);			(*cell_1).rc = minuspercent___system_u813((*cell_1).rc, ((NI)16));
		}
LA6_: ;
		nimln_(527);		rememberCycle__system_u3573(result, cell_1, (*((TNimTypeV2**) (p_p0))));
	}
LA3_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZjazzyZcoreZserver_u182)(tyObject_Env_asyncmacrodotnim_serveNimAsyncContinue___ElhNFGpLGpiqK1CYfRGoZg* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).itX60gensym41_.ClE_0);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).itX60gensym41_.ClE_0);
	}
LA4_: ;
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).futX60gensym40_);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).futX60gensym40_);
	}
LA9_: ;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4293);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__pkgZjazzyZcoreZserver_u320)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___pkgZjazzyZcoreZserver_u182(((tyObject_Env_asyncmacrodotnim_serveNimAsyncContinue___ElhNFGpLGpiqK1CYfRGoZg*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(NI, pluspercent___system_u793)(NI x_p0, NI y_p1) {
	NI result;
	nimfr_("+%", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/arithmetics.nim");
	nimlf_(366, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/arithmetics.nim");	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) + (NU64)(((NU) (y_p1))))));
	popFrame();
	return result;
}
static N_INLINE(void, add__system_u3094)(tyObject_CellSeq__tmpRNCI2baMQRvZpqUI72g* s_p0, void** c_p1, TNimTypeV2* t_p2) {
	void** colontmp_;
	TNimTypeV2* colontmp__2;
	nimfr_("add", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/cellseqs_v2.nim");
	nimlf_(28, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/cellseqs_v2.nim");	{
		if (!((*s_p0).cap <= (*s_p0).len)) goto LA3_;
		nimln_(29);		resize__system_u3102(s_p0);
	}
LA3_: ;
	nimln_(30);	colontmp_ = c_p1;
	colontmp__2 = t_p2;
	(*s_p0).d[(*s_p0).len].Field0 = colontmp_;
	(*s_p0).d[(*s_p0).len].Field1 = colontmp__2;
	nimln_(31);	(*s_p0).len = pluspercent___system_u793((*s_p0).len, ((NI)1));
	popFrame();
}
static N_INLINE(void, nimTraceRefDyn)(void* q_p0, void* env_p1) {
	void** p_1;
	nimfr_("nimTraceRefDyn", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/orc.nim");
	nimlf_(138, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/orc.nim");	p_1 = ((void**) (q_p0));
	nimln_(139);	{
		tyObject_GcEnv__85WwC9a1qDcL9aPJ9b1qr0g2Q* j_1;
		if (!!(((*p_1) == NIM_NIL))) goto LA3_;
		nimln_(140);		j_1 = ((tyObject_GcEnv__85WwC9a1qDcL9aPJ9b1qr0g2Q*) (env_p1));
		nimln_(141);		add__system_u3094((&(*j_1).traceStack), p_1, (*((TNimTypeV2**) ((*p_1)))));
	}
LA3_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___pkgZjazzyZcoreZserver_u194)(tyObject_Env_asyncmacrodotnim_serveNimAsyncContinue___ElhNFGpLGpiqK1CYfRGoZg* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).futX60gensym40_, env_p1);
	nimTraceRefDyn((&(*dest_p0).itX60gensym41_.ClE_0), env_p1);
}
static N_INLINE(NIM_BOOL, finished__pkgZjazzyZcoreZserver_u45)(tyProc__9aRgHm8v4viL9ca0DLqdkxfw x_p0) {
	NIM_BOOL result;
	nimfr_("finished", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system.nim");
	result = (NIM_BOOL)0;
	nimlf_(2457, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system.nim");	    result = ((NI*) x_p0.ClE_0)[1] < 0;
    
	popFrame();
	return result;
}
N_LIB_PRIVATE N_CLOSURE(void, colonanonymous___pkgZjazzyZcoreZserver_u106)(void* ClE_0) {
	tyObject_Env_asyncmacrodotnim_serveNimAsyncContinue___ElhNFGpLGpiqK1CYfRGoZg* colonenvP__1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	colonenvP__1 = (tyObject_Env_asyncmacrodotnim_serveNimAsyncContinue___ElhNFGpLGpiqK1CYfRGoZg*) ClE_0;
	serveNimAsyncContinue__pkgZjazzyZcoreZserver_u13((*colonenvP__1).futX60gensym40_, (*colonenvP__1).itX60gensym41_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	nimSetMem__system_u2188(p_p0, ((int)0), size_p1);
}
static N_INLINE(NIM_BOOL, isObjDisplayCheck)(TNimTypeV2* source_p0, NI16 targetDepth_p1, NU32 token_p2) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	nimfr_("isObjDisplayCheck", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/arc.nim");
	nimlf_(288, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/arc.nim");	T1_ = (NIM_BOOL)0;
	T1_ = (targetDepth_p1 <= (*source_p0).depth);
	if (!(T1_)) goto LA2_;
	T1_ = ((*source_p0).display[targetDepth_p1] == token_p2);
LA2_: ;
	result = T1_;
	popFrame();
	return result;
}
static N_INLINE(Exception*, nimBorrowCurrentException)(void) {
	Exception* result;
	nimfr_("nimBorrowCurrentException", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system.nim");
	nimlf_(2371, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system.nim");	result = currException__system_u3704;
	popFrame();
	return result;
}
static N_INLINE(Exception*, getCurrentException)(void) {
	Exception* result;
	nimfr_("getCurrentException", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system.nim");
	result = NIM_NIL;
	nimlf_(107, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/excpt.nim");	eqcopy___system_u3737(&result, currException__system_u3704, NIM_FALSE);
	popFrame();
	return result;
}
static N_INLINE(void, popCurrentException)(void) {
	eqcopy___system_u3737(&currException__system_u3704, (*currException__system_u3704).up, NIM_FALSE);
}
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicStatic)(void* p_p0, TNimTypeV2* desc_p1) {
	NIM_BOOL result;
	nimfr_("nimDecRefIsLastCyclicStatic", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/orc.nim");
	nimlf_(544, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/orc.nim");	result = NIM_FALSE;
	nimln_(545);	{
		tyObject_RefHeader__sqhyc4FSbGmPtkvXRNl9acg* cell_1;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		nimln_(546);		nimlf_(60, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/arc.nim");		T5_ = (NI)0;
		T5_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)16));
		cell_1 = ((tyObject_RefHeader__sqhyc4FSbGmPtkvXRNl9acg*) (T5_));
		nimlf_(547, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/orc.nim");		{
			if (!((NI)((*cell_1).rc & ((NI)-16)) == ((NI)0))) goto LA8_;
			nimln_(548);			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			nimln_(551);			(*cell_1).rc = minuspercent___system_u813((*cell_1).rc, ((NI)16));
		}
LA6_: ;
		nimln_(553);		rememberCycle__system_u3573(result, cell_1, desc_p1);
	}
LA3_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZjazzyZcoreZserver_u222)(tyObject_Env_asyncmacrodotnim_serveNimAsyncContinue___ElhNFGpLGpiqK1CYfRGoZg* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicStatic(dest_p0, ((TNimTypeV2*) ((&NTIv2__ElhNFGpLGpiqK1CYfRGoZg_))));
		if (!T3_) goto LA4_;
		eqdestroy___pkgZjazzyZcoreZserver_u182((&(*dest_p0)));
		nimRawDispose(dest_p0, ((NI)8));
	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, serveNimAsyncContinue__pkgZjazzyZcoreZserver_u13)(tyObject_FuturecolonObjectType___7M77QG5xE71ZeiEPHTHzlw* futX60gensym4__p0, tyProc__9aRgHm8v4viL9ca0DLqdkxfw itX60gensym4__p1) {
	tyObject_Env_asyncmacrodotnim_serveNimAsyncContinue___ElhNFGpLGpiqK1CYfRGoZg* colonenv__1;
	tyObject_Env_asyncmacrodotnim_serveNimAsyncContinue___ElhNFGpLGpiqK1CYfRGoZg* T2_;
NIM_BOOL oldNimErrFin9_;
NIM_BOOL oldNimErrFin1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	colonenv__1 = NIM_NIL;
	T2_ = NIM_NIL;
	T2_ = (tyObject_Env_asyncmacrodotnim_serveNimAsyncContinue___ElhNFGpLGpiqK1CYfRGoZg*) nimNewObj(sizeof(tyObject_Env_asyncmacrodotnim_serveNimAsyncContinue___ElhNFGpLGpiqK1CYfRGoZg), NIM_ALIGNOF(tyObject_Env_asyncmacrodotnim_serveNimAsyncContinue___ElhNFGpLGpiqK1CYfRGoZg));
	(*T2_).Sup.m_type = (&NTIv2__ElhNFGpLGpiqK1CYfRGoZg_);
	colonenv__1 = T2_;
	eqcopy___pureZasyncfutures_u550(&(*colonenv__1).futX60gensym40_, futX60gensym4__p0, NIM_TRUE);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	eqcopy___pkgZjazzyZcoreZserver_u55((&(*colonenv__1).itX60gensym41_), itX60gensym4__p1, NIM_TRUE);
	{
		NIM_BOOL T6_;
		tyObject_FutureBasecolonObjectType___JUz0HBo9c4EYTeM7Tvc9bBRg* nextX60gensym4__1;
		tyObject_FutureBasecolonObjectType___JUz0HBo9c4EYTeM7Tvc9bBRg* T10_;
		T6_ = (NIM_BOOL)0;
		T6_ = finished__pkgZjazzyZcoreZserver_u45((*colonenv__1).itX60gensym41_);
		if (!!(T6_)) goto LA7_;
		nextX60gensym4__1 = NIM_NIL;
		T10_ = NIM_NIL;
		T10_ = (*colonenv__1).itX60gensym41_.ClP_0((*colonenv__1).futX60gensym40_, (*colonenv__1).itX60gensym41_.ClE_0);
		if (NIM_UNLIKELY(*nimErr_)) goto LA9_;
		nextX60gensym4__1 = T10_;
		{
			while (1) {
				NIM_BOOL T13_;
				tyObject_FutureBasecolonObjectType___JUz0HBo9c4EYTeM7Tvc9bBRg* T15_;
				T13_ = (NIM_BOOL)0;
				T13_ = !((nextX60gensym4__1 == 0));
				if (!(T13_)) goto LA14_;
				T13_ = finished__pureZasyncdispatch_u8644(nextX60gensym4__1);
				if (NIM_UNLIKELY(*nimErr_)) goto LA9_;
LA14_: ;
				if (!T13_) goto LA12;
				T15_ = NIM_NIL;
				T15_ = (*colonenv__1).itX60gensym41_.ClP_0((*colonenv__1).futX60gensym40_, (*colonenv__1).itX60gensym41_.ClE_0);
				if (NIM_UNLIKELY(*nimErr_)) goto LA9_;
				eqsink___pureZasyncfutures_u534(&nextX60gensym4__1, T15_);
				if (NIM_UNLIKELY(*nimErr_)) goto LA9_;
				{
					NIM_BOOL T18_;
					T18_ = (NIM_BOOL)0;
					T18_ = finished__pkgZjazzyZcoreZserver_u45((*colonenv__1).itX60gensym41_);
					if (!T18_) goto LA19_;
					goto LA11;
				}
LA19_: ;
			} LA12: ;
		} LA11: ;
		{
			if (!(nextX60gensym4__1 == ((tyObject_FutureBasecolonObjectType___JUz0HBo9c4EYTeM7Tvc9bBRg*) NIM_NIL))) goto LA23_;
			{
				NIM_BOOL T27_;
				NimStringV2 msgX60gensym4__1;
				tyObject_AssertionDefect__fAtMgIeNQyfDKIqRjGsXPw* T30_;
				T27_ = (NIM_BOOL)0;
				T27_ = finished__pkgZjazzyZcoreZserver_u95((*colonenv__1).futX60gensym40_);
				if (NIM_UNLIKELY(*nimErr_)) goto LA9_;
				if (!!(T27_)) goto LA28_;
				msgX60gensym4__1.len = 0; msgX60gensym4__1.p = NIM_NIL;
				msgX60gensym4__1 = TM__VOvae9c8Y2K9aBawx5M9cHhAQ_8;
				T30_ = NIM_NIL;
				T30_ = (tyObject_AssertionDefect__fAtMgIeNQyfDKIqRjGsXPw*) nimNewObj(sizeof(tyObject_AssertionDefect__fAtMgIeNQyfDKIqRjGsXPw), NIM_ALIGNOF(tyObject_AssertionDefect__fAtMgIeNQyfDKIqRjGsXPw));
				(*T30_).Sup.Sup.Sup.m_type = (&NTIv2__fAtMgIeNQyfDKIqRjGsXPw_);
				(*T30_).Sup.Sup.name = "AssertionDefect";
				(*T30_).Sup.Sup.message = nsuFormatSingleElem(msgX60gensym4__1, TM__VOvae9c8Y2K9aBawx5M9cHhAQ_9);
				if (NIM_UNLIKELY(*nimErr_)) goto LA9_;
				(*T30_).Sup.Sup.parent = ((Exception*) NIM_NIL);
				raiseExceptionEx((Exception*)T30_, "AssertionDefect", "serveNimAsyncContinue", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/pure/asyncmacro.nim", 44);
goto LA9_;
			}
LA28_: ;
		}
		goto LA21_;
LA23_: ;
		{
			tyProc__HzVCwACFYM9cx9aV62PdjtuA T32_;
			tyProc__HzVCwACFYM9cx9aV62PdjtuA T33_;
			nimZeroMem((void*)(&T32_), sizeof(tyProc__HzVCwACFYM9cx9aV62PdjtuA));
			T32_.ClP_0 = colonanonymous___pkgZjazzyZcoreZserver_u106; T32_.ClE_0 = colonenv__1;
			nimZeroMem((void*)(&T33_), sizeof(tyProc__HzVCwACFYM9cx9aV62PdjtuA));
			T33_.ClP_0 = colonanonymous___pkgZjazzyZcoreZserver_u106; T33_.ClE_0 = colonenv__1;
			addCallback__pureZasyncfutures_u677(nextX60gensym4__1, T33_);
			if (NIM_UNLIKELY(*nimErr_)) goto LA9_;
		}
LA21_: ;
		{
			LA9_:;
		}
		{
			oldNimErrFin9_ = *nimErr_; *nimErr_ = NIM_FALSE;
			eqdestroy___pureZasyncfutures_u523(nextX60gensym4__1);
			if (NIM_UNLIKELY(*nimErr_)) goto LA3_;
			*nimErr_ = oldNimErrFin9_;
		}
		if (NIM_UNLIKELY(*nimErr_)) goto LA3_;
	}
LA7_: ;
	if (NIM_UNLIKELY(*nimErr_)) {
		LA3_:;
		if (isObjDisplayCheck(nimBorrowCurrentException()->Sup.m_type, 1, 1285336064)) {
			*nimErr_ = NIM_FALSE;
			{
				NIM_BOOL T41_;
				T41_ = (NIM_BOOL)0;
				T41_ = finished__pkgZjazzyZcoreZserver_u95((*colonenv__1).futX60gensym40_);
				if (NIM_UNLIKELY(*nimErr_)) goto LA37_;
				if (!T41_) goto LA42_;
				reraiseException();
goto LA37_;
			}
			goto LA39_;
LA42_: ;
			{
				Exception* colontmpD_;
				colontmpD_ = NIM_NIL;
				colontmpD_ = getCurrentException();
				fail__pureZasyncdispatch_u5492((*colonenv__1).futX60gensym40_, colontmpD_);
				if (NIM_UNLIKELY(*nimErr_)) goto LA45_;
				{
					LA45_:;
				}
				{
					eqdestroy___system_u3734(colontmpD_);
				}
				if (NIM_UNLIKELY(*nimErr_)) goto LA37_;
			}
LA39_: ;
			popCurrentException();
			LA37_:;
		}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		LA1_:;
	}
	{
		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
		eqdestroy___pkgZjazzyZcoreZserver_u222(colonenv__1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		*nimErr_ = oldNimErrFin1_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_CLOSURE(tyObject_FutureBasecolonObjectType___JUz0HBo9c4EYTeM7Tvc9bBRg*, serveX20X28AsyncX29___pkgZjazzyZcoreZserver_u7)(tyObject_FuturecolonObjectType___7M77QG5xE71ZeiEPHTHzlw* retFutParamSym_p0, void* ClE_0) {
	tyObject_FutureBasecolonObjectType___JUz0HBo9c4EYTeM7Tvc9bBRg* result;
	tyObject_Env_asyncmacrodotnim_serveX20X28AsyncX29___Zlu8vHPJZ6LjmjoyKQN9bGQ* colonenvP__1;
NIM_BOOL oldNimErrFin4_;
NIM_BOOL* nimErr_;
	nimfr_("serve (Async)", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/pure/asyncmacro.nim");
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	colonenvP__1 = (tyObject_Env_asyncmacrodotnim_serveX20X28AsyncX29___Zlu8vHPJZ6LjmjoyKQN9bGQ*) ClE_0;
	while (1) {
		{
			switch ((*colonenvP__1).colonstate_) {
			case ((NI)0):
			{
				tyObject_FuturecolonObjectType___7M77QG5xE71ZeiEPHTHzlw* result_2;
				NIM_BOOL needsCompletion_1;
				result_2 = NIM_NIL;
				nimlf_(264, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/pure/asyncmacro.nim");				result_2 = 0;
				nimln_(248);				needsCompletion_1 = NIM_FALSE;
				{
					nimlf_(12, "/home/icarogdo/.nimble/pkgs2/jazzy-0.4.5-4fdda426bdb506437985763b18fb2c79ca01e6e0/jazzy/core/server.nim");					quit__system_u8532(TM__VOvae9c8Y2K9aBawx5M9cHhAQ_12, ((NI)1));
				}
				nimlf_(273, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/pure/asyncmacro.nim");				complete__pureZasyncfutures_u247(retFutParamSym_p0, result_2);
				if (NIM_UNLIKELY(*nimErr_)) goto LA4_;
				nimln_(247);				(*colonenvP__1).colonstate_ = ((NI)-1);
				nimlf_(162, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/pure/asyncfutures.nim");				eqdestroy___pureZasyncfutures_u547(result_2);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				goto LA2;
				{
					LA4_:;
				}
				{
					oldNimErrFin4_ = *nimErr_; *nimErr_ = NIM_FALSE;
					nimln_(162);					eqdestroy___pureZasyncfutures_u547(result_2);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					*nimErr_ = oldNimErrFin4_;
				}
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			}
			break;
			default:
			{
				goto BeforeRet_;
			}
			break;
			}
		} LA2: ;
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZjazzyZcoreZserver_u260)(tyObject_Env_asyncmacrodotnim_serveX20X28AsyncX29___Zlu8vHPJZ6LjmjoyKQN9bGQ* dest_p0) {
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZjazzyZcoreZserver_u285)(tyObject_Env_asyncmacrodotnim_serveX20X28AsyncX29___Zlu8vHPJZ6LjmjoyKQN9bGQ* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicStatic(dest_p0, ((TNimTypeV2*) ((&NTIv2__Zlu8vHPJZ6LjmjoyKQN9bGQ_))));
		if (!T3_) goto LA4_;
		eqdestroy___pkgZjazzyZcoreZserver_u260((&(*dest_p0)));
		nimRawDispose(dest_p0, ((NI)8));
	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType___7M77QG5xE71ZeiEPHTHzlw*, serve__pkgZjazzyZcoreZserver_u19)(tyObject_ServerDrivercolonObjectType___1B9aC8SAqlBwmqHUT5tnGMg* driver_p0, NI port_p1, NimStringV2 address_p2, tyProc__9bEKzqwPW59c2SORTEBVDeiQ handler_p3) {
	tyObject_FuturecolonObjectType___7M77QG5xE71ZeiEPHTHzlw* result;
	tyObject_FuturecolonObjectType___7M77QG5xE71ZeiEPHTHzlw* retFuture_1;
	tyObject_Env_asyncmacrodotnim_serveX20X28AsyncX29___Zlu8vHPJZ6LjmjoyKQN9bGQ* colonenv__1;
	tyObject_Env_asyncmacrodotnim_serveX20X28AsyncX29___Zlu8vHPJZ6LjmjoyKQN9bGQ* T2_;
	tyProc__9aRgHm8v4viL9ca0DLqdkxfw T3_;
NIM_BOOL oldNimErrFin1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	retFuture_1 = NIM_NIL;
	colonenv__1 = NIM_NIL;
	retFuture_1 = newFuture__pureZasyncdispatch_u5453(TM__VOvae9c8Y2K9aBawx5M9cHhAQ_3);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T2_ = NIM_NIL;
	T2_ = (tyObject_Env_asyncmacrodotnim_serveX20X28AsyncX29___Zlu8vHPJZ6LjmjoyKQN9bGQ*) nimNewObj(sizeof(tyObject_Env_asyncmacrodotnim_serveX20X28AsyncX29___Zlu8vHPJZ6LjmjoyKQN9bGQ), NIM_ALIGNOF(tyObject_Env_asyncmacrodotnim_serveX20X28AsyncX29___Zlu8vHPJZ6LjmjoyKQN9bGQ));
	(*T2_).Sup.m_type = (&NTIv2__Zlu8vHPJZ6LjmjoyKQN9bGQ_);
	colonenv__1 = T2_;
	nimZeroMem((void*)(&T3_), sizeof(tyProc__9aRgHm8v4viL9ca0DLqdkxfw));
	T3_.ClP_0 = serveX20X28AsyncX29___pkgZjazzyZcoreZserver_u7; T3_.ClE_0 = colonenv__1;
	serveNimAsyncContinue__pkgZjazzyZcoreZserver_u13(retFuture_1, T3_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	result = retFuture_1;
	eqwasMoved___pureZasyncfutures_u544(&retFuture_1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	eqdestroy___pkgZjazzyZcoreZserver_u285(colonenv__1);
	eqdestroy___pureZasyncfutures_u547(retFuture_1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	goto BeforeRet_;
	{
		LA1_:;
	}
	{
		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
		eqdestroy___pkgZjazzyZcoreZserver_u285(colonenv__1);
		eqdestroy___pureZasyncfutures_u547(retFuture_1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		*nimErr_ = oldNimErrFin1_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
