/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -fno-strict-aliasing -pthread -I/home/icarogdo/.nimble/pkgs2/bearssl-0.2.10-e53ab85b8c4c1ce3aa1f4eb251c0ab29e08d4972/bearssl/abi -I/home/icarogdo/.nimble/pkgs2/bearssl-0.2.10-e53ab85b8c4c1ce3aa1f4eb251c0ab29e08d4972/bearssl/abi/../csources/src/ -I/home/icarogdo/.nimble/pkgs2/bearssl-0.2.10-e53ab85b8c4c1ce3aa1f4eb251c0ab29e08d4972/bearssl/abi/../csources/inc/ -I/home/icarogdo/.nimble/pkgs2/bearssl-0.2.10-e53ab85b8c4c1ce3aa1f4eb251c0ab29e08d4972/bearssl/abi/../csources/tools/ -DBR_USE_UNIX_TIME=1 -DBR_USE_URANDOM=1 -DBR_LE_UNALIGNED=1 -DBR_64=1  -DBR_amd64=1 -DBR_INT128=1 -Wno-incompatible-pointer-types -I/usr/include/webkitgtk-4.1 -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/cloudproviders -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/glycin-2 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/atk-1.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/fribidi -I/usr/include/pixman-1 -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gio-unix-2.0 -I/usr/include/libsoup-3.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-6 -pthread  -msha -msse2 -mssse3 -msse4.1  -I/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib -I/home/icarogdo/dev/macroobras-jazzy/app/macroobras/src -o /home/icarogdo/dev/macroobras-jazzy/app/macroobras/.nimcache/@nnimcrypto-0.7.3-f72b90fe3f4da09efa482de4f8729e7ee4abea2f@snimcrypto@ssha2@ssha2_sha.nim.c.o /home/icarogdo/dev/macroobras-jazzy/app/macroobras/.nimcache/@nnimcrypto-0.7.3-f72b90fe3f4da09efa482de4f8729e7ee4abea2f@snimcrypto@ssha2@ssha2_sha.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <x86intrin.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef NU64 tyArray__taWZDEZhXZ6W9aPxa9aL9aXaA[2];
typedef __m128i tyArray__SJBsSIUb9bxw6UMNLtKlhpw[4];
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4511)(void);
static N_INLINE(void, popFrame)(void);
extern NIM_THREADVAR TFrame* framePtr__system_u2809;
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2809 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2809).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2809;
	framePtr__system_u2809 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4511();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2809 = (*framePtr__system_u2809).prev;
}
N_LIB_PRIVATE N_NIMCALL(void, sha256Compress__pkgZnimcryptoZsha2Zsha295sha_u67)(NU32* state_p0, NU8* data_p1, NI data_p1Len_0, NI blocks_p2) {
	NIM_ALIGN(32) __m128i shufMask_1;
	tyArray__SJBsSIUb9bxw6UMNLtKlhpw msgtmp_1;
	NIM_ALIGN(32) __m128i msg_1;
	NIM_ALIGN(32) __m128i tmp_1;
	__m128i T1_;
	NIM_ALIGN(32) __m128i state1_1;
	__m128i T2_;
	NIM_ALIGN(32) __m128i state0_1;
	NI blocksCount_1;
	NI offset_1;
	nimfr_("sha256Compress", "/home/icarogdo/.nimble/pkgs2/nimcrypto-0.7.3-f72b90fe3f4da09efa482de4f8729e7ee4abea2f/nimcrypto/sha2/sha2_sha.nim");
{	nimlf_(88, "/home/icarogdo/.nimble/pkgs2/nimcrypto-0.7.3-f72b90fe3f4da09efa482de4f8729e7ee4abea2f/nimcrypto/sha2/sha2_sha.nim");	nimln_(89);	shufMask_1 = _mm_set_epi64x(868365760874482187ULL, 289644378169868803ULL);
	nimln_(94);	T1_ = _mm_loadu_si128(((__m128i*) ((&state_p0[(((NI)0))- 0]))));
	tmp_1 = _mm_shuffle_epi32(T1_, ((NU32)177));
	nimln_(95);	T2_ = _mm_loadu_si128(((__m128i*) ((&state_p0[(((NI)4))- 0]))));
	state1_1 = _mm_shuffle_epi32(T2_, ((NU32)27));
	nimln_(96);	state0_1 = _mm_alignr_epi8(tmp_1, state1_1, ((NU32)8));
	nimln_(97);	blocksCount_1 = blocks_p2;
	nimln_(98);	offset_1 = ((NI)0);
	nimln_(100);	state1_1 = _mm_blend_epi16(state1_1, tmp_1, ((NU32)240));
	{
		nimln_(102);		while (1) {
			__m128i state0_save_1;
			__m128i state1_save_1;
			__m128i T5_;
			__m128i T6_;
			NI TM__QMTBJ3B2LA4Z4wAiKYiWww_2;
			__m128i T7_;
			__m128i T8_;
			NI TM__QMTBJ3B2LA4Z4wAiKYiWww_3;
			__m128i T9_;
			__m128i T10_;
			NI TM__QMTBJ3B2LA4Z4wAiKYiWww_4;
			__m128i T11_;
			__m128i T12_;
			__m128i T13_;
			__m128i T14_;
			__m128i T15_;
			__m128i T16_;
			__m128i T17_;
			__m128i T18_;
			__m128i T19_;
			__m128i T20_;
			__m128i T21_;
			__m128i T22_;
			__m128i T23_;
			__m128i T24_;
			NI TM__QMTBJ3B2LA4Z4wAiKYiWww_5;
			NI TM__QMTBJ3B2LA4Z4wAiKYiWww_6;
			if (!(((NI)0) < blocksCount_1)) goto LA4;
			nimln_(104);			state0_save_1 = state0_1;
			nimln_(105);			state1_save_1 = state1_1;
			nimln_(107);			if (offset_1 < 0 || offset_1 >= data_p1Len_0){ raiseIndexError2(offset_1,data_p1Len_0-1); goto BeforeRet_;
			}
			T5_ = _mm_loadu_si128(((__m128i*) ((&data_p1[offset_1]))));
			msgtmp_1[(((NI)0))- 0] = _mm_shuffle_epi8(T5_, shufMask_1);
			nimln_(108);			T6_ = _mm_setr_epi32(((NU32)1116352408), ((NU32)1899447441), ((NU32)IL64(3049323471)), ((NU32)IL64(3921009573)));
			msg_1 = _mm_add_epi32(msgtmp_1[(((NI)0))- 0], T6_);
			nimln_(109);			state1_1 = _mm_sha256rnds2_epu32(state1_1, state0_1, msg_1);
			nimln_(110);			msg_1 = _mm_shuffle_epi32(msg_1, ((NU32)14));
			nimln_(111);			state0_1 = _mm_sha256rnds2_epu32(state0_1, state1_1, msg_1);
			nimln_(113);			if (nimAddInt(offset_1, ((NI)16), &TM__QMTBJ3B2LA4Z4wAiKYiWww_2)) { raiseOverflow(); goto BeforeRet_;
			};
			if ((NI)(TM__QMTBJ3B2LA4Z4wAiKYiWww_2) < 0 || (NI)(TM__QMTBJ3B2LA4Z4wAiKYiWww_2) >= data_p1Len_0){ raiseIndexError2((NI)(TM__QMTBJ3B2LA4Z4wAiKYiWww_2),data_p1Len_0-1); goto BeforeRet_;
			}
			T7_ = _mm_loadu_si128(((__m128i*) ((&data_p1[(NI)(TM__QMTBJ3B2LA4Z4wAiKYiWww_2)]))));
			msgtmp_1[(((NI)1))- 0] = _mm_shuffle_epi8(T7_, shufMask_1);
			nimln_(114);			T8_ = _mm_setr_epi32(((NU32)961987163), ((NU32)1508970993), ((NU32)IL64(2453635748)), ((NU32)IL64(2870763221)));
			msg_1 = _mm_add_epi32(msgtmp_1[(((NI)1))- 0], T8_);
			nimln_(115);			state1_1 = _mm_sha256rnds2_epu32(state1_1, state0_1, msg_1);
			nimln_(116);			msg_1 = _mm_shuffle_epi32(msg_1, ((NU32)14));
			nimln_(117);			state0_1 = _mm_sha256rnds2_epu32(state0_1, state1_1, msg_1);
			nimln_(118);			msgtmp_1[(((NI)0))- 0] = _mm_sha256msg1_epu32(msgtmp_1[(((NI)0))- 0], msgtmp_1[(((NI)1))- 0]);
			nimln_(120);			if (nimAddInt(offset_1, ((NI)32), &TM__QMTBJ3B2LA4Z4wAiKYiWww_3)) { raiseOverflow(); goto BeforeRet_;
			};
			if ((NI)(TM__QMTBJ3B2LA4Z4wAiKYiWww_3) < 0 || (NI)(TM__QMTBJ3B2LA4Z4wAiKYiWww_3) >= data_p1Len_0){ raiseIndexError2((NI)(TM__QMTBJ3B2LA4Z4wAiKYiWww_3),data_p1Len_0-1); goto BeforeRet_;
			}
			T9_ = _mm_loadu_si128(((__m128i*) ((&data_p1[(NI)(TM__QMTBJ3B2LA4Z4wAiKYiWww_3)]))));
			msgtmp_1[(((NI)2))- 0] = _mm_shuffle_epi8(T9_, shufMask_1);
			nimln_(121);			T10_ = _mm_setr_epi32(((NU32)IL64(3624381080)), ((NU32)310598401), ((NU32)607225278), ((NU32)1426881987));
			msg_1 = _mm_add_epi32(msgtmp_1[(((NI)2))- 0], T10_);
			nimln_(122);			state1_1 = _mm_sha256rnds2_epu32(state1_1, state0_1, msg_1);
			nimln_(123);			msg_1 = _mm_shuffle_epi32(msg_1, ((NU32)14));
			nimln_(124);			state0_1 = _mm_sha256rnds2_epu32(state0_1, state1_1, msg_1);
			nimln_(125);			msgtmp_1[(((NI)1))- 0] = _mm_sha256msg1_epu32(msgtmp_1[(((NI)1))- 0], msgtmp_1[(((NI)2))- 0]);
			nimln_(127);			if (nimAddInt(offset_1, ((NI)48), &TM__QMTBJ3B2LA4Z4wAiKYiWww_4)) { raiseOverflow(); goto BeforeRet_;
			};
			if ((NI)(TM__QMTBJ3B2LA4Z4wAiKYiWww_4) < 0 || (NI)(TM__QMTBJ3B2LA4Z4wAiKYiWww_4) >= data_p1Len_0){ raiseIndexError2((NI)(TM__QMTBJ3B2LA4Z4wAiKYiWww_4),data_p1Len_0-1); goto BeforeRet_;
			}
			T11_ = _mm_loadu_si128(((__m128i*) ((&data_p1[(NI)(TM__QMTBJ3B2LA4Z4wAiKYiWww_4)]))));
			msgtmp_1[(((NI)3))- 0] = _mm_shuffle_epi8(T11_, shufMask_1);
			nimln_(130);			T12_ = _mm_setr_epi32(((NU32)1925078388), ((NU32)IL64(2162078206)), ((NU32)IL64(2614888103)), ((NU32)IL64(3248222580)));
			msg_1 = _mm_add_epi32(msgtmp_1[(((NI)3))- 0], T12_);
			nimln_(131);			state1_1 = _mm_sha256rnds2_epu32(state1_1, state0_1, msg_1);
			nimln_(132);			tmp_1 = _mm_alignr_epi8(msgtmp_1[(((NI)3))- 0], msgtmp_1[(((NI)2))- 0], ((NU32)4));
			nimln_(133);			msgtmp_1[(((NI)0))- 0] = _mm_add_epi32(msgtmp_1[(((NI)0))- 0], tmp_1);
			nimln_(134);			msgtmp_1[(((NI)0))- 0] = _mm_sha256msg2_epu32(msgtmp_1[(((NI)0))- 0], msgtmp_1[(((NI)3))- 0]);
			nimln_(135);			msg_1 = _mm_shuffle_epi32(msg_1, ((NU32)14));
			nimln_(136);			state0_1 = _mm_sha256rnds2_epu32(state0_1, state1_1, msg_1);
			nimln_(137);			msgtmp_1[(((NI)2))- 0] = _mm_sha256msg1_epu32(msgtmp_1[(((NI)2))- 0], msgtmp_1[(((NI)3))- 0]);
			nimln_(139);			T13_ = _mm_setr_epi32(((NU32)IL64(3835390401)), ((NU32)IL64(4022224774)), ((NU32)264347078), ((NU32)604807628));
			msg_1 = _mm_add_epi32(msgtmp_1[(((NI)0))- 0], T13_);
			nimln_(140);			state1_1 = _mm_sha256rnds2_epu32(state1_1, state0_1, msg_1);
			nimln_(141);			tmp_1 = _mm_alignr_epi8(msgtmp_1[(((NI)0))- 0], msgtmp_1[(((NI)3))- 0], ((NU32)4));
			nimln_(142);			msgtmp_1[(((NI)1))- 0] = _mm_add_epi32(msgtmp_1[(((NI)1))- 0], tmp_1);
			nimln_(143);			msgtmp_1[(((NI)1))- 0] = _mm_sha256msg2_epu32(msgtmp_1[(((NI)1))- 0], msgtmp_1[(((NI)0))- 0]);
			nimln_(144);			msg_1 = _mm_shuffle_epi32(msg_1, ((NU32)14));
			nimln_(145);			state0_1 = _mm_sha256rnds2_epu32(state0_1, state1_1, msg_1);
			nimln_(146);			msgtmp_1[(((NI)3))- 0] = _mm_sha256msg1_epu32(msgtmp_1[(((NI)3))- 0], msgtmp_1[(((NI)0))- 0]);
			nimln_(148);			T14_ = _mm_setr_epi32(((NU32)770255983), ((NU32)1249150122), ((NU32)1555081692), ((NU32)1996064986));
			msg_1 = _mm_add_epi32(msgtmp_1[(((NI)1))- 0], T14_);
			nimln_(149);			state1_1 = _mm_sha256rnds2_epu32(state1_1, state0_1, msg_1);
			nimln_(150);			tmp_1 = _mm_alignr_epi8(msgtmp_1[(((NI)1))- 0], msgtmp_1[(((NI)0))- 0], ((NU32)4));
			nimln_(151);			msgtmp_1[(((NI)2))- 0] = _mm_add_epi32(msgtmp_1[(((NI)2))- 0], tmp_1);
			nimln_(152);			msgtmp_1[(((NI)2))- 0] = _mm_sha256msg2_epu32(msgtmp_1[(((NI)2))- 0], msgtmp_1[(((NI)1))- 0]);
			nimln_(153);			msg_1 = _mm_shuffle_epi32(msg_1, ((NU32)14));
			nimln_(154);			state0_1 = _mm_sha256rnds2_epu32(state0_1, state1_1, msg_1);
			nimln_(155);			msgtmp_1[(((NI)0))- 0] = _mm_sha256msg1_epu32(msgtmp_1[(((NI)0))- 0], msgtmp_1[(((NI)1))- 0]);
			nimln_(157);			T15_ = _mm_setr_epi32(((NU32)IL64(2554220882)), ((NU32)IL64(2821834349)), ((NU32)IL64(2952996808)), ((NU32)IL64(3210313671)));
			msg_1 = _mm_add_epi32(msgtmp_1[(((NI)2))- 0], T15_);
			nimln_(158);			state1_1 = _mm_sha256rnds2_epu32(state1_1, state0_1, msg_1);
			nimln_(159);			tmp_1 = _mm_alignr_epi8(msgtmp_1[(((NI)2))- 0], msgtmp_1[(((NI)1))- 0], ((NU32)4));
			nimln_(160);			msgtmp_1[(((NI)3))- 0] = _mm_add_epi32(msgtmp_1[(((NI)3))- 0], tmp_1);
			nimln_(161);			msgtmp_1[(((NI)3))- 0] = _mm_sha256msg2_epu32(msgtmp_1[(((NI)3))- 0], msgtmp_1[(((NI)2))- 0]);
			nimln_(162);			msg_1 = _mm_shuffle_epi32(msg_1, ((NU32)14));
			nimln_(163);			state0_1 = _mm_sha256rnds2_epu32(state0_1, state1_1, msg_1);
			nimln_(164);			msgtmp_1[(((NI)1))- 0] = _mm_sha256msg1_epu32(msgtmp_1[(((NI)1))- 0], msgtmp_1[(((NI)2))- 0]);
			nimln_(166);			T16_ = _mm_setr_epi32(((NU32)IL64(3336571891)), ((NU32)IL64(3584528711)), ((NU32)113926993), ((NU32)338241895));
			msg_1 = _mm_add_epi32(msgtmp_1[(((NI)3))- 0], T16_);
			nimln_(167);			state1_1 = _mm_sha256rnds2_epu32(state1_1, state0_1, msg_1);
			nimln_(168);			tmp_1 = _mm_alignr_epi8(msgtmp_1[(((NI)3))- 0], msgtmp_1[(((NI)2))- 0], ((NU32)4));
			nimln_(169);			msgtmp_1[(((NI)0))- 0] = _mm_add_epi32(msgtmp_1[(((NI)0))- 0], tmp_1);
			nimln_(170);			msgtmp_1[(((NI)0))- 0] = _mm_sha256msg2_epu32(msgtmp_1[(((NI)0))- 0], msgtmp_1[(((NI)3))- 0]);
			nimln_(171);			msg_1 = _mm_shuffle_epi32(msg_1, ((NU32)14));
			nimln_(172);			state0_1 = _mm_sha256rnds2_epu32(state0_1, state1_1, msg_1);
			nimln_(173);			msgtmp_1[(((NI)2))- 0] = _mm_sha256msg1_epu32(msgtmp_1[(((NI)2))- 0], msgtmp_1[(((NI)3))- 0]);
			nimln_(175);			T17_ = _mm_setr_epi32(((NU32)666307205), ((NU32)773529912), ((NU32)1294757372), ((NU32)1396182291));
			msg_1 = _mm_add_epi32(msgtmp_1[(((NI)0))- 0], T17_);
			nimln_(176);			state1_1 = _mm_sha256rnds2_epu32(state1_1, state0_1, msg_1);
			nimln_(177);			tmp_1 = _mm_alignr_epi8(msgtmp_1[(((NI)0))- 0], msgtmp_1[(((NI)3))- 0], ((NU32)4));
			nimln_(178);			msgtmp_1[(((NI)1))- 0] = _mm_add_epi32(msgtmp_1[(((NI)1))- 0], tmp_1);
			nimln_(179);			msgtmp_1[(((NI)1))- 0] = _mm_sha256msg2_epu32(msgtmp_1[(((NI)1))- 0], msgtmp_1[(((NI)0))- 0]);
			nimln_(180);			msg_1 = _mm_shuffle_epi32(msg_1, ((NU32)14));
			nimln_(181);			state0_1 = _mm_sha256rnds2_epu32(state0_1, state1_1, msg_1);
			nimln_(182);			msgtmp_1[(((NI)3))- 0] = _mm_sha256msg1_epu32(msgtmp_1[(((NI)3))- 0], msgtmp_1[(((NI)0))- 0]);
			nimln_(184);			T18_ = _mm_setr_epi32(((NU32)1695183700), ((NU32)1986661051), ((NU32)IL64(2177026350)), ((NU32)IL64(2456956037)));
			msg_1 = _mm_add_epi32(msgtmp_1[(((NI)1))- 0], T18_);
			nimln_(185);			state1_1 = _mm_sha256rnds2_epu32(state1_1, state0_1, msg_1);
			nimln_(186);			tmp_1 = _mm_alignr_epi8(msgtmp_1[(((NI)1))- 0], msgtmp_1[(((NI)0))- 0], ((NU32)4));
			nimln_(187);			msgtmp_1[(((NI)2))- 0] = _mm_add_epi32(msgtmp_1[(((NI)2))- 0], tmp_1);
			nimln_(188);			msgtmp_1[(((NI)2))- 0] = _mm_sha256msg2_epu32(msgtmp_1[(((NI)2))- 0], msgtmp_1[(((NI)1))- 0]);
			nimln_(189);			msg_1 = _mm_shuffle_epi32(msg_1, ((NU32)14));
			nimln_(190);			state0_1 = _mm_sha256rnds2_epu32(state0_1, state1_1, msg_1);
			nimln_(191);			msgtmp_1[(((NI)0))- 0] = _mm_sha256msg1_epu32(msgtmp_1[(((NI)0))- 0], msgtmp_1[(((NI)1))- 0]);
			nimln_(193);			T19_ = _mm_setr_epi32(((NU32)IL64(2730485921)), ((NU32)IL64(2820302411)), ((NU32)IL64(3259730800)), ((NU32)IL64(3345764771)));
			msg_1 = _mm_add_epi32(msgtmp_1[(((NI)2))- 0], T19_);
			nimln_(194);			state1_1 = _mm_sha256rnds2_epu32(state1_1, state0_1, msg_1);
			nimln_(195);			tmp_1 = _mm_alignr_epi8(msgtmp_1[(((NI)2))- 0], msgtmp_1[(((NI)1))- 0], ((NU32)4));
			nimln_(196);			msgtmp_1[(((NI)3))- 0] = _mm_add_epi32(msgtmp_1[(((NI)3))- 0], tmp_1);
			nimln_(197);			msgtmp_1[(((NI)3))- 0] = _mm_sha256msg2_epu32(msgtmp_1[(((NI)3))- 0], msgtmp_1[(((NI)2))- 0]);
			nimln_(198);			msg_1 = _mm_shuffle_epi32(msg_1, ((NU32)14));
			nimln_(199);			state0_1 = _mm_sha256rnds2_epu32(state0_1, state1_1, msg_1);
			nimln_(200);			msgtmp_1[(((NI)1))- 0] = _mm_sha256msg1_epu32(msgtmp_1[(((NI)1))- 0], msgtmp_1[(((NI)2))- 0]);
			nimln_(202);			T20_ = _mm_setr_epi32(((NU32)IL64(3516065817)), ((NU32)IL64(3600352804)), ((NU32)IL64(4094571909)), ((NU32)275423344));
			msg_1 = _mm_add_epi32(msgtmp_1[(((NI)3))- 0], T20_);
			nimln_(203);			state1_1 = _mm_sha256rnds2_epu32(state1_1, state0_1, msg_1);
			nimln_(204);			tmp_1 = _mm_alignr_epi8(msgtmp_1[(((NI)3))- 0], msgtmp_1[(((NI)2))- 0], ((NU32)4));
			nimln_(205);			msgtmp_1[(((NI)0))- 0] = _mm_add_epi32(msgtmp_1[(((NI)0))- 0], tmp_1);
			nimln_(206);			msgtmp_1[(((NI)0))- 0] = _mm_sha256msg2_epu32(msgtmp_1[(((NI)0))- 0], msgtmp_1[(((NI)3))- 0]);
			nimln_(207);			msg_1 = _mm_shuffle_epi32(msg_1, ((NU32)14));
			nimln_(208);			state0_1 = _mm_sha256rnds2_epu32(state0_1, state1_1, msg_1);
			nimln_(209);			msgtmp_1[(((NI)2))- 0] = _mm_sha256msg1_epu32(msgtmp_1[(((NI)2))- 0], msgtmp_1[(((NI)3))- 0]);
			nimln_(211);			T21_ = _mm_setr_epi32(((NU32)430227734), ((NU32)506948616), ((NU32)659060556), ((NU32)883997877));
			msg_1 = _mm_add_epi32(msgtmp_1[(((NI)0))- 0], T21_);
			nimln_(212);			state1_1 = _mm_sha256rnds2_epu32(state1_1, state0_1, msg_1);
			nimln_(213);			tmp_1 = _mm_alignr_epi8(msgtmp_1[(((NI)0))- 0], msgtmp_1[(((NI)3))- 0], ((NU32)4));
			nimln_(214);			msgtmp_1[(((NI)1))- 0] = _mm_add_epi32(msgtmp_1[(((NI)1))- 0], tmp_1);
			nimln_(215);			msgtmp_1[(((NI)1))- 0] = _mm_sha256msg2_epu32(msgtmp_1[(((NI)1))- 0], msgtmp_1[(((NI)0))- 0]);
			nimln_(216);			msg_1 = _mm_shuffle_epi32(msg_1, ((NU32)14));
			nimln_(217);			state0_1 = _mm_sha256rnds2_epu32(state0_1, state1_1, msg_1);
			nimln_(218);			msgtmp_1[(((NI)3))- 0] = _mm_sha256msg1_epu32(msgtmp_1[(((NI)3))- 0], msgtmp_1[(((NI)0))- 0]);
			nimln_(220);			T22_ = _mm_setr_epi32(((NU32)958139571), ((NU32)1322822218), ((NU32)1537002063), ((NU32)1747873779));
			msg_1 = _mm_add_epi32(msgtmp_1[(((NI)1))- 0], T22_);
			nimln_(221);			state1_1 = _mm_sha256rnds2_epu32(state1_1, state0_1, msg_1);
			nimln_(222);			tmp_1 = _mm_alignr_epi8(msgtmp_1[(((NI)1))- 0], msgtmp_1[(((NI)0))- 0], ((NU32)4));
			nimln_(223);			msgtmp_1[(((NI)2))- 0] = _mm_add_epi32(msgtmp_1[(((NI)2))- 0], tmp_1);
			nimln_(224);			msgtmp_1[(((NI)2))- 0] = _mm_sha256msg2_epu32(msgtmp_1[(((NI)2))- 0], msgtmp_1[(((NI)1))- 0]);
			nimln_(225);			msg_1 = _mm_shuffle_epi32(msg_1, ((NU32)14));
			nimln_(226);			state0_1 = _mm_sha256rnds2_epu32(state0_1, state1_1, msg_1);
			nimln_(227);			msgtmp_1[(((NI)0))- 0] = _mm_sha256msg1_epu32(msgtmp_1[(((NI)0))- 0], msgtmp_1[(((NI)1))- 0]);
			nimln_(229);			T23_ = _mm_setr_epi32(((NU32)1955562222), ((NU32)2024104815), ((NU32)IL64(2227730452)), ((NU32)IL64(2361852424)));
			msg_1 = _mm_add_epi32(msgtmp_1[(((NI)2))- 0], T23_);
			nimln_(230);			state1_1 = _mm_sha256rnds2_epu32(state1_1, state0_1, msg_1);
			nimln_(231);			tmp_1 = _mm_alignr_epi8(msgtmp_1[(((NI)2))- 0], msgtmp_1[(((NI)1))- 0], ((NU32)4));
			nimln_(232);			msgtmp_1[(((NI)3))- 0] = _mm_add_epi32(msgtmp_1[(((NI)3))- 0], tmp_1);
			nimln_(233);			msgtmp_1[(((NI)3))- 0] = _mm_sha256msg2_epu32(msgtmp_1[(((NI)3))- 0], msgtmp_1[(((NI)2))- 0]);
			nimln_(234);			msg_1 = _mm_shuffle_epi32(msg_1, ((NU32)14));
			nimln_(235);			state0_1 = _mm_sha256rnds2_epu32(state0_1, state1_1, msg_1);
			nimln_(236);			msgtmp_1[(((NI)1))- 0] = _mm_sha256msg1_epu32(msgtmp_1[(((NI)1))- 0], msgtmp_1[(((NI)2))- 0]);
			nimln_(238);			T24_ = _mm_setr_epi32(((NU32)IL64(2428436474)), ((NU32)IL64(2756734187)), ((NU32)IL64(3204031479)), ((NU32)IL64(3329325298)));
			msg_1 = _mm_add_epi32(msgtmp_1[(((NI)3))- 0], T24_);
			nimln_(239);			state1_1 = _mm_sha256rnds2_epu32(state1_1, state0_1, msg_1);
			nimln_(240);			msg_1 = _mm_shuffle_epi32(msg_1, ((NU32)14));
			nimln_(241);			state0_1 = _mm_sha256rnds2_epu32(state0_1, state1_1, msg_1);
			nimln_(243);			state0_1 = _mm_add_epi32(state0_1, state0_save_1);
			nimln_(244);			state1_1 = _mm_add_epi32(state1_1, state1_save_1);
			nimln_(246);			if (nimAddInt(offset_1, ((NI)64), &TM__QMTBJ3B2LA4Z4wAiKYiWww_5)) { raiseOverflow(); goto BeforeRet_;
			};
			offset_1 = (NI)(TM__QMTBJ3B2LA4Z4wAiKYiWww_5);
			nimln_(247);			if (nimSubInt(blocksCount_1, ((NI)1), &TM__QMTBJ3B2LA4Z4wAiKYiWww_6)) { raiseOverflow(); goto BeforeRet_;
			};
			blocksCount_1 = (NI)(TM__QMTBJ3B2LA4Z4wAiKYiWww_6);
		} LA4: ;
	}
	nimln_(249);	tmp_1 = _mm_shuffle_epi32(state0_1, ((NU32)27));
	nimln_(250);	state1_1 = _mm_shuffle_epi32(state1_1, ((NU32)177));
	nimln_(251);	state0_1 = _mm_blend_epi16(tmp_1, state1_1, ((NU32)240));
	nimln_(252);	state1_1 = _mm_alignr_epi8(state1_1, tmp_1, ((NU32)8));
	nimln_(254);	_mm_store_si128(((__m128i*) ((&state_p0[(((NI)0))- 0]))), state0_1);
	nimln_(255);	_mm_store_si128(((__m128i*) ((&state_p0[(((NI)4))- 0]))), state1_1);
	}BeforeRet_: ;
	popFrame();
}
