/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -fno-strict-aliasing -pthread -I/home/icarogdo/.nimble/pkgs2/bearssl-0.2.10-e53ab85b8c4c1ce3aa1f4eb251c0ab29e08d4972/bearssl/abi -I/home/icarogdo/.nimble/pkgs2/bearssl-0.2.10-e53ab85b8c4c1ce3aa1f4eb251c0ab29e08d4972/bearssl/abi/../csources/src/ -I/home/icarogdo/.nimble/pkgs2/bearssl-0.2.10-e53ab85b8c4c1ce3aa1f4eb251c0ab29e08d4972/bearssl/abi/../csources/inc/ -I/home/icarogdo/.nimble/pkgs2/bearssl-0.2.10-e53ab85b8c4c1ce3aa1f4eb251c0ab29e08d4972/bearssl/abi/../csources/tools/ -DBR_USE_UNIX_TIME=1 -DBR_USE_URANDOM=1 -DBR_LE_UNALIGNED=1 -DBR_64=1  -DBR_amd64=1 -DBR_INT128=1 -Wno-incompatible-pointer-types -I/usr/include/webkitgtk-4.1 -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/cloudproviders -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/glycin-2 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/atk-1.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/fribidi -I/usr/include/pixman-1 -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gio-unix-2.0 -I/usr/include/libsoup-3.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-6 -pthread   -I/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib -I/home/icarogdo/dev/macroobras-jazzy/app/macroobras/src -o /home/icarogdo/dev/macroobras-jazzy/app/macroobras/.nimcache/@pheapqueue.nim.c.o /home/icarogdo/dev/macroobras-jazzy/app/macroobras/.nimcache/@pheapqueue.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tyObject_HeapQueue__aCSIiXNDYmvClNY9a9coAR9bw tyObject_HeapQueue__aCSIiXNDYmvClNY9a9coAR9bw;
typedef struct tyObject_NodecolonObjectType___9c8lg9bJC5hGtVW69cGAJ8H0w tyObject_NodecolonObjectType___9c8lg9bJC5hGtVW69cGAJ8H0w;
typedef struct tySequence__k9cWM9cIZUGnLEakQzRrrH1A tySequence__k9cWM9cIZUGnLEakQzRrrH1A;
typedef struct tySequence__k9cWM9cIZUGnLEakQzRrrH1A_Content tySequence__k9cWM9cIZUGnLEakQzRrrH1A_Content;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tyObject_RefHeader__sqhyc4FSbGmPtkvXRNl9acg tyObject_RefHeader__sqhyc4FSbGmPtkvXRNl9acg;
typedef struct tySequence__7kmTXLGpeKFI9af9bxASU4iA tySequence__7kmTXLGpeKFI9af9bxASU4iA;
typedef struct tySequence__7kmTXLGpeKFI9af9bxASU4iA_Content tySequence__7kmTXLGpeKFI9af9bxASU4iA_Content;
typedef struct tyTuple__Yk9co6DjRTcTlU6U0WDauNQ tyTuple__Yk9co6DjRTcTlU6U0WDauNQ;
typedef struct tyObject_MonoTime__q7ChpWAXgp7ebEHTX9afOZg tyObject_MonoTime__q7ChpWAXgp7ebEHTX9afOZg;
typedef struct tyObject_FuturecolonObjectType___7M77QG5xE71ZeiEPHTHzlw tyObject_FuturecolonObjectType___7M77QG5xE71ZeiEPHTHzlw;
typedef struct tyObject_GcEnv__85WwC9a1qDcL9aPJ9b1qr0g2Q tyObject_GcEnv__85WwC9a1qDcL9aPJ9b1qr0g2Q;
typedef struct tyObject_CellSeq__tmpRNCI2baMQRvZpqUI72g tyObject_CellSeq__tmpRNCI2baMQRvZpqUI72g;
typedef struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q tyTuple__N4J9cV4JZGem3ljqqj5rT0Q;
typedef struct tyObject_CellSeq__bUU9cGCnoYZUQbR5GgWvc0g tyObject_CellSeq__bUU9cGCnoYZUQbR5GgWvc0g;
typedef struct tyTuple__WEETd9ajw9a010wvV0CoGNuw tyTuple__WEETd9ajw9a010wvV0CoGNuw;
typedef struct tyObject_HeapQueue__bwC4EuJ0YPM6kGXJDg8U5Q tyObject_HeapQueue__bwC4EuJ0YPM6kGXJDg8U5Q;
struct tySequence__k9cWM9cIZUGnLEakQzRrrH1A {
  NI len; tySequence__k9cWM9cIZUGnLEakQzRrrH1A_Content* p;
};
struct tyObject_HeapQueue__aCSIiXNDYmvClNY9a9coAR9bw {
	tySequence__k9cWM9cIZUGnLEakQzRrrH1A data;
};
struct tyObject_NodecolonObjectType___9c8lg9bJC5hGtVW69cGAJ8H0w {
	NI symbol;
	NI freq;
	tyObject_NodecolonObjectType___9c8lg9bJC5hGtVW69cGAJ8H0w* left;
	tyObject_NodecolonObjectType___9c8lg9bJC5hGtVW69cGAJ8H0w* right;
};
struct tyObject_RefHeader__sqhyc4FSbGmPtkvXRNl9acg {
	NI rc;
	NI rootIdx;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct tySequence__7kmTXLGpeKFI9af9bxASU4iA {
  NI len; tySequence__7kmTXLGpeKFI9af9bxASU4iA_Content* p;
};
struct tyObject_MonoTime__q7ChpWAXgp7ebEHTX9afOZg {
	NI64 ticks;
};
struct tyTuple__Yk9co6DjRTcTlU6U0WDauNQ {
	tyObject_MonoTime__q7ChpWAXgp7ebEHTX9afOZg Field0;
	tyObject_FuturecolonObjectType___7M77QG5xE71ZeiEPHTHzlw* Field1;
};
struct tyObject_CellSeq__tmpRNCI2baMQRvZpqUI72g {
	NI len;
	NI cap;
	tyTuple__N4J9cV4JZGem3ljqqj5rT0Q* d;
};
struct tyObject_CellSeq__bUU9cGCnoYZUQbR5GgWvc0g {
	NI len;
	NI cap;
	tyTuple__WEETd9ajw9a010wvV0CoGNuw* d;
};
struct tyObject_GcEnv__85WwC9a1qDcL9aPJ9b1qr0g2Q {
	tyObject_CellSeq__tmpRNCI2baMQRvZpqUI72g traceStack;
	tyObject_CellSeq__bUU9cGCnoYZUQbR5GgWvc0g toFree;
	NI freed;
	NI touched;
	NI edges;
	NI rcSum;
	NIM_BOOL keepThreshold;
};
struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q {
	void** Field0;
	TNimTypeV2* Field1;
};
struct tyObject_HeapQueue__bwC4EuJ0YPM6kGXJDg8U5Q {
	tySequence__7kmTXLGpeKFI9af9bxASU4iA data;
};
struct tySequence__k9cWM9cIZUGnLEakQzRrrH1A_Content { NI cap; tyObject_NodecolonObjectType___9c8lg9bJC5hGtVW69cGAJ8H0w* data[SEQ_DECL_SIZE]; };
struct tySequence__7kmTXLGpeKFI9af9bxASU4iA_Content { NI cap; tyTuple__Yk9co6DjRTcTlU6U0WDauNQ data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(void, add__pkgZzippyZdeflate_u149)(tySequence__k9cWM9cIZUGnLEakQzRrrH1A* x_p0, tyObject_NodecolonObjectType___9c8lg9bJC5hGtVW69cGAJ8H0w* y_p1);
static N_INLINE(void, nimMarkCyclic)(void* p_p0);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4511)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, siftup__pkgZzippyZdeflate_u224)(tyObject_HeapQueue__aCSIiXNDYmvClNY9a9coAR9bw* heap_p0, NI startpos_p1, NI p_p2);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pkgZzippyZdeflate_u278)(tyObject_NodecolonObjectType___9c8lg9bJC5hGtVW69cGAJ8H0w** dest_p0, tyObject_NodecolonObjectType___9c8lg9bJC5hGtVW69cGAJ8H0w* src_p1, NIM_BOOL cyclic_p2);
static N_INLINE(tyObject_NodecolonObjectType___9c8lg9bJC5hGtVW69cGAJ8H0w**, X5BX5D___pkgZzippyZdeflate_u231)(tyObject_HeapQueue__aCSIiXNDYmvClNY9a9coAR9bw* heap_p0, NI i_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NIM_BOOL, heapCmp__pkgZzippyZdeflate_u267)(tyObject_NodecolonObjectType___9c8lg9bJC5hGtVW69cGAJ8H0w* x_p0, tyObject_NodecolonObjectType___9c8lg9bJC5hGtVW69cGAJ8H0w* y_p1);
static N_INLINE(NIM_BOOL, lt___pkgZzippyZdeflate_u14)(tyObject_NodecolonObjectType___9c8lg9bJC5hGtVW69cGAJ8H0w* a_p0, tyObject_NodecolonObjectType___9c8lg9bJC5hGtVW69cGAJ8H0w* b_p1);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___pkgZzippyZdeflate_u286)(tyObject_NodecolonObjectType___9c8lg9bJC5hGtVW69cGAJ8H0w** dest_p0, tyObject_NodecolonObjectType___9c8lg9bJC5hGtVW69cGAJ8H0w* src_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___pkgZzippyZdeflate_u272)(tyObject_NodecolonObjectType___9c8lg9bJC5hGtVW69cGAJ8H0w** dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZzippyZdeflate_u275)(tyObject_NodecolonObjectType___9c8lg9bJC5hGtVW69cGAJ8H0w* dest_p0);
static N_INLINE(NI, len__pkgZzippyZdeflate_u217)(tyObject_HeapQueue__aCSIiXNDYmvClNY9a9coAR9bw heap_p0);
static N_INLINE(tyObject_NodecolonObjectType___9c8lg9bJC5hGtVW69cGAJ8H0w*, pop__pkgZzippyZdeflate_u376)(tySequence__k9cWM9cIZUGnLEakQzRrrH1A* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, shrink__pkgZzippyZdeflate_u391)(tySequence__k9cWM9cIZUGnLEakQzRrrH1A* x_p0, NI newLen_p1);
N_LIB_PRIVATE N_NIMCALL(void, siftdownToBottom__pkgZzippyZdeflate_u492)(tyObject_HeapQueue__aCSIiXNDYmvClNY9a9coAR9bw* heap_p0, NI p_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZzippyZdeflate_u580)(tySequence__k9cWM9cIZUGnLEakQzRrrH1A dest_p0);
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicStatic)(void* p_p0, TNimTypeV2* desc_p1);
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1);
N_LIB_PRIVATE N_NOINLINE(void, rememberCycle__system_u3573)(NIM_BOOL isDestroyAction_p0, tyObject_RefHeader__sqhyc4FSbGmPtkvXRNl9acg* s_p1, TNimTypeV2* desc_p2);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZzippyZdeflate_u295)(tyObject_NodecolonObjectType___9c8lg9bJC5hGtVW69cGAJ8H0w* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimRawDispose)(void* p_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(void, alignedDealloc)(void* p_p0, NI align_p1);
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p_p0);
static N_INLINE(void, nimTraceRefDyn)(void* q_p0, void* env_p1);
static N_INLINE(void, add__system_u3094)(tyObject_CellSeq__tmpRNCI2baMQRvZpqUI72g* s_p0, void** c_p1, TNimTypeV2* t_p2);
N_LIB_PRIVATE N_NIMCALL(void, resize__system_u3102)(tyObject_CellSeq__tmpRNCI2baMQRvZpqUI72g* s_p0);
static N_INLINE(NI, pluspercent___system_u793)(NI x_p0, NI y_p1);
N_LIB_PRIVATE N_NIMCALL(void, setLen__pureZasyncdispatch_u263)(tySequence__7kmTXLGpeKFI9af9bxASU4iA* s_p0, NI newlen_p1);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(void, pop__pureZasyncdispatch_u221)(tySequence__7kmTXLGpeKFI9af9bxASU4iA* s_p0, tyTuple__Yk9co6DjRTcTlU6U0WDauNQ* Result);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___pureZasyncdispatch_u236)(tyTuple__Yk9co6DjRTcTlU6U0WDauNQ* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, shrink__pureZasyncdispatch_u259)(tySequence__7kmTXLGpeKFI9af9bxASU4iA* x_p0, NI newLen_p1);
static N_INLINE(NI, len__pureZasyncdispatch_u84)(tyObject_HeapQueue__bwC4EuJ0YPM6kGXJDg8U5Q heap_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pureZasyncdispatch_u242)(tyTuple__Yk9co6DjRTcTlU6U0WDauNQ* dest_p0, tyTuple__Yk9co6DjRTcTlU6U0WDauNQ src_p1);
static N_INLINE(tyTuple__Yk9co6DjRTcTlU6U0WDauNQ*, X5BX5D___pureZasyncdispatch_u156)(tyObject_HeapQueue__bwC4EuJ0YPM6kGXJDg8U5Q* heap_p0, NI i_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___pureZasyncdispatch_u248)(tyTuple__Yk9co6DjRTcTlU6U0WDauNQ* dest_p0, tyTuple__Yk9co6DjRTcTlU6U0WDauNQ src_p1);
N_LIB_PRIVATE N_NIMCALL(void, siftdownToBottom__pureZasyncdispatch_u471)(tyObject_HeapQueue__bwC4EuJ0YPM6kGXJDg8U5Q* heap_p0, NI p_p1);
static N_INLINE(NIM_BOOL, heapCmp__pureZasyncdispatch_u733)(tyTuple__Yk9co6DjRTcTlU6U0WDauNQ x_p0, tyTuple__Yk9co6DjRTcTlU6U0WDauNQ y_p1);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, lt___pureZasyncdispatch_u738)(tyTuple__Yk9co6DjRTcTlU6U0WDauNQ x_p0, tyTuple__Yk9co6DjRTcTlU6U0WDauNQ y_p1);
N_LIB_PRIVATE N_NIMCALL(void, siftup__pureZasyncdispatch_u877)(tyObject_HeapQueue__bwC4EuJ0YPM6kGXJDg8U5Q* heap_p0, NI startpos_p1, NI p_p2);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZasyncdispatch_u239)(tyTuple__Yk9co6DjRTcTlU6U0WDauNQ* dest_p0);
extern TNimTypeV2 NTIv2__9c8lg9bJC5hGtVW69cGAJ8H0w_;
extern NIM_THREADVAR TFrame* framePtr__system_u2809;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4293;
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2809 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2809).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2809;
	framePtr__system_u2809 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4511();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2809 = (*framePtr__system_u2809).prev;
}
static N_INLINE(void, nimMarkCyclic)(void* p_p0) {
	nimfr_("nimMarkCyclic", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/orc.nim");
	popFrame();
}
static N_INLINE(tyObject_NodecolonObjectType___9c8lg9bJC5hGtVW69cGAJ8H0w**, X5BX5D___pkgZzippyZdeflate_u231)(tyObject_HeapQueue__aCSIiXNDYmvClNY9a9coAR9bw* heap_p0, NI i_p1) {
	tyObject_NodecolonObjectType___9c8lg9bJC5hGtVW69cGAJ8H0w** result;
	nimfr_("[]", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/pure/collections/heapqueue.nim");
{	nimlf_(76, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/pure/collections/heapqueue.nim");	if (i_p1 < 0 || i_p1 >= (*heap_p0).data.len){ raiseIndexError2(i_p1,(*heap_p0).data.len-1); goto BeforeRet_;
	}
	result = &(*heap_p0).data.p->data[i_p1];
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, lt___pkgZzippyZdeflate_u14)(tyObject_NodecolonObjectType___9c8lg9bJC5hGtVW69cGAJ8H0w* a_p0, tyObject_NodecolonObjectType___9c8lg9bJC5hGtVW69cGAJ8H0w* b_p1) {
	NIM_BOOL result;
	nimfr_("<", "/home/icarogdo/.nimble/pkgs2/zippy-0.10.19-706d8c10778f32d28b060dbcc84143ca4bfb9bcd/zippy/deflate.nim");
	nimlf_(11, "/home/icarogdo/.nimble/pkgs2/zippy-0.10.19-706d8c10778f32d28b060dbcc84143ca4bfb9bcd/zippy/deflate.nim");	result = ((*a_p0).freq < (*b_p1).freq);
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4293);
	return result;
}
static N_INLINE(NIM_BOOL, heapCmp__pkgZzippyZdeflate_u267)(tyObject_NodecolonObjectType___9c8lg9bJC5hGtVW69cGAJ8H0w* x_p0, tyObject_NodecolonObjectType___9c8lg9bJC5hGtVW69cGAJ8H0w* y_p1) {
	NIM_BOOL result;
NIM_BOOL* nimErr_;
	nimfr_("heapCmp", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/pure/collections/heapqueue.nim");
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	result = lt___pkgZzippyZdeflate_u14(x_p0, y_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, siftup__pkgZzippyZdeflate_u224)(tyObject_HeapQueue__aCSIiXNDYmvClNY9a9coAR9bw* heap_p0, NI startpos_p1, NI p_p2) {
	tyObject_NodecolonObjectType___9c8lg9bJC5hGtVW69cGAJ8H0w* newitem_1;
	NI pos_1;
	tyObject_NodecolonObjectType___9c8lg9bJC5hGtVW69cGAJ8H0w** T2_;
NIM_BOOL oldNimErrFin5_;
NIM_BOOL* nimErr_;
	nimfr_("siftup", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/pure/collections/heapqueue.nim");
{nimErr_ = nimErrorFlag();
	newitem_1 = NIM_NIL;
	nimlf_(92, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/pure/collections/heapqueue.nim");	pos_1 = p_p2;
	nimln_(93);	if ((pos_1) < ((NI)0) || (pos_1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(pos_1, ((NI)0), ((NI)IL64(9223372036854775807))); goto LA1_;
	}
	T2_ = (tyObject_NodecolonObjectType___9c8lg9bJC5hGtVW69cGAJ8H0w**)0;
	T2_ = X5BX5D___pkgZzippyZdeflate_u231((&(*heap_p0)), (pos_1));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	eqcopy___pkgZzippyZdeflate_u278(&newitem_1, (*T2_), NIM_FALSE);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		nimln_(96);		while (1) {
			tyObject_NodecolonObjectType___9c8lg9bJC5hGtVW69cGAJ8H0w* parent_1;
			NI parentpos_1;
			NI TM__f2bNHCHm2LvO7iSrwQtdiQ_2;
			tyObject_NodecolonObjectType___9c8lg9bJC5hGtVW69cGAJ8H0w** T6_;
			if (!(startpos_p1 < pos_1)) goto LA4;
			parent_1 = NIM_NIL;
			nimln_(97);			if (nimSubInt(pos_1, ((NI)1), &TM__f2bNHCHm2LvO7iSrwQtdiQ_2)) { raiseOverflow(); goto LA5_;
			};
			parentpos_1 = (NI)((NI64)((NI)(TM__f2bNHCHm2LvO7iSrwQtdiQ_2)) >> (NU64)(((NI)1) & (64 - 1)));
			nimln_(93);			nimln_(98);			if ((parentpos_1) < ((NI)0) || (parentpos_1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(parentpos_1, ((NI)0), ((NI)IL64(9223372036854775807))); goto LA5_;
			}
			T6_ = (tyObject_NodecolonObjectType___9c8lg9bJC5hGtVW69cGAJ8H0w**)0;
			T6_ = X5BX5D___pkgZzippyZdeflate_u231((&(*heap_p0)), (parentpos_1));
			if (NIM_UNLIKELY(*nimErr_)) goto LA5_;
			nimln_(93);			eqcopy___pkgZzippyZdeflate_u278(&parent_1, (*T6_), NIM_FALSE);
			if (NIM_UNLIKELY(*nimErr_)) goto LA5_;
			nimln_(99);			{
				NIM_BOOL T9_;
				T9_ = (NIM_BOOL)0;
				T9_ = heapCmp__pkgZzippyZdeflate_u267(newitem_1, parent_1);
				if (NIM_UNLIKELY(*nimErr_)) goto LA5_;
				if (!T9_) goto LA10_;
				nimln_(93);				if (pos_1 < 0 || pos_1 >= (*heap_p0).data.len){ raiseIndexError2(pos_1,(*heap_p0).data.len-1); goto LA5_;
				}
				eqsink___pkgZzippyZdeflate_u286(&(*heap_p0).data.p->data[pos_1], parent_1);
				if (NIM_UNLIKELY(*nimErr_)) goto LA5_;
				eqwasMoved___pkgZzippyZdeflate_u272(&parent_1);
				if (NIM_UNLIKELY(*nimErr_)) goto LA5_;
				nimln_(101);				pos_1 = parentpos_1;
			}
			goto LA7_;
LA10_: ;
			{
				nimln_(93);				eqdestroy___pkgZzippyZdeflate_u275(parent_1);
				if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
				nimln_(103);				goto LA3;
			}
LA7_: ;
			{
				LA5_:;
			}
			{
				oldNimErrFin5_ = *nimErr_; *nimErr_ = NIM_FALSE;
				nimln_(93);				eqdestroy___pkgZzippyZdeflate_u275(parent_1);
				if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
				*nimErr_ = oldNimErrFin5_;
			}
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		} LA4: ;
	} LA3: ;
	if (pos_1 < 0 || pos_1 >= (*heap_p0).data.len){ raiseIndexError2(pos_1,(*heap_p0).data.len-1); goto LA1_;
	}
	eqsink___pkgZzippyZdeflate_u286(&(*heap_p0).data.p->data[pos_1], newitem_1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		LA1_:;
	}
	{
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(NI, len__pkgZzippyZdeflate_u217)(tyObject_HeapQueue__aCSIiXNDYmvClNY9a9coAR9bw heap_p0) {
	NI result;
	NI T1_;
	nimfr_("len", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/pure/collections/heapqueue.nim");
	nimln_(73);	T1_ = heap_p0.data.len;
	result = T1_;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, push__pkgZzippyZdeflate_u203)(tyObject_HeapQueue__aCSIiXNDYmvClNY9a9coAR9bw* heap_p0, tyObject_NodecolonObjectType___9c8lg9bJC5hGtVW69cGAJ8H0w* item_p1) {
	tyObject_NodecolonObjectType___9c8lg9bJC5hGtVW69cGAJ8H0w* blitTmp_1;
	NI T1_;
	NI TM__f2bNHCHm2LvO7iSrwQtdiQ_3;
NIM_BOOL* nimErr_;
	nimfr_("push", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/pure/collections/heapqueue.nim");
{nimErr_ = nimErrorFlag();
	nimln_(146);	blitTmp_1 = item_p1;
	nimMarkCyclic(item_p1);
	add__pkgZzippyZdeflate_u149((&(*heap_p0).data), blitTmp_1);
	nimln_(147);	T1_ = (NI)0;
	T1_ = len__pkgZzippyZdeflate_u217((*heap_p0));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	if (nimSubInt(T1_, ((NI)1), &TM__f2bNHCHm2LvO7iSrwQtdiQ_3)) { raiseOverflow(); goto BeforeRet_;
	};
	siftup__pkgZzippyZdeflate_u224(heap_p0, ((NI)0), (NI)(TM__f2bNHCHm2LvO7iSrwQtdiQ_3));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(tyObject_NodecolonObjectType___9c8lg9bJC5hGtVW69cGAJ8H0w*, pop__pkgZzippyZdeflate_u376)(tySequence__k9cWM9cIZUGnLEakQzRrrH1A* s_p0) {
	tyObject_NodecolonObjectType___9c8lg9bJC5hGtVW69cGAJ8H0w* result;
	NI L_1;
	NI T1_;
	NI TM__f2bNHCHm2LvO7iSrwQtdiQ_4;
	nimfr_("pop", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system.nim");
{	result = NIM_NIL;
	nimlf_(1949, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system.nim");	T1_ = (*s_p0).len;
	if (nimSubInt(T1_, ((NI)1), &TM__f2bNHCHm2LvO7iSrwQtdiQ_4)) { raiseOverflow(); goto BeforeRet_;
	};
	L_1 = (NI)(TM__f2bNHCHm2LvO7iSrwQtdiQ_4);
	nimln_(1951);	if (L_1 < 0 || L_1 >= (*s_p0).len){ raiseIndexError2(L_1,(*s_p0).len-1); goto BeforeRet_;
	}
	result = (*s_p0).p->data[L_1];
	eqwasMoved___pkgZzippyZdeflate_u272((&(*s_p0).p->data[L_1]));
	nimln_(1952);	if ((L_1) < ((NI)0) || (L_1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(L_1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	shrink__pkgZzippyZdeflate_u391(s_p0, (L_1));
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, siftdownToBottom__pkgZzippyZdeflate_u492)(tyObject_HeapQueue__aCSIiXNDYmvClNY9a9coAR9bw* heap_p0, NI p_p1) {
	tyObject_NodecolonObjectType___9c8lg9bJC5hGtVW69cGAJ8H0w* newitem_1;
	NI endpos_1;
	NI pos_1;
	NI startpos_1;
	tyObject_NodecolonObjectType___9c8lg9bJC5hGtVW69cGAJ8H0w** T1_;
	NI childpos_1;
	NI TM__f2bNHCHm2LvO7iSrwQtdiQ_5;
	NI TM__f2bNHCHm2LvO7iSrwQtdiQ_6;
NIM_BOOL* nimErr_;
	nimfr_("siftdownToBottom", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/pure/collections/heapqueue.nim");
{nimErr_ = nimErrorFlag();
	newitem_1 = NIM_NIL;
	nimlf_(108, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/pure/collections/heapqueue.nim");	endpos_1 = len__pkgZzippyZdeflate_u217((*heap_p0));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(109);	pos_1 = p_p1;
	nimln_(110);	startpos_1 = pos_1;
	nimln_(93);	nimln_(111);	if ((pos_1) < ((NI)0) || (pos_1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(pos_1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	T1_ = (tyObject_NodecolonObjectType___9c8lg9bJC5hGtVW69cGAJ8H0w**)0;
	T1_ = X5BX5D___pkgZzippyZdeflate_u231((&(*heap_p0)), (pos_1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(93);	eqcopy___pkgZzippyZdeflate_u278(&newitem_1, (*T1_), NIM_FALSE);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(113);	if (nimMulInt(((NI)2), pos_1, &TM__f2bNHCHm2LvO7iSrwQtdiQ_5)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimAddInt((NI)(TM__f2bNHCHm2LvO7iSrwQtdiQ_5), ((NI)1), &TM__f2bNHCHm2LvO7iSrwQtdiQ_6)) { raiseOverflow(); goto BeforeRet_;
	};
	childpos_1 = (NI)(TM__f2bNHCHm2LvO7iSrwQtdiQ_6);
	{
		nimln_(114);		while (1) {
			NI rightpos_1;
			NI TM__f2bNHCHm2LvO7iSrwQtdiQ_7;
			tyObject_NodecolonObjectType___9c8lg9bJC5hGtVW69cGAJ8H0w** T13_;
			NI TM__f2bNHCHm2LvO7iSrwQtdiQ_8;
			NI TM__f2bNHCHm2LvO7iSrwQtdiQ_9;
			if (!(childpos_1 < endpos_1)) goto LA3;
			nimln_(116);			if (nimAddInt(childpos_1, ((NI)1), &TM__f2bNHCHm2LvO7iSrwQtdiQ_7)) { raiseOverflow(); goto BeforeRet_;
			};
			rightpos_1 = (NI)(TM__f2bNHCHm2LvO7iSrwQtdiQ_7);
			nimln_(117);			{
				NIM_BOOL T6_;
				tyObject_NodecolonObjectType___9c8lg9bJC5hGtVW69cGAJ8H0w** T8_;
				tyObject_NodecolonObjectType___9c8lg9bJC5hGtVW69cGAJ8H0w** T9_;
				NIM_BOOL T10_;
				T6_ = (NIM_BOOL)0;
				T6_ = (rightpos_1 < endpos_1);
				if (!(T6_)) goto LA7_;
				if ((childpos_1) < ((NI)0) || (childpos_1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(childpos_1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
				}
				T8_ = (tyObject_NodecolonObjectType___9c8lg9bJC5hGtVW69cGAJ8H0w**)0;
				T8_ = X5BX5D___pkgZzippyZdeflate_u231((&(*heap_p0)), (childpos_1));
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				if ((rightpos_1) < ((NI)0) || (rightpos_1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(rightpos_1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
				}
				T9_ = (tyObject_NodecolonObjectType___9c8lg9bJC5hGtVW69cGAJ8H0w**)0;
				T9_ = X5BX5D___pkgZzippyZdeflate_u231((&(*heap_p0)), (rightpos_1));
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				T10_ = (NIM_BOOL)0;
				T10_ = heapCmp__pkgZzippyZdeflate_u267((*T8_), (*T9_));
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				T6_ = !(T10_);
LA7_: ;
				if (!T6_) goto LA11_;
				nimln_(118);				childpos_1 = rightpos_1;
			}
LA11_: ;
			nimln_(93);			if (pos_1 < 0 || pos_1 >= (*heap_p0).data.len){ raiseIndexError2(pos_1,(*heap_p0).data.len-1); goto BeforeRet_;
			}
			nimln_(120);			if ((childpos_1) < ((NI)0) || (childpos_1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(childpos_1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
			}
			T13_ = (tyObject_NodecolonObjectType___9c8lg9bJC5hGtVW69cGAJ8H0w**)0;
			T13_ = X5BX5D___pkgZzippyZdeflate_u231((&(*heap_p0)), (childpos_1));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(93);			eqcopy___pkgZzippyZdeflate_u278(&(*heap_p0).data.p->data[pos_1], (*T13_), NIM_TRUE);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(121);			pos_1 = childpos_1;
			nimln_(122);			if (nimMulInt(((NI)2), pos_1, &TM__f2bNHCHm2LvO7iSrwQtdiQ_8)) { raiseOverflow(); goto BeforeRet_;
			};
			if (nimAddInt((NI)(TM__f2bNHCHm2LvO7iSrwQtdiQ_8), ((NI)1), &TM__f2bNHCHm2LvO7iSrwQtdiQ_9)) { raiseOverflow(); goto BeforeRet_;
			};
			childpos_1 = (NI)(TM__f2bNHCHm2LvO7iSrwQtdiQ_9);
		} LA3: ;
	}
	nimln_(93);	if (pos_1 < 0 || pos_1 >= (*heap_p0).data.len){ raiseIndexError2(pos_1,(*heap_p0).data.len-1); goto BeforeRet_;
	}
	eqsink___pkgZzippyZdeflate_u286(&(*heap_p0).data.p->data[pos_1], newitem_1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(126);	siftup__pkgZzippyZdeflate_u224(heap_p0, startpos_1, pos_1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(tyObject_NodecolonObjectType___9c8lg9bJC5hGtVW69cGAJ8H0w*, pop__pkgZzippyZdeflate_u372)(tyObject_HeapQueue__aCSIiXNDYmvClNY9a9coAR9bw* heap_p0) {
	tyObject_NodecolonObjectType___9c8lg9bJC5hGtVW69cGAJ8H0w* result;
	tyObject_NodecolonObjectType___9c8lg9bJC5hGtVW69cGAJ8H0w* lastelt_1;
NIM_BOOL* nimErr_;
	nimfr_("pop", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/pure/collections/heapqueue.nim");
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	lastelt_1 = NIM_NIL;
	nimln_(171);	lastelt_1 = pop__pkgZzippyZdeflate_u376((&(*heap_p0).data));
	nimln_(172);	{
		NI T3_;
		tyObject_NodecolonObjectType___9c8lg9bJC5hGtVW69cGAJ8H0w** T6_;
		T3_ = (NI)0;
		T3_ = len__pkgZzippyZdeflate_u217((*heap_p0));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!(((NI)0) < T3_)) goto LA4_;
		nimln_(93);		nimln_(173);		T6_ = (tyObject_NodecolonObjectType___9c8lg9bJC5hGtVW69cGAJ8H0w**)0;
		T6_ = X5BX5D___pkgZzippyZdeflate_u231((&(*heap_p0)), ((NI)0));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(93);		eqcopy___pkgZzippyZdeflate_u278(&result, (*T6_), NIM_FALSE);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (((NI)0) < 0 || ((NI)0) >= (*heap_p0).data.len){ raiseIndexError2(((NI)0),(*heap_p0).data.len-1); goto BeforeRet_;
		}
		eqsink___pkgZzippyZdeflate_u286(&(*heap_p0).data.p->data[((NI)0)], lastelt_1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(175);		siftdownToBottom__pkgZzippyZdeflate_u492(heap_p0, ((NI)0));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA1_;
LA4_: ;
	{
		nimln_(177);		result = lastelt_1;
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1) {
	NI result;
	nimfr_("-%", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/arithmetics.nim");
	nimlf_(377, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/arithmetics.nim");	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) - (NU64)(((NU) (y_p1))))));
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicStatic)(void* p_p0, TNimTypeV2* desc_p1) {
	NIM_BOOL result;
	nimfr_("nimDecRefIsLastCyclicStatic", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/orc.nim");
	nimlf_(544, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/orc.nim");	result = NIM_FALSE;
	nimln_(545);	{
		tyObject_RefHeader__sqhyc4FSbGmPtkvXRNl9acg* cell_1;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		nimln_(546);		nimlf_(60, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/arc.nim");		T5_ = (NI)0;
		T5_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)16));
		cell_1 = ((tyObject_RefHeader__sqhyc4FSbGmPtkvXRNl9acg*) (T5_));
		nimlf_(547, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/orc.nim");		{
			if (!((NI)((*cell_1).rc & ((NI)-16)) == ((NI)0))) goto LA8_;
			nimln_(548);			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			nimln_(551);			(*cell_1).rc = minuspercent___system_u813((*cell_1).rc, ((NI)16));
		}
LA6_: ;
		nimln_(553);		rememberCycle__system_u3573(result, cell_1, desc_p1);
	}
LA3_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZzippyZdeflate_u580)(tySequence__k9cWM9cIZUGnLEakQzRrrH1A dest_p0) {
	NI colontmp_;
	colontmp_ = ((NI)0);
	{
		while (1) {
			NI T3_;
			T3_ = dest_p0.len;
			if (!(colontmp_ < T3_)) goto LA2;
			{
				NIM_BOOL T6_;
				T6_ = (NIM_BOOL)0;
				T6_ = nimDecRefIsLastCyclicStatic(dest_p0.p->data[colontmp_], ((TNimTypeV2*) ((&NTIv2__9c8lg9bJC5hGtVW69cGAJ8H0w_))));
				if (!T6_) goto LA7_;
				eqdestroy___pkgZzippyZdeflate_u295((&(*dest_p0.p->data[colontmp_])));
				nimRawDispose(dest_p0.p->data[colontmp_], ((NI)8));
			}
LA7_: ;
			colontmp_ += ((NI)1);
		} LA2: ;
	}
	if (dest_p0.p && !(dest_p0.p->cap & NIM_STRLIT_FLAG)) {
 alignedDealloc(dest_p0.p, NIM_ALIGNOF(tyObject_NodecolonObjectType___9c8lg9bJC5hGtVW69cGAJ8H0w*));
}
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZzippyZdeflate_u562)(tyObject_HeapQueue__aCSIiXNDYmvClNY9a9coAR9bw* dest_p0) {
	eqdestroy___pkgZzippyZdeflate_u580((*dest_p0).data);
}
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0) {
	NIM_BOOL result;
	nimfr_("nimDecRefIsLastCyclicDyn", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/orc.nim");
	nimln_(518);	result = NIM_FALSE;
	nimln_(519);	{
		tyObject_RefHeader__sqhyc4FSbGmPtkvXRNl9acg* cell_1;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		nimln_(520);		nimlf_(60, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/arc.nim");		T5_ = (NI)0;
		T5_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)16));
		cell_1 = ((tyObject_RefHeader__sqhyc4FSbGmPtkvXRNl9acg*) (T5_));
		nimlf_(521, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/orc.nim");		{
			if (!((NI)((*cell_1).rc & ((NI)-16)) == ((NI)0))) goto LA8_;
			nimln_(522);			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			nimln_(525);			(*cell_1).rc = minuspercent___system_u813((*cell_1).rc, ((NI)16));
		}
LA6_: ;
		nimln_(527);		rememberCycle__system_u3573(result, cell_1, (*((TNimTypeV2**) (p_p0))));
	}
LA3_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZasyncdispatch_u2039)(tySequence__7kmTXLGpeKFI9af9bxASU4iA dest_p0) {
	NI colontmp_;
	colontmp_ = ((NI)0);
	{
		while (1) {
			NI T3_;
			T3_ = dest_p0.len;
			if (!(colontmp_ < T3_)) goto LA2;
			{
				NIM_BOOL T6_;
				T6_ = (NIM_BOOL)0;
				T6_ = nimDecRefIsLastCyclicDyn(dest_p0.p->data[colontmp_].Field1);
				if (!T6_) goto LA7_;
				nimDestroyAndDispose(dest_p0.p->data[colontmp_].Field1);
			}
LA7_: ;
			colontmp_ += ((NI)1);
		} LA2: ;
	}
	if (dest_p0.p && !(dest_p0.p->cap & NIM_STRLIT_FLAG)) {
 alignedDealloc(dest_p0.p, NIM_ALIGNOF(tyTuple__Yk9co6DjRTcTlU6U0WDauNQ));
}
}
static N_INLINE(NI, pluspercent___system_u793)(NI x_p0, NI y_p1) {
	NI result;
	nimfr_("+%", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/arithmetics.nim");
	nimlf_(366, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/arithmetics.nim");	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) + (NU64)(((NU) (y_p1))))));
	popFrame();
	return result;
}
static N_INLINE(void, add__system_u3094)(tyObject_CellSeq__tmpRNCI2baMQRvZpqUI72g* s_p0, void** c_p1, TNimTypeV2* t_p2) {
	void** colontmp_;
	TNimTypeV2* colontmp__2;
	nimfr_("add", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/cellseqs_v2.nim");
	nimlf_(28, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/cellseqs_v2.nim");	{
		if (!((*s_p0).cap <= (*s_p0).len)) goto LA3_;
		nimln_(29);		resize__system_u3102(s_p0);
	}
LA3_: ;
	nimln_(30);	colontmp_ = c_p1;
	colontmp__2 = t_p2;
	(*s_p0).d[(*s_p0).len].Field0 = colontmp_;
	(*s_p0).d[(*s_p0).len].Field1 = colontmp__2;
	nimln_(31);	(*s_p0).len = pluspercent___system_u793((*s_p0).len, ((NI)1));
	popFrame();
}
static N_INLINE(void, nimTraceRefDyn)(void* q_p0, void* env_p1) {
	void** p_1;
	nimfr_("nimTraceRefDyn", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/orc.nim");
	nimlf_(138, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/orc.nim");	p_1 = ((void**) (q_p0));
	nimln_(139);	{
		tyObject_GcEnv__85WwC9a1qDcL9aPJ9b1qr0g2Q* j_1;
		if (!!(((*p_1) == NIM_NIL))) goto LA3_;
		nimln_(140);		j_1 = ((tyObject_GcEnv__85WwC9a1qDcL9aPJ9b1qr0g2Q*) (env_p1));
		nimln_(141);		add__system_u3094((&(*j_1).traceStack), p_1, (*((TNimTypeV2**) ((*p_1)))));
	}
LA3_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___pureZasyncdispatch_u2051)(tySequence__7kmTXLGpeKFI9af9bxASU4iA* dest_p0, void* env_p1) {
	NI colontmp_;
	colontmp_ = ((NI)0);
	{
		while (1) {
			NI T3_;
			T3_ = (*dest_p0).len;
			if (!(colontmp_ < T3_)) goto LA2;
			nimTraceRefDyn(&(*dest_p0).p->data[colontmp_].Field1, env_p1);
			colontmp_ += ((NI)1);
		} LA2: ;
	}
}
N_LIB_PRIVATE N_NIMCALL(void, clear__pureZasyncdispatch_u1983)(tyObject_HeapQueue__bwC4EuJ0YPM6kGXJDg8U5Q* heap_p0) {
	nimfr_("clear", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/pure/collections/heapqueue.nim");
	nimlf_(254, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/pure/collections/heapqueue.nim");	setLen__pureZasyncdispatch_u263((&(*heap_p0).data), ((NI)0));
	popFrame();
}
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	nimSetMem__system_u2188(p_p0, ((int)0), size_p1);
}
static N_INLINE(void, pop__pureZasyncdispatch_u221)(tySequence__7kmTXLGpeKFI9af9bxASU4iA* s_p0, tyTuple__Yk9co6DjRTcTlU6U0WDauNQ* Result) {
	NI L_1;
	NI T1_;
	NI TM__f2bNHCHm2LvO7iSrwQtdiQ_10;
	nimfr_("pop", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system.nim");
{	nimZeroMem((void*)Result, sizeof(tyTuple__Yk9co6DjRTcTlU6U0WDauNQ));
	nimlf_(1949, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system.nim");	T1_ = (*s_p0).len;
	if (nimSubInt(T1_, ((NI)1), &TM__f2bNHCHm2LvO7iSrwQtdiQ_10)) { raiseOverflow(); goto BeforeRet_;
	};
	L_1 = (NI)(TM__f2bNHCHm2LvO7iSrwQtdiQ_10);
	nimln_(1951);	if (L_1 < 0 || L_1 >= (*s_p0).len){ raiseIndexError2(L_1,(*s_p0).len-1); goto BeforeRet_;
	}
	(*Result).Field0 = (*s_p0).p->data[L_1].Field0;
	(*Result).Field1 = (*s_p0).p->data[L_1].Field1;
	eqwasMoved___pureZasyncdispatch_u236((&(*s_p0).p->data[L_1]));
	nimln_(1952);	if ((L_1) < ((NI)0) || (L_1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(L_1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	shrink__pureZasyncdispatch_u259(s_p0, (L_1));
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(NI, len__pureZasyncdispatch_u84)(tyObject_HeapQueue__bwC4EuJ0YPM6kGXJDg8U5Q heap_p0) {
	NI result;
	NI T1_;
	nimfr_("len", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/pure/collections/heapqueue.nim");
	nimlf_(73, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/pure/collections/heapqueue.nim");	T1_ = heap_p0.data.len;
	result = T1_;
	popFrame();
	return result;
}
static N_INLINE(tyTuple__Yk9co6DjRTcTlU6U0WDauNQ*, X5BX5D___pureZasyncdispatch_u156)(tyObject_HeapQueue__bwC4EuJ0YPM6kGXJDg8U5Q* heap_p0, NI i_p1) {
	tyTuple__Yk9co6DjRTcTlU6U0WDauNQ* result;
	nimfr_("[]", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/pure/collections/heapqueue.nim");
{	nimln_(76);	if (i_p1 < 0 || i_p1 >= (*heap_p0).data.len){ raiseIndexError2(i_p1,(*heap_p0).data.len-1); goto BeforeRet_;
	}
	result = (&(*heap_p0).data.p->data[i_p1]);
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, heapCmp__pureZasyncdispatch_u733)(tyTuple__Yk9co6DjRTcTlU6U0WDauNQ x_p0, tyTuple__Yk9co6DjRTcTlU6U0WDauNQ y_p1) {
	NIM_BOOL result;
	nimfr_("heapCmp", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/pure/collections/heapqueue.nim");
	result = lt___pureZasyncdispatch_u738(x_p0, y_p1);
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, siftup__pureZasyncdispatch_u877)(tyObject_HeapQueue__bwC4EuJ0YPM6kGXJDg8U5Q* heap_p0, NI startpos_p1, NI p_p2) {
	tyTuple__Yk9co6DjRTcTlU6U0WDauNQ newitem_1;
	NI pos_1;
	tyTuple__Yk9co6DjRTcTlU6U0WDauNQ* T2_;
NIM_BOOL oldNimErrFin5_;
NIM_BOOL* nimErr_;
	nimfr_("siftup", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/pure/collections/heapqueue.nim");
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&newitem_1), sizeof(tyTuple__Yk9co6DjRTcTlU6U0WDauNQ));
	nimln_(92);	pos_1 = p_p2;
	nimlf_(170, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system.nim");	nimlf_(93, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/pure/collections/heapqueue.nim");	if ((pos_1) < ((NI)0) || (pos_1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(pos_1, ((NI)0), ((NI)IL64(9223372036854775807))); goto LA1_;
	}
	T2_ = (tyTuple__Yk9co6DjRTcTlU6U0WDauNQ*)0;
	T2_ = X5BX5D___pureZasyncdispatch_u156((&(*heap_p0)), (pos_1));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimlf_(170, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system.nim");	eqcopy___pureZasyncdispatch_u242((&newitem_1), (*T2_));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		nimlf_(96, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/pure/collections/heapqueue.nim");		while (1) {
			tyTuple__Yk9co6DjRTcTlU6U0WDauNQ parent_1;
			NI parentpos_1;
			NI TM__f2bNHCHm2LvO7iSrwQtdiQ_16;
			tyTuple__Yk9co6DjRTcTlU6U0WDauNQ* T6_;
			if (!(startpos_p1 < pos_1)) goto LA4;
			nimZeroMem((void*)(&parent_1), sizeof(tyTuple__Yk9co6DjRTcTlU6U0WDauNQ));
			nimln_(97);			if (nimSubInt(pos_1, ((NI)1), &TM__f2bNHCHm2LvO7iSrwQtdiQ_16)) { raiseOverflow(); goto LA5_;
			};
			parentpos_1 = (NI)((NI64)((NI)(TM__f2bNHCHm2LvO7iSrwQtdiQ_16)) >> (NU64)(((NI)1) & (64 - 1)));
			nimlf_(170, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system.nim");			nimlf_(98, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/pure/collections/heapqueue.nim");			if ((parentpos_1) < ((NI)0) || (parentpos_1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(parentpos_1, ((NI)0), ((NI)IL64(9223372036854775807))); goto LA5_;
			}
			T6_ = (tyTuple__Yk9co6DjRTcTlU6U0WDauNQ*)0;
			T6_ = X5BX5D___pureZasyncdispatch_u156((&(*heap_p0)), (parentpos_1));
			if (NIM_UNLIKELY(*nimErr_)) goto LA5_;
			nimlf_(170, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system.nim");			eqcopy___pureZasyncdispatch_u242((&parent_1), (*T6_));
			if (NIM_UNLIKELY(*nimErr_)) goto LA5_;
			nimlf_(99, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/pure/collections/heapqueue.nim");			{
				NIM_BOOL T9_;
				T9_ = (NIM_BOOL)0;
				T9_ = heapCmp__pureZasyncdispatch_u733(newitem_1, parent_1);
				if (NIM_UNLIKELY(*nimErr_)) goto LA5_;
				if (!T9_) goto LA10_;
				nimlf_(170, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system.nim");				if (pos_1 < 0 || pos_1 >= (*heap_p0).data.len){ raiseIndexError2(pos_1,(*heap_p0).data.len-1); goto LA5_;
				}
				eqsink___pureZasyncdispatch_u248((&(*heap_p0).data.p->data[pos_1]), parent_1);
				if (NIM_UNLIKELY(*nimErr_)) goto LA5_;
				eqwasMoved___pureZasyncdispatch_u236((&parent_1));
				if (NIM_UNLIKELY(*nimErr_)) goto LA5_;
				nimlf_(101, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/pure/collections/heapqueue.nim");				pos_1 = parentpos_1;
			}
			goto LA7_;
LA10_: ;
			{
				nimlf_(170, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system.nim");				eqdestroy___pureZasyncdispatch_u239((&parent_1));
				if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
				nimlf_(103, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/pure/collections/heapqueue.nim");				goto LA3;
			}
LA7_: ;
			{
				LA5_:;
			}
			{
				oldNimErrFin5_ = *nimErr_; *nimErr_ = NIM_FALSE;
				nimlf_(170, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system.nim");				eqdestroy___pureZasyncdispatch_u239((&parent_1));
				if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
				*nimErr_ = oldNimErrFin5_;
			}
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		} LA4: ;
	} LA3: ;
	if (pos_1 < 0 || pos_1 >= (*heap_p0).data.len){ raiseIndexError2(pos_1,(*heap_p0).data.len-1); goto LA1_;
	}
	eqsink___pureZasyncdispatch_u248((&(*heap_p0).data.p->data[pos_1]), newitem_1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		LA1_:;
	}
	{
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, siftdownToBottom__pureZasyncdispatch_u471)(tyObject_HeapQueue__bwC4EuJ0YPM6kGXJDg8U5Q* heap_p0, NI p_p1) {
	tyTuple__Yk9co6DjRTcTlU6U0WDauNQ newitem_1;
	NI endpos_1;
	NI pos_1;
	NI startpos_1;
	tyTuple__Yk9co6DjRTcTlU6U0WDauNQ* T1_;
	NI childpos_1;
	NI TM__f2bNHCHm2LvO7iSrwQtdiQ_11;
	NI TM__f2bNHCHm2LvO7iSrwQtdiQ_12;
NIM_BOOL* nimErr_;
	nimfr_("siftdownToBottom", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/pure/collections/heapqueue.nim");
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&newitem_1), sizeof(tyTuple__Yk9co6DjRTcTlU6U0WDauNQ));
	nimlf_(108, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/pure/collections/heapqueue.nim");	endpos_1 = len__pureZasyncdispatch_u84((*heap_p0));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(109);	pos_1 = p_p1;
	nimln_(110);	startpos_1 = pos_1;
	nimlf_(170, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system.nim");	nimlf_(111, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/pure/collections/heapqueue.nim");	if ((pos_1) < ((NI)0) || (pos_1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(pos_1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	T1_ = (tyTuple__Yk9co6DjRTcTlU6U0WDauNQ*)0;
	T1_ = X5BX5D___pureZasyncdispatch_u156((&(*heap_p0)), (pos_1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimlf_(170, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system.nim");	eqcopy___pureZasyncdispatch_u242((&newitem_1), (*T1_));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimlf_(113, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/pure/collections/heapqueue.nim");	if (nimMulInt(((NI)2), pos_1, &TM__f2bNHCHm2LvO7iSrwQtdiQ_11)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimAddInt((NI)(TM__f2bNHCHm2LvO7iSrwQtdiQ_11), ((NI)1), &TM__f2bNHCHm2LvO7iSrwQtdiQ_12)) { raiseOverflow(); goto BeforeRet_;
	};
	childpos_1 = (NI)(TM__f2bNHCHm2LvO7iSrwQtdiQ_12);
	{
		nimln_(114);		while (1) {
			NI rightpos_1;
			NI TM__f2bNHCHm2LvO7iSrwQtdiQ_13;
			tyTuple__Yk9co6DjRTcTlU6U0WDauNQ* T13_;
			NI TM__f2bNHCHm2LvO7iSrwQtdiQ_14;
			NI TM__f2bNHCHm2LvO7iSrwQtdiQ_15;
			if (!(childpos_1 < endpos_1)) goto LA3;
			nimln_(116);			if (nimAddInt(childpos_1, ((NI)1), &TM__f2bNHCHm2LvO7iSrwQtdiQ_13)) { raiseOverflow(); goto BeforeRet_;
			};
			rightpos_1 = (NI)(TM__f2bNHCHm2LvO7iSrwQtdiQ_13);
			nimln_(117);			{
				NIM_BOOL T6_;
				tyTuple__Yk9co6DjRTcTlU6U0WDauNQ* T8_;
				tyTuple__Yk9co6DjRTcTlU6U0WDauNQ* T9_;
				NIM_BOOL T10_;
				T6_ = (NIM_BOOL)0;
				T6_ = (rightpos_1 < endpos_1);
				if (!(T6_)) goto LA7_;
				if ((childpos_1) < ((NI)0) || (childpos_1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(childpos_1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
				}
				T8_ = (tyTuple__Yk9co6DjRTcTlU6U0WDauNQ*)0;
				T8_ = X5BX5D___pureZasyncdispatch_u156((&(*heap_p0)), (childpos_1));
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				if ((rightpos_1) < ((NI)0) || (rightpos_1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(rightpos_1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
				}
				T9_ = (tyTuple__Yk9co6DjRTcTlU6U0WDauNQ*)0;
				T9_ = X5BX5D___pureZasyncdispatch_u156((&(*heap_p0)), (rightpos_1));
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				T10_ = (NIM_BOOL)0;
				T10_ = heapCmp__pureZasyncdispatch_u733((*T8_), (*T9_));
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				T6_ = !(T10_);
LA7_: ;
				if (!T6_) goto LA11_;
				nimln_(118);				childpos_1 = rightpos_1;
			}
LA11_: ;
			nimlf_(170, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system.nim");			if (pos_1 < 0 || pos_1 >= (*heap_p0).data.len){ raiseIndexError2(pos_1,(*heap_p0).data.len-1); goto BeforeRet_;
			}
			nimlf_(120, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/pure/collections/heapqueue.nim");			if ((childpos_1) < ((NI)0) || (childpos_1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(childpos_1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
			}
			T13_ = (tyTuple__Yk9co6DjRTcTlU6U0WDauNQ*)0;
			T13_ = X5BX5D___pureZasyncdispatch_u156((&(*heap_p0)), (childpos_1));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimlf_(170, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system.nim");			eqcopy___pureZasyncdispatch_u242((&(*heap_p0).data.p->data[pos_1]), (*T13_));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimlf_(121, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/pure/collections/heapqueue.nim");			pos_1 = childpos_1;
			nimln_(122);			if (nimMulInt(((NI)2), pos_1, &TM__f2bNHCHm2LvO7iSrwQtdiQ_14)) { raiseOverflow(); goto BeforeRet_;
			};
			if (nimAddInt((NI)(TM__f2bNHCHm2LvO7iSrwQtdiQ_14), ((NI)1), &TM__f2bNHCHm2LvO7iSrwQtdiQ_15)) { raiseOverflow(); goto BeforeRet_;
			};
			childpos_1 = (NI)(TM__f2bNHCHm2LvO7iSrwQtdiQ_15);
		} LA3: ;
	}
	nimlf_(170, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system.nim");	if (pos_1 < 0 || pos_1 >= (*heap_p0).data.len){ raiseIndexError2(pos_1,(*heap_p0).data.len-1); goto BeforeRet_;
	}
	eqsink___pureZasyncdispatch_u248((&(*heap_p0).data.p->data[pos_1]), newitem_1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimlf_(126, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/pure/collections/heapqueue.nim");	siftup__pureZasyncdispatch_u877(heap_p0, startpos_1, pos_1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, pop__pureZasyncdispatch_u217)(tyObject_HeapQueue__bwC4EuJ0YPM6kGXJDg8U5Q* heap_p0, tyTuple__Yk9co6DjRTcTlU6U0WDauNQ* Result) {
	tyTuple__Yk9co6DjRTcTlU6U0WDauNQ lastelt_1;
NIM_BOOL* nimErr_;
	nimfr_("pop", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/pure/collections/heapqueue.nim");
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)Result, sizeof(tyTuple__Yk9co6DjRTcTlU6U0WDauNQ));
	nimZeroMem((void*)(&lastelt_1), sizeof(tyTuple__Yk9co6DjRTcTlU6U0WDauNQ));
	nimln_(171);	pop__pureZasyncdispatch_u221((&(*heap_p0).data), (&lastelt_1));
	nimln_(172);	{
		NI T3_;
		tyTuple__Yk9co6DjRTcTlU6U0WDauNQ* T6_;
		T3_ = (NI)0;
		T3_ = len__pureZasyncdispatch_u84((*heap_p0));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!(((NI)0) < T3_)) goto LA4_;
		nimlf_(170, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system.nim");		nimlf_(173, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/pure/collections/heapqueue.nim");		T6_ = (tyTuple__Yk9co6DjRTcTlU6U0WDauNQ*)0;
		T6_ = X5BX5D___pureZasyncdispatch_u156((&(*heap_p0)), ((NI)0));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimlf_(170, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system.nim");		eqcopy___pureZasyncdispatch_u242(Result, (*T6_));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (((NI)0) < 0 || ((NI)0) >= (*heap_p0).data.len){ raiseIndexError2(((NI)0),(*heap_p0).data.len-1); goto BeforeRet_;
		}
		eqsink___pureZasyncdispatch_u248((&(*heap_p0).data.p->data[((NI)0)]), lastelt_1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimlf_(175, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/pure/collections/heapqueue.nim");		siftdownToBottom__pureZasyncdispatch_u471(heap_p0, ((NI)0));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA1_;
LA4_: ;
	{
		nimln_(177);		(*Result).Field0 = lastelt_1.Field0;
		(*Result).Field1 = lastelt_1.Field1;
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
}
