/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -fno-strict-aliasing -pthread -I/home/icarogdo/.nimble/pkgs2/bearssl-0.2.10-e53ab85b8c4c1ce3aa1f4eb251c0ab29e08d4972/bearssl/abi -I/home/icarogdo/.nimble/pkgs2/bearssl-0.2.10-e53ab85b8c4c1ce3aa1f4eb251c0ab29e08d4972/bearssl/abi/../csources/src/ -I/home/icarogdo/.nimble/pkgs2/bearssl-0.2.10-e53ab85b8c4c1ce3aa1f4eb251c0ab29e08d4972/bearssl/abi/../csources/inc/ -I/home/icarogdo/.nimble/pkgs2/bearssl-0.2.10-e53ab85b8c4c1ce3aa1f4eb251c0ab29e08d4972/bearssl/abi/../csources/tools/ -DBR_USE_UNIX_TIME=1 -DBR_USE_URANDOM=1 -DBR_LE_UNALIGNED=1 -DBR_64=1  -DBR_amd64=1 -DBR_INT128=1 -Wno-incompatible-pointer-types -I/usr/include/webkitgtk-4.1 -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/cloudproviders -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/glycin-2 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/atk-1.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/fribidi -I/usr/include/pixman-1 -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gio-unix-2.0 -I/usr/include/libsoup-3.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-6 -pthread   -I/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib -I/home/icarogdo/dev/macroobras-jazzy/app/macroobras/src -o /home/icarogdo/dev/macroobras-jazzy/app/macroobras/.nimcache/@phttpcore.nim.c.o /home/icarogdo/dev/macroobras-jazzy/app/macroobras/.nimcache/@phttpcore.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tyObject_HttpHeaderscolonObjectType___q5RmldX8ngqdFdLFcD77Rw tyObject_HttpHeaderscolonObjectType___q5RmldX8ngqdFdLFcD77Rw;
typedef struct tyObject_RefHeader__sqhyc4FSbGmPtkvXRNl9acg tyObject_RefHeader__sqhyc4FSbGmPtkvXRNl9acg;
typedef struct tyObject_Table__vMsav2LrmlVebnca684Wgg tyObject_Table__vMsav2LrmlVebnca684Wgg;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content;
typedef struct tyObject_NimRawSeq__2kUMFDNh0hpLnOTOSL0tSA tyObject_NimRawSeq__2kUMFDNh0hpLnOTOSL0tSA;
struct tyObject_RefHeader__sqhyc4FSbGmPtkvXRNl9acg {
	NI rc;
	NI rootIdx;
};
struct tyObject_HttpHeaderscolonObjectType___q5RmldX8ngqdFdLFcD77Rw {
	tyObject_Table__vMsav2LrmlVebnca684Wgg* table;
	NIM_BOOL isTitleCase;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  NI len; tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content* p;
};
struct tyObject_NimRawSeq__2kUMFDNh0hpLnOTOSL0tSA {
	NI len;
	void* p;
};
typedef NU8 tyEnum_HttpMethod__8E0cnqA4t7LOGc109a8NMBg;
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE]; };
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p_p0);
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4511)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZhttpcore_u302)(tyObject_Table__vMsav2LrmlVebnca684Wgg* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimRawDispose)(void* p_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZhttpcore_u414)(tyObject_HttpHeaderscolonObjectType___q5RmldX8ngqdFdLFcD77Rw* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObjUninit)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_Table__vMsav2LrmlVebnca684Wgg*, newTable__pureZhttpcore_u133)(NI initialSize_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasKey__pureZhttpcore_u575)(tyObject_Table__vMsav2LrmlVebnca684Wgg* t_p0, NimStringV2 key_p1);
static N_INLINE(NimStringV2, toCaseInsensitive__pureZhttpcore_u110)(tyObject_HttpHeaderscolonObjectType___q5RmldX8ngqdFdLFcD77Rw* headers_p0, NimStringV2 s_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, toTitleCase__pureZhttpcore_u101)(NimStringV2 s_p0);
N_NIMCALL(NimStringV2, mnewString)(NI len_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimPrepareStrMutationImpl__system_u2511)(NimStringV2* s_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_CHAR, nsuToUpperAsciiChar)(NIM_CHAR c_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_CHAR, nsuToLowerAsciiChar)(NIM_CHAR c_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuToLowerAsciiStr)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq___pureZhttpcore_u1183)(tyObject_Table__vMsav2LrmlVebnca684Wgg* t_p0, NimStringV2 key_p1, tySequence__sM4lkSb7zS6F7OVMvW9cffQ val_p2);
N_LIB_PRIVATE N_NIMCALL(void*, newSeqPayload)(NI cap_p0, NI elemSize_p1, NI elemAlign_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, eqdup___system_u2775)(NimStringV2 src_p0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, add__stdZenumutils_u70)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ* x_p0, NimStringV2 y_p1);
N_LIB_PRIVATE N_NIMCALL(tySequence__sM4lkSb7zS6F7OVMvW9cffQ*, X5BX5D___pureZhttpcore_u950)(tyObject_Table__vMsav2LrmlVebnca684Wgg* t_p0, NimStringV2 key_p1);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasKey__pureZhttpcore_u3936)(tyObject_HttpHeaderscolonObjectType___q5RmldX8ngqdFdLFcD77Rw* headers_p0, NimStringV2 key_p1);
N_LIB_PRIVATE N_NIMCALL(tySequence__sM4lkSb7zS6F7OVMvW9cffQ, X5BX5D___pureZhttpcore_u2949)(tyObject_HttpHeaderscolonObjectType___q5RmldX8ngqdFdLFcD77Rw* headers_p0, NimStringV2 key_p1);
N_LIB_PRIVATE N_NIMCALL(tySequence__sM4lkSb7zS6F7OVMvW9cffQ, eqdup___system_u5663)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ src_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pureZhttpcore_u3037)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ* dest_p0, tySequence__sM4lkSb7zS6F7OVMvW9cffQ src_p1);
static N_INLINE(NIM_BOOL, sameSeqPayload)(void* x_p0, void* y_p1);
N_LIB_PRIVATE N_NIMCALL(void, setLen__system_u5561)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ* s_p0, NI newlen_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u2772)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(void, alignedDealloc)(void* p_p0, NI align_p1);
static N_INLINE(void, nimIncRef)(void* p_p0);
static N_INLINE(NI, pluspercent___system_u793)(NI x_p0, NI y_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u5660)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ* dest_p0, tySequence__sM4lkSb7zS6F7OVMvW9cffQ src_p1);
N_LIB_PRIVATE N_NIMCALL(void, del__pureZhttpcore_u3263)(tyObject_Table__vMsav2LrmlVebnca684Wgg* t_p0, NimStringV2 key_p1);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1);
static N_INLINE(NIM_BOOL, equalMem__system_u1763)(void* a_p0, void* b_p1, NI size_p2);
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u95)(NimStringV2 msg_p0);
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__Evu9b2R1utZubyCikahWx1g_4 = { 4 | NIM_STRLIT_FLAG, "HEAD" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_5 = {4, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_4};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__Evu9b2R1utZubyCikahWx1g_6 = { 3 | NIM_STRLIT_FLAG, "GET" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_7 = {3, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_6};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__Evu9b2R1utZubyCikahWx1g_8 = { 4 | NIM_STRLIT_FLAG, "POST" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_9 = {4, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_8};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__Evu9b2R1utZubyCikahWx1g_10 = { 3 | NIM_STRLIT_FLAG, "PUT" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_11 = {3, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_10};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__Evu9b2R1utZubyCikahWx1g_12 = { 6 | NIM_STRLIT_FLAG, "DELETE" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_13 = {6, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_12};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__Evu9b2R1utZubyCikahWx1g_14 = { 5 | NIM_STRLIT_FLAG, "TRACE" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_15 = {5, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_14};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__Evu9b2R1utZubyCikahWx1g_16 = { 7 | NIM_STRLIT_FLAG, "OPTIONS" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_17 = {7, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_16};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__Evu9b2R1utZubyCikahWx1g_18 = { 7 | NIM_STRLIT_FLAG, "CONNECT" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_19 = {7, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_18};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__Evu9b2R1utZubyCikahWx1g_20 = { 5 | NIM_STRLIT_FLAG, "PATCH" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_21 = {5, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_20};
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__Evu9b2R1utZubyCikahWx1g_22 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_23 = {0, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_22};
static const struct {
  NI cap; NIM_CHAR data[149+1];
} TM__Evu9b2R1utZubyCikahWx1g_24 = { 149 | NIM_STRLIT_FLAG, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/iterators.nim(254, 11) `len(a) == L` the length of the seq changed while iterating over it" };
static const NimStringV2 TM__Evu9b2R1utZubyCikahWx1g_25 = {149, (NimStrPayload*)&TM__Evu9b2R1utZubyCikahWx1g_24};
extern NIM_THREADVAR TFrame* framePtr__system_u2809;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4293;
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2809 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2809).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2809;
	framePtr__system_u2809 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4511();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2809 = (*framePtr__system_u2809).prev;
}
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1) {
	NI result;
	nimfr_("-%", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/arithmetics.nim");
	nimlf_(377, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/arithmetics.nim");	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) - (NU64)(((NU) (y_p1))))));
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p_p0) {
	NIM_BOOL result;
	nimfr_("nimDecRefIsLast", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/arc.nim");
	nimlf_(239, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/arc.nim");	result = NIM_FALSE;
	nimln_(240);	{
		tyObject_RefHeader__sqhyc4FSbGmPtkvXRNl9acg* cell_1;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		nimln_(241);		nimln_(60);		T5_ = (NI)0;
		T5_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)16));
		cell_1 = ((tyObject_RefHeader__sqhyc4FSbGmPtkvXRNl9acg*) (T5_));
		nimln_(255);		{
			if (!((NI)((NI64)((*cell_1).rc) >> (NU64)(((NI)4) & (64 - 1))) == ((NI)0))) goto LA8_;
			nimln_(256);			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			nimln_(86);			(*cell_1).rc = minuspercent___system_u813((*cell_1).rc, ((NI)16));
		}
LA6_: ;
	}
LA3_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZhttpcore_u414)(tyObject_HttpHeaderscolonObjectType___q5RmldX8ngqdFdLFcD77Rw* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast((*dest_p0).table);
		if (!T3_) goto LA4_;
		eqdestroy___pureZhttpcore_u302((*dest_p0).table);
		nimRawDispose((*dest_p0).table, ((NI)8));
	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___pureZhttpcore_u449)(tyObject_HttpHeaderscolonObjectType___q5RmldX8ngqdFdLFcD77Rw** dest_p0, tyObject_HttpHeaderscolonObjectType___q5RmldX8ngqdFdLFcD77Rw* src_p1) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast((*dest_p0));
		if (!T3_) goto LA4_;
		eqdestroy___pureZhttpcore_u414((&(*(*dest_p0))));
		nimRawDispose((*dest_p0), ((NI)8));
	}
LA4_: ;
	(*dest_p0) = src_p1;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4293);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_HttpHeaderscolonObjectType___q5RmldX8ngqdFdLFcD77Rw*, newHttpHeaders__pureZhttpcore_u114)(NIM_BOOL titleCase_p0) {
	tyObject_HttpHeaderscolonObjectType___q5RmldX8ngqdFdLFcD77Rw* result;
	tyObject_HttpHeaderscolonObjectType___q5RmldX8ngqdFdLFcD77Rw* T1_;
NIM_BOOL* nimErr_;
	nimfr_("newHttpHeaders", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/pure/httpcore.nim");
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	nimlf_(136, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/pure/httpcore.nim");	T1_ = NIM_NIL;
	T1_ = (tyObject_HttpHeaderscolonObjectType___q5RmldX8ngqdFdLFcD77Rw*) nimNewObjUninit(sizeof(tyObject_HttpHeaderscolonObjectType___q5RmldX8ngqdFdLFcD77Rw), NIM_ALIGNOF(tyObject_HttpHeaderscolonObjectType___q5RmldX8ngqdFdLFcD77Rw));
	(*T1_).table = newTable__pureZhttpcore_u133(((NI)32));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*T1_).isTitleCase = titleCase_p0;
	result = T1_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZhttpcore_u440)(tyObject_HttpHeaderscolonObjectType___q5RmldX8ngqdFdLFcD77Rw* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast(dest_p0);
		if (!T3_) goto LA4_;
		eqdestroy___pureZhttpcore_u414((&(*dest_p0)));
		nimRawDispose(dest_p0, ((NI)8));
	}
LA4_: ;
}
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = !(((*s_p0).p == ((NimStrPayload*) NIM_NIL)));
		if (!(T3_)) goto LA4_;
		T3_ = ((NI)((*(*s_p0).p).cap & ((NI)IL64(4611686018427387904))) == ((NI)IL64(4611686018427387904)));
LA4_: ;
		if (!T3_) goto LA5_;
		nimPrepareStrMutationImpl__system_u2511(s_p0);
	}
LA5_: ;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, toTitleCase__pureZhttpcore_u101)(NimStringV2 s_p0) {
	NimStringV2 result;
	NIM_BOOL upper_1;
NIM_BOOL* nimErr_;
	nimfr_("toTitleCase", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/pure/httpcore.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimln_(123);	if ((s_p0.len) < ((NI)0) || (s_p0.len) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(s_p0.len, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	result = mnewString((s_p0.len));
	nimln_(124);	upper_1 = NIM_TRUE;
	{
		NI i_1;
		NI colontmp_;
		NI TM__Evu9b2R1utZubyCikahWx1g_2;
		NI res_1;
		i_1 = (NI)0;
		colontmp_ = (NI)0;
		nimlf_(81, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/iterators_1.nim");		nimlf_(125, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/pure/httpcore.nim");		if (nimSubInt(s_p0.len, ((NI)1), &TM__Evu9b2R1utZubyCikahWx1g_2)) { raiseOverflow(); goto BeforeRet_;
		};
		colontmp_ = (NI)(TM__Evu9b2R1utZubyCikahWx1g_2);
		nimlf_(96, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/iterators_1.nim");		res_1 = ((NI)0);
		{
			nimln_(97);			while (1) {
				NIM_CHAR T4_;
				NI TM__Evu9b2R1utZubyCikahWx1g_3;
				if (!(res_1 <= colontmp_)) goto LA3;
				nimlf_(125, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/pure/httpcore.nim");				i_1 = ((NI) (res_1));
				T4_ = (NIM_CHAR)0;
				nimln_(126);				{
					NIM_CHAR T9_;
					if (!upper_1) goto LA7_;
					if (i_1 < 0 || i_1 >= result.len){ raiseIndexError2(i_1,result.len-1); goto BeforeRet_;
					}
					nimPrepareStrMutationV2((&result));
					if (i_1 < 0 || i_1 >= s_p0.len){ raiseIndexError2(i_1,s_p0.len-1); goto BeforeRet_;
					}
					T9_ = (NIM_CHAR)0;
					T9_ = nsuToUpperAsciiChar(s_p0.p->data[i_1]);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					result.p->data[i_1] = T9_;
				}
				goto LA5_;
LA7_: ;
				{
					NIM_CHAR T11_;
					if (i_1 < 0 || i_1 >= result.len){ raiseIndexError2(i_1,result.len-1); goto BeforeRet_;
					}
					nimPrepareStrMutationV2((&result));
					if (i_1 < 0 || i_1 >= s_p0.len){ raiseIndexError2(i_1,s_p0.len-1); goto BeforeRet_;
					}
					T11_ = (NIM_CHAR)0;
					T11_ = nsuToLowerAsciiChar(s_p0.p->data[i_1]);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					result.p->data[i_1] = T11_;
				}
LA5_: ;
				nimln_(127);				if (i_1 < 0 || i_1 >= s_p0.len){ raiseIndexError2(i_1,s_p0.len-1); goto BeforeRet_;
				}
				upper_1 = ((NU8)(s_p0.p->data[i_1]) == (NU8)(45));
				nimlf_(102, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/iterators_1.nim");				if (nimAddInt(res_1, ((NI)1), &TM__Evu9b2R1utZubyCikahWx1g_3)) { raiseOverflow(); goto BeforeRet_;
				};
				res_1 = (NI)(TM__Evu9b2R1utZubyCikahWx1g_3);
			} LA3: ;
		}
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NimStringV2, toCaseInsensitive__pureZhttpcore_u110)(tyObject_HttpHeaderscolonObjectType___q5RmldX8ngqdFdLFcD77Rw* headers_p0, NimStringV2 s_p1) {
	NimStringV2 result;
	NimStringV2 T1_;
NIM_BOOL* nimErr_;
	nimfr_("toCaseInsensitive", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/pure/httpcore.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimlf_(131, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/pure/httpcore.nim");	T1_.len = 0; T1_.p = NIM_NIL;
	{
		if (!(*headers_p0).isTitleCase) goto LA4_;
		nimln_(129);		nimln_(131);		result = toTitleCase__pureZhttpcore_u101(s_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA2_;
LA4_: ;
	{
		nimln_(129);		nimln_(131);		result = nsuToLowerAsciiStr(s_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA2_: ;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, add__pureZhttpcore_u3721)(tyObject_HttpHeaderscolonObjectType___q5RmldX8ngqdFdLFcD77Rw* headers_p0, NimStringV2 key_p1, NimStringV2 value_p2) {
	NimStringV2 colontmpD_;
NIM_BOOL* nimErr_;
	nimfr_("add", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/pure/httpcore.nim");
{nimErr_ = nimErrorFlag();
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	nimln_(197);	{
		NIM_BOOL T4_;
		NimStringV2 colontmpD__2;
		NimStringV2 colontmpD__3;
		tySequence__sM4lkSb7zS6F7OVMvW9cffQ T7_;
		colontmpD_ = toCaseInsensitive__pureZhttpcore_u110(headers_p0, key_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		T4_ = (NIM_BOOL)0;
		T4_ = hasKey__pureZhttpcore_u575((*headers_p0).table, colontmpD_);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		if (!!(T4_)) goto LA5_;
		colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
		nimln_(198);		colontmpD__2 = toCaseInsensitive__pureZhttpcore_u110(headers_p0, key_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		T7_.len = 0; T7_.p = NIM_NIL;
		T7_.len = 1; T7_.p = (tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content*) newSeqPayload(1, sizeof(NimStringV2), NIM_ALIGNOF(NimStringV2));
		nimlf_(1715, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system.nim");		colontmpD__3 = eqdup___system_u2775(value_p2);
		T7_.p->data[0] = colontmpD__3;
		nimlf_(198, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/pure/httpcore.nim");		X5BX5Deq___pureZhttpcore_u1183((*headers_p0).table, colontmpD__2, T7_);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		nimlf_(394, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system.nim");		if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
	}
	goto LA2_;
LA5_: ;
	{
		NimStringV2 colontmpD__4;
		NimStringV2 colontmpD__5;
		tySequence__sM4lkSb7zS6F7OVMvW9cffQ* T10_;
		colontmpD__4.len = 0; colontmpD__4.p = NIM_NIL;
		nimlf_(200, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/pure/httpcore.nim");		colontmpD__4 = toCaseInsensitive__pureZhttpcore_u110(headers_p0, key_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto LA9_;
		T10_ = (tySequence__sM4lkSb7zS6F7OVMvW9cffQ*)0;
		T10_ = X5BX5D___pureZhttpcore_u950((*headers_p0).table, colontmpD__4);
		if (NIM_UNLIKELY(*nimErr_)) goto LA9_;
		nimlf_(1715, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system.nim");		colontmpD__5 = eqdup___system_u2775(value_p2);
		nimlf_(200, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/pure/httpcore.nim");		add__stdZenumutils_u70((&(*T10_)), colontmpD__5);
		{
			LA9_:;
		}
		{
			nimlf_(394, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system.nim");			if (colontmpD__4.p && !(colontmpD__4.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__4.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
LA2_: ;
	{
		LA1_:;
	}
	{
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasKey__pureZhttpcore_u3936)(tyObject_HttpHeaderscolonObjectType___q5RmldX8ngqdFdLFcD77Rw* headers_p0, NimStringV2 key_p1) {
	NIM_BOOL result;
	NimStringV2 colontmpD_;
NIM_BOOL* nimErr_;
	nimfr_("hasKey", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/pure/httpcore.nim");
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	nimlf_(220, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/pure/httpcore.nim");	nimln_(219);	nimln_(220);	colontmpD_ = toCaseInsensitive__pureZhttpcore_u110(headers_p0, key_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	result = hasKey__pureZhttpcore_u575((*headers_p0).table, colontmpD_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimlf_(394, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system.nim");	if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	goto BeforeRet_;
	{
		LA1_:;
	}
	{
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tySequence__sM4lkSb7zS6F7OVMvW9cffQ, X5BX5D___pureZhttpcore_u2949)(tyObject_HttpHeaderscolonObjectType___q5RmldX8ngqdFdLFcD77Rw* headers_p0, NimStringV2 key_p1) {
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ result;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ tmp_1;
	NimStringV2 colontmpD_;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ colontmpD__2;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ* T2_;
NIM_BOOL* nimErr_;
	nimfr_("[]", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/pure/httpcore.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	tmp_1.len = 0; tmp_1.p = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	nimlf_(167, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/pure/httpcore.nim");	colontmpD_ = toCaseInsensitive__pureZhttpcore_u110(headers_p0, key_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T2_ = (tySequence__sM4lkSb7zS6F7OVMvW9cffQ*)0;
	T2_ = X5BX5D___pureZhttpcore_u950((*headers_p0).table, colontmpD_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	tmp_1 = (*T2_);
	nimln_(168);	nimln_(158);	nimln_(168);	nimlf_(2219, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system.nim");	colontmpD__2 = eqdup___system_u5663(tmp_1);
	result = colontmpD__2;
	nimln_(394);	if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	goto BeforeRet_;
	{
		LA1_:;
	}
	{
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, sameSeqPayload)(void* x_p0, void* y_p1) {
	NIM_BOOL result;
	result = ((*((tyObject_NimRawSeq__2kUMFDNh0hpLnOTOSL0tSA*) (x_p0))).p == (*((tyObject_NimRawSeq__2kUMFDNh0hpLnOTOSL0tSA*) (y_p1))).p);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pureZhttpcore_u3037)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ* dest_p0, tySequence__sM4lkSb7zS6F7OVMvW9cffQ src_p1) {
	NI T6_;
	NI colontmp_;
{	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = sameSeqPayload(dest_p0, (&src_p1));
		if (!T3_) goto LA4_;
		goto BeforeRet_;
	}
LA4_: ;
	T6_ = src_p1.len;
	setLen__system_u5561((&(*dest_p0)), T6_);
	colontmp_ = ((NI)0);
	{
		while (1) {
			NI T9_;
			T9_ = (*dest_p0).len;
			if (!(colontmp_ < T9_)) goto LA8;
			eqcopy___system_u2772((&(*dest_p0).p->data[colontmp_]), src_p1.p->data[colontmp_]);
			colontmp_ += ((NI)1);
		} LA8: ;
	}
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(tySequence__sM4lkSb7zS6F7OVMvW9cffQ, getOrDefault__pureZhttpcore_u3981)(tyObject_HttpHeaderscolonObjectType___q5RmldX8ngqdFdLFcD77Rw* headers_p0, NimStringV2 key_p1, tySequence__sM4lkSb7zS6F7OVMvW9cffQ default_p2) {
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ result;
NIM_BOOL* nimErr_;
	nimfr_("getOrDefault", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/pure/httpcore.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimlf_(226, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/pure/httpcore.nim");	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = hasKey__pureZhttpcore_u3936(headers_p0, key_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!T3_) goto LA4_;
		nimln_(227);		nimln_(222);		nimln_(227);		result = X5BX5D___pureZhttpcore_u2949(headers_p0, key_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
	}
	goto LA1_;
LA4_: ;
	{
		nimln_(229);		nimln_(168);		eqcopy___pureZhttpcore_u3037((&result), default_p2);
		goto BeforeRet_;
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZhttpcore_u3030)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ dest_p0) {
	NI colontmp_;
	colontmp_ = ((NI)0);
	{
		while (1) {
			NI T3_;
			T3_ = dest_p0.len;
			if (!(colontmp_ < T3_)) goto LA2;
			if (dest_p0.p->data[colontmp_].p && !(dest_p0.p->data[colontmp_].p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(dest_p0.p->data[colontmp_].p);
}
			colontmp_ += ((NI)1);
		} LA2: ;
	}
	if (dest_p0.p && !(dest_p0.p->cap & NIM_STRLIT_FLAG)) {
 alignedDealloc(dest_p0.p, NIM_ALIGNOF(NimStringV2));
}
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, toString__pureZhttpcore_u3066)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ values_p0) {
	NimStringV2 result;
	nimfr_("toString", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/pure/httpcore.nim");
{	result.len = 0; result.p = NIM_NIL;
	nimln_(171);	nimlf_(1715, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system.nim");	if (((NI)0) < 0 || ((NI)0) >= values_p0.len){ raiseIndexError2(((NI)0),values_p0.len-1); goto BeforeRet_;
	}
	eqcopy___system_u2772((&result), values_p0.p->data[((NI)0)]);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq___pureZhttpcore_u3128)(tyObject_HttpHeaderscolonObjectType___q5RmldX8ngqdFdLFcD77Rw* headers_p0, NimStringV2 key_p1, NimStringV2 value_p2) {
	NimStringV2 colontmpD_;
	NimStringV2 colontmpD__2;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ T1_;
NIM_BOOL* nimErr_;
	nimfr_("[]=", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/pure/httpcore.nim");
{nimErr_ = nimErrorFlag();
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	nimlf_(183, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/pure/httpcore.nim");	colontmpD_ = toCaseInsensitive__pureZhttpcore_u110(headers_p0, key_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T1_.len = 0; T1_.p = NIM_NIL;
	T1_.len = 1; T1_.p = (tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content*) newSeqPayload(1, sizeof(NimStringV2), NIM_ALIGNOF(NimStringV2));
	nimlf_(1715, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system.nim");	colontmpD__2 = eqdup___system_u2775(value_p2);
	T1_.p->data[0] = colontmpD__2;
	nimlf_(183, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/pure/httpcore.nim");	X5BX5Deq___pureZhttpcore_u1183((*headers_p0).table, colontmpD_, T1_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimlf_(394, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system.nim");	if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(NI, pluspercent___system_u793)(NI x_p0, NI y_p1) {
	NI result;
	nimfr_("+%", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/arithmetics.nim");
	nimlf_(366, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/arithmetics.nim");	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) + (NU64)(((NU) (y_p1))))));
	popFrame();
	return result;
}
static N_INLINE(void, nimIncRef)(void* p_p0) {
	NI T1_;
	NI T2_;
	nimfr_("nimIncRef", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/arc.nim");
	nimlf_(88, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/arc.nim");	nimln_(60);	T1_ = (NI)0;
	T1_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)16));
	nimln_(88);	nimln_(60);	T2_ = (NI)0;
	T2_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)16));
	nimln_(88);	(*((tyObject_RefHeader__sqhyc4FSbGmPtkvXRNl9acg*) (T1_))).rc = pluspercent___system_u793((*((tyObject_RefHeader__sqhyc4FSbGmPtkvXRNl9acg*) (T2_))).rc, ((NI)16));
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pureZhttpcore_u443)(tyObject_HttpHeaderscolonObjectType___q5RmldX8ngqdFdLFcD77Rw** dest_p0, tyObject_HttpHeaderscolonObjectType___q5RmldX8ngqdFdLFcD77Rw* src_p1) {
	{
		if (!src_p1) goto LA3_;
		nimIncRef(src_p1);
	}
LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = nimDecRefIsLast((*dest_p0));
		if (!T7_) goto LA8_;
		eqdestroy___pureZhttpcore_u414((&(*(*dest_p0))));
		nimRawDispose((*dest_p0), ((NI)8));
	}
LA8_: ;
	(*dest_p0) = src_p1;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___pureZhttpcore_u34)(tyEnum_HttpMethod__8E0cnqA4t7LOGc109a8NMBg e_p0) {
	NimStringV2 result;
	switch (e_p0) {
	case ((tyEnum_HttpMethod__8E0cnqA4t7LOGc109a8NMBg)0):
	{
		result = TM__Evu9b2R1utZubyCikahWx1g_5;
	}
	break;
	case ((tyEnum_HttpMethod__8E0cnqA4t7LOGc109a8NMBg)1):
	{
		result = TM__Evu9b2R1utZubyCikahWx1g_7;
	}
	break;
	case ((tyEnum_HttpMethod__8E0cnqA4t7LOGc109a8NMBg)2):
	{
		result = TM__Evu9b2R1utZubyCikahWx1g_9;
	}
	break;
	case ((tyEnum_HttpMethod__8E0cnqA4t7LOGc109a8NMBg)3):
	{
		result = TM__Evu9b2R1utZubyCikahWx1g_11;
	}
	break;
	case ((tyEnum_HttpMethod__8E0cnqA4t7LOGc109a8NMBg)4):
	{
		result = TM__Evu9b2R1utZubyCikahWx1g_13;
	}
	break;
	case ((tyEnum_HttpMethod__8E0cnqA4t7LOGc109a8NMBg)5):
	{
		result = TM__Evu9b2R1utZubyCikahWx1g_15;
	}
	break;
	case ((tyEnum_HttpMethod__8E0cnqA4t7LOGc109a8NMBg)6):
	{
		result = TM__Evu9b2R1utZubyCikahWx1g_17;
	}
	break;
	case ((tyEnum_HttpMethod__8E0cnqA4t7LOGc109a8NMBg)7):
	{
		result = TM__Evu9b2R1utZubyCikahWx1g_19;
	}
	break;
	case ((tyEnum_HttpMethod__8E0cnqA4t7LOGc109a8NMBg)8):
	{
		result = TM__Evu9b2R1utZubyCikahWx1g_21;
	}
	break;
	default:
	{
		result = TM__Evu9b2R1utZubyCikahWx1g_23;
	}
	break;
	}
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq___pureZhttpcore_u3178)(tyObject_HttpHeaderscolonObjectType___q5RmldX8ngqdFdLFcD77Rw* headers_p0, NimStringV2 key_p1, tySequence__sM4lkSb7zS6F7OVMvW9cffQ value_p2) {
NIM_BOOL* nimErr_;
	nimfr_("[]=", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/pure/httpcore.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(189, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/pure/httpcore.nim");	{
		NI T3_;
		NimStringV2 colontmpD_;
		tySequence__sM4lkSb7zS6F7OVMvW9cffQ colontmpD__2;
		T3_ = value_p2.len;
		if (!(((NI)0) < T3_)) goto LA4_;
		colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
		nimln_(190);		colontmpD_ = toCaseInsensitive__pureZhttpcore_u110(headers_p0, key_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
		nimlf_(2219, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system.nim");		eqcopy___system_u5660((&colontmpD__2), value_p2);
		nimlf_(190, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/pure/httpcore.nim");		X5BX5Deq___pureZhttpcore_u1183((*headers_p0).table, colontmpD_, colontmpD__2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimlf_(394, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system.nim");		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}
	goto LA1_;
LA4_: ;
	{
		NimStringV2 colontmpD__3;
		colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
		nimlf_(192, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/pure/httpcore.nim");		colontmpD__3 = toCaseInsensitive__pureZhttpcore_u110(headers_p0, key_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		del__pureZhttpcore_u3263((*headers_p0).table, colontmpD__3);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimlf_(394, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system.nim");		if (colontmpD__3.p && !(colontmpD__3.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__3.p);
}
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, del__pureZhttpcore_u3870)(tyObject_HttpHeaderscolonObjectType___q5RmldX8ngqdFdLFcD77Rw* headers_p0, NimStringV2 key_p1) {
	NimStringV2 colontmpD_;
NIM_BOOL* nimErr_;
	nimfr_("del", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/pure/httpcore.nim");
{nimErr_ = nimErrorFlag();
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	nimlf_(204, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/pure/httpcore.nim");	colontmpD_ = toCaseInsensitive__pureZhttpcore_u110(headers_p0, key_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	del__pureZhttpcore_u3263((*headers_p0).table, colontmpD_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimlf_(394, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system.nim");	if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2) {
	int result;
	result = memcmp(a_p0, b_p1, ((size_t) (size_p2)));
	return result;
}
static N_INLINE(NIM_BOOL, equalMem__system_u1763)(void* a_p0, void* b_p1, NI size_p2) {
	NIM_BOOL result;
	int T1_;
	T1_ = (int)0;
	T1_ = nimCmpMem(a_p0, b_p1, size_p2);
	result = (T1_ == ((NI32)0));
	return result;
}
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1) {
	NIM_BOOL result;
	NI alen_1;
	NI blen_1;
	nimfr_("eqStrings", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/strmantle.nim");
{	nimlf_(33, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/strmantle.nim");	result = NIM_FALSE;
	nimln_(34);	alen_1 = a_p0.len;
	nimln_(35);	blen_1 = b_p1.len;
	nimln_(36);	{
		if (!(alen_1 == blen_1)) goto LA3_;
		nimln_(37);		{
			if (!(alen_1 == ((NI)0))) goto LA7_;
			nimln_(32);			nimln_(37);			result = NIM_TRUE;
			goto BeforeRet_;
		}
LA7_: ;
		nimln_(38);		nimln_(32);		nimln_(38);		result = equalMem__system_u1763(((void*) ((&a_p0.p->data[((NI)0)]))), ((void*) ((&b_p1.p->data[((NI)0)]))), (alen_1));
		goto BeforeRet_;
	}
LA3_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, contains__pureZhttpcore_u3928)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ values_p0, NimStringV2 value_p1) {
	NIM_BOOL result;
NIM_BOOL* nimErr_;
	nimfr_("contains", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/pure/httpcore.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(215, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/pure/httpcore.nim");	result = NIM_FALSE;
	{
		NimStringV2* val_1;
		NI i_1;
		NI L_1;
		NI T2_;
		val_1 = (NimStringV2*)0;
		nimlf_(249, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/iterators.nim");		i_1 = ((NI)0);
		nimln_(250);		T2_ = values_p0.len;
		L_1 = T2_;
		{
			nimln_(251);			while (1) {
				NimStringV2 colontmpD_;
				NimStringV2 colontmpD__2;
				if (!(i_1 < L_1)) goto LA4;
				colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
				colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
				nimlf_(216, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/pure/httpcore.nim");				if (i_1 < 0 || i_1 >= values_p0.len){ raiseIndexError2(i_1,values_p0.len-1); goto LA5_;
				}
				val_1 = (&values_p0.p->data[i_1]);
				nimln_(217);				{
					colontmpD_ = nsuToLowerAsciiStr((*val_1));
					if (NIM_UNLIKELY(*nimErr_)) goto LA5_;
					colontmpD__2 = nsuToLowerAsciiStr(value_p1);
					if (NIM_UNLIKELY(*nimErr_)) goto LA5_;
					if (!eqStrings(colontmpD_, colontmpD__2)) goto LA8_;
					nimln_(212);					nimln_(217);					result = NIM_TRUE;
					nimlf_(394, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system.nim");					if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
					if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
					goto BeforeRet_;
				}
LA8_: ;
				nimlf_(13, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/iterators.nim");				i_1 += ((NI)1);
				nimln_(254);				{
					NI T12_;
					T12_ = values_p0.len;
					if (!!((T12_ == L_1))) goto LA13_;
					failedAssertImpl__stdZassertions_u95(TM__Evu9b2R1utZubyCikahWx1g_25);
					if (NIM_UNLIKELY(*nimErr_)) goto LA5_;
				}
LA13_: ;
				{
					LA5_:;
				}
				{
					nimlf_(394, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system.nim");					if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
					if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
				}
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			} LA4: ;
		}
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
