/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -fno-strict-aliasing -pthread -I/home/icarogdo/.nimble/pkgs2/bearssl-0.2.10-e53ab85b8c4c1ce3aa1f4eb251c0ab29e08d4972/bearssl/abi -I/home/icarogdo/.nimble/pkgs2/bearssl-0.2.10-e53ab85b8c4c1ce3aa1f4eb251c0ab29e08d4972/bearssl/abi/../csources/src/ -I/home/icarogdo/.nimble/pkgs2/bearssl-0.2.10-e53ab85b8c4c1ce3aa1f4eb251c0ab29e08d4972/bearssl/abi/../csources/inc/ -I/home/icarogdo/.nimble/pkgs2/bearssl-0.2.10-e53ab85b8c4c1ce3aa1f4eb251c0ab29e08d4972/bearssl/abi/../csources/tools/ -DBR_USE_UNIX_TIME=1 -DBR_USE_URANDOM=1 -DBR_LE_UNALIGNED=1 -DBR_64=1  -DBR_amd64=1 -DBR_INT128=1 -Wno-incompatible-pointer-types -I/usr/include/webkitgtk-4.1 -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/cloudproviders -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/glycin-2 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/atk-1.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/fribidi -I/usr/include/pixman-1 -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gio-unix-2.0 -I/usr/include/libsoup-3.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-6 -pthread   -I/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib -I/home/icarogdo/dev/macroobras-jazzy/app/macroobras/src -o /home/icarogdo/dev/macroobras-jazzy/app/macroobras/.nimcache/@popenssl.nim.c.o /home/icarogdo/dev/macroobras-jazzy/app/macroobras/.nimcache/@popenssl.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_LibraryError__mFRrgtH6YneJrrZNWIHf9cQ tyObject_LibraryError__mFRrgtH6YneJrrZNWIHf9cQ;
typedef struct tyObject_OSError__mgJw6oFbS4BLzYIO9ccv8FQ tyObject_OSError__mgJw6oFbS4BLzYIO9ccv8FQ;
typedef struct tyObject_CatchableError__kvV4Jp5z2ULaSZq53myi9ag tyObject_CatchableError__kvV4Jp5z2ULaSZq53myi9ag;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tySequence__UIJx6FJrflnhA9a3u1VF1vA tySequence__UIJx6FJrflnhA9a3u1VF1vA;
typedef struct tySequence__UIJx6FJrflnhA9a3u1VF1vA_Content tySequence__UIJx6FJrflnhA9a3u1VF1vA_Content;
typedef struct tyObject_SslStruct__RoEokPmVBr9cvvHDuS2fjew tyObject_SslStruct__RoEokPmVBr9cvvHDuS2fjew;
typedef struct tyObject_StackTraceEntry__UznwMnjUHK6AxZHnP9bMXEA tyObject_StackTraceEntry__UznwMnjUHK6AxZHnP9bMXEA;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tySequence__UIJx6FJrflnhA9a3u1VF1vA {
  NI len; tySequence__UIJx6FJrflnhA9a3u1VF1vA_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__UIJx6FJrflnhA9a3u1VF1vA trace;
	Exception* up;
};
struct tyObject_CatchableError__kvV4Jp5z2ULaSZq53myi9ag {
	Exception Sup;
};
struct tyObject_OSError__mgJw6oFbS4BLzYIO9ccv8FQ {
	tyObject_CatchableError__kvV4Jp5z2ULaSZq53myi9ag Sup;
	NI32 errorCode;
};
struct tyObject_LibraryError__mFRrgtH6YneJrrZNWIHf9cQ {
	tyObject_OSError__mgJw6oFbS4BLzYIO9ccv8FQ Sup;
};
typedef N_CDECL_PTR(int, tyProc__bj29cdE9aA9bshc5NUghhGaWw) (NU64 opts_p0, NU8 settings_p1);
typedef N_CDECL_PTR(int, tyProc__u0PsAQN5ndneEiWxnCoc9aw) (void);
typedef N_CDECL_PTR(void, tyProc__ln4kdL5W9bbX4a1xl8nnVXQ) (void);
typedef N_CDECL_PTR(NI, tyProc__1moENrYD5tFKVHdbrK2Heg) (tyObject_SslStruct__RoEokPmVBr9cvvHDuS2fjew* ssl_p0, int cmd_p1, NI larg_p2, void* parg_p3);
typedef N_CDECL_PTR(int, tyProc__UtOqI0ZkblBIu9btVw6gCWw) (tyObject_SslStruct__RoEokPmVBr9cvvHDuS2fjew* ssl_p0);
typedef N_CDECL_PTR(int, tyProc__s4vzCIUdrW34nq0jAV5eYA) (tyObject_SslStruct__RoEokPmVBr9cvvHDuS2fjew* s_p0, int ret_code_p1);
typedef N_CDECL_PTR(unsigned long, tyProc__Zp8a7gsqfDHPKe06nErJjg) (void);
typedef N_CDECL_PTR(NCSTRING, tyProc__HE9clvqwtdfVXvgz4Z0y1cw) (unsigned long e_p0, NCSTRING buf_p1);
typedef N_CDECL_PTR(tyObject_SslStruct__RoEokPmVBr9cvvHDuS2fjew*, tyProc__XolGP5GhNzMBqZoTFFraQg) (tyObject_SslStruct__RoEokPmVBr9cvvHDuS2fjew* ssl_p0);
struct tyObject_SslStruct__RoEokPmVBr9cvvHDuS2fjew {
	char dummy;
};
typedef N_CDECL_PTR(int, tyProc__k2mwfQqK5hf649av9aEy6UTw) (tyObject_SslStruct__RoEokPmVBr9cvvHDuS2fjew* cert_p0, NCSTRING name_p1, int namelen_p2, unsigned int flags_p3, NCSTRING peername_p4);
typedef N_CDECL_PTR(void, tyProc__RCaJyw9a9ctK8XohyBKi8bHw) (tyObject_SslStruct__RoEokPmVBr9cvvHDuS2fjew* cert_p0);
typedef N_CDECL_PTR(tyObject_SslStruct__RoEokPmVBr9cvvHDuS2fjew*, tyProc__Y7QUkO1nk1DNA9b7LGGYtyQ) (void);
typedef N_CDECL_PTR(int, tyProc__ZPts6i9cfNix9chUrKa0HF9cQ) (tyObject_SslStruct__RoEokPmVBr9cvvHDuS2fjew* s_p0, NCSTRING ciphers_p1);
typedef N_CDECL_PTR(long, tyProc__cpabs4aa3ecbY9bS4SKZ1dQ) (tyObject_SslStruct__RoEokPmVBr9cvvHDuS2fjew* ctx_p0, int cmd_p1, long larg_p2, void* parg_p3);
typedef N_CDECL_PTR(NI, tyProc__aF4y9aPKIi8D4VGrVvX011Q) (NI a_p0, void* b_p1);
typedef N_CDECL_PTR(void, tyProc__2j0TTzVJ9a9cEDxsWAx4Kp4A) (tyObject_SslStruct__RoEokPmVBr9cvvHDuS2fjew* s_p0, NI mode_p1, tyProc__aF4y9aPKIi8D4VGrVvX011Q cb_p2);
typedef N_STDCALL_PTR(int, tyProc__6maZ6QUdZ03gNCZayireMg) (tyObject_SslStruct__RoEokPmVBr9cvvHDuS2fjew* ctx_p0, NCSTRING filename_p1);
typedef N_CDECL_PTR(int, tyProc__kY8HHYDGX8ujDZ0VNhR8oA) (tyObject_SslStruct__RoEokPmVBr9cvvHDuS2fjew* ctx_p0, NCSTRING filename_p1, int typ_p2);
typedef N_CDECL_PTR(int, tyProc__kBpkyPG8KLZuxR9aU6SFubg) (tyObject_SslStruct__RoEokPmVBr9cvvHDuS2fjew* ctx_p0, NCSTRING CAfile_p1, NCSTRING CApath_p2);
typedef N_CDECL_PTR(int, tyProc__wGd67TAKmh8ASBusfOEIIQ) (tyObject_SslStruct__RoEokPmVBr9cvvHDuS2fjew* ssl_p0, NCSTRING buf_p1, NI num_p2);
typedef N_CDECL_PTR(int, tyProc__4URUeKrPaJERpY9cYSDW0cA) (tyObject_SslStruct__RoEokPmVBr9cvvHDuS2fjew* ssl_p0, void* buf_p1, NI num_p2);
struct tyObject_StackTraceEntry__UznwMnjUHK6AxZHnP9bMXEA {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__UIJx6FJrflnhA9a3u1VF1vA_Content { NI cap; tyObject_StackTraceEntry__UznwMnjUHK6AxZHnP9bMXEA data[SEQ_DECL_SIZE]; };
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4511)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void*, sslSymNullable__wrappersZopenssl_u193)(NimStringV2 name_p0, NimStringV2 alternativeName_p1);
N_LIB_PRIVATE N_NIMCALL(void*, symNullable__wrappersZopenssl_u187)(void* dll_p0, NimStringV2 name_p1, NimStringV2 alternativeName_p2);
N_LIB_PRIVATE N_NIMCALL(void*, symAddr__pureZdynlib_u74)(void* lib_p0, NCSTRING name_p1);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0);
static N_INLINE(void*, thisModule__wrappersZopenssl_u177)(void);
N_LIB_PRIVATE N_NIMCALL(void*, loadLib__pureZdynlib_u6)(void);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void*, sslModule__wrappersZopenssl_u180)(void);
N_LIB_PRIVATE N_NIMCALL(void*, loadLibPattern__pureZdynlib_u93)(NimStringV2 pattern_p0, NIM_BOOL globalSymbols_p1);
N_LIB_PRIVATE N_NIMCALL(void, raiseDefect)(void);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
static N_INLINE(void, popCurrentException)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u3737)(Exception** dest_p0, Exception* src_p1, NIM_BOOL cyclic_p2);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e_p0, NCSTRING ename_p1, NCSTRING procname_p2, NCSTRING filename_p3, NI line_p4);
N_LIB_PRIVATE N_NIMCALL(void*, sslSymThrows__wrappersZopenssl_u197)(NimStringV2 name_p0, NimStringV2 alternativeName_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseInvalidLibrary__pureZdynlib_u9)(NCSTRING name_p0);
static N_INLINE(void*, utilModule__wrappersZopenssl_u184)(void);
N_LIB_PRIVATE N_NIMCALL(void*, nimLoadLibrary)(NimStringV2 path_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimLoadLibraryError)(NimStringV2 path_p0);
N_LIB_PRIVATE N_NIMCALL(void*, nimGetProcAddr)(void* lib_p0, NCSTRING name_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_SslStruct__RoEokPmVBr9cvvHDuS2fjew*, loadPSSLMethod__wrappersZopenssl_u205)(NimStringV2 method1_p0, NimStringV2 method2_p1);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space_p0);
N_LIB_PRIVATE N_NIMCALL(void*, utilSymNullable__wrappersZopenssl_u201)(NimStringV2 name_p0, NimStringV2 alternativeName_p1);
static const struct {
  NI cap; NIM_CHAR data[94+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_2 = { 94 | NIM_STRLIT_FLAG, "libssl.so(.3|.1.1|.1.0.2|.1.0.1|.1.0.0|.0.9.9|.0.9.8|.48|.47|.46|.45|.44|.43|.41|.39|.38|.10|)" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_3 = {94, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_2};
extern TNimTypeV2 NTIv2__mFRrgtH6YneJrrZNWIHf9cQ_;
static const struct {
  NI cap; NIM_CHAR data[119+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_4 = { 119 | NIM_STRLIT_FLAG, "Could not load SSL using libssl.so(.3|.1.1|.1.0.2|.1.0.1|.1.0.0|.0.9.9|.0.9.8|.48|.47|.46|.45|.44|.43|.41|.39|.38|.10|)" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_5 = {119, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_4};
static const struct {
  NI cap; NIM_CHAR data[16+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_6 = { 16 | NIM_STRLIT_FLAG, "OPENSSL_init_ssl" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_7 = {16, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_6};
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_8 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_9 = {0, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_8};
static const struct {
  NI cap; NIM_CHAR data[16+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_10 = { 16 | NIM_STRLIT_FLAG, "SSL_library_init" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_11 = {16, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_10};
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_12 = {0, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_8};
static const struct {
  NI cap; NIM_CHAR data[22+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_13 = { 22 | NIM_STRLIT_FLAG, "SSL_load_error_strings" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_14 = {22, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_13};
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_15 = {0, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_8};
static const struct {
  NI cap; NIM_CHAR data[97+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_16 = { 97 | NIM_STRLIT_FLAG, "libcrypto.so(.3|.1.1|.1.0.2|.1.0.1|.1.0.0|.0.9.9|.0.9.8|.48|.47|.46|.45|.44|.43|.41|.39|.38|.10|)" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_17 = {97, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_16};
static const struct {
  NI cap; NIM_CHAR data[20+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_18 = { 20 | NIM_STRLIT_FLAG, "ERR_load_BIO_strings" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_19 = {20, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_18};
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_20 = {0, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_8};
static const struct {
  NI cap; NIM_CHAR data[31+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_21 = { 31 | NIM_STRLIT_FLAG, "OPENSSL_add_all_algorithms_conf" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_22 = {31, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_21};
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_23 = {0, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_8};
static const struct {
  NI cap; NIM_CHAR data[11+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_26 = { 11 | NIM_STRLIT_FLAG, "libssl.so.3" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_27 = {11, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_26};
static const struct {
  NI cap; NIM_CHAR data[13+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_29 = { 13 | NIM_STRLIT_FLAG, "libssl.so.1.1" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_30 = {13, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_29};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_32 = { 15 | NIM_STRLIT_FLAG, "libssl.so.1.0.2" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_33 = {15, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_32};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_35 = { 15 | NIM_STRLIT_FLAG, "libssl.so.1.0.1" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_36 = {15, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_35};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_38 = { 15 | NIM_STRLIT_FLAG, "libssl.so.1.0.0" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_39 = {15, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_38};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_41 = { 15 | NIM_STRLIT_FLAG, "libssl.so.0.9.9" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_42 = {15, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_41};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_44 = { 15 | NIM_STRLIT_FLAG, "libssl.so.0.9.8" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_45 = {15, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_44};
static const struct {
  NI cap; NIM_CHAR data[12+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_47 = { 12 | NIM_STRLIT_FLAG, "libssl.so.48" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_48 = {12, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_47};
static const struct {
  NI cap; NIM_CHAR data[12+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_50 = { 12 | NIM_STRLIT_FLAG, "libssl.so.47" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_51 = {12, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_50};
static const struct {
  NI cap; NIM_CHAR data[12+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_53 = { 12 | NIM_STRLIT_FLAG, "libssl.so.46" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_54 = {12, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_53};
static const struct {
  NI cap; NIM_CHAR data[12+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_56 = { 12 | NIM_STRLIT_FLAG, "libssl.so.45" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_57 = {12, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_56};
static const struct {
  NI cap; NIM_CHAR data[12+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_59 = { 12 | NIM_STRLIT_FLAG, "libssl.so.44" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_60 = {12, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_59};
static const struct {
  NI cap; NIM_CHAR data[12+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_62 = { 12 | NIM_STRLIT_FLAG, "libssl.so.43" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_63 = {12, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_62};
static const struct {
  NI cap; NIM_CHAR data[12+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_65 = { 12 | NIM_STRLIT_FLAG, "libssl.so.41" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_66 = {12, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_65};
static const struct {
  NI cap; NIM_CHAR data[12+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_68 = { 12 | NIM_STRLIT_FLAG, "libssl.so.39" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_69 = {12, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_68};
static const struct {
  NI cap; NIM_CHAR data[12+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_71 = { 12 | NIM_STRLIT_FLAG, "libssl.so.38" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_72 = {12, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_71};
static const struct {
  NI cap; NIM_CHAR data[12+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_74 = { 12 | NIM_STRLIT_FLAG, "libssl.so.10" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_75 = {12, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_74};
static const struct {
  NI cap; NIM_CHAR data[9+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_77 = { 9 | NIM_STRLIT_FLAG, "libssl.so" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_78 = {9, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_77};
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_79 = {94, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_2};
static const struct {
  NI cap; NIM_CHAR data[14+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_84 = { 14 | NIM_STRLIT_FLAG, "libcrypto.so.3" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_85 = {14, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_84};
static const struct {
  NI cap; NIM_CHAR data[16+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_87 = { 16 | NIM_STRLIT_FLAG, "libcrypto.so.1.1" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_88 = {16, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_87};
static const struct {
  NI cap; NIM_CHAR data[18+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_90 = { 18 | NIM_STRLIT_FLAG, "libcrypto.so.1.0.2" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_91 = {18, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_90};
static const struct {
  NI cap; NIM_CHAR data[18+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_93 = { 18 | NIM_STRLIT_FLAG, "libcrypto.so.1.0.1" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_94 = {18, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_93};
static const struct {
  NI cap; NIM_CHAR data[18+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_96 = { 18 | NIM_STRLIT_FLAG, "libcrypto.so.1.0.0" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_97 = {18, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_96};
static const struct {
  NI cap; NIM_CHAR data[18+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_99 = { 18 | NIM_STRLIT_FLAG, "libcrypto.so.0.9.9" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_100 = {18, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_99};
static const struct {
  NI cap; NIM_CHAR data[18+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_102 = { 18 | NIM_STRLIT_FLAG, "libcrypto.so.0.9.8" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_103 = {18, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_102};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_105 = { 15 | NIM_STRLIT_FLAG, "libcrypto.so.48" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_106 = {15, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_105};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_108 = { 15 | NIM_STRLIT_FLAG, "libcrypto.so.47" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_109 = {15, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_108};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_111 = { 15 | NIM_STRLIT_FLAG, "libcrypto.so.46" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_112 = {15, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_111};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_114 = { 15 | NIM_STRLIT_FLAG, "libcrypto.so.45" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_115 = {15, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_114};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_117 = { 15 | NIM_STRLIT_FLAG, "libcrypto.so.44" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_118 = {15, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_117};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_120 = { 15 | NIM_STRLIT_FLAG, "libcrypto.so.43" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_121 = {15, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_120};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_123 = { 15 | NIM_STRLIT_FLAG, "libcrypto.so.41" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_124 = {15, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_123};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_126 = { 15 | NIM_STRLIT_FLAG, "libcrypto.so.39" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_127 = {15, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_126};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_129 = { 15 | NIM_STRLIT_FLAG, "libcrypto.so.38" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_130 = {15, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_129};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_132 = { 15 | NIM_STRLIT_FLAG, "libcrypto.so.10" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_133 = {15, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_132};
static const struct {
  NI cap; NIM_CHAR data[12+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_135 = { 12 | NIM_STRLIT_FLAG, "libcrypto.so" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_136 = {12, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_135};
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_137 = {97, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_16};
static const struct {
  NI cap; NIM_CHAR data[24+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_148 = { 24 | NIM_STRLIT_FLAG, "SSL_get_peer_certificate" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_149 = {24, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_148};
static const struct {
  NI cap; NIM_CHAR data[25+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_150 = { 25 | NIM_STRLIT_FLAG, "SSL_get1_peer_certificate" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_151 = {25, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_150};
static const struct {
  NI cap; NIM_CHAR data[68+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_152 = { 68 | NIM_STRLIT_FLAG, "Could not load SSL_get_peer_certificate or SSL_get1_peer_certificate" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_153 = {68, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_152};
static const struct {
  NI cap; NIM_CHAR data[11+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_158 = { 11 | NIM_STRLIT_FLAG, "SSL_in_init" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_159 = {11, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_158};
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_160 = {0, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_8};
static const struct {
  NI cap; NIM_CHAR data[9+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_161 = { 9 | NIM_STRLIT_FLAG, "SSL_state" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_162 = {9, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_161};
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_163 = {0, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_8};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_168 = { 15 | NIM_STRLIT_FLAG, "Could not load " };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_169 = {15, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_168};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_170 = { 5 | NIM_STRLIT_FLAG, " nor " };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_171 = {5, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_170};
static const struct {
  NI cap; NIM_CHAR data[10+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_172 = { 10 | NIM_STRLIT_FLAG, "TLS_method" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_173 = {10, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_172};
static const struct {
  NI cap; NIM_CHAR data[13+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_174 = { 13 | NIM_STRLIT_FLAG, "SSLv23_method" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_175 = {13, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_174};
static const struct {
  NI cap; NIM_CHAR data[19+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_180 = { 19 | NIM_STRLIT_FLAG, "OpenSSL_version_num" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_181 = {19, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_180};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_182 = { 6 | NIM_STRLIT_FLAG, "SSLeay" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_183 = {6, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_182};
static const struct {
  NI cap; NIM_CHAR data[24+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_184 = { 24 | NIM_STRLIT_FLAG, "SSL_CTX_set_ciphersuites" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_185 = {24, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_184};
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_186 = {0, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_8};
extern NIM_THREADVAR TFrame* framePtr__system_u2809;
N_LIB_PRIVATE void* thisMod__wrappersZopenssl_u179;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4293;
N_LIB_PRIVATE void* sslMod__wrappersZopenssl_u182;
extern NIM_THREADVAR Exception* currException__system_u3704;
N_LIB_PRIVATE void* utilMod__wrappersZopenssl_u186;
static void* TM__SLGpYVEqpFQ7VaPsJH6HIA_24;
tyProc__1moENrYD5tFKVHdbrK2Heg Dl_2097152674_;
static void* TM__SLGpYVEqpFQ7VaPsJH6HIA_82;
tyProc__ln4kdL5W9bbX4a1xl8nnVXQ Dl_2097152766_;
tyProc__UtOqI0ZkblBIu9btVw6gCWw Dl_2097152545_;
tyProc__s4vzCIUdrW34nq0jAV5eYA Dl_2097152555_;
tyProc__Zp8a7gsqfDHPKe06nErJjg Dl_2097152602_;
tyProc__HE9clvqwtdfVXvgz4Z0y1cw Dl_2097152598_;
tyProc__k2mwfQqK5hf649av9aEy6UTw Dl_2097153085_;
tyProc__RCaJyw9a9ctK8XohyBKi8bHw Dl_2097153091_;
N_LIB_PRIVATE tyProc__UtOqI0ZkblBIu9btVw6gCWw theProc__wrappersZopenssl_u415;
N_LIB_PRIVATE tyProc__UtOqI0ZkblBIu9btVw6gCWw sslState__wrappersZopenssl_u418;
tyProc__UtOqI0ZkblBIu9btVw6gCWw Dl_2097152538_;
tyProc__RCaJyw9a9ctK8XohyBKi8bHw Dl_2097152476_;
tyProc__XolGP5GhNzMBqZoTFFraQg Dl_2097152489_;
tyProc__ZPts6i9cfNix9chUrKa0HF9cQ Dl_2097152506_;
N_LIB_PRIVATE tyProc__ZPts6i9cfNix9chUrKa0HF9cQ theProc__wrappersZopenssl_u451;
tyProc__cpabs4aa3ecbY9bS4SKZ1dQ Dl_2097152661_;
tyProc__2j0TTzVJ9a9cEDxsWAx4Kp4A Dl_2097152497_;
tyProc__6maZ6QUdZ03gNCZayireMg Dl_2097152513_;
tyProc__kY8HHYDGX8ujDZ0VNhR8oA Dl_2097152516_;
tyProc__UtOqI0ZkblBIu9btVw6gCWw Dl_2097152520_;
tyProc__kBpkyPG8KLZuxR9aU6SFubg Dl_2097152491_;
tyProc__wGd67TAKmh8ASBusfOEIIQ Dl_2097152551_;
tyProc__4URUeKrPaJERpY9cYSDW0cA Dl_2097152547_;
tyProc__UtOqI0ZkblBIu9btVw6gCWw Dl_2097152560_;
tyProc__XolGP5GhNzMBqZoTFFraQg Dl_2097152474_;
tyProc__s4vzCIUdrW34nq0jAV5eYA Dl_2097152535_;
tyProc__UtOqI0ZkblBIu9btVw6gCWw Dl_2097152558_;
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2809 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2809).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2809;
	framePtr__system_u2809 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4511();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2809 = (*framePtr__system_u2809).prev;
}
N_LIB_PRIVATE N_NIMCALL(void, CRYPTO_malloc_init__wrappersZopenssl_u660)(void) {
	nimfr_("CRYPTO_malloc_init", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/wrappers/openssl.nim");
	popFrame();
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0) {
	NCSTRING result;
	{
		if (!(s_p0.len == ((NI)0))) goto LA3_;
		result = "";
	}
	goto LA1_;
LA3_: ;
	{
		result = ((NCSTRING) ((*s_p0.p).data));
	}
LA1_: ;
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4293);
	return result;
}
static N_INLINE(void*, thisModule__wrappersZopenssl_u177)(void) {
	void* result;
NIM_BOOL* nimErr_;
	nimfr_("thisModule", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/wrappers/openssl.nim");
{nimErr_ = nimErrorFlag();
	result = (void*)0;
	nimlf_(344, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/wrappers/openssl.nim");	{
		void* T5_;
		if (!(thisMod__wrappersZopenssl_u179 == 0)) goto LA3_;
		T5_ = (void*)0;
		T5_ = loadLib__pureZdynlib_u6();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		thisMod__wrappersZopenssl_u179 = T5_;
	}
LA3_: ;
	nimln_(346);	result = thisMod__wrappersZopenssl_u179;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void*, symNullable__wrappersZopenssl_u187)(void* dll_p0, NimStringV2 name_p1, NimStringV2 alternativeName_p2) {
	void* result;
NIM_BOOL* nimErr_;
	nimfr_("symNullable", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/wrappers/openssl.nim");
{nimErr_ = nimErrorFlag();
	result = (void*)0;
	nimln_(365);	{
		if (!!((dll_p0 == 0))) goto LA3_;
		nimln_(366);		result = symAddr__pureZdynlib_u74(dll_p0, nimToCStringConv(name_p1));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(367);		{
			NIM_BOOL T7_;
			T7_ = (NIM_BOOL)0;
			T7_ = (result == 0);
			if (!(T7_)) goto LA8_;
			T7_ = (((NI)0) < alternativeName_p2.len);
LA8_: ;
			if (!T7_) goto LA9_;
			nimln_(368);			result = symAddr__pureZdynlib_u74(dll_p0, nimToCStringConv(alternativeName_p2));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA9_: ;
	}
	goto LA1_;
LA3_: ;
	{
		nimln_(370);		result = NIM_NIL;
	}
LA1_: ;
	nimln_(373);	{
		void* thisDynlib_1;
		if (!(result == 0)) goto LA14_;
		nimln_(374);		thisDynlib_1 = thisModule__wrappersZopenssl_u177();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(375);		{
			if (!(thisDynlib_1 == 0)) goto LA18_;
			nimln_(363);			nimln_(375);			result = NIM_NIL;
			goto BeforeRet_;
		}
LA18_: ;
		nimln_(376);		result = symAddr__pureZdynlib_u74(thisDynlib_1, nimToCStringConv(name_p1));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(377);		{
			NIM_BOOL T22_;
			T22_ = (NIM_BOOL)0;
			T22_ = (result == 0);
			if (!(T22_)) goto LA23_;
			T22_ = (((NI)0) < alternativeName_p2.len);
LA23_: ;
			if (!T22_) goto LA24_;
			nimln_(378);			result = symAddr__pureZdynlib_u74(thisDynlib_1, nimToCStringConv(alternativeName_p2));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA24_: ;
	}
LA14_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, popCurrentException)(void) {
	eqcopy___system_u3737(&currException__system_u3704, (*currException__system_u3704).up, NIM_FALSE);
}
static N_INLINE(void*, sslModule__wrappersZopenssl_u180)(void) {
	void* result;
NIM_BOOL* nimErr_;
	nimfr_("sslModule", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/wrappers/openssl.nim");
{nimErr_ = nimErrorFlag();
	result = (void*)0;
	nimln_(351);	{
		void* T6_;
		if (!(sslMod__wrappersZopenssl_u182 == 0)) goto LA4_;
		T6_ = (void*)0;
		T6_ = loadLibPattern__pureZdynlib_u93(TM__SLGpYVEqpFQ7VaPsJH6HIA_3, NIM_FALSE);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		sslMod__wrappersZopenssl_u182 = T6_;
	}
LA4_: ;
	if (NIM_UNLIKELY(*nimErr_)) {
		LA1_:;
		{
			tyObject_LibraryError__mFRrgtH6YneJrrZNWIHf9cQ* T10_;
			*nimErr_ = NIM_FALSE;
			nimln_(353);			raiseDefect();
			T10_ = NIM_NIL;
			T10_ = (tyObject_LibraryError__mFRrgtH6YneJrrZNWIHf9cQ*) nimNewObj(sizeof(tyObject_LibraryError__mFRrgtH6YneJrrZNWIHf9cQ), NIM_ALIGNOF(tyObject_LibraryError__mFRrgtH6YneJrrZNWIHf9cQ));
			(*T10_).Sup.Sup.Sup.Sup.m_type = (&NTIv2__mFRrgtH6YneJrrZNWIHf9cQ_);
			(*T10_).Sup.Sup.Sup.name = "LibraryError";
			(*T10_).Sup.Sup.Sup.message = TM__SLGpYVEqpFQ7VaPsJH6HIA_5;
			(*T10_).Sup.Sup.Sup.parent = ((Exception*) NIM_NIL);
			popCurrentException();
			raiseExceptionEx((Exception*)T10_, "LibraryError", "sslModule", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/wrappers/openssl.nim", 353);
goto LA8_;
			popCurrentException();
			LA8_:;
		}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(355);	result = sslMod__wrappersZopenssl_u182;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void*, sslSymNullable__wrappersZopenssl_u193)(NimStringV2 name_p0, NimStringV2 alternativeName_p1) {
	void* result;
	void* T1_;
NIM_BOOL* nimErr_;
	nimfr_("sslSymNullable", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/wrappers/openssl.nim");
{nimErr_ = nimErrorFlag();
	result = (void*)0;
	nimln_(381);	T1_ = (void*)0;
	T1_ = sslModule__wrappersZopenssl_u180();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = symNullable__wrappersZopenssl_u187(T1_, name_p0, alternativeName_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void*, sslSymThrows__wrappersZopenssl_u197)(NimStringV2 name_p0, NimStringV2 alternativeName_p1) {
	void* result;
NIM_BOOL* nimErr_;
	nimfr_("sslSymThrows", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/wrappers/openssl.nim");
{nimErr_ = nimErrorFlag();
	result = (void*)0;
	nimln_(384);	result = sslSymNullable__wrappersZopenssl_u193(name_p0, alternativeName_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(385);	{
		if (!(result == 0)) goto LA3_;
		raiseInvalidLibrary__pureZdynlib_u9(nimToCStringConv(name_p0));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA3_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(int, SSL_library_init__wrappersZopenssl_u282)(void) {
	int result;
	void* newInitSym_1;
	tyProc__u0PsAQN5ndneEiWxnCoc9aw olderProc_1;
	void* T5_;
NIM_BOOL* nimErr_;
	nimfr_("SSL_library_init", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/wrappers/openssl.nim");
{nimErr_ = nimErrorFlag();
	nimln_(407);	result = ((int)0);
	nimln_(408);	newInitSym_1 = sslSymNullable__wrappersZopenssl_u193(TM__SLGpYVEqpFQ7VaPsJH6HIA_7, TM__SLGpYVEqpFQ7VaPsJH6HIA_9);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(409);	{
		tyProc__bj29cdE9aA9bshc5NUghhGaWw newInitProc_1;
		if (!!((newInitSym_1 == 0))) goto LA3_;
		nimln_(410);		newInitProc_1 = ((tyProc__bj29cdE9aA9bshc5NUghhGaWw) (newInitSym_1));
		nimln_(412);		nimln_(404);		nimln_(412);		result = newInitProc_1(0ULL, ((NU8)0));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
	}
LA3_: ;
	nimln_(413);	T5_ = (void*)0;
	T5_ = sslSymThrows__wrappersZopenssl_u197(TM__SLGpYVEqpFQ7VaPsJH6HIA_11, TM__SLGpYVEqpFQ7VaPsJH6HIA_12);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	olderProc_1 = ((tyProc__u0PsAQN5ndneEiWxnCoc9aw) (T5_));
	nimln_(414);	{
		if (!!((olderProc_1 == 0))) goto LA8_;
		result = olderProc_1();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA8_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, SSL_load_error_strings__wrappersZopenssl_u332)(void) {
	tyProc__ln4kdL5W9bbX4a1xl8nnVXQ theProc_1;
	void* T1_;
NIM_BOOL* nimErr_;
	nimfr_("SSL_load_error_strings", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/wrappers/openssl.nim");
{nimErr_ = nimErrorFlag();
	nimln_(418);	T1_ = (void*)0;
	T1_ = sslSymNullable__wrappersZopenssl_u193(TM__SLGpYVEqpFQ7VaPsJH6HIA_14, TM__SLGpYVEqpFQ7VaPsJH6HIA_15);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	theProc_1 = ((tyProc__ln4kdL5W9bbX4a1xl8nnVXQ) (T1_));
	nimln_(419);	{
		if (!!((theProc_1 == 0))) goto LA4_;
		theProc_1();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA4_: ;
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(void*, utilModule__wrappersZopenssl_u184)(void) {
	void* result;
NIM_BOOL* nimErr_;
	nimfr_("utilModule", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/wrappers/openssl.nim");
{nimErr_ = nimErrorFlag();
	result = (void*)0;
	nimln_(359);	{
		void* T5_;
		if (!(utilMod__wrappersZopenssl_u186 == 0)) goto LA3_;
		T5_ = (void*)0;
		T5_ = loadLibPattern__pureZdynlib_u93(TM__SLGpYVEqpFQ7VaPsJH6HIA_17, NIM_FALSE);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		utilMod__wrappersZopenssl_u186 = T5_;
	}
LA3_: ;
	nimln_(361);	result = utilMod__wrappersZopenssl_u186;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, ERR_load_BIO_strings__wrappersZopenssl_u357)(void) {
	tyProc__ln4kdL5W9bbX4a1xl8nnVXQ theProc_1;
	void* T1_;
	void* T2_;
NIM_BOOL* nimErr_;
	nimfr_("ERR_load_BIO_strings", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/wrappers/openssl.nim");
{nimErr_ = nimErrorFlag();
	nimln_(422);	T1_ = (void*)0;
	T1_ = utilModule__wrappersZopenssl_u184();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T2_ = (void*)0;
	T2_ = symNullable__wrappersZopenssl_u187(T1_, TM__SLGpYVEqpFQ7VaPsJH6HIA_19, TM__SLGpYVEqpFQ7VaPsJH6HIA_20);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	theProc_1 = ((tyProc__ln4kdL5W9bbX4a1xl8nnVXQ) (T2_));
	nimln_(423);	{
		if (!!((theProc_1 == 0))) goto LA5_;
		theProc_1();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA5_: ;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, OpenSSL_add_all_algorithms__wrappersZopenssl_u377)(void) {
	tyProc__ln4kdL5W9bbX4a1xl8nnVXQ theProc_1;
	void* T1_;
NIM_BOOL* nimErr_;
	nimfr_("OpenSSL_add_all_algorithms", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/wrappers/openssl.nim");
{nimErr_ = nimErrorFlag();
	nimln_(448);	T1_ = (void*)0;
	T1_ = sslSymNullable__wrappersZopenssl_u193(TM__SLGpYVEqpFQ7VaPsJH6HIA_22, TM__SLGpYVEqpFQ7VaPsJH6HIA_23);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	theProc_1 = ((tyProc__ln4kdL5W9bbX4a1xl8nnVXQ) (T1_));
	nimln_(449);	{
		if (!!((theProc_1 == 0))) goto LA4_;
		theProc_1();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA4_: ;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(NI, SSL_set_tlsext_host_name__wrappersZopenssl_u679)(tyObject_SslStruct__RoEokPmVBr9cvvHDuS2fjew* ssl_p0, NCSTRING name_p1) {
	NI result;
	nimfr_("SSL_set_tlsext_host_name", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/wrappers/openssl.nim");
	nimln_(614);	result = Dl_2097152674_(ssl_p0, ((int)55), ((NI)0), ((void*) (name_p1)));
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SslStruct__RoEokPmVBr9cvvHDuS2fjew*, SSL_get_peer_certificate__wrappersZopenssl_u1045)(tyObject_SslStruct__RoEokPmVBr9cvvHDuS2fjew* ssl_p0) {
	tyObject_SslStruct__RoEokPmVBr9cvvHDuS2fjew* result;
	void* methodSym_1;
	tyProc__XolGP5GhNzMBqZoTFFraQg method2Proc_1;
NIM_BOOL* nimErr_;
	nimfr_("SSL_get_peer_certificate", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/wrappers/openssl.nim");
{nimErr_ = nimErrorFlag();
	result = (tyObject_SslStruct__RoEokPmVBr9cvvHDuS2fjew*)0;
	nimln_(850);	methodSym_1 = sslSymNullable__wrappersZopenssl_u193(TM__SLGpYVEqpFQ7VaPsJH6HIA_149, TM__SLGpYVEqpFQ7VaPsJH6HIA_151);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(851);	{
		tyObject_LibraryError__mFRrgtH6YneJrrZNWIHf9cQ* T5_;
		if (!(methodSym_1 == 0)) goto LA3_;
		T5_ = NIM_NIL;
		T5_ = (tyObject_LibraryError__mFRrgtH6YneJrrZNWIHf9cQ*) nimNewObj(sizeof(tyObject_LibraryError__mFRrgtH6YneJrrZNWIHf9cQ), NIM_ALIGNOF(tyObject_LibraryError__mFRrgtH6YneJrrZNWIHf9cQ));
		(*T5_).Sup.Sup.Sup.Sup.m_type = (&NTIv2__mFRrgtH6YneJrrZNWIHf9cQ_);
		(*T5_).Sup.Sup.Sup.name = "LibraryError";
		(*T5_).Sup.Sup.Sup.message = TM__SLGpYVEqpFQ7VaPsJH6HIA_153;
		(*T5_).Sup.Sup.Sup.parent = ((Exception*) NIM_NIL);
		nimln_(852);		raiseExceptionEx((Exception*)T5_, "LibraryError", "SSL_get_peer_certificate", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/wrappers/openssl.nim", 852);
goto BeforeRet_;
	}
LA3_: ;
	nimln_(853);	method2Proc_1 = ((tyProc__XolGP5GhNzMBqZoTFFraQg) (methodSym_1));
	nimln_(854);	nimln_(849);	nimln_(854);	result = method2Proc_1(ssl_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(int, SSL_in_init__wrappersZopenssl_u409)(tyObject_SslStruct__RoEokPmVBr9cvvHDuS2fjew* ssl_p0) {
	int result;
NIM_BOOL* nimErr_;
	nimfr_("SSL_in_init", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/wrappers/openssl.nim");
{nimErr_ = nimErrorFlag();
	result = (int)0;
	nimln_(466);	{
		if (!!((theProc__wrappersZopenssl_u415 == 0))) goto LA3_;
		nimln_(467);		result = theProc__wrappersZopenssl_u415(ssl_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA1_;
LA3_: ;
	{
		int T8_;
		nimln_(468);		if (!!((sslState__wrappersZopenssl_u418 == 0))) goto LA6_;
		nimln_(469);		T8_ = (int)0;
		T8_ = sslState__wrappersZopenssl_u418(ssl_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		result = (NI32)(T8_ & ((NI32)12288));
	}
	goto LA1_;
LA6_: ;
	{
		nimln_(471);		raiseInvalidLibrary__pureZdynlib_u9("SSL_in_init");
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
	{
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		copyMem__system_u1755(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		(*dest_p0).len += src_p1.len;
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SslStruct__RoEokPmVBr9cvvHDuS2fjew*, loadPSSLMethod__wrappersZopenssl_u205)(NimStringV2 method1_p0, NimStringV2 method2_p1) {
	tyObject_SslStruct__RoEokPmVBr9cvvHDuS2fjew* result;
	void* methodSym_1;
	tyProc__Y7QUkO1nk1DNA9b7LGGYtyQ method2Proc_1;
NIM_BOOL* nimErr_;
	nimfr_("loadPSSLMethod", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/wrappers/openssl.nim");
{nimErr_ = nimErrorFlag();
	result = (tyObject_SslStruct__RoEokPmVBr9cvvHDuS2fjew*)0;
	nimln_(393);	methodSym_1 = sslSymNullable__wrappersZopenssl_u193(method1_p0, method2_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(394);	{
		tyObject_LibraryError__mFRrgtH6YneJrrZNWIHf9cQ* T5_;
		NimStringV2 T6_;
		if (!(methodSym_1 == 0)) goto LA3_;
		T5_ = NIM_NIL;
		T5_ = (tyObject_LibraryError__mFRrgtH6YneJrrZNWIHf9cQ*) nimNewObj(sizeof(tyObject_LibraryError__mFRrgtH6YneJrrZNWIHf9cQ), NIM_ALIGNOF(tyObject_LibraryError__mFRrgtH6YneJrrZNWIHf9cQ));
		(*T5_).Sup.Sup.Sup.Sup.m_type = (&NTIv2__mFRrgtH6YneJrrZNWIHf9cQ_);
		(*T5_).Sup.Sup.Sup.name = "LibraryError";
		nimln_(395);		T6_.len = 0; T6_.p = NIM_NIL;
		T6_ = rawNewString(method1_p0.len + method2_p1.len + 20);
appendString((&T6_), TM__SLGpYVEqpFQ7VaPsJH6HIA_169);
appendString((&T6_), method1_p0);
appendString((&T6_), TM__SLGpYVEqpFQ7VaPsJH6HIA_171);
appendString((&T6_), method2_p1);
		(*T5_).Sup.Sup.Sup.message = T6_;
		(*T5_).Sup.Sup.Sup.parent = ((Exception*) NIM_NIL);
		raiseExceptionEx((Exception*)T5_, "LibraryError", "loadPSSLMethod", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/wrappers/openssl.nim", 395);
goto BeforeRet_;
	}
LA3_: ;
	nimln_(397);	method2Proc_1 = ((tyProc__Y7QUkO1nk1DNA9b7LGGYtyQ) (methodSym_1));
	nimln_(398);	nimln_(390);	nimln_(398);	result = method2Proc_1();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SslStruct__RoEokPmVBr9cvvHDuS2fjew*, TLS_method__wrappersZopenssl_u371)(void) {
	tyObject_SslStruct__RoEokPmVBr9cvvHDuS2fjew* result;
NIM_BOOL* nimErr_;
	nimfr_("TLS_method", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/wrappers/openssl.nim");
{nimErr_ = nimErrorFlag();
	result = (tyObject_SslStruct__RoEokPmVBr9cvvHDuS2fjew*)0;
	nimln_(438);	result = loadPSSLMethod__wrappersZopenssl_u205(TM__SLGpYVEqpFQ7VaPsJH6HIA_173, TM__SLGpYVEqpFQ7VaPsJH6HIA_175);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void*, utilSymNullable__wrappersZopenssl_u201)(NimStringV2 name_p0, NimStringV2 alternativeName_p1) {
	void* result;
	void* T1_;
NIM_BOOL* nimErr_;
	nimfr_("utilSymNullable", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/wrappers/openssl.nim");
{nimErr_ = nimErrorFlag();
	result = (void*)0;
	nimln_(388);	T1_ = (void*)0;
	T1_ = utilModule__wrappersZopenssl_u184();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = symNullable__wrappersZopenssl_u187(T1_, name_p0, alternativeName_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(unsigned long, getOpenSSLVersion__wrappersZopenssl_u383)(void) {
	unsigned long result;
	tyProc__Zp8a7gsqfDHPKe06nErJjg theProc_1;
	void* T1_;
	unsigned long T2_;
NIM_BOOL* nimErr_;
	nimfr_("getOpenSSLVersion", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/wrappers/openssl.nim");
{nimErr_ = nimErrorFlag();
	result = (unsigned long)0;
	nimln_(453);	T1_ = (void*)0;
	T1_ = utilSymNullable__wrappersZopenssl_u201(TM__SLGpYVEqpFQ7VaPsJH6HIA_181, TM__SLGpYVEqpFQ7VaPsJH6HIA_183);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	theProc_1 = ((tyProc__Zp8a7gsqfDHPKe06nErJjg) (T1_));
	T2_ = (unsigned long)0;
	nimln_(455);	{
		if (!(theProc_1 == 0)) goto LA5_;
		nimln_(454);		nimln_(455);		result = ((unsigned long)0);
	}
	goto LA3_;
LA5_: ;
	{
		nimln_(454);		nimln_(456);		result = theProc_1();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA3_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(int, SSL_CTX_set_ciphersuites__wrappersZopenssl_u444)(tyObject_SslStruct__RoEokPmVBr9cvvHDuS2fjew* ctx_p0, NCSTRING str_p1) {
	int result;
NIM_BOOL* nimErr_;
	nimfr_("SSL_CTX_set_ciphersuites", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/wrappers/openssl.nim");
{nimErr_ = nimErrorFlag();
	result = (int)0;
	nimln_(475);	{
		void* T5_;
		if (!(theProc__wrappersZopenssl_u451 == 0)) goto LA3_;
		nimln_(476);		T5_ = (void*)0;
		T5_ = sslSymThrows__wrappersZopenssl_u197(TM__SLGpYVEqpFQ7VaPsJH6HIA_185, TM__SLGpYVEqpFQ7VaPsJH6HIA_186);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		theProc__wrappersZopenssl_u451 = ((tyProc__ZPts6i9cfNix9chUrKa0HF9cQ) (T5_));
	}
LA3_: ;
	nimln_(477);	result = theProc__wrappersZopenssl_u451(ctx_p0, str_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, SSLCTXSetMode__wrappersZopenssl_u670)(tyObject_SslStruct__RoEokPmVBr9cvvHDuS2fjew* ctx_p0, NI mode_p1) {
	NI result;
	nimfr_("SSLCTXSetMode", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/wrappers/openssl.nim");
	nimln_(606);	result = Dl_2097152661_(ctx_p0, ((int)33), ((long) (mode_p1)), NIM_NIL);
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, atpopenssldotnim_Init000)(void) {
{
	TFrame FR_; FR_.len = 0;
	void* T100001_;
	void* T100002_;
	T100001_ = (void*)0;
	T100001_ = sslSymNullable__wrappersZopenssl_u193(TM__SLGpYVEqpFQ7VaPsJH6HIA_159, TM__SLGpYVEqpFQ7VaPsJH6HIA_160);
	theProc__wrappersZopenssl_u415 = ((tyProc__UtOqI0ZkblBIu9btVw6gCWw) (T100001_));
	T100002_ = (void*)0;
	T100002_ = sslSymNullable__wrappersZopenssl_u193(TM__SLGpYVEqpFQ7VaPsJH6HIA_162, TM__SLGpYVEqpFQ7VaPsJH6HIA_163);
	sslState__wrappersZopenssl_u418 = ((tyProc__UtOqI0ZkblBIu9btVw6gCWw) (T100002_));
}/* preInitProc end */
{
}
}

N_LIB_PRIVATE N_NIMCALL(void, atpopenssldotnim_DatInit000)(void) {
if (!((TM__SLGpYVEqpFQ7VaPsJH6HIA_24 = nimLoadLibrary(TM__SLGpYVEqpFQ7VaPsJH6HIA_27))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_24 = nimLoadLibrary(TM__SLGpYVEqpFQ7VaPsJH6HIA_30))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_24 = nimLoadLibrary(TM__SLGpYVEqpFQ7VaPsJH6HIA_33))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_24 = nimLoadLibrary(TM__SLGpYVEqpFQ7VaPsJH6HIA_36))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_24 = nimLoadLibrary(TM__SLGpYVEqpFQ7VaPsJH6HIA_39))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_24 = nimLoadLibrary(TM__SLGpYVEqpFQ7VaPsJH6HIA_42))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_24 = nimLoadLibrary(TM__SLGpYVEqpFQ7VaPsJH6HIA_45))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_24 = nimLoadLibrary(TM__SLGpYVEqpFQ7VaPsJH6HIA_48))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_24 = nimLoadLibrary(TM__SLGpYVEqpFQ7VaPsJH6HIA_51))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_24 = nimLoadLibrary(TM__SLGpYVEqpFQ7VaPsJH6HIA_54))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_24 = nimLoadLibrary(TM__SLGpYVEqpFQ7VaPsJH6HIA_57))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_24 = nimLoadLibrary(TM__SLGpYVEqpFQ7VaPsJH6HIA_60))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_24 = nimLoadLibrary(TM__SLGpYVEqpFQ7VaPsJH6HIA_63))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_24 = nimLoadLibrary(TM__SLGpYVEqpFQ7VaPsJH6HIA_66))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_24 = nimLoadLibrary(TM__SLGpYVEqpFQ7VaPsJH6HIA_69))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_24 = nimLoadLibrary(TM__SLGpYVEqpFQ7VaPsJH6HIA_72))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_24 = nimLoadLibrary(TM__SLGpYVEqpFQ7VaPsJH6HIA_75))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_24 = nimLoadLibrary(TM__SLGpYVEqpFQ7VaPsJH6HIA_78))
)) nimLoadLibraryError(TM__SLGpYVEqpFQ7VaPsJH6HIA_79);
	Dl_2097152674_ = (tyProc__1moENrYD5tFKVHdbrK2Heg) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_24, "SSL_ctrl");
if (!((TM__SLGpYVEqpFQ7VaPsJH6HIA_82 = nimLoadLibrary(TM__SLGpYVEqpFQ7VaPsJH6HIA_85))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_82 = nimLoadLibrary(TM__SLGpYVEqpFQ7VaPsJH6HIA_88))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_82 = nimLoadLibrary(TM__SLGpYVEqpFQ7VaPsJH6HIA_91))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_82 = nimLoadLibrary(TM__SLGpYVEqpFQ7VaPsJH6HIA_94))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_82 = nimLoadLibrary(TM__SLGpYVEqpFQ7VaPsJH6HIA_97))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_82 = nimLoadLibrary(TM__SLGpYVEqpFQ7VaPsJH6HIA_100))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_82 = nimLoadLibrary(TM__SLGpYVEqpFQ7VaPsJH6HIA_103))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_82 = nimLoadLibrary(TM__SLGpYVEqpFQ7VaPsJH6HIA_106))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_82 = nimLoadLibrary(TM__SLGpYVEqpFQ7VaPsJH6HIA_109))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_82 = nimLoadLibrary(TM__SLGpYVEqpFQ7VaPsJH6HIA_112))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_82 = nimLoadLibrary(TM__SLGpYVEqpFQ7VaPsJH6HIA_115))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_82 = nimLoadLibrary(TM__SLGpYVEqpFQ7VaPsJH6HIA_118))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_82 = nimLoadLibrary(TM__SLGpYVEqpFQ7VaPsJH6HIA_121))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_82 = nimLoadLibrary(TM__SLGpYVEqpFQ7VaPsJH6HIA_124))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_82 = nimLoadLibrary(TM__SLGpYVEqpFQ7VaPsJH6HIA_127))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_82 = nimLoadLibrary(TM__SLGpYVEqpFQ7VaPsJH6HIA_130))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_82 = nimLoadLibrary(TM__SLGpYVEqpFQ7VaPsJH6HIA_133))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_82 = nimLoadLibrary(TM__SLGpYVEqpFQ7VaPsJH6HIA_136))
)) nimLoadLibraryError(TM__SLGpYVEqpFQ7VaPsJH6HIA_137);
	Dl_2097152766_ = (tyProc__ln4kdL5W9bbX4a1xl8nnVXQ) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_82, "ERR_clear_error");
	Dl_2097152545_ = (tyProc__UtOqI0ZkblBIu9btVw6gCWw) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_24, "SSL_connect");
	Dl_2097152555_ = (tyProc__s4vzCIUdrW34nq0jAV5eYA) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_24, "SSL_get_error");
	Dl_2097152602_ = (tyProc__Zp8a7gsqfDHPKe06nErJjg) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_82, "ERR_peek_last_error");
	Dl_2097152598_ = (tyProc__HE9clvqwtdfVXvgz4Z0y1cw) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_82, "ERR_error_string");
	Dl_2097153085_ = (tyProc__k2mwfQqK5hf649av9aEy6UTw) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_24, "X509_check_host");
	Dl_2097153091_ = (tyProc__RCaJyw9a9ctK8XohyBKi8bHw) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_24, "X509_free");
	Dl_2097152538_ = (tyProc__UtOqI0ZkblBIu9btVw6gCWw) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_24, "SSL_shutdown");
	Dl_2097152476_ = (tyProc__RCaJyw9a9ctK8XohyBKi8bHw) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_24, "SSL_free");
	Dl_2097152489_ = (tyProc__XolGP5GhNzMBqZoTFFraQg) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_24, "SSL_CTX_new");
	Dl_2097152506_ = (tyProc__ZPts6i9cfNix9chUrKa0HF9cQ) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_24, "SSL_CTX_set_cipher_list");
	Dl_2097152661_ = (tyProc__cpabs4aa3ecbY9bS4SKZ1dQ) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_24, "SSL_CTX_ctrl");
	Dl_2097152497_ = (tyProc__2j0TTzVJ9a9cEDxsWAx4Kp4A) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_24, "SSL_CTX_set_verify");
	Dl_2097152513_ = (tyProc__6maZ6QUdZ03gNCZayireMg) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_24, "SSL_CTX_use_certificate_chain_file");
	Dl_2097152516_ = (tyProc__kY8HHYDGX8ujDZ0VNhR8oA) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_24, "SSL_CTX_use_PrivateKey_file");
	Dl_2097152520_ = (tyProc__UtOqI0ZkblBIu9btVw6gCWw) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_24, "SSL_CTX_check_private_key");
	Dl_2097152491_ = (tyProc__kBpkyPG8KLZuxR9aU6SFubg) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_24, "SSL_CTX_load_verify_locations");
	Dl_2097152551_ = (tyProc__wGd67TAKmh8ASBusfOEIIQ) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_24, "SSL_write");
	Dl_2097152547_ = (tyProc__4URUeKrPaJERpY9cYSDW0cA) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_24, "SSL_read");
	Dl_2097152560_ = (tyProc__UtOqI0ZkblBIu9btVw6gCWw) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_24, "SSL_pending");
	Dl_2097152474_ = (tyProc__XolGP5GhNzMBqZoTFFraQg) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_24, "SSL_new");
	Dl_2097152535_ = (tyProc__s4vzCIUdrW34nq0jAV5eYA) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_24, "SSL_set_fd");
	Dl_2097152558_ = (tyProc__UtOqI0ZkblBIu9btVw6gCWw) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_24, "SSL_accept");
}

