/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -fno-strict-aliasing -pthread -I/home/icarogdo/.nimble/pkgs2/bearssl-0.2.10-e53ab85b8c4c1ce3aa1f4eb251c0ab29e08d4972/bearssl/abi -I/home/icarogdo/.nimble/pkgs2/bearssl-0.2.10-e53ab85b8c4c1ce3aa1f4eb251c0ab29e08d4972/bearssl/abi/../csources/src/ -I/home/icarogdo/.nimble/pkgs2/bearssl-0.2.10-e53ab85b8c4c1ce3aa1f4eb251c0ab29e08d4972/bearssl/abi/../csources/inc/ -I/home/icarogdo/.nimble/pkgs2/bearssl-0.2.10-e53ab85b8c4c1ce3aa1f4eb251c0ab29e08d4972/bearssl/abi/../csources/tools/ -DBR_USE_UNIX_TIME=1 -DBR_USE_URANDOM=1 -DBR_LE_UNALIGNED=1 -DBR_64=1  -DBR_amd64=1 -DBR_INT128=1 -Wno-incompatible-pointer-types -I/usr/include/webkitgtk-4.1 -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/cloudproviders -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/glycin-2 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/atk-1.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/fribidi -I/usr/include/pixman-1 -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gio-unix-2.0 -I/usr/include/libsoup-3.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-6 -pthread   -I/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib -I/home/icarogdo/dev/macroobras-jazzy/app/macroobras/src -o /home/icarogdo/dev/macroobras-jazzy/app/macroobras/.nimcache/@pstd@sprivate@sthreadtypes.nim.c.o /home/icarogdo/dev/macroobras-jazzy/app/macroobras/.nimcache/@pstd@sprivate@sthreadtypes.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <sys/types.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_Thread__5cAJ9aHG5xQ0XGadlfs3GAw tyObject_Thread__5cAJ9aHG5xQ0XGadlfs3GAw;
typedef struct tyObject_GcThread__i6AP0dlU0qsgmi9b8YqNWmQ tyObject_GcThread__i6AP0dlU0qsgmi9b8YqNWmQ;
typedef struct tyObject_ServerObj__TJATNz6TttQ9aAy1rh4EooA tyObject_ServerObj__TJATNz6TttQ9aAy1rh4EooA;
typedef struct tyObject_Thread__kNPgudhS9cp5A31EDT2HnIA tyObject_Thread__kNPgudhS9cp5A31EDT2HnIA;
typedef struct tyObject_ServerConfig__gv9col5QHOhBlq5XM9bSDfgg tyObject_ServerConfig__gv9col5QHOhBlq5XM9bSDfgg;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef N_NIMCALL_PTR(void, tyProc__fKwtNKDYI1EPgyIftJbXgw) (tyObject_ServerObj__TJATNz6TttQ9aAy1rh4EooA* m_p0);
struct tyObject_Thread__5cAJ9aHG5xQ0XGadlfs3GAw {
	tyObject_GcThread__i6AP0dlU0qsgmi9b8YqNWmQ* core;
	pthread_t sys;
	tyProc__fKwtNKDYI1EPgyIftJbXgw dataFn;
	tyObject_ServerObj__TJATNz6TttQ9aAy1rh4EooA* data;
};
typedef N_NIMCALL_PTR(void, tyProc__PqzWj19czLM3mB5yO2JGEgg) (tyObject_ServerConfig__gv9col5QHOhBlq5XM9bSDfgg* m_p0);
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tyObject_ServerConfig__gv9col5QHOhBlq5XM9bSDfgg {
	NI port;
	NimStringV2 address;
	NimStringV2 prodDir;
	NimStringV2 corsOrigins;
};
struct tyObject_Thread__kNPgudhS9cp5A31EDT2HnIA {
	tyObject_GcThread__i6AP0dlU0qsgmi9b8YqNWmQ* core;
	pthread_t sys;
	tyProc__PqzWj19czLM3mB5yO2JGEgg dataFn;
	tyObject_ServerConfig__gv9col5QHOhBlq5XM9bSDfgg data;
};
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZmummy_u8746)(tyObject_Thread__5cAJ9aHG5xQ0XGadlfs3GAw* dest_p0) {
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___pkgZmummy_u8743)(tyObject_Thread__5cAJ9aHG5xQ0XGadlfs3GAw* dest_p0) {
	(*dest_p0).core = 0;
	(*dest_p0).sys = 0;
	(*dest_p0).dataFn = 0;
	(*dest_p0).data = 0;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZjazzy95desktopZserver_u23)(tyObject_Thread__kNPgudhS9cp5A31EDT2HnIA* dest_p0) {
	if ((*dest_p0).data.corsOrigins.p && !((*dest_p0).data.corsOrigins.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).data.corsOrigins.p);
}
	if ((*dest_p0).data.prodDir.p && !((*dest_p0).data.prodDir.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).data.prodDir.p);
}
	if ((*dest_p0).data.address.p && !((*dest_p0).data.address.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).data.address.p);
}
}
