/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -fno-strict-aliasing -pthread -I/home/icarogdo/.nimble/pkgs2/bearssl-0.2.10-e53ab85b8c4c1ce3aa1f4eb251c0ab29e08d4972/bearssl/abi -I/home/icarogdo/.nimble/pkgs2/bearssl-0.2.10-e53ab85b8c4c1ce3aa1f4eb251c0ab29e08d4972/bearssl/abi/../csources/src/ -I/home/icarogdo/.nimble/pkgs2/bearssl-0.2.10-e53ab85b8c4c1ce3aa1f4eb251c0ab29e08d4972/bearssl/abi/../csources/inc/ -I/home/icarogdo/.nimble/pkgs2/bearssl-0.2.10-e53ab85b8c4c1ce3aa1f4eb251c0ab29e08d4972/bearssl/abi/../csources/tools/ -DBR_USE_UNIX_TIME=1 -DBR_USE_URANDOM=1 -DBR_LE_UNALIGNED=1 -DBR_64=1  -DBR_amd64=1 -DBR_INT128=1 -Wno-incompatible-pointer-types -I/usr/include/webkitgtk-4.1 -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/cloudproviders -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/glycin-2 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/atk-1.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/fribidi -I/usr/include/pixman-1 -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gio-unix-2.0 -I/usr/include/libsoup-3.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-6 -pthread   -I/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib -I/home/icarogdo/dev/macroobras-jazzy/app/macroobras/src -o /home/icarogdo/dev/macroobras-jazzy/app/macroobras/.nimcache/@psystem@sexceptions.nim.c.o /home/icarogdo/dev/macroobras-jazzy/app/macroobras/.nimcache/@psystem@sexceptions.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tyObject_RangeDefect__39bmND756Jn4TbmMyoPiAaw tyObject_RangeDefect__39bmND756Jn4TbmMyoPiAaw;
typedef struct tyObject_RefHeader__sqhyc4FSbGmPtkvXRNl9acg tyObject_RefHeader__sqhyc4FSbGmPtkvXRNl9acg;
typedef struct tyObject_OverflowDefect__CGiRGxBaa9ayq9c0XyRtJx1w tyObject_OverflowDefect__CGiRGxBaa9ayq9c0XyRtJx1w;
typedef struct tyObject_ArithmeticDefect__aOZfpsWsYxgjFBl3u6zGIw tyObject_ArithmeticDefect__aOZfpsWsYxgjFBl3u6zGIw;
typedef struct tyObject_Defect__9cay1P9cMS9bqQj8GzEyUp67g tyObject_Defect__9cay1P9cMS9bqQj8GzEyUp67g;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tySequence__UIJx6FJrflnhA9a3u1VF1vA tySequence__UIJx6FJrflnhA9a3u1VF1vA;
typedef struct tySequence__UIJx6FJrflnhA9a3u1VF1vA_Content tySequence__UIJx6FJrflnhA9a3u1VF1vA_Content;
typedef struct tyObject_GcEnv__85WwC9a1qDcL9aPJ9b1qr0g2Q tyObject_GcEnv__85WwC9a1qDcL9aPJ9b1qr0g2Q;
typedef struct tyObject_CellSeq__tmpRNCI2baMQRvZpqUI72g tyObject_CellSeq__tmpRNCI2baMQRvZpqUI72g;
typedef struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q tyTuple__N4J9cV4JZGem3ljqqj5rT0Q;
typedef struct tyObject_CellSeq__bUU9cGCnoYZUQbR5GgWvc0g tyObject_CellSeq__bUU9cGCnoYZUQbR5GgWvc0g;
typedef struct tyTuple__WEETd9ajw9a010wvV0CoGNuw tyTuple__WEETd9ajw9a010wvV0CoGNuw;
typedef struct tyObject_IndexDefect__9bd1PhiEWFQ1CQmRpNFMavg tyObject_IndexDefect__9bd1PhiEWFQ1CQmRpNFMavg;
typedef struct tyObject_AssertionDefect__fAtMgIeNQyfDKIqRjGsXPw tyObject_AssertionDefect__fAtMgIeNQyfDKIqRjGsXPw;
typedef struct tyObject_LibraryError__mFRrgtH6YneJrrZNWIHf9cQ tyObject_LibraryError__mFRrgtH6YneJrrZNWIHf9cQ;
typedef struct tyObject_OSError__mgJw6oFbS4BLzYIO9ccv8FQ tyObject_OSError__mgJw6oFbS4BLzYIO9ccv8FQ;
typedef struct tyObject_CatchableError__kvV4Jp5z2ULaSZq53myi9ag tyObject_CatchableError__kvV4Jp5z2ULaSZq53myi9ag;
typedef struct tyObject_IOError__DxZ2JM72pLUaxjq9asr9aWqA tyObject_IOError__DxZ2JM72pLUaxjq9asr9aWqA;
typedef struct tyObject_ValueError__NZcE89crkraWmH1VkcjYX9ag tyObject_ValueError__NZcE89crkraWmH1VkcjYX9ag;
typedef struct tyObject_ReraiseDefect__DWvedQ43ZWh8VIcEkQMgDg tyObject_ReraiseDefect__DWvedQ43ZWh8VIcEkQMgDg;
typedef struct tyObject_KeyError__WyMCFOyjoQlpL9bXWFR7E6w tyObject_KeyError__WyMCFOyjoQlpL9bXWFR7E6w;
typedef struct tyObject_DivByZeroDefect__JuSN9cUNzjzPm3TyrxpQuSQ tyObject_DivByZeroDefect__JuSN9cUNzjzPm3TyrxpQuSQ;
typedef struct tyObject_FieldDefect__3VcP7BdxdifTuWcQ9cS8W5Q tyObject_FieldDefect__3VcP7BdxdifTuWcQ9cS8W5Q;
typedef struct tyObject_ResourceExhaustedError__UQwskKRmJUTGWzyUPx6xEQ tyObject_ResourceExhaustedError__UQwskKRmJUTGWzyUPx6xEQ;
typedef struct tyObject_ObjectConversionDefect__vytQGr7jGiOAFxkcnUnOrw tyObject_ObjectConversionDefect__vytQGr7jGiOAFxkcnUnOrw;
typedef struct tyObject_NilAccessDefect__uyHbhIsc9aGhR9abVgYn9clSQ tyObject_NilAccessDefect__uyHbhIsc9aGhR9abVgYn9clSQ;
typedef struct tyObject_StackTraceEntry__UznwMnjUHK6AxZHnP9bMXEA tyObject_StackTraceEntry__UznwMnjUHK6AxZHnP9bMXEA;
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct tyObject_RefHeader__sqhyc4FSbGmPtkvXRNl9acg {
	NI rc;
	NI rootIdx;
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tySequence__UIJx6FJrflnhA9a3u1VF1vA {
  NI len; tySequence__UIJx6FJrflnhA9a3u1VF1vA_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__UIJx6FJrflnhA9a3u1VF1vA trace;
	Exception* up;
};
struct tyObject_Defect__9cay1P9cMS9bqQj8GzEyUp67g {
	Exception Sup;
};
struct tyObject_ArithmeticDefect__aOZfpsWsYxgjFBl3u6zGIw {
	tyObject_Defect__9cay1P9cMS9bqQj8GzEyUp67g Sup;
};
struct tyObject_OverflowDefect__CGiRGxBaa9ayq9c0XyRtJx1w {
	tyObject_ArithmeticDefect__aOZfpsWsYxgjFBl3u6zGIw Sup;
};
struct tyObject_CellSeq__tmpRNCI2baMQRvZpqUI72g {
	NI len;
	NI cap;
	tyTuple__N4J9cV4JZGem3ljqqj5rT0Q* d;
};
struct tyObject_CellSeq__bUU9cGCnoYZUQbR5GgWvc0g {
	NI len;
	NI cap;
	tyTuple__WEETd9ajw9a010wvV0CoGNuw* d;
};
struct tyObject_GcEnv__85WwC9a1qDcL9aPJ9b1qr0g2Q {
	tyObject_CellSeq__tmpRNCI2baMQRvZpqUI72g traceStack;
	tyObject_CellSeq__bUU9cGCnoYZUQbR5GgWvc0g toFree;
	NI freed;
	NI touched;
	NI edges;
	NI rcSum;
	NIM_BOOL keepThreshold;
};
struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q {
	void** Field0;
	TNimTypeV2* Field1;
};
struct tyObject_RangeDefect__39bmND756Jn4TbmMyoPiAaw {
	tyObject_Defect__9cay1P9cMS9bqQj8GzEyUp67g Sup;
};
struct tyObject_IndexDefect__9bd1PhiEWFQ1CQmRpNFMavg {
	tyObject_Defect__9cay1P9cMS9bqQj8GzEyUp67g Sup;
};
struct tyObject_AssertionDefect__fAtMgIeNQyfDKIqRjGsXPw {
	tyObject_Defect__9cay1P9cMS9bqQj8GzEyUp67g Sup;
};
struct tyObject_CatchableError__kvV4Jp5z2ULaSZq53myi9ag {
	Exception Sup;
};
struct tyObject_OSError__mgJw6oFbS4BLzYIO9ccv8FQ {
	tyObject_CatchableError__kvV4Jp5z2ULaSZq53myi9ag Sup;
	NI32 errorCode;
};
struct tyObject_LibraryError__mFRrgtH6YneJrrZNWIHf9cQ {
	tyObject_OSError__mgJw6oFbS4BLzYIO9ccv8FQ Sup;
};
struct tyObject_IOError__DxZ2JM72pLUaxjq9asr9aWqA {
	tyObject_CatchableError__kvV4Jp5z2ULaSZq53myi9ag Sup;
};
struct tyObject_ValueError__NZcE89crkraWmH1VkcjYX9ag {
	tyObject_CatchableError__kvV4Jp5z2ULaSZq53myi9ag Sup;
};
struct tyObject_ReraiseDefect__DWvedQ43ZWh8VIcEkQMgDg {
	tyObject_Defect__9cay1P9cMS9bqQj8GzEyUp67g Sup;
};
struct tyObject_KeyError__WyMCFOyjoQlpL9bXWFR7E6w {
	tyObject_ValueError__NZcE89crkraWmH1VkcjYX9ag Sup;
};
struct tyObject_DivByZeroDefect__JuSN9cUNzjzPm3TyrxpQuSQ {
	tyObject_ArithmeticDefect__aOZfpsWsYxgjFBl3u6zGIw Sup;
};
struct tyObject_FieldDefect__3VcP7BdxdifTuWcQ9cS8W5Q {
	tyObject_Defect__9cay1P9cMS9bqQj8GzEyUp67g Sup;
};
struct tyObject_ResourceExhaustedError__UQwskKRmJUTGWzyUPx6xEQ {
	tyObject_CatchableError__kvV4Jp5z2ULaSZq53myi9ag Sup;
};
struct tyObject_ObjectConversionDefect__vytQGr7jGiOAFxkcnUnOrw {
	tyObject_Defect__9cay1P9cMS9bqQj8GzEyUp67g Sup;
};
struct tyObject_NilAccessDefect__uyHbhIsc9aGhR9abVgYn9clSQ {
	tyObject_Defect__9cay1P9cMS9bqQj8GzEyUp67g Sup;
};
struct tyObject_StackTraceEntry__UznwMnjUHK6AxZHnP9bMXEA {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__UIJx6FJrflnhA9a3u1VF1vA_Content { NI cap; tyObject_StackTraceEntry__UznwMnjUHK6AxZHnP9bMXEA data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u56)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4641)(tyObject_RangeDefect__39bmND756Jn4TbmMyoPiAaw* dest_p0);
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0);
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4511)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NOINLINE(void, rememberCycle__system_u3573)(NIM_BOOL isDestroyAction_p0, tyObject_RefHeader__sqhyc4FSbGmPtkvXRNl9acg* s_p1, TNimTypeV2* desc_p2);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u58)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u5114)(tyObject_OverflowDefect__CGiRGxBaa9ayq9c0XyRtJx1w* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u3775)(tySequence__UIJx6FJrflnhA9a3u1VF1vA dest_p0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u5126)(tyObject_OverflowDefect__CGiRGxBaa9ayq9c0XyRtJx1w* dest_p0, void* env_p1);
static N_INLINE(void, nimTraceRefDyn)(void* q_p0, void* env_p1);
static N_INLINE(void, add__system_u3094)(tyObject_CellSeq__tmpRNCI2baMQRvZpqUI72g* s_p0, void** c_p1, TNimTypeV2* t_p2);
N_LIB_PRIVATE N_NIMCALL(void, resize__system_u3102)(tyObject_CellSeq__tmpRNCI2baMQRvZpqUI72g* s_p0);
static N_INLINE(NI, pluspercent___system_u793)(NI x_p0, NI y_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u4653)(tyObject_RangeDefect__39bmND756Jn4TbmMyoPiAaw* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u62)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4710)(tyObject_IndexDefect__9bd1PhiEWFQ1CQmRpNFMavg* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u4722)(tyObject_IndexDefect__9bd1PhiEWFQ1CQmRpNFMavg* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u64)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZassertions_u37)(tyObject_AssertionDefect__fAtMgIeNQyfDKIqRjGsXPw* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___stdZassertions_u49)(tyObject_AssertionDefect__fAtMgIeNQyfDKIqRjGsXPw* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u66)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZdynlib_u15)(tyObject_LibraryError__mFRrgtH6YneJrrZNWIHf9cQ* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___pureZdynlib_u27)(tyObject_LibraryError__mFRrgtH6YneJrrZNWIHf9cQ* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u68)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u9255)(tyObject_IOError__DxZ2JM72pLUaxjq9asr9aWqA* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u9267)(tyObject_IOError__DxZ2JM72pLUaxjq9asr9aWqA* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u70)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___coreZmacros_u567)(tyObject_ValueError__NZcE89crkraWmH1VkcjYX9ag* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___coreZmacros_u579)(tyObject_ValueError__NZcE89crkraWmH1VkcjYX9ag* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u72)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4387)(tyObject_ReraiseDefect__DWvedQ43ZWh8VIcEkQMgDg* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u4399)(tyObject_ReraiseDefect__DWvedQ43ZWh8VIcEkQMgDg* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u74)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZjson_u3373)(tyObject_KeyError__WyMCFOyjoQlpL9bXWFR7E6w* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___pureZjson_u3385)(tyObject_KeyError__WyMCFOyjoQlpL9bXWFR7E6w* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u76)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u5180)(tyObject_DivByZeroDefect__JuSN9cUNzjzPm3TyrxpQuSQ* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u5192)(tyObject_DivByZeroDefect__JuSN9cUNzjzPm3TyrxpQuSQ* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u78)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZoserrors_u60)(tyObject_OSError__mgJw6oFbS4BLzYIO9ccv8FQ* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___stdZoserrors_u72)(tyObject_OSError__mgJw6oFbS4BLzYIO9ccv8FQ* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u80)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4800)(tyObject_FieldDefect__3VcP7BdxdifTuWcQ9cS8W5Q* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u4812)(tyObject_FieldDefect__3VcP7BdxdifTuWcQ9cS8W5Q* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u82)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZtypedthreads_u220)(tyObject_ResourceExhaustedError__UQwskKRmJUTGWzyUPx6xEQ* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___stdZtypedthreads_u232)(tyObject_ResourceExhaustedError__UQwskKRmJUTGWzyUPx6xEQ* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u84)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4933)(tyObject_ObjectConversionDefect__vytQGr7jGiOAFxkcnUnOrw* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u4945)(tyObject_ObjectConversionDefect__vytQGr7jGiOAFxkcnUnOrw* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u86)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u5037)(tyObject_NilAccessDefect__uyHbhIsc9aGhR9abVgYn9clSQ* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u5049)(tyObject_NilAccessDefect__uyHbhIsc9aGhR9abVgYn9clSQ* dest_p0, void* env_p1);
N_LIB_PRIVATE TNimTypeV2 NTIv2__39bmND756Jn4TbmMyoPiAaw_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__CGiRGxBaa9ayq9c0XyRtJx1w_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__9bd1PhiEWFQ1CQmRpNFMavg_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__fAtMgIeNQyfDKIqRjGsXPw_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__mFRrgtH6YneJrrZNWIHf9cQ_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__DxZ2JM72pLUaxjq9asr9aWqA_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__NZcE89crkraWmH1VkcjYX9ag_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__DWvedQ43ZWh8VIcEkQMgDg_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__WyMCFOyjoQlpL9bXWFR7E6w_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__JuSN9cUNzjzPm3TyrxpQuSQ_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__mgJw6oFbS4BLzYIO9ccv8FQ_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__3VcP7BdxdifTuWcQ9cS8W5Q_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__UQwskKRmJUTGWzyUPx6xEQ_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__vytQGr7jGiOAFxkcnUnOrw_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__uyHbhIsc9aGhR9abVgYn9clSQ_;
extern NIM_THREADVAR TFrame* framePtr__system_u2809;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4293;
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_2[5] = {3701606400, 1285336064, 2897559296, 3865028096, 1754340096};
N_LIB_PRIVATE TNimTypeV2 NTIv2__CGiRGxBaa9ayq9c0XyRtJx1w_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u58, .size = sizeof(tyObject_OverflowDefect__CGiRGxBaa9ayq9c0XyRtJx1w), .align = (NI16) NIM_ALIGNOF(tyObject_OverflowDefect__CGiRGxBaa9ayq9c0XyRtJx1w), .depth = 4, .display = TM__TzI3paKQY09cLjc9cmCvur3A_2, .traceImpl = (void*)eqtrace___system_u5126, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_3[4] = {3701606400, 1285336064, 2897559296, 3918335744};
N_LIB_PRIVATE TNimTypeV2 NTIv2__39bmND756Jn4TbmMyoPiAaw_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u56, .size = sizeof(tyObject_RangeDefect__39bmND756Jn4TbmMyoPiAaw), .align = (NI16) NIM_ALIGNOF(tyObject_RangeDefect__39bmND756Jn4TbmMyoPiAaw), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_3, .traceImpl = (void*)eqtrace___system_u4653, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_4[4] = {3701606400, 1285336064, 2897559296, 3712976384};
N_LIB_PRIVATE TNimTypeV2 NTIv2__9bd1PhiEWFQ1CQmRpNFMavg_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u62, .size = sizeof(tyObject_IndexDefect__9bd1PhiEWFQ1CQmRpNFMavg), .align = (NI16) NIM_ALIGNOF(tyObject_IndexDefect__9bd1PhiEWFQ1CQmRpNFMavg), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_4, .traceImpl = (void*)eqtrace___system_u4722, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_5[4] = {3701606400, 1285336064, 2897559296, 189562880};
N_LIB_PRIVATE TNimTypeV2 NTIv2__fAtMgIeNQyfDKIqRjGsXPw_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u64, .size = sizeof(tyObject_AssertionDefect__fAtMgIeNQyfDKIqRjGsXPw), .align = (NI16) NIM_ALIGNOF(tyObject_AssertionDefect__fAtMgIeNQyfDKIqRjGsXPw), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_5, .traceImpl = (void*)eqtrace___stdZassertions_u49, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_6[5] = {3701606400, 1285336064, 4118291968, 40954368, 1416331776};
N_LIB_PRIVATE TNimTypeV2 NTIv2__mFRrgtH6YneJrrZNWIHf9cQ_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u66, .size = sizeof(tyObject_LibraryError__mFRrgtH6YneJrrZNWIHf9cQ), .align = (NI16) NIM_ALIGNOF(tyObject_LibraryError__mFRrgtH6YneJrrZNWIHf9cQ), .depth = 4, .display = TM__TzI3paKQY09cLjc9cmCvur3A_6, .traceImpl = (void*)eqtrace___pureZdynlib_u27, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_7[4] = {3701606400, 1285336064, 4118291968, 376841216};
N_LIB_PRIVATE TNimTypeV2 NTIv2__DxZ2JM72pLUaxjq9asr9aWqA_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u68, .size = sizeof(tyObject_IOError__DxZ2JM72pLUaxjq9asr9aWqA), .align = (NI16) NIM_ALIGNOF(tyObject_IOError__DxZ2JM72pLUaxjq9asr9aWqA), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_7, .traceImpl = (void*)eqtrace___system_u9267, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_8[4] = {3701606400, 1285336064, 4118291968, 2533683968};
N_LIB_PRIVATE TNimTypeV2 NTIv2__NZcE89crkraWmH1VkcjYX9ag_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u70, .size = sizeof(tyObject_ValueError__NZcE89crkraWmH1VkcjYX9ag), .align = (NI16) NIM_ALIGNOF(tyObject_ValueError__NZcE89crkraWmH1VkcjYX9ag), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_8, .traceImpl = (void*)eqtrace___coreZmacros_u579, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_9[4] = {3701606400, 1285336064, 2897559296, 1809741056};
N_LIB_PRIVATE TNimTypeV2 NTIv2__DWvedQ43ZWh8VIcEkQMgDg_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u72, .size = sizeof(tyObject_ReraiseDefect__DWvedQ43ZWh8VIcEkQMgDg), .align = (NI16) NIM_ALIGNOF(tyObject_ReraiseDefect__DWvedQ43ZWh8VIcEkQMgDg), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_9, .traceImpl = (void*)eqtrace___system_u4399, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_10[5] = {3701606400, 1285336064, 4118291968, 2533683968, 587338752};
N_LIB_PRIVATE TNimTypeV2 NTIv2__WyMCFOyjoQlpL9bXWFR7E6w_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u74, .size = sizeof(tyObject_KeyError__WyMCFOyjoQlpL9bXWFR7E6w), .align = (NI16) NIM_ALIGNOF(tyObject_KeyError__WyMCFOyjoQlpL9bXWFR7E6w), .depth = 4, .display = TM__TzI3paKQY09cLjc9cmCvur3A_10, .traceImpl = (void*)eqtrace___pureZjson_u3385, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_11[5] = {3701606400, 1285336064, 2897559296, 3865028096, 3834510592};
N_LIB_PRIVATE TNimTypeV2 NTIv2__JuSN9cUNzjzPm3TyrxpQuSQ_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u76, .size = sizeof(tyObject_DivByZeroDefect__JuSN9cUNzjzPm3TyrxpQuSQ), .align = (NI16) NIM_ALIGNOF(tyObject_DivByZeroDefect__JuSN9cUNzjzPm3TyrxpQuSQ), .depth = 4, .display = TM__TzI3paKQY09cLjc9cmCvur3A_11, .traceImpl = (void*)eqtrace___system_u5192, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_12[4] = {3701606400, 1285336064, 4118291968, 40954368};
N_LIB_PRIVATE TNimTypeV2 NTIv2__mgJw6oFbS4BLzYIO9ccv8FQ_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u78, .size = sizeof(tyObject_OSError__mgJw6oFbS4BLzYIO9ccv8FQ), .align = (NI16) NIM_ALIGNOF(tyObject_OSError__mgJw6oFbS4BLzYIO9ccv8FQ), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_12, .traceImpl = (void*)eqtrace___stdZoserrors_u72, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_13[4] = {3701606400, 1285336064, 2897559296, 1460661248};
N_LIB_PRIVATE TNimTypeV2 NTIv2__3VcP7BdxdifTuWcQ9cS8W5Q_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u80, .size = sizeof(tyObject_FieldDefect__3VcP7BdxdifTuWcQ9cS8W5Q), .align = (NI16) NIM_ALIGNOF(tyObject_FieldDefect__3VcP7BdxdifTuWcQ9cS8W5Q), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_13, .traceImpl = (void*)eqtrace___system_u4812, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_14[4] = {3701606400, 1285336064, 4118291968, 204247040};
N_LIB_PRIVATE TNimTypeV2 NTIv2__UQwskKRmJUTGWzyUPx6xEQ_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u82, .size = sizeof(tyObject_ResourceExhaustedError__UQwskKRmJUTGWzyUPx6xEQ), .align = (NI16) NIM_ALIGNOF(tyObject_ResourceExhaustedError__UQwskKRmJUTGWzyUPx6xEQ), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_14, .traceImpl = (void*)eqtrace___stdZtypedthreads_u232, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_15[4] = {3701606400, 1285336064, 2897559296, 726669824};
N_LIB_PRIVATE TNimTypeV2 NTIv2__vytQGr7jGiOAFxkcnUnOrw_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u84, .size = sizeof(tyObject_ObjectConversionDefect__vytQGr7jGiOAFxkcnUnOrw), .align = (NI16) NIM_ALIGNOF(tyObject_ObjectConversionDefect__vytQGr7jGiOAFxkcnUnOrw), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_15, .traceImpl = (void*)eqtrace___system_u4945, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_16[4] = {3701606400, 1285336064, 2897559296, 568034304};
N_LIB_PRIVATE TNimTypeV2 NTIv2__uyHbhIsc9aGhR9abVgYn9clSQ_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u86, .size = sizeof(tyObject_NilAccessDefect__uyHbhIsc9aGhR9abVgYn9clSQ), .align = (NI16) NIM_ALIGNOF(tyObject_NilAccessDefect__uyHbhIsc9aGhR9abVgYn9clSQ), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_16, .traceImpl = (void*)eqtrace___system_u5049, .flags = 0};
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2809 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2809).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2809;
	framePtr__system_u2809 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4511();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2809 = (*framePtr__system_u2809).prev;
}
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1) {
	NI result;
	nimfr_("-%", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/arithmetics.nim");
	nimlf_(377, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/arithmetics.nim");	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) - (NU64)(((NU) (y_p1))))));
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u5114)(tyObject_OverflowDefect__CGiRGxBaa9ayq9c0XyRtJx1w* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.up);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.up);
	}
LA4_: ;
	eqdestroy___system_u3775((*dest_p0).Sup.Sup.Sup.trace);
	if ((*dest_p0).Sup.Sup.Sup.message.p && !((*dest_p0).Sup.Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.Sup.message.p);
}
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.parent);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.parent);
	}
LA9_: ;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4293);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u58)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___system_u5114(((tyObject_OverflowDefect__CGiRGxBaa9ayq9c0XyRtJx1w*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(NI, pluspercent___system_u793)(NI x_p0, NI y_p1) {
	NI result;
	nimfr_("+%", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/arithmetics.nim");
	nimln_(366);	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) + (NU64)(((NU) (y_p1))))));
	popFrame();
	return result;
}
static N_INLINE(void, add__system_u3094)(tyObject_CellSeq__tmpRNCI2baMQRvZpqUI72g* s_p0, void** c_p1, TNimTypeV2* t_p2) {
	void** colontmp_;
	TNimTypeV2* colontmp__2;
	nimfr_("add", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/cellseqs_v2.nim");
	nimlf_(28, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/cellseqs_v2.nim");	{
		if (!((*s_p0).cap <= (*s_p0).len)) goto LA3_;
		nimln_(29);		resize__system_u3102(s_p0);
	}
LA3_: ;
	nimln_(30);	colontmp_ = c_p1;
	colontmp__2 = t_p2;
	(*s_p0).d[(*s_p0).len].Field0 = colontmp_;
	(*s_p0).d[(*s_p0).len].Field1 = colontmp__2;
	nimln_(31);	(*s_p0).len = pluspercent___system_u793((*s_p0).len, ((NI)1));
	popFrame();
}
static N_INLINE(void, nimTraceRefDyn)(void* q_p0, void* env_p1) {
	void** p_1;
	nimfr_("nimTraceRefDyn", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/orc.nim");
	nimlf_(138, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/orc.nim");	p_1 = ((void**) (q_p0));
	nimln_(139);	{
		tyObject_GcEnv__85WwC9a1qDcL9aPJ9b1qr0g2Q* j_1;
		if (!!(((*p_1) == NIM_NIL))) goto LA3_;
		nimln_(140);		j_1 = ((tyObject_GcEnv__85WwC9a1qDcL9aPJ9b1qr0g2Q*) (env_p1));
		nimln_(141);		add__system_u3094((&(*j_1).traceStack), p_1, (*((TNimTypeV2**) ((*p_1)))));
	}
LA3_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u5126)(tyObject_OverflowDefect__CGiRGxBaa9ayq9c0XyRtJx1w* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.Sup.up, env_p1);
}
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0) {
	NIM_BOOL result;
	nimfr_("nimDecRefIsLastCyclicDyn", "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/orc.nim");
	nimln_(518);	result = NIM_FALSE;
	nimln_(519);	{
		tyObject_RefHeader__sqhyc4FSbGmPtkvXRNl9acg* cell_1;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		nimln_(520);		nimlf_(60, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/arc.nim");		T5_ = (NI)0;
		T5_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)16));
		cell_1 = ((tyObject_RefHeader__sqhyc4FSbGmPtkvXRNl9acg*) (T5_));
		nimlf_(521, "/home/icarogdo/.choosenim/toolchains/nim-2.2.10/lib/system/orc.nim");		{
			if (!((NI)((*cell_1).rc & ((NI)-16)) == ((NI)0))) goto LA8_;
			nimln_(522);			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			nimln_(525);			(*cell_1).rc = minuspercent___system_u813((*cell_1).rc, ((NI)16));
		}
LA6_: ;
		nimln_(527);		rememberCycle__system_u3573(result, cell_1, (*((TNimTypeV2**) (p_p0))));
	}
LA3_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4641)(tyObject_RangeDefect__39bmND756Jn4TbmMyoPiAaw* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.up);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA4_: ;
	eqdestroy___system_u3775((*dest_p0).Sup.Sup.trace);
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.parent);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u56)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___system_u4641(((tyObject_RangeDefect__39bmND756Jn4TbmMyoPiAaw*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u4653)(tyObject_RangeDefect__39bmND756Jn4TbmMyoPiAaw* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4710)(tyObject_IndexDefect__9bd1PhiEWFQ1CQmRpNFMavg* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.up);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA4_: ;
	eqdestroy___system_u3775((*dest_p0).Sup.Sup.trace);
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.parent);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u62)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___system_u4710(((tyObject_IndexDefect__9bd1PhiEWFQ1CQmRpNFMavg*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u4722)(tyObject_IndexDefect__9bd1PhiEWFQ1CQmRpNFMavg* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZassertions_u37)(tyObject_AssertionDefect__fAtMgIeNQyfDKIqRjGsXPw* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.up);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA4_: ;
	eqdestroy___system_u3775((*dest_p0).Sup.Sup.trace);
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.parent);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u64)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___stdZassertions_u37(((tyObject_AssertionDefect__fAtMgIeNQyfDKIqRjGsXPw*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___stdZassertions_u49)(tyObject_AssertionDefect__fAtMgIeNQyfDKIqRjGsXPw* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZdynlib_u15)(tyObject_LibraryError__mFRrgtH6YneJrrZNWIHf9cQ* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.up);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.up);
	}
LA4_: ;
	eqdestroy___system_u3775((*dest_p0).Sup.Sup.Sup.trace);
	if ((*dest_p0).Sup.Sup.Sup.message.p && !((*dest_p0).Sup.Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.Sup.message.p);
}
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.parent);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.parent);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u66)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___pureZdynlib_u15(((tyObject_LibraryError__mFRrgtH6YneJrrZNWIHf9cQ*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___pureZdynlib_u27)(tyObject_LibraryError__mFRrgtH6YneJrrZNWIHf9cQ* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u9255)(tyObject_IOError__DxZ2JM72pLUaxjq9asr9aWqA* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.up);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA4_: ;
	eqdestroy___system_u3775((*dest_p0).Sup.Sup.trace);
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.parent);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u68)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___system_u9255(((tyObject_IOError__DxZ2JM72pLUaxjq9asr9aWqA*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u9267)(tyObject_IOError__DxZ2JM72pLUaxjq9asr9aWqA* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___coreZmacros_u567)(tyObject_ValueError__NZcE89crkraWmH1VkcjYX9ag* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.up);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA4_: ;
	eqdestroy___system_u3775((*dest_p0).Sup.Sup.trace);
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.parent);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u70)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___coreZmacros_u567(((tyObject_ValueError__NZcE89crkraWmH1VkcjYX9ag*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___coreZmacros_u579)(tyObject_ValueError__NZcE89crkraWmH1VkcjYX9ag* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4387)(tyObject_ReraiseDefect__DWvedQ43ZWh8VIcEkQMgDg* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.up);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA4_: ;
	eqdestroy___system_u3775((*dest_p0).Sup.Sup.trace);
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.parent);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u72)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___system_u4387(((tyObject_ReraiseDefect__DWvedQ43ZWh8VIcEkQMgDg*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u4399)(tyObject_ReraiseDefect__DWvedQ43ZWh8VIcEkQMgDg* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZjson_u3373)(tyObject_KeyError__WyMCFOyjoQlpL9bXWFR7E6w* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.up);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.up);
	}
LA4_: ;
	eqdestroy___system_u3775((*dest_p0).Sup.Sup.Sup.trace);
	if ((*dest_p0).Sup.Sup.Sup.message.p && !((*dest_p0).Sup.Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.Sup.message.p);
}
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.parent);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.parent);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u74)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___pureZjson_u3373(((tyObject_KeyError__WyMCFOyjoQlpL9bXWFR7E6w*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___pureZjson_u3385)(tyObject_KeyError__WyMCFOyjoQlpL9bXWFR7E6w* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u5180)(tyObject_DivByZeroDefect__JuSN9cUNzjzPm3TyrxpQuSQ* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.up);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.up);
	}
LA4_: ;
	eqdestroy___system_u3775((*dest_p0).Sup.Sup.Sup.trace);
	if ((*dest_p0).Sup.Sup.Sup.message.p && !((*dest_p0).Sup.Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.Sup.message.p);
}
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.parent);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.parent);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u76)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___system_u5180(((tyObject_DivByZeroDefect__JuSN9cUNzjzPm3TyrxpQuSQ*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u5192)(tyObject_DivByZeroDefect__JuSN9cUNzjzPm3TyrxpQuSQ* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZoserrors_u60)(tyObject_OSError__mgJw6oFbS4BLzYIO9ccv8FQ* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.up);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA4_: ;
	eqdestroy___system_u3775((*dest_p0).Sup.Sup.trace);
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.parent);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u78)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___stdZoserrors_u60(((tyObject_OSError__mgJw6oFbS4BLzYIO9ccv8FQ*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___stdZoserrors_u72)(tyObject_OSError__mgJw6oFbS4BLzYIO9ccv8FQ* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4800)(tyObject_FieldDefect__3VcP7BdxdifTuWcQ9cS8W5Q* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.up);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA4_: ;
	eqdestroy___system_u3775((*dest_p0).Sup.Sup.trace);
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.parent);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u80)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___system_u4800(((tyObject_FieldDefect__3VcP7BdxdifTuWcQ9cS8W5Q*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u4812)(tyObject_FieldDefect__3VcP7BdxdifTuWcQ9cS8W5Q* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZtypedthreads_u220)(tyObject_ResourceExhaustedError__UQwskKRmJUTGWzyUPx6xEQ* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.up);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA4_: ;
	eqdestroy___system_u3775((*dest_p0).Sup.Sup.trace);
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.parent);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u82)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___stdZtypedthreads_u220(((tyObject_ResourceExhaustedError__UQwskKRmJUTGWzyUPx6xEQ*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___stdZtypedthreads_u232)(tyObject_ResourceExhaustedError__UQwskKRmJUTGWzyUPx6xEQ* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4933)(tyObject_ObjectConversionDefect__vytQGr7jGiOAFxkcnUnOrw* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.up);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA4_: ;
	eqdestroy___system_u3775((*dest_p0).Sup.Sup.trace);
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.parent);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u84)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___system_u4933(((tyObject_ObjectConversionDefect__vytQGr7jGiOAFxkcnUnOrw*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u4945)(tyObject_ObjectConversionDefect__vytQGr7jGiOAFxkcnUnOrw* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u5037)(tyObject_NilAccessDefect__uyHbhIsc9aGhR9abVgYn9clSQ* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.up);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA4_: ;
	eqdestroy___system_u3775((*dest_p0).Sup.Sup.trace);
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.parent);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u86)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___system_u5037(((tyObject_NilAccessDefect__uyHbhIsc9aGhR9abVgYn9clSQ*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u5049)(tyObject_NilAccessDefect__uyHbhIsc9aGhR9abVgYn9clSQ* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.up, env_p1);
}
