export const inventoryMaterialsSeed = [
  { id: "inv-buerarema-cimento", city: "Buerarema", warehouse: "Depósito central", description: "Cimento CP II 50 kg", category: "Estrutura", unit: "saco", availableQuantity: 180, reservedQuantity: 40, averageUnitValue: 39.9, condition: "Disponível" },
  { id: "inv-buerarema-areia", city: "Buerarema", warehouse: "Pátio municipal", description: "Areia média lavada", category: "Agregados", unit: "m³", availableQuantity: 36, reservedQuantity: 8, averageUnitValue: 164, condition: "Disponível" },
  { id: "inv-sao-felipe-cabo", city: "São Felipe", warehouse: "Almoxarifado da obra", description: "Cabo flexível 10 mm²", category: "Elétrica", unit: "m", availableQuantity: 920, reservedQuantity: 360, averageUnitValue: 9.8, condition: "Disponível" },
  { id: "inv-itabuna-piso", city: "Itabuna", warehouse: "Depósito regional", description: "Piso intertravado 10 × 20 cm", category: "Pavimentação", unit: "m²", availableQuantity: 740, reservedQuantity: 120, averageUnitValue: 58.5, condition: "Disponível" },
  { id: "inv-salvador-refletor", city: "Salvador", warehouse: "Centro de distribuição", description: "Refletor LED para estádio", category: "Iluminação", unit: "un", availableQuantity: 18, reservedQuantity: 6, averageUnitValue: 3980, condition: "Inspeção concluída" },
];

export const ticketsSeed = [
  {
    id: "ticket-transferencia-led",
    title: "Separar refletores para São Felipe",
    description: "Reservar e despachar os refletores disponíveis no centro de distribuição.",
    type: "Transferência de material",
    requesterPersonId: "rh-person-1",
    responsiblePersonId: "rh-person-2",
    approverPersonId: "rh-person-1",
    workId: "obra-sao-felipe-led",
    workItemId: "sf-led",
    inventoryMaterialId: "inv-salvador-refletor",
    priority: "Alta",
    status: "Pendente",
    scheduledAt: "2026-08-01",
    dueAt: "2026-08-03",
    requirements: ["Confirmar quantidade", "Anexar comprovante de separação"],
    attachments: [],
  },
  {
    id: "ticket-diario-buerarema",
    title: "Fechar diário da preparação da base",
    description: "Registrar execução, gastos e evidências do serviço antes da medição.",
    type: "Diário de obra",
    requesterPersonId: "rh-person-1",
    responsiblePersonId: "rh-person-1",
    approverPersonId: "rh-person-2",
    workId: "obra-buerarema-estadio",
    workItemId: "bue-03",
    inventoryMaterialId: "",
    priority: "Média",
    status: "Agendado",
    scheduledAt: "2026-08-04",
    dueAt: "2026-08-04",
    requirements: ["Anexar fotos de campo", "Informar percentual executado"],
    attachments: [],
  },
];
